### ISSUE TITLE
Router: Provide support for parameter-only navigation

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#10054]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When navigating via the router service, a string path is required even if navigating within the same route, but only changing route parameters

**Expected/desired behavior**

If only providing an object with route params, the router should take the current route path and navigate with the updated parameters.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

Given the following routes

```js
const projectsRoutes: RouterConfig = [
    {
        path: "projects",
        component: ProjectsComponent,
        children: [
            {
                path: "all",
                component: ProjectListComponent
            }
        ]
    }
];
```

From within the `ProjectListComponent` I should be able to use 

```js
this.router.navigate([ { query: 'test' } ], { relativeTo: this.activatedRoute });
```

and the router navigate to 

```html
/projects/all;query=test
```

Currently an error is thrown: `TypeError: Cannot read property 'path' of undefined`

To make this work I have to traverse upwards to come back to the same route.

```js
this.router.navigate([ "../all", { query: 'test' } ], { relativeTo: this.activatedRoute });
```

**What is the motivation / use case for changing the behavior?**

Navigating relatively within the current route

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 

cc: @bennadel @vsavkin @wardbell

**Comment by bennadel** [comment]
Awesome! This would be very helpful.

**Comment by Alberthaff** [comment]
I am having a similar issue with linking to following address:

/:agreementId/dashboard

It works fine with following function:
`switchAgreement(agreement){
    this._router.navigate(['/',agreementId,'dashboard']);
}`

The route above also works fine, if i access it directly through the browser.

However, if i try to link to the path above, with the [routerLink] property binding, it fails:
`<a [routerLink]="['/',agreementId,'dashboard']">{{ agreementName }}</a>`

**Comment by GabrielDelepine** [comment]
Hi @Alberthaff,
Can you confirm your issue is solved with [this fix](https://github.com/angular/angular/issues/10613) mentioned above, witch is merged in angular 2.0.0-rc.6 ?
Thanks

**Comment by beenokle** [comment]
Hi @GabrielDelepine  @vsavkin 

Still reproducable on `router@3.0.0-rc.2` and `angular@2.0.0-rc.7`

When I call 

```js
this.router.navigate([{page: nextPage}], {relativeTo: this.activatedRoute});
```

I got:

```
error_handler.js:51 TypeError: Cannot read property 'path' of undefined
    at createNewSegmentGroup (create_url_tree.js:250)
    at updateSegmentGroup (create_url_tree.js:186)
    at createUrlTree (create_url_tree.js:23)
    at Router.createUrlTree (router.js:256)
    at Router.navigate (router.js:311)
```
