### ISSUE TITLE
@ContentChildren can select host component as well

### ISSUE THREAD

**Issue by jack-guy** [angular/angular#10098]
**I'm submitting a ...**  (check one with "x")

```
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`@ContentChildren` will select the host component if the component selector matches it.

```
<foo the-root>
   <foo></foo>
   <foo></foo>
   <foo></foo>
</foo>
```

And for `the-root`

```
@ContentChildren(FooComponent) foos;
assert(foos.length === 4);
```

**Expected/desired behavior**
The `foo` host component should not be selected.

```
assert(foos.length === 3);
```

**Reproduction of the problem**
https://plnkr.co/edit/E7D0nMdHnPr0OxfxzysB?p=preview

**What is the motivation / use case for changing the behavior?**
Semantically, one would expect the selection of `@ContentChildren` to be only strict descendants.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.0
- **Browser:** all
- **Language:** all

**Comment by tbosch** [comment]
We have a test for this behavior, [see here](https://github.com/angular/angular/blob/master/modules/@angular/core/test/linker/query_integration_spec.ts#L27). That being said, we should decide whether this is right...

@rkirov @mhevery What do you think?

**Comment by vicb** [comment]
Could we make it an option ? Default would be false, breaking change.

**Comment by mhevery** [comment]
I think the word `children` gives it away, hence the host should not be selected. I don't see a need to select yourself.  Yes this is a bug.

**Comment by rkirov** [comment]
+1 Accessing the tag itself was part of earlier design when we had 'selfOnly' modifier. It is not needed because directives on the tag are already available for regular injection.

**Comment by christian-laakmann** [comment]
Is this possibly the same issue here: #8292 ?

**Comment by mattheiler** [comment]
Including the host is not intuitive. The host is not its own child.
This breaks recursive templates, as you will get a stack overflow.
There is a workaround: filter the query list.

`<template #itemTemplate let-item>
    <div class="tree-item">
        <div class="tree-item-header">{{ item.name }}</div>
        <div class="tree-item-content" *ngIf="item.items.length > 0 && item.expanded">
            <template *ngFor="let item of item.items" [ngTemplateOutlet]="itemTemplate" [ngOutletContext]="{ $implicit: item }"></template>
        </div>
    </div>
</template>
<div class="tree">
    <div class="tree-content" *ngIf="items.length > 0">
        <template *ngFor="let item of items" [ngTemplateOutlet]="itemTemplate" [ngOutletContext]="{ $implicit: item }">
        </template>
    </div>
</div>`

`@Directive({
    selector: 'tree-item'
})
export class TreeItem {

    constructor( @Optional() @SkipSelf() @Inject(forwardRef(() => BreadcrumbItem)) parent: TreeItem) {
    }

    @Input()
    @HostBinding('attr.disabled')
    disabled = false;

    @Input()
    expanded = false;

    @Input()
    name: string;

    @ContentChildren(TreeItem)
    private _items: QueryList<TreeItem>;

    @ContentChildren(TreeItem)
    get items(): TreeItem[] {
        return this._items.filter(item => item !== this);
    }

}`

**Comment by nitro52** [comment]
+1. Ran into this problem as well, where an inherited type needs to find all base type children. 

    <nav-list>
        <nav-list >
            <div>
                <nav-item>item1</nav-item>
            </div>
            <nav-item>Item 2</nav-item>
        </nav-list>
    </nav-list>

So a nav-list is a nav-item but with additional behavior. I'm looking for all nav-item's and using a forwardRef to include nav-list children. But it looks like its also including itself.

**Comment by stckcrsh** [comment]
I tried writing this but i keep getting the error
Operator '!==' cannot be applied to types 'this' and 'TreeItem'

`get items(): TreeItem[] {
        return this._items.filter(item => item !== this);
    }`

Is there another way to filter our itself

**Comment by nitro52** [comment]
Does anyone know of a work around to filter out the "self" item while still getting updates from angular?

as the QueryList docs say x. 

"An unmodifiable list of items that Angular keeps up to date when the state of the application changes"

Well i need to modify it while still receiving updates when the state changes. At the moment I've filtered by ID but that seems to return an Array so that would break updates wouldn't it?

`this.navigationItems = this.children.filter((navItem)=>navItem.navId != this.navId);`

**Comment by mspoerer** [comment]
+1 dev. a not expected behaviour.

**Comment by Nunien** [comment]
+1 dev. a not expected behaviour.

**Comment by Nunien** [comment]
Isn't the "self" one always the 1st element of the returned array?

**Comment by adrm** [comment]
I'm relying on this behaviour because I have a directive that may or may not be applied to a `<template>`, and I need to get the `TemplateRef` in that case. If I try to inject `TemplateRef` in the directive's constructor, I get an error since there is no `TemplateRef` to inject for the cases when the directive is not applied to a `<template>` element.

Is there some other way to get the `TemplateRef` of the host or `undefined` if it's not a template just like it happens right now with `@ContentChild(MyHostDirective, { read: TemplateRef })`? Thanks.

**Comment by wizarrc** [comment]
@adrm try instead `@Optional private templateRef: TemplateRef | null` in the constructor. I'd be interested if that would work.
https://angular.io/docs/ts/latest/cookbook/dependency-injection.html#!#qualify-dependency-lookup

**Comment by adrm** [comment]
@wizarrc It works! `@Optional` is definitely the correct answer for my case. This is what I inject now: `@Optional() public cellTemplate: TemplateRef<any>`. It doesn't work if I try to add the `null` type, seems to confuse the DI.

Thanks!

**Comment by wizarrc** [comment]
@adrm Good to hear. I updated my comment

**Comment by wizarrc** [comment]
@adrm Another thought. Because it's a parameter maybe `@Optional() public cellTemplate: TemplateRef<any> | undefined` would work instead using `undefined` instead of `null`. I only mention this because in strictNullCheck mode, I want the compiler to make sure I check if it exists before I try to dot into it.

**Comment by desfero** [comment]
Is there any updates regarding this bug?

**Comment by nitro52** [comment]
I would also love to know as its a blocking issue

**Comment by tytskyi** [comment]
@desfero @nitro52 As a workarond you can use component inheritance to create 2 the same components with different class names, but override `ContentChildren` query to use each other.  And only use one in onther. 

Like 
```
<foo-odd>
  <foo-even>
</foo-odd>

<!-- or -->
<foo-even>
  <foo-odd>
</foo-even>
```

I modified original plunker to show an example: http://plnkr.co/edit/1YZfOzReblMLXqvralkZ?p=preview

**Comment by desfero** [comment]
@tytskyi but we can also use `.filter(x => x !== this)`, we don't need to introduce additional components i guess

**Comment by linktothapast** [comment]
FWIW, I just spent at least 3 hours debugging because I never would've expected the component itself to be matched by `@ContentChildren`. Not at all the expected behavior IMO.

**Comment by dirkluijk** [comment]
+1 removing, or better, for making this an option.

`.filter(x => x !== this)` doesn't work in my case as I use 2 different types of directives:

```
<div parentDirective>
  <div childDirective></div>
  <div childDirective></div>
</div>
```
Where I want to be able to repeat this:
```
<div parentDirective>
  <div childDirective parentDirective> <-- goes wrong, parent has also itself as child
     <div childDirective></div>
   </div>
  <div childDirective></div>
</div>
```

**Comment by kklimczak** [comment]
The most annoying case connected with this issue, is when I call method from children. After run app, I get in console `RangeError: Maximum call stack size exceeded`.

**Comment by fetis** [comment]
will it be fixed in Ivy engine?

**Comment by pkozlowski-opensource** [comment]
> will it be fixed in Ivy engine?

@fetis Yes

**Comment by mind0n** [comment]
Hi guys,

Looks like this bug still exists in the latest angular 7?  Who is going to fix this?

**Comment by dudewad** [comment]
+1 Yeah I am also seeing the issue. Easy enough to work around but i'm surprised that this was reported 3 years ago and hasn't been fixed; it seems like a pretty important break in terms of confusion/intuive-ness.

**Comment by pkozlowski-opensource** [comment]
This is fixed in v9 with ivy: https://ng-run.com/edit/Z8gBDyjXvcl4jAj4wNbC

**Comment by StefanKern** [comment]
We used this feature, that @ViewChild selected the Hostcompoennt as well. 

What is the correct way to select an element from the Host component

**Comment by pkozlowski-opensource** [comment]
> . What is the correct way to select an element from the Host component now?

Inject a directive instance in a constructor.

**Comment by StefanKern** [comment]
@pkozlowski-opensource how can I do that? 

I tried `constructor(@Host() public viewport: CdkVirtualScrollViewport) {` but got 
`ERROR Error: Uncaught (in promise): Error: Circular dep for CdkVirtualScrollViewport`

**Comment by pkozlowski-opensource** [comment]
@StefanKern I'm sorry, it is super-hard to help without seeing the exact use-case. Can you setup a minimal reproduce scenario using https://ng-run.com/ ?

**Comment by StefanKern** [comment]
Sorry, my problem was that I use CdkVirtualScrollViewport in the the component and the `VirtualScrollStrategy`. So the problem is unrelated to the change, I will delete the compents later.

Please like if this is OK for you, not that your comments are still there then, without pointing to the questions :)
