### ISSUE TITLE
Router: lazy loaded component can't see service provided in its lazy loaded AppModule

### ISSUE THREAD

**Issue by wardbell** [angular/angular#10115]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request 
```
**Use Case**
Lazy loading a feature area with its own components, services, etc.

Want the same service instance to be used in a router guard and by the components that will be loaded with configuration specified in that lazy loaded AppModule.

For guarding, I must provide it in the AppModule.  

**Current behavior**

A service provided in the lazy loaded AppModule is **not** available to the components that are lazy loaded with that module.

It appears that they are instantiated with the application's root injector, not the child injector of the lazy loaded AppModule.

Consequently, have to re-provide the service, potentially in the lazy modules top routing component. Of course this is **not** the same service instance. That can be a problem if the service has state (e.g., fetches data and stores in cache).

**Expected/desired behavior**

A service provided in the lazy loaded AppModule should be available to all components lazily loaded via that AppModule.

I believe that would happen automatically if lazily loaded component injectors "inherited" from their parent AppModule's injector.

**Reproduction of the problem**
See http://plnkr.co/edit/17wH7sSm87TXUajNPQ1q?p=preview

The plunker pulls from the latest build on master (as of date of this issue, 16 July 2016). 

`HeroService` is provided in `app/hero/hero.module.ts`, the lazy loaded AppModule.

I had to re-provide it on line #10 in `app/hero/hero.component.ts` .

Run the plunker and navigate to "Heroes". It works.

Comment out line #10  and refresh. You'll see it fail with console error: "No provider for HeroService!"

**Comment by choeller** [comment]
I think this is a dub of the issue I just opened some days ago: https://github.com/angular/angular/issues/10044.

**Comment by PascalPrecht** [comment]
This has been fixed here: https://github.com/angular/angular/commit/85be729c70d278763f03589ac342ba6e1bdd2e14

**Comment by choeller** [comment]
@PascalPrecht @wardbell 
I think this is still not working as expected. I built from master and my use-case still didn't work. I also added a comment to #85be729 but did not get any feedback yet.

**Comment by wardbell** [comment]
Right. When I filed my issue, I based it on 1803ed2 which is several days later than 85be729

**Comment by vsavkin** [comment]
Fixed https://github.com/angular/angular/pull/10149
