### ISSUE TITLE
Http.get returned observables don't trigger a change detection

### ISSUE THREAD

**Issue by leonceeo** [angular/angular#10208]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using angular2-rc.4

I have a rxjs Observable returned by a _http.get(...)_ operation. I'm subscribing to it, however the model changes which occur in the subscription don't get reflected in the UI. Invoking the _http.get(...)_ operation once again triggers the UI updates which should have happened previously.

If I convert the Observable to a Promise, things work as expected. The Promise subscription modifies the variables which in turn trigger the angular change detection.

I've noticed that the rxjs subscribing function doesn't get called inside a ngzone.

> VM43288 app.ts!transpiled:48 console.trace()(anonymous function) @ VM43288 app.ts!transpiled:48SafeSubscriber.__tryOrUnsub @ VM43294 Subscriber.js:225SafeSubscriber.next @ VM43294 
Subscriber.js:174Subscriber._next @ VM43294 
Subscriber.js:124Subscriber.next @ VM43294 
Subscriber.js:88Subscriber._next @ VM43294 
Subscriber.js:124Subscriber.next @ VM43294 
Subscriber.js:88MapSubscriber._next @ VM43306 
map.js:82Subscriber.next @ VM43294 
Subscriber.js:88onLoad @ VM43634 
xhr_backend.js:68

Promise subscription get's called inside a ngzone

> (anonymous function)	@	VM43288 app.ts!transpiled:55
ZoneDelegate.invoke	@	VM43271 zone.js@0.6.12:281
onInvoke	@	VM43368 ng_zone_impl.js:53
ZoneDelegate.invoke	@	VM43271 zone.js@0.6.12:280
Zone.run	@	VM43271 zone.js@0.6.12:174
(anonymous function)	@	VM43271 zone.js@0.6.12:529
ZoneDelegate.invokeTask	@	VM43271 zone.js@0.6.12:314
onInvokeTask	@	VM43368 ng_zone_impl.js:44
ZoneDelegate.invokeTask	@	VM43271 zone.js@0.6.12:313
Zone.runTask	@	VM43271 zone.js@0.6.12:214
drainMicroTaskQueue	@	VM43271 zone.js@0.6.12:432

**Expected/desired behavior**
I'm expecting the Observable subscription to work the same as the Promise subscription.

**Reproduction of the problem**
[Plunker](https://embed.plnkr.co/fC4XMB/)

The app displays two buttons. On the first button, I'm using rxjs observables, on the second one js promises. A click on the first button doesn't show anything, a second event is necessary in order to trigger change detection. The second button reacts on the first click.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Chrome 53.0.2785.8 | Firefox 47.0 | Safari 9.1.1 ] 
 
* **Language:** [TypeScript 1.8]

**Comment by zoechi** [comment]
I got an error for accessing `test.json` from within Plunker using HTTP therefore I changed the code to use another server (that allows CORS requests) and I can't reproduce.

https://plnkr.co/edit/zQAW26?p=info

**Comment by zoechi** [comment]
I updated to Plunker because I got an error for accessing `test.json` 
https://plnkr.co/edit/zQAW26?p=preview reproduces (please ignore my previous comment)

**Comment by gdi2290** [comment]
for some reason the callback is being invoked in the root zone
https://plnkr.co/edit/Mo1iX4fEEHuvcaCuLWd2?p=preview
the workaround would be to wrap the callback within the current angular zone
```typescript
      .subscribe(Zone.current.wrap(val => {
        console.log(val);
        this.rxjsResponse = val;
        
      }));
```

**Comment by gdi2290** [comment]
oh I found the problem. the zone.js on npmcdn is giving us the node version rather than the browser version. so it's not patching XMLHttpRequest

**Comment by gdi2290** [comment]
change your script for zone to 
<script src="https://npmcdn.com/zone.js@0.6.12?main=browser"></script>
notice the `?main=browser`
https://npmcdn.com/#/query-parameters

**Comment by sunshineo** [comment]
+1
I'm experiencing this with the Safari browser only.
I had to use the solution here[http://stackoverflow.com/questions/37980271/angular-2-ui-not-updating-when-items-added-to-array-on-image-onload] to manually trigger change detection.

**Comment by qdouble** [comment]
@sunshineo are you using rc4 or earlier? The issue should be fixed in rc5.

**Comment by sunshineo** [comment]
@qdouble I'm using rc5. It's not fixed. Not for Safari

**Comment by guojenman** [comment]
Possibly related to a bug which I thought only affected UpgradeAdapter but seems to be a problem w/ angular/zone: https://github.com/angular/angular/issues/11572#issuecomment-247262774.

My Plnker is using v2.0.0 final and illustrate this bug only only with Http but also with setTimeout
https://plnkr.co/edit/B3sSt9?p=preview

**Comment by sunshineo** [comment]
This bug made into the final version? :(

**Comment by sunshineo** [comment]
I think this is fixed. I moved to 2.0.1 and seems I don't need my workaround anymore.

**Comment by pkozlowski-opensource** [comment]
Based on all the comments it looks like the issue is fixed now.

**Comment by metzc** [comment]
@pkozlowski-opensource i'm on angular 2.0.2 and i still have the issue that on Safari updates in an Observable are not detected (for example when using an async pipe).

**Comment by pkozlowski-opensource** [comment]
> i'm on angular 2.0.2 and i still have the issue that on Safari updates in an Observable are not detected (for example when using an async pipe).

Please open a new issue then and fill in issue template.

**Comment by DzmitryShylovich** [comment]
@metzc what zone.js version do u use?

**Comment by metzc** [comment]
@DzmitryShylovich 0.6.25

**Comment by metzc** [comment]
@pkozlowski-opensource i could narrow the problem down, please tell me if you think this issue is still angular related, then i'll create a new ticket:

I'm using PouchDB (6.0) which has a custom "change" event. If i call observer.next within that change callback, angular (2.1.0) stays blind on safari (a template var with an async pipe only gets updated after the next change detection run). I just tried to wrap "observer.next" in a zone.run call and it starts working. On Chrome it also works without.

**Comment by pkozlowski-opensource** [comment]
@metzc I'm sorry but I can't say if an issue is related to Angular or not without reproduce scenario....

**Comment by DzmitryShylovich** [comment]
> I'm using PouchDB (6.0) which has a custom "change" event. If i call observer.next within that change callback 

You should run callback inside `NgZone.run`

**Comment by metzc** [comment]
@DzmitryShylovich yes thats what i did now. thanks all. its just strange that it works perfectly in Chrome without zone.run

**Comment by sebek64** [comment]
I've seen the same bug in angular 2.4.5 in an hybrid app. I'll try to isolate a small reproduction case soon.

**Comment by sebek64** [comment]
At first, I suspected that it is caused by angular-ui-router. But since it is fixed in 2.4.6, I guess it was the same as https://github.com/angular/angular/issues/14182.

**Comment by aabluedragon** [comment]
Happens for me using 2.4.6 and 2.4.7.
reproduces only on Safari, works fine on Chrome.

**Comment by mightypenguin** [comment]
I believe I'm seeing this issue with angular-cli angular v4.0.0 (zone.js v0.8.5)
Seeing this with both setTimeout and http.post .subscribe

**Comment by aabluedragon** [comment]
The issue I encountered was fixed in https://github.com/angular/zone.js/issues/671 (the fix was applied in a later release of `zone.js`)
