### ISSUE TITLE
Use of '+' character in URLSearchParams()

### ISSUE THREAD

**Issue by gnujeremie** [angular/angular#11058]
**I'm submitting a ...**

```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Code exemple

```
let body = new URLSearchParams();

for (let i in values) {
    body.set(i, values[i]);
}

let options = RequestOptions();
options.headers.append('Content-Type', 'application/x-www-form-urlencoded')
return this.http.post(uri, body, options).then();
[...]
```

If `values[i]` has a '+' character in it, then it is replaced by spaces. 

**Expected/desired behavior**
'+' should be sent as any other character.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Browser:** [all | Chrome XX | Firefox XX | IE XX ] 
- **Language:** [Typescript]

**Comment by vicb** [comment]
Have you checked for pending issues / PRs ?

**Comment by gnujeremie** [comment]
I checked for the pending issues, found nothing, but now looking for PRs, it may be related to this one https://github.com/angular/angular/pull/9651 . But it is merged, so I should not have the problem right ? Or do I do something wrong ? >.<

**Comment by gnujeremie** [comment]
After digging deeper, it seems like the value posted is ok, (and the '+' appears in the string), but it's on the server side, it is replaced by an empty space, even when I simply get it from $_POST in PHP.

**Comment by mhevery** [comment]
Your code example does not actually show the issue. Could you create a better example for reproducing the problem?

**Comment by gnujeremie** [comment]
Sure : 
```javascript
let body = new URLSearchParams();

body.set('label', 'here is a label with + in it');

let options = RequestOptions();
options.headers.append('Content-Type', 'application/x-www-form-urlencoded')
return this.http.post('http://localhost/admin/save/', body, options).then();
[...]
```

Then, in ```admin/save``` :
```php
$label = $_POST['label'];
echo $label;
```
It displays : 
```
here is a label with    in it
```

When I check the browser dev tools, I can see that the value sent is ```here is a label with + in it```, so I am not sure if this is an angular bug or if it is the way PHP handles it. For now, I fixed it by using a custom QueryEncoder with ```URLSearchParams('', new CustomQueryEncoder())```, with encodeKey() and encodeValue() just doing this : 
```javascript
    encodeKey(k: string): string {
        return this.encode(k);
    }
    encodeValue(v: string): string {
        return this.encode(v);
    }

    private encode(v: string): string {
        return encodeURIComponent(v)
        .replace(/%40/gi, '@')
        .replace(/%3A/gi, ':')
        .replace(/%24/gi, '$')
        .replace(/%2C/gi, ',')
        .replace(/%3B/gi, ';')
        //.replace(/%2B/gi, '+')
        .replace(/%3D/gi, ';')
        .replace(/%3F/gi, '?')
        .replace(/%2F/gi, '/');
  }
```

**Comment by Bolza** [comment]
I'm using an API that requires an `application/x-www-form-urlencoded` format for the payload.
Now if i want to send a string containing the character `+` for example, it doesn't get encoded but if i try to encode it myself (with `%2B` ) it gets double-encoded because the `%` gets encoded as well.

What would be the solution for this issue?

**Comment by hjalle** [comment]
Is it the same problem when navigating to an URL? 
When going to for example
http://localhost:5000/?q=test+test
the url suddenly http://localhost:5000/?q=test%2Btest

Thats the way in 2.0.0 as well..

**Comment by tinchou** [comment]
I'm experiencing this issue and `GhQueryEncoder` seems to fix it. 

Note: The Chrome inspector shows an empty space in the Form Data for my POST request, but if I click "view source" right next to "Form Data" it does appear.

My server is an ASP.NET Core application with all the defaults for model binding.

**Comment by manklu** [comment]
Excerpt of the [HTML 4.01](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1) specification
>Control names and values are escaped. Space characters are replaced by `+', and ...

So '+' is a reserved character.

The [HTML 5](https://www.w3.org/TR/html5/forms.html#application/x-www-form-urlencoded-encoding-algorithm) specification includes a much better description of the application/x-www-form-urlencoded encoding.

**Comment by manklu** [comment]
>as + becomes space in some PHP implementations.

Also in Tomcat, and thus in all the servers that use it behind the scenes.

**Comment by laserus** [comment]
Addition to this issue: I have a param that is ISO8601 (2016-10-03T13:27:25+03:00) 

UrlSearchParams.append makes this + sing into spaces. Given that this issue here from Aug19th and complicated, is there good workaround for this?

**Comment by tinchou** [comment]
Yes, the workaround is to use the GhQueryEncoder (see above) or any other encoder that would fit your needs.

But we probably need this to be compliant instead of using workarounds.

**Comment by laserus** [comment]
@Bolza @tinchou while we at it. Why  encodeValue(v: string): string  uses super.encodeKey but not super.encodeValue? Is there a particular reason?

**Comment by nicolashenry** [comment]
Why angular's URLSearchParams does not work like the standard URLSearchParams (https://url.spec.whatwg.org/#urlsearchparams) by default ?

I tested angular with this test https://github.com/w3c/web-platform-tests/blob/master/url/urlsearchparams-stringifier.html :

```typescript

import { URLSearchParams } from '@angular/http';

function test(fn: Function, text: string) {
	fn();
}

function assert_equals(o1: any, o2: any) {
	if (o1 !== o2) {
		console.error(o1 + ' should be equals to ' + o2);
	}
}

test(function () {
	var params = new URLSearchParams();
	params.append('a', 'b c');
	assert_equals(params + '', 'a=b+c');
	params.delete('a');
	params.append('a b', 'c');
	assert_equals(params + '', 'a+b=c');
}, 'Serialize space');
test(function() {
	var params = new URLSearchParams();
	params.append('a', '');
	assert_equals(params + '', 'a=');
	params.append('a', '');
	assert_equals(params + '', 'a=&a=');
	params.append('', 'b');
	assert_equals(params + '', 'a=&a=&=b');
	params.append('', '');
	assert_equals(params + '', 'a=&a=&=b&=');
	params.append('', '');
	assert_equals(params + '', 'a=&a=&=b&=&=');
}, 'Serialize empty value');
test(function() {
	var params = new URLSearchParams();
	params.append('', 'b');
	assert_equals(params + '', '=b');
	params.append('', 'b');
	assert_equals(params + '', '=b&=b');
}, 'Serialize empty name');
test(function() {
	var params = new URLSearchParams();
	params.append('', '');
	assert_equals(params + '', '=');
	params.append('', '');
	assert_equals(params + '', '=&=');
}, 'Serialize empty name and value');
test(function() {
	var params = new URLSearchParams();
	params.append('a', 'b+c');
	assert_equals(params + '', 'a=b%2Bc');
	params.delete('a');
	params.append('a+b', 'c');
	assert_equals(params + '', 'a%2Bb=c');
}, 'Serialize +');
test(function() {
	var params = new URLSearchParams();
	params.append('=', 'a');
	assert_equals(params + '', '%3D=a');
	params.append('b', '=');
	assert_equals(params + '', '%3D=a&b=%3D');
}, 'Serialize =');
test(function() {
	var params = new URLSearchParams();
	params.append('&', 'a');
	assert_equals(params + '', '%26=a');
	params.append('b', '&');
	assert_equals(params + '', '%26=a&b=%26');
}, 'Serialize &');
test(function() {
	var params = new URLSearchParams();
	params.append('a', '*-._');
	assert_equals(params + '', 'a=*-._');
	params.delete('a');
	params.append('*-._', 'c');
	assert_equals(params + '', '*-._=c');
}, 'Serialize *-._');
test(function() {
	var params = new URLSearchParams();
	params.append('a', 'b%c');
	assert_equals(params + '', 'a=b%25c');
	params.delete('a');
	params.append('a%b', 'c');
	assert_equals(params + '', 'a%25b=c');
}, 'Serialize %');
test(function() {
	var params = new URLSearchParams();
	params.append('a', 'b\0c');
	assert_equals(params + '', 'a=b%00c');
	params.delete('a');
	params.append('a\0b', 'c');
	assert_equals(params + '', 'a%00b=c');
}, 'Serialize \\0');
test(function() {
	var params = new URLSearchParams();
	params.append('a', 'b\uD83D\uDCA9c');
	assert_equals(params + '', 'a=b%F0%9F%92%A9c');
	params.delete('a');
	params.append('a\uD83D\uDCA9b', 'c');
	assert_equals(params + '', 'a%F0%9F%92%A9b=c');
}, 'Serialize \uD83D\uDCA9');  // Unicode Character 'PILE OF POO' (U+1F4A9)
test(function() {
	var params: URLSearchParams;
	params = new URLSearchParams('a=b&c=d&&e&&');
	assert_equals(params.toString(), 'a=b&c=d&e=');
	params = new URLSearchParams('a = b &a=b&c=d%20');
	assert_equals(params.toString(), 'a+=+b+&a=b&c=d+');
	// The lone '=' _does_ survive the roundtrip.
	params = new URLSearchParams('a=&a=b');
	assert_equals(params.toString(), 'a=&a=b');
}, 'URLSearchParams.toString');

```

The result :
```
a=b%20c should be equals to a=b+c
a%20b=c should be equals to a+b=c
a=b+c should be equals to a=b%2Bc
a+b=c should be equals to a%2Bb=c
==a should be equals to %3D=a
==a&b== should be equals to %3D=a&b=%3D
a=b&c=d&=&=&=&e= should be equals to a=b&c=d&e=
a%20=%20b%20&a=b&c=d%2520 should be equals to a+=+b+&a=b&c=d+
```

**Comment by swierchola** [comment]
Same problem with `+` encoding, but after migration from AngularJS. In AngularJS it worked fine. In backend we have Jetty and Scalatra. It interpretes `+` as `space`.

In AngularJS we used service [$httpParamSerializerJQLike](https://docs.angularjs.org/api/ng/service/$httpParamSerializerJQLike) for POST. Internally it uses [encodeUriQuery] (https://github.com/angular/angular.js/blob/6f072c8a415ae942e584681b7ee999023351c4ab/src/Angular.js#L1424) function:
```javascript
/**
 * This method is intended for encoding *key* or *value* parts of query component. We need a custom
 * method because encodeURIComponent is too aggressive and encodes stuff that doesn't have to be
 * encoded per http://tools.ietf.org/html/rfc3986:
 *    query         = *( pchar / "/" / "?" )
 *    pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
 *    unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
 *    pct-encoded   = "%" HEXDIG HEXDIG
 *    sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
 *                     / "*" / "+" / "," / ";" / "="
 */
function encodeUriQuery(val, pctEncodeSpaces) {
  return encodeURIComponent(val).
             replace(/%40/gi, '@').
             replace(/%3A/gi, ':').
             replace(/%24/g, '$').
             replace(/%2C/gi, ',').
             replace(/%3B/gi, ';').
             replace(/%20/g, (pctEncodeSpaces ? '%20' : '+'));
}
```
`encodeUriQuery("+") ` returns `%2B`.

In Angular 2 URLSearchParams internally uses  [standardEncoding](https://github.com/angular/angular/blob/2.2.0/modules/%40angular/http/src/url_search_params.ts#L33) function. It has more characters that are not encoded:
```javascript
function standardEncoding(v: string): string {
  return encodeURIComponent(v)
      .replace(/%40/gi, '@')
      .replace(/%3A/gi, ':')
      .replace(/%24/gi, '$')
      .replace(/%2C/gi, ',')
      .replace(/%3B/gi, ';')
      .replace(/%2B/gi, '+')
      .replace(/%3D/gi, '=')
      .replace(/%3F/gi, '?')
      .replace(/%2F/gi, '/');
}
```
`standardEncoding("+") ` returns `+`.

**Comment by robwormald** [comment]
For V3/4 I reckon we should drop this type, and delegate to the native implementation, and require it to be polyfilled otherwise. This is currently akin to importing `Promise` and that's something we want to avoid.

Polyfill - https://github.com/WebReflection/url-search-params

**Comment by nbuso** [comment]
I'm experiencing the same problem as hjalle. Is URLSearchParams linked with a rewriting of the URL? Is it possible to avoid this behaviour with some configuration?

**Comment by ayrad** [comment]
This is still happening in Angular 4.0.1.
`mohammadi+1` is left as it is and should be `mohammadi%2B1`.
Temporarily fixed this by adding a custom QueryEncoder (like `GhQueryEncoder`) that extends the parent `QueryEncoder`.

IMO this should be done in the default QueryEncoder.

**Comment by jsgoupil** [comment]
Can you share that encoder @ayrad please?

**Comment by ayrad** [comment]
@jsgoupil actually, it's same approach as the one shared right [here](#issuecomment-247367318).

Full usage is just below.

```typescript
/*
 * CustomQueryEncoderHelper
 * Fix plus sign (+) not encoding, so sent as blank space
 * See: https://github.com/angular/angular/issues/11058#issuecomment-247367318
 */
import { QueryEncoder } from "@angular/http";

export class CustomQueryEncoderHelper extends QueryEncoder {
    encodeKey(k: string): string {
        k = super.encodeKey(k);
        return k.replace(/\+/gi, '%2B');
    }
    encodeValue(v: string): string {
        v = super.encodeValue(v);
        return v.replace(/\+/gi, '%2B');
    }
}
```


```typescript
import { CustomQueryEncoderHelper } from '../shared/helpers';
//...
login(username: string, password: string) {
	let headers = new Headers({
		'Accept': 'application/json',
		'Content-Type': 'application/x-www-form-urlencoded'
	});

	let params: URLSearchParams = new URLSearchParams('', new CustomQueryEncoderHelper());
	params.append('username', username);
	params.append('password', password);

	return this.http.post(this.loginUrl, params.toString(), { headers: headers }).map((response: Response) => {
		//...
	});
}
//...
```

**Comment by mmedic** [comment]
This is still an issue in angular 4.

**Comment by NKjoep** [comment]
@ayrad in your example you are using a `http.post`. Does it work with `http.get` as well?

The two methods have a different signature and I am afraid doesn't work with the `http.get`.

**Comment by kernwig** [comment]
@NKjoep Just search for how to URLSearchParams with http.get. There are many examples on stack exchange. Just pass the `new CustomQueryEncoderHelper()` into the constructor as shown above, and otherwise use like normal.

I just ran into this rather obvious bug. Ten months without a one-liner fix is just sad.

**Comment by wOOx92** [comment]
Any Updates here?

**Comment by jameskleeh** [comment]
Still hitting this issue in Angular 4.2

**Comment by erinhoeam** [comment]
I still have this problem with the version of Angular
   "dependencies": {
     "@ angular / animations": "^ 4.4.0-RC.0",
     "@ angular / common": "^ 4.4.0-RC.0",
     "@ angular / compiler": "^ 4.4.0-RC.0",
     "@ angular / core": "^ 4.4.0-RC.0",
     "@ angular / forms": "^ 4.4.0-RC.0",
     "@ angular / http": "^ 4.4.0-RC.0",
     "@ angular / platform-browser": "^ 4.4.0-RC.0",
     "@ angular / platform-browser-dynamic": "^ 4.4.0-RC.0",
     "@ angular / router": "^ 4.4.0-RC.0",

When I have a URL with "+" that is changed by% 2B a 404 error is thrown

  http://www.condominio-mais.com/usuario/resetar/4995ffba-6e78-486e-8653-0fb8f4e6996e/CfDJ8KvZVIfag49BieUUcQkCHC0WR%2FQNYNjUtosCAOJ6V5VTJHn0phbIUB4zWt2wWX3rKBK3iwrktVIzeuuZ5bYOQYFMGSN2cFTkKx%2B7AcN0Uw7KcpPwkhU2fGDAMUssZMxwqNnoEPscVdZIQJlQ4NvbAyHSJk4I9g1wjZoTumSiT5VDDkebFvjild8RVoFtXYcsObpvpfgmxT3Cdld5h%2Fot3L5h3qkYSbfbg%2BxcE1VTxJb5saXQYWtnnDBJb4aBwH5zZg%3D%3D

**Comment by dani-inside** [comment]
We also hit this issue, with Angular 2.4.8. It took as quite a while to find the root cause of the issue, as we also experienced the issue of double encoding whenever we tried to manipulate the encoding of URLSearchParams. The solution of @ayrad / @Bolza worked out though, thanks for that. I assume this should be addressed anyway in upcoming Angular releases.

**Comment by tiangolo** [comment]
This also affects Flask back ends.

Flask follows the W3C standard and converts `+` characters to a "space" character (` `).

I could create a PR [removing that line](https://github.com/angular/angular/blob/master/packages/common/http/src/params.ts#L64).

```TypeScript
...
      .replace(/%2B/gi, '+')
...
```

...but first I would like to ask, is there a reason why you overrode the standard `encodeURIComponent`? 

It seems like the code was clearly written to override the default encoding and override the encoding / escaping of reserved characters (like `+`).

@alxhub could you explain to us what was the idea / motivation in that code section and if you see any better approach to solving it? Git blame says you're the person to ask...

Would it be acceptable if I create a PR removing the custom overriding and decoding for reserved characters?

**Comment by trotyl** [comment]
@tiangolo `encodeURIComponent` does not follow W3C/WHATWG standard as well,
W3C/WHATWG Standard is: ` ` -> `+` & `+` -> `%2B`
encodeURIComponent is: ` ` -> `%20` & `+` -> `%2B`

There is nothing wrong to rewrite the result of `encodeURIComponent`, the problem is for how to rewrite it.

**Comment by tiangolo** [comment]
Thanks for the clarification @trotyl . 

I guess that both W3C/WHATWG and `encodeURIComponent` end up rendering a valid and "compatible" URL. At least, parseable by back ends without creating side effects.

But the current encoder is actually reversing it, it is taking the encoded version of `+`, that results from `encodeURIComponent` (and would be the same effect using the W3C/WHATWG encoding) and converting it back to a literal `+`.

`%2B` -> `+` 

instead of leaving 

`+` -> `%2B` (that is compatible with both versions)

And the same for: `@`, `:`, `$`, `,`, `;`, `+`, `=`, `?`, `/`.

I can imagine how it could generate problems having those characters being parsed by the back end literally, unencoded, in parameter keys or values. At least for: `:`, `+`, `=`, `?`, `/`.

As of now, we have confirmed that it creates issues with PHP and Python back ends, from the comments above. I imagine there could be more back end languages and frameworks that would expect encoded params in a way that is compatible with at least one of W3C/WHATWG or `encodeURIComponent`.

---

I know this project is huge, with more than 250 PRs open (including a 2 months old one from me). So I don't know if submitting a PR is actually appreciated. Especially before knowing if the changes would acceptable.

@alxhub could you give us a hint? What was the reason for overwriting the native `encodeURIComponent`? Would a PR removing one or more of those lines be acceptable / desired?

**Comment by JoshuaBaert** [comment]
I'm having this same issue. I don't believe it is related to the server or back-end at all...

After sending the post in angular you can find it being displayed in Chrome debug tools here.

![2017-09-25 19_28_36-urltest](https://user-images.githubusercontent.com/22752236/30837092-16a5a52c-a228-11e7-9f43-61c1cce5efe1.png)

Do we know if the angular team is working on this?

**Comment by pckrishnadas88** [comment]
I don't think it's an issue at the server side. Am using node with angular version **4.3.6** and having the same issue.

**Comment by maximelafarie** [comment]
Error still here in Angular 4.4.4 . Hope you'll fix that in Angular 5 !

**Comment by SayakMukhopadhyay** [comment]
Issue present in Angular 5

**Comment by tiangolo** [comment]
I created a PR to solve this here: https://github.com/angular/angular/pull/19711

And to solve the same problem when using `HttpClientModule` and `HttpClient`: https://github.com/angular/angular/pull/19710 .

But they have been there waiting to be reviewed since October.

---

So, I created a package to solve it (at least while it is reviewed / merged) for the case of `HttpClient`. It's a simple drop-in replacement that modifies the minimum to fix the problem. It works with just changing one import.

Check it here: https://github.com/tiangolo/ngx-http-client

**Comment by ravraponi** [comment]
For angular 5.1 create your own encoder:


```
import {HttpParameterCodec} from '@angular/common/http'

/**
 * A `HttpParameterCodec` that uses `encodeURIComponent` and `decodeURIComponent` to
 * serialize and parse URL parameter keys and values.
 *
 * @stable
 */
export class WebHttpUrlEncodingCodec implements HttpParameterCodec {
  encodeKey(k: string): string { return encodeURIComponent(k); }

  encodeValue(v: string): string { return encodeURIComponent(v); }

  decodeKey(k: string): string { return decodeURIComponent(k); }

  decodeValue(v: string) { return decodeURIComponent(v); }
}
```


Then in HttpParams add it as an option!

```
const params = new HttpParams({encoder: new WebHttpUrlEncodingCodec() })
.set('username', this.anonUsername)
.set('password', this.anonPassword);
```

**Comment by SayakMukhopadhyay** [comment]
I am currently using the custom encoder solution but looking at the tags in this issue, it seems like this has been acknowledged as a bug.

**Comment by dtwright** [comment]
So I've run into this as well, and will implement a fix as advised above (with a custom encoder) - but I have to ask, what possible reason is there for this bug to still be open? It is just plain incorrect according to the HTTP standards to *not* encode + as %2B, so am I missing something here?

**Comment by tiangolo** [comment]
@dtwright I wrote a section explaining all the details I found in the package I created to solve the problem: https://github.com/tiangolo/ngx-http-client#very-technical-details

**Comment by jameskleeh** [comment]
How is this simple of an issue not resolved yet after **1.5 years**?

**Comment by tiangolo** [comment]
You can try the package I built to solve it: https://github.com/tiangolo/ngx-http-client

---

```bash
npm install --save ngx-http-client
```

And in your code, replace this line:

```TypeScript
import {HttpClientModule} from '@angular/common/http';
```

with:

```TypeScript
// import {HttpClientModule} from '@angular/common/http';

import {HttpClientModule} from 'ngx-http-client';
```

...that's it. The rest of your code is the same. Let me know if it works (or not).

**Comment by auqfyanjun** [comment]
I am from china ,so sorry for my English .....  I have the same problem  when i post (use httpCilent), if post data have "+" ,ng maybe change it as space . I find router path could not have "+" also..

**Comment by SayakMukhopadhyay** [comment]
@auqfyanjun check the comment https://github.com/angular/angular/issues/11058#issuecomment-351864976 or a package developed for this purpose as mentioned in https://github.com/angular/angular/issues/11058#issuecomment-357861890

**Comment by auqfyanjun** [comment]
@SayakMukhopadhyay   HI ,THS for you help ,I find in this comment ,maybe someoen has give me answer,
when  post , i will change HttpParams use next way,  ''  httpParams.toString().replace(/\+/g, '%2B')  ''  .

**Comment by moxival** [comment]
Is this issue ever get resolved or at least someone from the team to explain why it works the way it works and why it is not resolved, it is infuriating that Angular (5+) brakes this simple standard?

**Comment by elias-garcia** [comment]
Same issue here, I can't send dates in ISO 8601 format to the API because the `+` sign is being replace by a blank space...

**Comment by mrutter** [comment]
Same issue here.

I'm using URLSearchParams to prepare the parameters to post to the auth/token service. The '+' char is replaced/encoded with a space so the authentication fails.

**Comment by jmesquita** [comment]
Ain't what the PR #19711 is trying to address for us and it is just sitting there?

**Comment by ptixed** [comment]
xD
ahem
I mean... 
same issue here

**Comment by cloud2806** [comment]
How to deal with it in Angular 5.X
First of all create custom encoder:

**Comment by dmayes403** [comment]
Here's how I solved encoding a dynamic set of params:

Create the custom encoder:
`export class CustomQueryEncoderHelper implements HttpParameterCodec {
    encodeKey(k: string): string {
        return encodeURIComponent(k);
    }

    encodeValue(v: string): string {
        return encodeURIComponent(v);
    }

    decodeKey(k: string): string {
        return decodeURIComponent(k);
    }

    decodeValue(v: string): string {
        return decodeURIComponent(v);
    }
}`

Create helper function to convert params:
`toHttpParams(params) {
        return Object.getOwnPropertyNames(params)
            .reduce((p, key) => p.set(key, params[key]), new HttpParams({encoder: new CustomQueryEncoderHelper()}));
    }`

Usage:
`get<T>(url: string, params?: {}): Observable<T> {
        let convertedParams;
        if (params) {
            convertedParams = this.toHttpParams(params);
        }

        return this.http.get(`${this.prefix}${url}`, { params: convertedParams }).pipe(
            map((response: T) => {
                return response;
            }),
            catchError((error: Response) => {
                return throwError(error);
            })
        );
    }`

**Comment by dmayes403** [comment]
Here's how I solved encoding a dynamic set of params:

Create a custom encoder:

```
export class CustomQueryEncoderHelper implements HttpParameterCodec {
    encodeKey(k: string): string {
        return encodeURIComponent(k);
    }

    encodeValue(v: string): string {
        return encodeURIComponent(v);
    }

    decodeKey(k: string): string {
        return decodeURIComponent(k);
    }

    decodeValue(v: string): string {
        return decodeURIComponent(v);
    }
}
```

Create a helper function to convert params:

```
toHttpParams(params) {
        return Object.getOwnPropertyNames(params)
            .reduce((p, key) => p.set(key, params[key]), new HttpParams({encoder: new CustomQueryEncoderHelper()}));
    }
```

Usage:

```
get<T>(url: string, params?: {}): Observable<T> {
        let convertedParams;
        if (params) {
            convertedParams = this.toHttpParams(params);
        }

        return this.http.get(url, { params: convertedParams }).pipe(
            map((response: T) => {
                return response;
            }),
            catchError((error: Response) => {
                return throwError(error);
            })
        );
    }
```

**Comment by CristuNaranjo** [comment]
More than 2 years and still open...

**Comment by hajdun** [comment]
+1  
I HATE THIS STUFF WE HAVE PHONE NUMBERS  like +36....

**Comment by atscott** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. `URLSearchParams` is no longer part of Angular. Please update to the most recent Angular version.

If the problem still exists in your application, please open a new issue and follow the instructions in the issue template.

**Comment by Lonli-Lokli** [comment]
@atscott there is similar issue for the new Angular as well.
Seems like you copy bugs from one implementation to another ;)
https://github.com/angular/angular/issues/18261

**Comment by ayrad** [comment]
4 years later...

**Comment by alxhub** [comment]
Confirmed as reported. A `+` should definitely not be encoded as itself, as this has a different meaning in URL encoded values.

I believe the long-ago origin of this bug was the re-implementation of the incorrect logic from angular.js' `encodeUriSegment`. This function was meant for paths in the URL part of the URI, not query parameters. This bug was unintentionally later copied to `HttpClient`, which used the same implementation of query encoding for backwards compatibility with `@angular/http`.

Angular's behavior here is incorrect and should be fixed. I'm concerned that fixing it might cause issues/breaking changes if people have applied workarounds, especially in their backends. Here's what I propose:

1) We introduce a new `HttpParameterCodec` with the correct encoding behavior and deprecate the old one. It's already possible to choose an encoder when creating `HttpParams`.

2) in v10.x, we make the default encoder configurable via DI/`HttpClientModule` options, allowing someone to opt-in globally to the fix.

3) in v11, we swap the default, and make an opt-out possible instead.

4) in v12, then, we remove the opt-out and the broken codec.

**Comment by alxhub** [comment]
Note that as mentioned in #33728 this issue isn't limited to `+`. The `=` character for example is left alone even for encoding query param keys, which means a key of `a=b` incorrectly gets interpreted as a key of `a` with its value prefixed by `b=`, which is just totally wrong.

**Comment by ayrad** [comment]
@alxhub :clap: :clap:

**Comment by d668** [comment]
This is an issue when using ASP.NET `GrantResourceOwnerCredentials` method. If I do `encodeURIComponent(loginModel.password)` then I will have to change `GrantResourceOwnerCredentials` to URL decode and it means people can't use % as password when they use `curl` to authenticate via my API

**Comment by ivan-khr85** [comment]
the issue open 4 years.
shitting Angular

**Comment by rooby** [comment]
#26979 is a dupe of this.

**Comment by VanonckelenDieter** [comment]
I see that this is still an issue, anyone knows if Angular is working on a solution?

**Comment by artfulsage** [comment]
Standard behaviour can be easily overriden globally with this interceptor.

```ts
@Injectable()
export class EncodeUrlParamsSafelyInterceptor implements HttpInterceptor, HttpParameterCodec {
  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    const newParams = new HttpParams({
      fromString: req.params.toString(),
      encoder: this,
    });

    return next.handle(req.clone({
      params: newParams,
    }));
  }

  encodeKey(key: string): string {
    return encodeURIComponent(key);
  }

  encodeValue(value: string): string {
    return encodeURIComponent(value);
  }

  decodeKey(key: string): string {
    return decodeURIComponent(key);
  }

  decodeValue(value: string): string {
    return decodeURIComponent(value);
  }
}
```

Then in **app.module.ts**
```ts
@NgModule({
    providers: [
    {
      provide: HTTP_INTERCEPTORS,
      useClass: EncodeUrlParamsSafelyInterceptor,
      multi: true,
    }],
})
export class AppModule {
}
```

**Comment by AKlaus** [comment]
@artfulsage, would double URL encoding be a concern?
Of course [it can be handled](https://stackoverflow.com/a/16094418/968003) on the back-end, but still....

**Comment by artfulsage** [comment]
@AKlaus double encoding is never happening because in my interceptor I replace standard codec with my own, and interceptor is called before actual URL encoding.

**Comment by Lonli-Lokli** [comment]
@alxhub is there any update for the updated codec (https://github.com/angular/angular/issues/11058#issuecomment-636114557) ?

**Comment by petebacondarwin** [comment]
As described here - https://github.com/angular/angular/issues/11058#issuecomment-636114557 - there is a proposed path to solving the issue. I think this would be a great opportunity for a community contribution?

**Comment by mvmn** [comment]
This issue breaks GET request Query parameters as well.

The plus symbol must be properly encoded as %2B, it cannot be sent as unencoded + in URL query parameters - or it will be URL-decoded by servers to space character, thus any parameter with value like "A+B" will be URL-decoded to "A B".

**Comment by mcalmus** [comment]
@artfulsage That doesn't work for me. req.params.toString() returns an empty string.

**Comment by artfulsage** [comment]
@mcalmus have you provided params via `params: HttpParams` into a `HttpClient`'s method?

**Comment by mcalmus** [comment]
@artfulsage Yep. I ended up using the codec part, though just creating a `HttpParams` using it inline.

**Comment by spanevin** [comment]
almost 5 years, really? :(

**Comment by LinPoLen** [comment]
this part of shit code is just in order to make url looks more beautiful.
but it's wrong when decode an have encoded url. there is no need to see `+` in url!
```typescript
 private encode(v: string): string {
        return encodeURIComponent(v)
        .replace(/%40/gi, '@')
        .replace(/%3A/gi, ':')
        .replace(/%24/gi, '$')
        .replace(/%2C/gi, ',')
        .replace(/%3B/gi, ';')
        //.replace(/%2B/gi, '+')
        .replace(/%3D/gi, ';')
        .replace(/%3F/gi, '?')
        .replace(/%2F/gi, '/');
  }
```

**Comment by petebacondarwin** [comment]
@LinPoLen  - thank you for editing your previous message and being aware of our [code of conduct](https://github.com/angular/code-of-conduct) when interacting on the issue tracker.

**Comment by petebacondarwin** [comment]
There are currently a couple of PRs open for this bug (#37385 and #32598).
The difficulty is finding an appropriate API and ensuring a reasonable migration path for the breaking change.

**Comment by zalito12** [comment]
I don't think '+' should be encoded to '%2B' by default, there is an standard that accepts '+' as an space for urls, there should be an easy way to do it when you need it, for example using a custom encoder, but with some interceptors this generates the double encode problem.
So maybe create an easy way to encode EVERY param, using a flag option or something similar.

**Comment by spanevin** [comment]
> 
> 
> I don't think '+' should be encoded to '%2B' by default, there is an standard that accepts '+' as an space for urls, there should be an easy way to do it when you need it, for example using a custom encoder, but with some interceptors this generates the double encode problem. So maybe create an easy way to encode EVERY param, using a flag option or something similar.

I don't understand. If + is an ENCODED SPACE, why do you suggest to not encode +? + is +, space is space. If somebody does pre-encoding, what's the difference between + and any other character like %  which can be a part of ENCODED string?

**Comment by spanevin** [comment]
Guys, 5 years. Are you kidding?

**Comment by fubar-coder** [comment]
We've been bitten by this bug too. It's simply broken and should be fixed.

**Comment by dylhunn** [comment]
@Clashsoft has provided a fix in #45111. Although no breakage shows up in Google's global tests, this is exactly the sort of breakage that's hard to detect with tests: it's at the client-server boundary, where most requests are mocked, and it's subtle.

We have a plan to move forward -- we're going to deploy it for a single large app, and collect data about how severe the breakage is. Then we can come up with a release plan. Depending on how long that takes, we might need to defer until v15.

**Comment by spanevin** [comment]
@dylhunn Why = was removed from the title?

Are you sure + is the only affected character? I don't see a test for & in parameter value.

Also I don't see a test for = in parameter name. I understand why it works without replacement in the value, but it will break name if it is not encoded properly.

Let's say we have a parameter with name="a=b" and value = "c&d=5"
What do we have in current implementation? I think it's ...a=b=c&d=5 right?
Which I, based on my knowledge, would parse as 2 parameters: "a" = "b=c" and "d" = "5"
instead of "a=b" = "c&d=5"
Am I wrong?

**Comment by dylhunn** [comment]
@spanevin almost all of the discussion here is about `+`. If `=` is also affected, we'd need a separate reproduction and issue, and we'd want to fix it in a separate PR, to minimize risk at one time.

**Comment by Lonli-Lokli** [comment]
@dylhunn are you kidding? It's a consolidated issue from angularjs time, a lot of other issues were just closed as duplicates in favor of this issue.

Also you can look into this comment https://github.com/angular/angular/issues/11058#issuecomment-636131153 by @alxhub

**Comment by dylhunn** [comment]
The behavior of `=` is a different question than the behavior `+`, and it's not nearly as clear cut.

After some discussion, we are not even sure that the urlencoding spec for form data allows `=` in keys at all. This is just not suitable for a combined fix.

**Comment by rooby** [comment]
@dylhunn if you are going to change the focus of this issue and it’s not up for discussion, please ensure that you have created other issue(s) for the parts you removed from this one and reference them here, so they aren’t lost and can be discussed in the other issues.

**Comment by rooby** [comment]
@dylhunn 

> After some discussion, we are not even sure that the urlencoding spec for form data allows `=` in keys at all.

Could you please explain this further?
It would be best if discussions critical to an issue are properly explained in the issue itself, so that everyone can be on the same page.

As far as I know the name attribute can contain any ASCII character and I’ve seen nothing that excludes equals from being allowed in a URL query parameter key or value.
I may not be sufficiently knowledgeable on that topic though so I’d be happy to be pointed in the right direction.

Sure, if you’re encoding a single string that is a complete set of params then you cannot know which equals (or ampersands) characters to encode and which not to, but when dealing with individual keys and values like HttpParams does there is no such problem.

**Comment by ranma42** [comment]
> The behavior of `=` is a different question than the behavior `+`, and it's not nearly as clear cut.
> 
> After some discussion, we are not even sure that the urlencoding spec for form data allows `=` in keys at all. This is just not suitable for a combined fix.

I think that the default `HttpParameterCodec` should strive to match the behavior of [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams).

That would be the least surprising (for developers) and easiest to integrate (when thinking of client-server interaction etc).

It has the additional bonus of being in a [specification](https://url.spec.whatwg.org/#interface-urlsearchparams) which can be looked up when debating what constraints are expected (such as legitimate key values).

IIUC the relevant part regarding your doubt is

> [URLSearchParams](https://url.spec.whatwg.org/#urlsearchparams) objects will percent-encode anything in the [application/x-www-form-urlencoded percent-encode set](https://url.spec.whatwg.org/#application-x-www-form-urlencoded-percent-encode-set), and will encode U+0020 SPACE as U+002B (+).

As mentioned [here](https://url.spec.whatwg.org/#application-x-www-form-urlencoded-percent-encode-set),
> The [application/x-www-form-urlencoded percent-encode set](https://url.spec.whatwg.org/#application-x-www-form-urlencoded-percent-encode-set) contains all code points, except the [ASCII alphanumeric](https://infra.spec.whatwg.org/#ascii-alphanumeric), U+002A (*), U+002D (-), U+002E (.), and U+005F (_).

Hence `=` (just like the other cases currently handled in a special way in angular) seems to be just fine in keys or values, they just need to be percent-encoded.

**Comment by dylhunn** [comment]
I re-read all the comments on this issue and on all linked issues -- there is no discussion of other characters such as `=`. I understand that it *seems* more correct to percent-encode `=`, but I'd really like to see concrete examples before making such a risky change. 

In particular, [the spec](https://url.spec.whatwg.org/#application/x-www-form-urlencoded) is about as clear as mud, and also features this gem:

> The application/x-www-form-urlencoded format is in many ways an aberrant monstrosity, the result of many years of implementation accidents and compromises leading to a set of requirements necessary for interoperability, but in no way representing good design practices.

**Comment by mchasej** [comment]
This issue also bit me yesterday.  TL;DR, I believe that the *default* param encoding provided by HttpClient should encode key-value pairs using `encocdeURIComponent` and *nothing else* so that data is sent to the server in most unambiguous manner possible.

It seems to me, that if a user issues an HttpClient GET request such as `this.http.get(path, { params: data })...`, where `data` is some object of type `{ [k: string]: string }`, then the key-value pairs should be sent such that the server will receive identical key-value pairs.  It's perfectly valid to have an object or mapping with keys containing any of the URI reserved characters ([RFC 3986 sec 2.2](https://datatracker.ietf.org/doc/html/rfc3986#section-2.2)).  Keys can be nearly any string.  This applies to JavaScript objects, PHP arrays, and Python dictionaries.  Why anyone would want to use the key "abc+def=foobar" isn't ours to ask.  But if that's the key, the server should see that key.  Same goes for values.

The current default parameter encoder, [`HttpUrlEncodingCodec`](https://github.com/angular/angular/blob/ea8256f43d1bac1888424b29c03bf530a222bef2/packages/common/http/src/params.ts#L34), isn't implemented to be unambiguous.  I don't know the history, but I'm guessing it was to make the query string "prettier".  But it can lead to unexpected behavior, as we can plainly see from this 6-year issue.

In my experimentation, I found that both PHP and Python's Flask interpret "+" as a space in the query string.   What's more, a "=" is perfectly legal as part of the key (if unorthodox) *if encoded*.  If multiple "=" characters appear in a query string key-value pair, then the first "=" is treated as the key-value separator, and the remaining "=" are assumed to be part of the value.

To prove out the problem, I created a simple testbed with a readily available PHP server (version 5.3.3) and Flask server (Python 3.10.4 / Flask 2.1.1 / Werkzeug 2.0.1).  They are included here for completeness:

### test-bed.component.ts
```
import { Component } from '@angular/core';
import { HttpClient, HttpParameterCodec, HttpParams } from '@angular/common/http';
import { Params } from '@angular/router';
import { fromPairs } from 'lodash-es';


@Component({
  selector: 'app-test-bed',
  templateUrl: './test-bed.component.html',
})
export class TestBedComponent {

  characters = ['@', ':', '$', ',', ';', '+', '=', '?', '/', ' '] // space is included for demonstration...

  // Obviously, these aren't the real paths ;)
  phpPath = 'http://server:8080/test.php';
  flaskPath = 'http://server:7070/test';

  useDefaultEncoder = true;

  expectedData: Params = null;
  phpData = null;
  flaskData = null;

  constructor (protected http: HttpClient) {
    this.expectedData = fromPairs(this.characters.map(x => [`a${x}b`, `c${x}d`]));
  }

  toggleEncoder (): void {
    this.useDefaultEncoder = !this.useDefaultEncoder;
  }

  testPHP (): void {
    const params = this.useDefaultEncoder ? this.expectedData : this.makeParams(this.expectedData);
    this.http.get(this.phpPath, { params: params })
      .subscribe(data => {
        this.phpData = data;
      });
  }

  testFlask (): void {
    const params = this.useDefaultEncoder ? this.expectedData : this.makeParams(this.expectedData);
    this.http.get(this.flaskPath, { params: params })
      .subscribe(data => {
        this.flaskData = data;
      });
  }

  makeParams (params: Params): HttpParams {
    return new HttpParams({ fromObject: params, encoder: new URIComponentCodec() });
  }

}

export class URIComponentCodec implements HttpParameterCodec {
  encodeKey (key: string): string {
    return encodeURIComponent(key);
  }
  encodeValue (value: string): string {
    return encodeURIComponent(value);
  }
  decodeKey (key: string): string {
    return decodeURIComponent(key);
  }
  decodeValue (value: string): string {
    return decodeURIComponent(value);
  }
}
```

### test-bed.component.html
```
<button type="button" (click)="toggleEncoder()">{{ useDefaultEncoder ? 'Default Encoder' : 'Custom Encoder' }}</button>

<pre>{{ expectedData | json }}</pre>

<button type="button" (click)="testPHP()">Test PHP</button>
<pre>{{ phpData | json }}</pre>

<button type="button" (click)="testFlask()">Test Flask</button>
<pre>{{ flaskData | json }}</pre>
```

### test.php
```
<?php

header('Access-Control-Allow-Origin: ' . $_SERVER['HTTP_ORIGIN']);

if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
    header('Access-Control-Allow-Headers: Authorization, Content-Type');
    header('Access-Control-Allow-Methods: GET, HEAD, OPTIONS');
    die();
}

echo json_encode($_GET);
```

### test.py 
```
from flask import Blueprint, jsonify, request

bp = Blueprint('base', __name__, url_prefix='')

@bp.route('/testbed')
def testbed ():
    return jsonify(request.args)

@bp.after_request
def set_cors_headers (response):
    if request.method == 'OPTIONS':
        response.access_control_allow_headers = ['Authorization', 'Content-Type']
        response.access_control_allow_methods = response.allow
    response.access_control_allow_origin = request.origin or '*'
    return response
```

As you can see, each PHP and Flask endpoint simply takes the parsed query string, which becomes the `$_GET` array in PHP, and the `request.args` dictionary in Python, and returns the JSON representation of that data.  Ideally, the data passed as params to `http.get()` should be returned exactly as we pass in the data.  Since these are objects/mappings/dictionaries, order is not guaranteed.  But content should be.  (PHP appeared to leave the order intact, while my Flask testbed sorted the keys for caching or debug purposes.)  I included `' '` in the character set to demonstrate how "+" and "%20" conflict.

#### expectedData
```
{
  "a@b": "c@d",
  "a:b": "c:d",
  "a$b": "c$d",
  "a,b": "c,d",
  "a;b": "c;d",
  "a+b": "c+d",
  "a=b": "c=d",
  "a?b": "c?d",
  "a/b": "c/d",
  "a b": "c d"
}
```

## Default encoder (HttpUrlEncodingCodec)
The GET requests to the testbeds results in URLs with the following query string:
`?a@b=c@d&a:b=c:d&a$b=c$d&a,b=c,d&a;b=c;d&a+b=c+d&a=b=c=d&a?b=c?d&a/b=c/d&a%20b=c%20d`  

#### phpData
```
{
  "a@b": "c@d",
  "a:b": "c:d",
  "a$b": "c$d",
  "a,b": "c,d",
  "a;b": "c;d",
  "a_b": "c d",
  "a": "b=c=d",
  "a?b": "c?d",
  "a/b": "c/d"
}
```
"+" in the query string is treated as a space.  (Note that PHP appears to dislike spaces in the $_GET keys, and automatically converts them to underscores.  This behavior is specific to PHP, and therefore not an issue to be corrected.)  Since "+" is equivalent to " ", the `"a b": "c d"` pair becomes a duplicate.  The key-pair "a=b=c=d" is interpreted as `"a": "b=c=d"`, which was not the intent.  

#### flaskData
```
{
  "a": "b=c=d",
  "a b": "c d",
  "a$b": "c$d",
  "a,b": "c,d",
  "a/b": "c/d",
  "a:b": "c:d",
  "a;b": "c;d",
  "a?b": "c?d",
  "a@b": "c@d"
}
```
Identical results, except that Flask/Python doesn't mind a space in the key.

It should be noted here that none of the other characters seem to cause issue.  So they're "safe", but I don't know if that's always guaranteed.  What I do know is that by encoding the key-value pairs with `encodeURIComponent()` and any reserved characters percent-encoded, there's zero chance that the characters are treated as reserved token characters.  Testing with the 
`URIComponentCodec` implementation above, the data sent and returned to/from the testbeds is more complete and correct:

## URIComponentCodec (using  only `encodeURIComponent()`)
The query string produced: `?a%40b=c%40d&a%3Ab=c%3Ad&a%24b=c%24d&a%2Cb=c%2Cd&a%3Bb=c%3Bd&a%2Bb=c%2Bd&a%3Db=c%3Dd&a%3Fb=c%3Fd&a%2Fb=c%2Fd&a%20b=c%20d`  (Yes, it's very ugly.)

#### phpData
```
{
  "a@b": "c@d",
  "a:b": "c:d",
  "a$b": "c$d",
  "a,b": "c,d",
  "a;b": "c;d",
  "a+b": "c+d",
  "a=b": "c=d",
  "a?b": "c?d",
  "a/b": "c/d",
  "a_b": "c d"
}
```
Note that we have "a+b", "a=b", and "a_b" keys.  All values are as expected.

### flaskData
```
{
  "a b": "c d",
  "a$b": "c$d",
  "a+b": "c+d",
  "a,b": "c,d",
  "a/b": "c/d",
  "a:b": "c:d",
  "a;b": "c;d",
  "a=b": "c=d",
  "a?b": "c?d",
  "a@b": "c@d"
}
```
Note that we again have all keys including "a+b", "a=b", and "a b".  All keys and values are as expected.

# Conclusion

I would propose that the entire "standard encoding" be thrown out, and `encodeURIComponent()` be used as-is.  `encodeURIComponent()` is available *specifically* to encode URI components such as query string keys and values.

I don't know the reasoning behind the "standard encoding".  I suspect it was for prettier query strings.  But the HttpClient is used mainly for asynchronous background data requests.  The user won't see the query string.  The server will, and the server needs to see the *correct* query string.

At a minimum, "+" and "=" should be left percent-encoded:
- "+" because it is the standard to treat "+" as a space in a query string.  A design decision made years ago when email was on a terminal, but it's been that way forever (exhibits [A](https://url.spec.whatwg.org/#urlencoded-parsing), [B](https://en.wikipedia.org/wiki/Percent-encoding#The_application/x-www-form-urlencoded_type), [C](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4), [D](https://www.w3.org/Addressing/URL/4_URI_Recommentations.html)).  `%20` and `%2B` are unambiguous.
- "=" should be left encoded because the current implementation mangles any keys containing a "=".  It's such an odd thing to do, so I doubt anyone has ever run into this issue.  But it's valid, and should be supported.  

For those still curious about why a "+" should be a space -- [https://www.w3.org/Addressing/URL/uri-spec.html](https://www.w3.org/Addressing/URL/uri-spec.html):
> #####Choices for a universal syntax
> ...
> The use of white space characters is risky in URIs to be printed or sent by electronic mail, and the use of multiple white space characters is very risky. This is because of the frequent introduction of extraneous white space when lines are wrapped by systems such as mail, or sheer necessity of narrow column width, and because of the inter-conversion of various forms of white space which occurs during character code conversion and the transfer of text between applications. This is why the canonical form for URIs has all white spaces encoded.
> ##### Query strings
> ...
> Within the query string, the plus sign is reserved as shorthand notation for a space. Therefore, real plus signs must be encoded. This method was used to make query URIs easier to pass in systems which did not allow spaces.

A change like this would likely need to be released in a major release.  It's *possibly* breaking, if users are expecting their "+" to be spaces on the server side.  Or if they're expecting `"a=b": "c"` to be `"a": "b=c"`... though I think it's safe to say *that's not clearly expected behavior*.

I realize that was a lot of data and opinion.  I'm very interested to know if purely percent-encoded values would break some server side API.  I guess I'm openly asking - what's the advantage to decoding some of the percent encoded values, other than making it less ugly?  Why not leave the query string components percent-encoded?

**Comment by dylhunn** [comment]
@mchasej Thank you for your incredibly detailed response.

>  I'm very interested to know if purely percent-encoded values would break some server side API.

Yes, definitely. You'd be shocked at how heavily clients depend on the most arcane implementation details. Even worse, almost nobody tests HTTP requests -- they just mock them out -- so there's no safe way to find all the troublesome code.

> "+" because it is the standard 

I agree we need to fix `+`; it's causing real pain as evidenced by the many issue reports.

> "=" should be left encoded because the current implementation mangles any keys containing a "=". 

I could maybe get on board with this. Just bear in mind that this is a very obscure use case, and we have to balance against the risk of causing breakages and outages. We are _extremely_ sensitive to breaking our clients, especially in such an undertested and risky area.

> none of the other characters seem to cause issue

This is my understanding as well. I really do not want to tinker with such a hazardous area for no discernible benefit (i.e. these other characters besides `+` and `+`).

> what's the advantage to decoding some of the percent encoded values

This code came from AngularJS around 10 years ago -- I'm not sure why it was implemented this way, unfortunately.

**Comment by mchasej** [comment]
@dylhunn Thanks for the reply.

> Even worse, almost nobody tests HTTP requests
You've made me very sad.  :)

I understand not wanting to break old code.  I've been around enough myself to know how fragile it can be.

I think we would agree that most users don't run into these issues.  They're sending a JSON body, or whatever else, and they simply don't hit these edge cases.  But when someone does, they inevitably google for a solution, end up here or StackOverflow, and they end up writing nearly identical work arounds.

It's not *difficult* to create a custom implementation of `HttpParameterCodec` and create `HttpParams` with a custom encoder.  When done in a wrapped service, a user can again pass in plain ol' JavaScript objects as a params argument.  Unfortunately, everyone trying to send ISO date times with a positive time zone offset as a parameter value is going to end up going down this same path.

*So...* What about making it easier for users to use an alternative encoder?  If there were an option as simple as `this.http.defaultParamEncoder = AlternativeEncodingCodec` -- it would be very nice.  And an example alternative encoder could be included in params.ts, making it easy for users to toggle.  Thoughts?

**Comment by dylhunn** [comment]
@mchasej 

On further thought, I think that it's probably worth it to try to fix `=` as well. Along with the fix for `+`, then it would likely be "fixed enough."

> What about making it easier for users to use an alternative encoder?

I am open to this. If it's something you actively want to implement, would you be able to draft a short (~1 page) design statement, showing the new API? Then I can circulate it with the team, in case there are any issues.

**Comment by rooby** [comment]
> _So..._ What about making it easier for users to use an alternative encoder? If there were an option as simple as `this.http.defaultParamEncoder = AlternativeEncodingCodec` -- it would be very nice. And an example alternative encoder could be included in params.ts, making it easy for users to toggle. Thoughts?

This is a good idea.
I think it would be good to include the current codec, plus a working (not just an example) codec that mimics `encocdeURIComponent()` so users can easily use their preferred, and potentially after sufficient notices to users, the latter option could be made the default.

If additional example implementations are required they could just go in the docs.

**Comment by dylhunn** [comment]
(N.B. note that this is already possible by passing an encoder when constructing `HttpParams`, so the new API would just be a simpler interface for that functionality)

**Comment by rooby** [comment]
> (N.B. note that this is already possible by passing an encoder when constructing `HttpParams`, so the new API would just be a simpler interface for a default codec)

Yes that’s true. The aim is for Angular to come with a more sensible codec and hopefully for that to become the default codec.

**Comment by spanevin** [comment]
I'd really like to have correct behavior by default, and a possible option to switch to legacy incorrect encoder just for really old projects where it's really required because of server-side implementation based on incorrectly encoded url values... This can easily be described in upgrade instructions. "Do you rely on legacy broken url encoder? Are you in doubt? Enable this fallback option. Do you have custom params encoder which fixes old broken default one? It can be removed."

We use alternative encoder in all our projects as a workaround already, for years, and it's an extra code you must not forget to add to each new project, it is really bad thing.

**Comment by ranma42** [comment]
> @dylhunn Thanks for the reply.
> 
> I understand not wanting to break old code. I've been around enough myself to know how fragile it can be.
> 
> I think we would agree that most users don't run into these issues. They're sending a JSON body, or whatever else, and they simply don't hit these edge cases. But when someone does, they inevitably google for a solution, end up here or StackOverflow, and they end up writing nearly identical work arounds.
> 
> It's not _difficult_ to create a custom implementation of `HttpParameterCodec` and create `HttpParams` with a custom encoder. When done in a wrapped service, a user can again pass in plain ol' JavaScript objects as a params argument. Unfortunately, everyone trying to send ISO date times with a positive time zone offset as a parameter value is going to end up going down this same path.
> 
> _So..._ What about making it easier for users to use an alternative encoder? If there were an option as simple as `this.http.defaultParamEncoder = AlternativeEncodingCodec` -- it would be very nice. And an example alternative encoder could be included in params.ts, making it easy for users to toggle. Thoughts?
> 
> _Update:_ Oh, and I'd be willing to contribute to do the work. Nothing comes for free, after all. :)

Your approach looks very similar to the one implemented in https://github.com/angular/angular/pull/37385

**Comment by camsteffen** [comment]
@dylhunn Why is this reopened? Isn't it fixed in Angular 14?

**Comment by Clashsoft** [comment]
Yes, it was fixed in Angular 14 via #45111

**Comment by ranma42** [comment]
> @dylhunn Why is this reopened? Isn't it fixed in Angular 14?

no, #45111 only fixed it for `+`, but not for the other characters

**Comment by tonyfarney** [comment]
It's unbelievable that this bug remains in angular 13
I've lost many hours debbuging my API and the bug was in the front end ¬¬

**Comment by Lonli-Lokli** [comment]
@dylhunn Is there already created PR for the `=`?

**Comment by Adrug** [comment]
Seems it was fixed for Angular v15
Accordingly  upgrade guide https://update.angular.io/?l=3&v=13.0-15.0

> Sending + as part of a query no longer requires workarounds since + no longer sends a space.

Can somebody confirm this?

**Comment by Lonli-Lokli** [comment]
@Adrug yes, in this thread https://github.com/angular/angular/issues/11058#issuecomment-1344111788

`=` is not fixed yet.

**Comment by micw** [comment]
For reference, the relevant RFC is https://www.rfc-editor.org/rfc/rfc1866#section-8.2
RFC3986 defines the _allowed_ chars in an URL. So + is allowed, as well as %20. rfc1866 defines the _meaning_ of the characters for example in a query string. So it states clearly that space is encoded as '+' - which implies that '+' _must_ be encoded otherwise.

I'm quite puzzled that this is still open and there's no correct implementation of this after 7 years.

**Comment by ALIAHMAD419** [comment]
**my system is accepting emails with plus '+' sign, and it's get ignored due to this issue, i used headers in my solution.**
  ```
  let myParams = new URLSearchParams();
    myParams.append("email", email)
    myParams.append("vendor_portal", "true")
    let headers = new Headers({'Content-type': 'application/x-www-form-urlencoded; charset=utf-8'});
    let options = new RequestOptions({ headers: headers });
    return this.http.put(this.base + "/generate_token", myParams.toString(), options)
```

**Comment by Clashsoft** [comment]
> **my system is accepting emails with plus '+' sign, and it's get ignored due to this issue, i used headers in my solution.**

Plus sign is fixed since Angular 15. This issue is still open because of other characters.

**Comment by ALIAHMAD419** [comment]
@Clashsoft The solution i have posted is for Angular 10, in-case someone using a Legacy system that can help him out.
