### ISSUE TITLE
'Unexpected token export' when importing @angular/core/src/facade/lang

### ISSUE THREAD

**Issue by Martin-Wegner** [angular/angular#11197]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Since nightly build https://github.com/angular/core-builds/commit/8509b8b39c67a80fa57d1ced70527896d6ca92cd an Angular 2 application does not start when importing `@angular/core/src/facade/lang` because of the error

Chrome:
> Uncaught SyntaxError: Unexpected token export

Firefox:
> SyntaxError: export declarations may only appear at top level of a module

**Expected/desired behavior**
No error.

**Reproduction of the problem**
```
import { global } from '@angular/core/src/facade/lang';
...
(global as any).innerWidth
```

**What is the expected behavior?**
No error.

**What is the motivation / use case for changing the behavior?**
No error.

**Please tell us about your environment:**

* **Angular version:** nightly build https://github.com/angular/core-builds/commit/8509b8b39c67a80fa57d1ced70527896d6ca92cd
 
* **Browser:** tested with latest Chrome and Firefox 
 
* **Language:** TypeScript

**Comment by ericmartinezr** [comment]
That's internal API, you're not supposed to use it in your apps.

**Comment by mhevery** [comment]
Yes, The only valid imports are: `@angular/core` and `@angular/core/testing` (or more generally `@angular/*` and `@angular/*/testing`) everything else is private API. Part of RC6's repackaging is to enforce that.

**Comment by pkozlowski-opensource** [comment]
For anyone bumping into this / similar issue and need to troubleshoot here are few hints:
* any private import will break with syntax errors on `import` or `export`
* an offending import for the private internals can come from your code _OR_ from a thrid-party  code you might be using
* if using WebPack you can see which files are resolved / included by adding `--d --display-reasons --display-modules` flags - this will dump more info on what gets included from where and can help you locate broken imports

**Comment by Martin-Wegner** [comment]
OK and how can I obtain a global variable?

**Comment by ocombe** [comment]
Thanks ! I have to update ng2-translate now because it will break a lot of builds :)

**Comment by born2net** [comment]
does this mean we have to wait for rc.7 for this fix?

**Comment by pkozlowski-opensource** [comment]
@born2net there is nothing to be "fixed" on our side - a library is using a private APIs / imports and it should nor. Ask the library author to update or use an alternative that is already updated to rc6: https://github.com/ng-bootstrap/ng-bootstrap

**Comment by Martin-Wegner** [comment]
@born2net valor-software/ng2-bootstrap has it already fixed in master.

**Comment by born2net** [comment]
@Martin-Wegner tx for the reply.
but the error persists with 1.1.0 latest build
regards

**Comment by born2net** [comment]
@pkozlowski-opensource yes I agree, the issue needs to be resolved with ng2-bootstrap not with angular 2

**Comment by Martin-Wegner** [comment]
@born2net I said on master which is not yet released :(

**Comment by anshumansworld** [comment]
@ocombe Did you fix this in 2.4.3, I suppose it's still not according to new declaration in `systemjs.config.js` because I am getting:

```
Error loading http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js/src/facade/lang as "@angular/core/src/facade/lang" from http://localhost:3000/node_modules/ng2-translate/src/translate.pipe.js
```

I have included `core` in `systemjs` as : `'@angular/core': 'npm:@angular/core/bundles/core.umd.js',`

Also tried by updating declaration of `core` in `map` like: 
```
'@angular/core': 'npm:@angular/core',
```
 and by adding in `packages` as:
```
'@angular/core': {
                main: './bundles/core.umd.js',
                defaultExtension: 'js'
            }
```
but then I got this: `Error loading http://localhost:3000/node_modules/@angular/core/src/facade/lang.js as "@angular/core/src/facade/lang" from http://localhost:3000/node_modules/ng2-translate/src/translate.pipe.js`

**Comment by ocombe** [comment]
@anshumansworld let's discuss this on https://github.com/ocombe/ng2-translate/issues/219 please
