### ISSUE TITLE
Changing router-outlet's name variable from Attribute to Input type

### ISSUE THREAD

**Issue by atang020** [angular/angular#12522]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

```
<router-outlet name="outlet1"></router-outlet>
<router-outlet name="outlet2"></router-outlet>
<router-outlet name="outlet3"></router-outlet>
```

**Expected behavior**

```
<div *ngFor="let outlet of outletList">
<router-outlet [name]="outlet.name"></router-outlet>
</div>
```

where outletList = [list1, list2, list3];
where list1.name = 'outlet1';
 list2.name = 'outlet2';
 list3.name = 'outlet3';

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**
I am requesting a feature change of router-outlet's name type from @Attribute to @Input property, so developers can bind a name dynamically to a router-outlet.
Currently, developers need to hard code a string for router-outlet's name attribute in the html template. If a developer needs to create multiple router outlets, he/she would need to create multiple router outlets and manually add the unique name to each router-outlet. 
This would enable developers to develop cleaner code when they use multiple router-outlets.

**Please tell us about your environment:**

- **Angular version:** 2.0.X
  Angular 2.0.0
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  Chrome
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
  Typescript 
- **Node (for AoT issues):** `node --version` =  
  node 6.4.0

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20781547/9af0af2a-b7be-11e6-9a40-1194daff249e.png)
![Uploading 图片.png…]()

**Comment by Jayaraj8905** [comment]
Hi, May I know when will we got the update on this.

**Comment by atang020** [comment]
I don't think there would be an immediate fix for this. So for now, hardcode each name to a router-outlet

**Comment by meysamsahragard** [comment]
How can i set router outlet name dynamically?

**Comment by itismelito** [comment]
Any Update on this? i have same issue.

**Comment by jakubjosef** [comment]
@itismelito This directive can be used for this purpose.
https://github.com/angular/angular/issues/17173#issuecomment-415322417

**Comment by jbogarthyde** [comment]
Resolved by PR

**Comment by trotyl** [comment]
@jbogarthyde This isn't resolved, the issue is about changing the underlying implementation from `Attribute` to `Input` to support value binding, not about the API documentation rendering.

**Comment by Splaktar** [comment]
Agreed. I think that we would need an official statement from DevRel on why this isn't viable or isn't planned for the future before closing it.

**Comment by atscott** [comment]
This change is being made in https://github.com/angular/angular/pull/46569 and I'm hoping to land it in v15. The change is considered breaking because it changes the specifics of the timing that components get created.
