### ISSUE TITLE
RouterLink: incorrect relative link if defined in component having empty path

### ISSUE THREAD

**Issue by dubadub** [angular/angular#13011]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In the case of such router config with ContainerComponent consuming empty path: 
```
const routes = [
  { 
    path: '', 
    component: ContainerComponent,
    children: [
      { path: 'a', component: AComponent },
      { path: 'b', component: BComponent },
    ]
  }
];
```
and ContainerComponent having relative links to children in template:

```
<a [routerLink]="['a']">Link to A</a>     (or  <a [routerLink]="['./a']">Link to A</a>)
<a [routerLink]="['b']">Link to B</a>
```

RouterLink directive generates incorrect links when user navigated to one of the child component. F.e. if user went to `/a` route, links would be like that: `/a/(a)` and `/a/(b)`.

**Expected behavior**

Relative links should be generated properly: `/a` and `/b`.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/Lf2Vfe?p=preview
Click on any link. Then you could see that links rendered in AppComponent are correct, but not the ones in ContainerComponent (they both look like `/a/(a)` and `/a/(b)`).

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** 4.2.1

**Comment by WilliamKoza** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on StackOverflow using tag angular.

If you are wondering why we don't resolve support issues via the issue tracker, please check out this explanation.

**Comment by DzmitryShylovich** [comment]
http://plnkr.co/edit/fYck0CbiXrPKszbMo4eW?p=preview

**Comment by dubadub** [comment]
@DzmitryShylovich Yeah, absolute paths work just fine. Problem comes when used **relative path**. It's necessary to use relative path for example in case of reusable module with own navigation bar and which is connected to components tree on quite deep level.

**Comment by DzmitryShylovich** [comment]
https://angular.io/docs/ts/latest/guide/router.html#!#relative-navigation

**Comment by dubadub** [comment]
It seems to me that I did everything right according to docs. Maybe I missed something. But... @DzmitryShylovich Did you manage to see that links look like `/a/(a)` and `/a/(b)`

**Comment by WilliamKoza** [comment]
If you want to use relative path, you must change your router configuration. http://plnkr.co/edit/xA2S46bMNg5ZgFa5XbNM?p=preview

**Comment by buctwbzs** [comment]
i think you maybe missed something.read docs,you will get it .

**Comment by vicb** [comment]
sounds like a legit bug

**Comment by klinki** [comment]
I have the same problem. It still doesn't work properly in templates.

**Comment by leon** [comment]
I have the same problem.
It looks like the router doesn't resolve urls which either don't have a path, or are abstract paths (no component).

```
export const ROUTES = [
  {
    // Index route job or product admin selection
    path: '',
    component: ProductsRoute
  },
  {
    path: ':locale',
    resolve: { categories: CategoriesResolver },
    children: [
      {
        // Index route for categories
        path: '',
        component: CategoriesRoute
      },
      {
        path: ':categoryId',
        resolve: { category: CategoryResolver },
        children: [
          {
            // Index route for a category
            path: '',
            component: CategoryRoute
          },
          {
            path: ':productId',
            component: ProductRoute,
            resolve: { product: ProductResolver }
          },
        ]
      },
    ]
  }
];
```

When I'm in a category and try to link up one level with

```
<a routerLink="../">Parent</a>
```

I'm still getting `/en/1` instead of `/en`

I've iven tried doing it from the Category Component with the same result

```
const urlTree = this.router.createUrlTree(['../'], { relativeTo: this.route });
console.log('CategoryRoute URL: ', urlTree.toString()); // outputs /en/1
```

**Comment by furcino** [comment]
Hello, I have the same problem. If there is a route **localhost/parent/child** and I have a `[routerLink]="[../sibling]"` link, it creates the url **localhost/parent/child/sibling** instead of **localhost/parent/sibling**.

**Comment by ytilis** [comment]
Can confirm that we're seeing the same issue as @leon with pathless routes breaking relative routerLink calls. Adding a path value fixes it, so it's definitely a bug. Using absolute paths for now until this is resolved.

**Comment by anantkamath** [comment]
I'm facing this issue too (angular 2 final release)

**Comment by dietergeerts** [comment]
Imho the routerlink relative path should not look at the actual url tree you create to build your routes, as you regurarly add empty paths to add resolves etc... So it should not depend on that, the relative routerlink should depend on the actual url created from the tree.

We now have broken links everytime we add a level for resolves that depend on each other....

**Comment by hccampos** [comment]
Still seeing this error with Angular 4.2.4. Using absolute links is pretty annoying indeed.

**Comment by ciesielskico** [comment]
This is still an issue

**Comment by willshowell** [comment]
Also seeing this, but specifically after a redirect to empty path component

http://run.plnkr.co/LU4DpQiyUkJ7zqa9/

**Comment by JiaJian** [comment]
It's still not fixed yet, I'm currently using absolute links which isn't really a good practice imo (if parent name change).

**Comment by web265p3** [comment]
Same problem here...

**Comment by TristanMarion** [comment]
I have the same problem, does someone have a solution ?

**Comment by pgiemza** [comment]
Hi @TristanMarion 

I had this issue too and redesigning of routes resolved the problem, something like below where only children can have empty path

`export const routes: Routes = [
  { path: 'login', component: LoginPageComponent }
];`

`export const routes: Routes = [
      {
        path: 'account',
        children: [
          { path: '', loadChildren: 'app/login/login.module#LoginModule' }
        ]
      }
];`


Hope that this can be helpful

**Comment by TristanMarion** [comment]
Hi @pgiemza,

Thanks for the answer, I'll try this !

**Comment by jpduckwo** [comment]
I'm an suffering to no end with relative route issues too... I think there might also be something in play when using lazy loading that also affects it too see: #17957 

I've ran into unbelievable issues just trying to relative route from 
```/parent/:someid/child```
to 
```/parent/:someid```

Absolute routes are a pain in this scenario when you have params in the url and would have to rebuild the absolute route with the current param... very frustrating.

@pgiemza I'll try what you're suggesting too and report back. Have you tried this with lazy loading modules too?

**Comment by pgiemza** [comment]
Hi @jpduckwo,

I had this issue too with lazy loaded modules. I just tested the plunker provided with issue #17957 and the solution works as well, so please retest your case with applied my proposition of solution :) if it works as well I think that we can close this issue and related, because it's more architectural inconvenience of routing design

**Comment by juliusstoerrle** [comment]
I'm working around this issue by going up 3 times ( '../../../') instead of just one. But this should be fixed soon!

**Comment by StickNitro** [comment]
I had the same issue and found (as @juliusstoerrle found) that I need to include a bunch of additional ../ in my relative link, so I want to navigate from `/admin/code/organization/users/allusers` to `/admin/code/organization/user`, but these are in nested modules which are lazy loaded so in my case to get this to work I need `[routerLink]="['../../../../../../user']"` which need 4 additional ../

Would be great to get any update on a fix for this issue as I know my application will break when this is eventually resolved

**Comment by Airblader** [comment]
You get an update by subscribing to this issue and/or reading the changelog. As someone doing the same I'd appreciate if comments were only made if they further the discussion on the issue. To simply subscribe to updates there's a button to do just that without sending emails to everyone already subscribed.

**Comment by jpduckwo** [comment]
Just reporting my understanding of this issue: It's not a bug but actually how the router is designed to work with relative routes. The routing is done based on the the router config 'tree' which does not necessarily match what the URL path is. Once I understood this - and that lazy loading adds another notch in the tree that needs traversing with relative router - I could work with it fine. 

However I do feel that it would be nice to also have relative routing based on URL path NOT router tree. I've written some little helpers to do this when I need do and I think when most people think of relative routing they are expecting it to work like this.

My work around for routing one level up from the current URL is something like this:
```
          const url = this.router.url.split('?')[0];
          const split = url.split('/');
          split.pop();
          const newUrl = split.length > 1 ? split.join('/') : '/';
          this.router.navigateByUrl(newUrl);
```
**Q: Would you like to see easy relative routing based on URL path rather than route config tree?**

**Comment by Jordan-Hall** [comment]
Made a helper function that actually help solves this based on @jpduckwo  comments. 

Pull request 22394 seemed to fixed some of the issue but it revealed an issue relating to named outlets. Going up the path on named outlet didn't work using `../../`

Now the solution is to use Relative path and use .parent on ActivatedRoute for each notch on the routing tree.

`
import { Router, ActivatedRoute } from '@angular/router';
/**
 *
 * Angular Relative path tempory solution. Angular doesn't like empty paths.
 * Should be fixed in version 6 Pull request 22394
 * https://github.com/angular/angular/pull/22394
 *
 * Angular Issue: https://github.com/angular/angular/issues/13011#issuecomment-274414952
 *
 * Before removing check relative paths work on named outlet. Using Navigate on named
 * outlet currently relates to secondary routes (outlet:'route/test)
 * this meant breaking out wasn't possiable using ../../ like documented in
 * angular own documentation
 *
 * key Information: This is relative to routes like anuglar intended NOT URL path
 *
 * Bug only relates to going to parent and down the tree
 *
 * @export NavigateByRelative
 * @param {string} path
 * @param {Router} router
 * @param {ActivatedRoute} route
 *
 */
export function NavigateByRelative(path: string, router: Router, route: ActivatedRoute) {

    /**
     * Relative paths should always start with '../' as per angular documentation
     * https://angular.io/guide/router#relative-navigation
     */
    if (path.startsWith('../')) {
        // split path into multiple paths
        const paths = path.split('/');

        // minus 1 on length as we gurantee need the last index
        const totalPathToLastIndex = paths.length - 1;

        // current index so we can start at this later on
        let currentPathIndex;

        // Relative to is so we get to the correct parent
        let relativeTo = route;

        // Check their is a parent and the current path still intended to go back up the tree
        for (currentPathIndex = 0;
            currentPathIndex < totalPathToLastIndex
            && relativeTo.parent !== undefined
            && paths[currentPathIndex] === '..';
            currentPathIndex++
        ) {
            relativeTo = relativeTo.parent;
        }

        // Navigate starting at the the currentpathIndex and relative to the current parent
        router.navigate([...paths.splice(currentPathIndex )], { relativeTo });

    } else {
        // else use navigation as normal as this should work correctly
        router.navigate([path]);
    }
}
`

Hopefully the above will help others out. surprisingly it taken couple of days to find out how to resolve this and looking though the routing code. Hopefully adriensamson pull request will fix this issue but if not hope the above solution helps deal with the pain

**Comment by pauldraper** [comment]
Enough `../` works. Specifically, you need to add as many extra as you have current paths.

So if the current URL is `/my/url/for/my/angular/app` and you want to go to `/my/url`, you need 6 + 4

```
routerLink="../../../../../../../../../.."
```

IDK about the original desired behavior, but I know if that if I write `<a href="../../../..">` works just fine in browsers; I imagine routerLink to be the same, but without a page reload.

**Comment by Jordan-Hall** [comment]
@pauldraper That's because angular router works on ActivatedRoute and not by the URL. This means if you have the follow:
```
[
 {
  path: 'hello'
  component: HelloComponent,
  children: [
   {
     path: ''
     component: ContainerComponent,
     children: [
      {
        path: 'world'
        component: WorldComponent
      }
     ]
   }
  ]
]
```

Your URL for the world component will look like this: **domain.tld/hello/world** however, the Active router will look more like this.

Hello => Container => World

This means when you are using relative path and you need to get back to Hello you will need to go back twice: "../../"  first takes you to the container and the next will actually take you to the hello.

**Comment by sarunint** [comment]
Hi all,

#22394 has been approved by the core team! Hopefully it'll be released with v6.1!

**Comment by trotyl** [comment]
Fixed by https://github.com/angular/angular/pull/22394, can be closed now.

**Comment by Fattouh92** [comment]
on Angular7 and still not working

**Comment by AckerApple** [comment]
In Angular 7, I have had to resort to constructing absolute urls for my routerLinks and for my Router.navigate I use ActivatedRoute.parent

Only my relative backwards navigation is affected

Hoping to see fix soon.

**Comment by niggoo** [comment]
Hi!

Just updated to 7.1.4 and the problem still seems to be there. Also it's not only the routerLink but it also seems to be the case for router.navigate .... when using the logically correct amount of "../" the promise returned by the router.navigate call just returns null, with no information on what the problem is, it just does nothing.

I had to use 4x '../' to get to the desired level of '../', that seems to be a really nasty bug.

Greets,
Niggo

**Comment by sarunint** [comment]
@niggoo It has been fixed already. You need to use `relativeLinkResolution: 'corrected'` in your router configuration.

See #22394 for more details.

**Comment by Fattouh92** [comment]
@sarunint Just updated today to Angular7.2 and configured my router accordingly but still not working. is there something I am missing?

example of my two sibling routes: 
```
  {
    path: "search",
    component: SearchPageComponent,
  },
  {
    path: 'privacy',
    component: PrivacyPageComponent
  }
```

and hovering over the following link ` <a routerLink="../privacy">Privacy</a>` when search is activated shows `localhost:4200/search/(privacy)`  instead of `localhost:4200/privacy`

**Comment by sarunint** [comment]
@Fattouh92 please create a StackBlitz showing the problem. I can't possibly help you without any code.

**Comment by Fattouh92** [comment]
@sarunint please have a look at this: https://stackblitz.com/edit/test-relative-routing

**Comment by tawani** [comment]
March 23rd 2019 - Angular 7 
This issue has still not been resolved.

**Comment by Jordan-Hall** [comment]
The issue also appears to exists with optional parameters

**Comment by alberthaff** [comment]
Using `relativeLinkResolution` = 'corrected' fixed the problem for me.
It must be defined in your routes that are defined with `forRoot`.

**Comment by soheil2540** [comment]
Solved for me.
Add prefix '/' for your path in routeLink. It works for me. I think without this prefix angular can not realize that this is a segment of route. It must be like this:
<a [routerLink]="/a">Link to A</a>    
<a [routerLink]="/b">Link to B</a>

**Comment by bharathiram** [comment]
> Solved for me.
> Add prefix '/' for your path in routeLink. It works for me. I think without this prefix angular can not realize that this is a segment of route. It must be like this:
> <a [routerLink]="/a">Link to A
> <a [routerLink]="/b">Link to B

These are absolute urls & not relative urls. "./a"

**Comment by giovannif23** [comment]
Adding config to update `relativeLinkResolution` from `legacy` to `corrected` solved it for me  - https://angular.io/api/router/ExtraOptions#relativeLinkResolution

```
@NgModule({
  imports: [
    RouterModule.forRoot([{...}], {relativeLinkResolution: 'corrected'})
  ],
  exports: [
    RouterModule
  ]
})
```

Make sure to restart your server to test that the relative paths are working correctly.

**Comment by joelpelaez** [comment]
This also occurs in Angular 8.1.3, I added relativeLinkResolution to ExtraConfig, but it didn't fix the issue.

**Comment by TomerAgmon** [comment]
Bug still hppanes in Angular 8.1.2. Also tried to add relativeLinkResolution. Did not work.

**Comment by blemaire** [comment]
I have just come across this issue and `relativeLinkResolution: 'corrected'` fixed the issue for me.
For anybody having this issue it would be best to post a stackblitz or similar to help with the debugging.

NOTE: for relative navigation via the router service, you also need to use the `relativeTo` option:
`router.navigate(['../'], {relatedTo: activatedRoute})`

**Comment by atscott** [comment]
Confirmed in v9 as well: https://stackblitz.com/edit/angular-ivy-b4xq64?file=src/app/app.module.ts
