### ISSUE TITLE
ng-xi18n failed when the project imports component from node_modules

### ISSUE THREAD

**Issue by reynardmh** [angular/angular#13186]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

ng-xi18n failed when the project imports component from node_modules, even though I can run the app just fine.

Clone this reproducible repo: 
https://github.com/reynardmh/bugdemo-angular-i18n-no-cli

```
$ npm install
$ ./node_modules/.bin/ng-xi18n
```

You'll get this error
```
Error: Unexpected value 'CoolComponent' declared by the module 'AppModule'
    at /angular-quickstart/node_modules/@angular/compiler/bundles/compiler.umd.js:14725:29
    at Array.forEach (native)
    at CompileMetadataResolver._loadNgModuleMetadata (/angular-quickstart/node_modules/@angular/compiler/bundles/compiler.umd.js:14702:56)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (/angular-quickstart/node_modules/@angular/compiler/bundles/compiler.umd.js:14636:23)
    at addNgModule (/angular-quickstart/node_modules/@angular/compiler/bundles/compiler.umd.js:12944:43)
    at /angular-quickstart/node_modules/@angular/compiler/bundles/compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (/angular-quickstart/node_modules/@angular/compiler/bundles/compiler.umd.js:12956:28)
    at analyzeNgModules (/angular-quickstart/node_modules/@angular/compiler/bundles/compiler.umd.js:12700:16)
    at Object.analyzeAndValidateNgModules (/angular-quickstart/node_modules/@angular/compiler/bundles/compiler.umd.js:12704:20)
Extraction failed
```

However the app works just fine. Run `npm start` and navigate to `localhost:3000`

Note this was originally posted on https://github.com/angular/angular/issues/12760 but it was closed because @vicb thought it's a CLI issue. I open this as a new issue because this is a problem even without using angular-cli. 

**Expected behavior**
ng-xi18n should work

**Minimal reproduction of the problem with instructions**
Clone the demo repository: 
https://github.com/reynardmh/bugdemo-angular-i18n-no-cli

```
npm install
./node_modules/.bin/ng-xi18n
```

**What is the motivation / use case for changing the behavior?**
Importing angular component from a shared library is a common use case. `ng-xi18n` should work for this use case. 

**Please tell us about your environment:**

macOS Sierra

* **Angular version:** 2.2.4

* **Browser:** 
Not applicable, the error happens when running command line `ng-xi18n`
 
* **Language:** TypeScript 2.0.9

* **Node (for AoT issues):** `node --version` =  v7.0.0

**Comment by reynardmh** [comment]
Please don't just close this report. I'm willing to look into this issue if someone can give me guidance (I have no knowledge of angular code base, but I'll try my best)

**Comment by matsko** [comment]
@vicb have you come across this issue in the past?

**Comment by vicb** [comment]
@reynardmh ngx-i18n shares a lot of code with the AoT compiler and the part that crawls the source files has been heavily refactored during the past weeks. I guess this must have been fixed.

Sorry for not seeing the message earlier. OTOH you probably do not want to work on this code first, it requires a very deep knowledge of Typescript internals. If you want to work on some issues to get more familiar with the code, some have a [community help](https://github.com/angular/angular/issues?q=is%3Aopen+is%3Aissue+label%3A%22hotlist%3A+community-help%22) label and should be good to start digging in the code base.

Could you please the issue if not reproducible. Thanks.

**Comment by reynardmh** [comment]
I still get the same error after upgrading to angular 2.4.2. 

I have updated the reproducible repo: https://github.com/reynardmh/bugdemo-angular-i18n-no-cli

**Comment by ocombe** [comment]
Have you tried it with version 4.x ?

**Comment by reynardmh** [comment]
not yet. Sorry I'm not up to date with the versioning change. So the latest released is 2.4.10 right? Angular 4 is still in RC? how do I use version 4.x?

**Comment by ocombe** [comment]
Just install @angular/... with version 4.0.0-rc.5

**Comment by reynardmh** [comment]
Ok updated to 4.0.0-rc.5 and get a more verbose message but basically the same.

```
Error: Unexpected value 'CoolComponent in /path/to/project/node_modules/angular2-component-module/lib/cool.component.d.ts' declared by the module 'AppModule in /path/to/project/app/app.module.ts'. Please add a @Pipe/@Directive/@Component annotation.
```

Is it because `ngx-i18n` only look at .d.ts file https://github.com/reynardmh/angular2-component-module/blob/master/lib/cool.component.d.ts which does not have component annotation. 

instead of the compiled .js
https://github.com/reynardmh/angular2-component-module/blob/master/lib/cool.component.js

Because I can run the project just fine, this error only happens when running `ngx-i18n`

**Comment by ocombe** [comment]
Ok thanks, we'll look into it.

**Comment by netdeamon** [comment]
I am facing the same issue. Using angular 4.X.

When trying to run the  `./node_modules/.bin/ng-xi18n`, it gives the error 

```
Error: Unexpected value 'NvD3Component in /Users/<username>/Projects/ppe/ppe_new/plugintest/angular/node_modules/ng2-nvd3/
build/ng2-nvd3.component.d.ts' declared by the module 'AppModule in /Users/<username>/Projects/ppe/ppe_new/plugintest/angu
lar/src/app/app.module.ts'. Please add a @Pipe/@Directive/@Component annotation.
```

I removed the nvd3component, but then it gives error in some other npm module file. 
Here is the `ng2-nvd3.component.d.ts` file

```
import { OnChanges, ElementRef, SimpleChanges } from '@angular/core';
export declare class NvD3Component implements OnChanges {
    options: any;
    data: any;
    el: HTMLElement;
    chart: any;
    chartType: string;
    svg: any;
    constructor(elementRef: ElementRef);
    ngOnChanges(changes: SimpleChanges): void;
    initChart(options: any): void;
    updateWithOptions(options: any): void;
    updateWithData(data: any): void;
    updateSize(): void;
    configure(chart: any, options: any, chartType: any): void;
    configureEvents(dispatch: any, options: any): void;
    clearElement(): void;
}
```

It does not have `@Component` annotation.

**Comment by vicb** [comment]
Is this still an issue ?

@ocombe could you please follow up and close if no issue.

**Comment by ocombe** [comment]
Should be resolved, another similar issue was fixed in 5.x.
Closing this, let us know if we should reopen.
