### ISSUE TITLE
Rollup fails on rxjs/Subject imported by @angular/core/src/facade/async.js

### ISSUE THREAD

**Issue by linusbrolin** [angular/angular#13532]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
angular.io [describes](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html) using Rollup for treeshaking and bundling, but Rollup fails with this message:
`Error: 'Subject' is not exported by node_modules\rxjs\Subject.js (imported by node_modules\@angular\core\src\facade\async.js).`

Supposedly, the solution is to use the `namedExports` option, but that doesn't make any difference at all...

My rollup-config.js looks like this:
```
import rollup from 'rollup';
import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import uglify from 'rollup-plugin-uglify';

export default {
  entry: 'aot/client.aot.js',
  dest: 'dist/build.js', // output a single application bundle
  sourceMap: false,
  format: 'iife',
  plugins: [
    nodeResolve({
      jsnext: true,
      module: true
    }),
    commonjs({
      include: 'node_modules/rxjs/**',
      namedExports: {
        'node_modules/rxjs/Subject.js': [ 'Subject' ]
      }
    }),
    uglify()
  ]
}
```
**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
OS: Windows 10, IDE: VSCode, package manager: npm

* **Angular version:** 2.2.4

* **Browser:** [all]
 
* **Language:** [ES2015]

* **Node (for AoT issues):** `node --version` =   v6.9.2

**Comment by schippie** [comment]
@linusbrolin Change the config to the following:

```javascript
export default {
  entry: 'aot/client.aot.js',
  dest: 'dist/build.js', // output a single application bundle
  sourceMap: false,
  format: 'iife',
  plugins: [
    nodeResolve({
      jsnext: true,
      module: true
    }),
    commonjs({
      include: 'node_modules/**'
    }),
    uglify()
  ]
}
```

**Comment by linusbrolin** [comment]
@schippie I've tried that, it doesn't make any difference.

**Comment by schippie** [comment]
@linusbrolin That's odd I'm currently using the above configuration with angular 2.2.3 which is working.

**Comment by linusbrolin** [comment]
@schippie yeah, I just found the problem.
In my project I use a gulpscript for compiling, due to having alot of other assets and libs that should be copied and/or compiled aswell.
However, doing the rollup from a gulpscript seems to produce this error. Very weird.

I posted my gulpscript here: https://github.com/rollup/rollup-plugin-commonjs/issues/137#issuecomment-268030321

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource the original issue was fixed ☝️ . can be closed

**Comment by dimpu** [comment]
Any fix for this issue?

**Comment by omouse** [comment]
This is still an issue and the Angular docs specifically mention using Rollup and have example code. Surprised to see this closed as "not a problem with Angular" when it's clearly mentioned in the Angular.io guide.

**Comment by hamzahamidi** [comment]
Unfortunately this is still an issue in angular 4

**Comment by pranesh229** [comment]
Any fix for this issue ?

**Comment by kumbiraibenjamin** [comment]
I currently have the same issue with this error, while thryin yo create umd file with rollup.js in Angular 5

[!] Error: 'Subject' is not exported by ../../node_modules/rxjs/Subject.js

Ive tried this but i still get an error.

   commonjs({
        include: 'node_modules/**',
        include: 'node_modules/rxjs/Subject.js',
        namedExports: {
            'node_modules/rxjs/Subject': [ 'Subject' ]
        }
    }

**Comment by sree-kumar-namputhiri** [comment]
When I got this error, I could resolve it by correcting the `node_modules` path in `rollup-config.js`. I pointed it to the path relative to the folder where I was running rollup, in my case, 
`commonjs({
        include: '../../../../node_modules/rxjs/**',
      })`

Of course, after this, I have a different problem now with `rxjs\util\isArrayLike.js` file, but I have crossed this stage, I think.
