### ISSUE TITLE
2.2.1 -> 2.4.1 Breaks loadChildren() => Module

### ISSUE THREAD

**Issue by peku33** [angular/angular#13692]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After upgrading from 2.2.1 to 2.4.1 `loadChildren: () => Module` in routes does not work anymore. Before upgrade I was able to use this construction to delegate certain route to external module. I did not use lazy loading. I used `loadChildren` to separate application parts.

Error in console:
`Uncaught TypeError: Cannot convert undefined or null to object`

thrown in:
```
	        ReflectionCapabilities.prototype.annotations = function (typeOrFunc) {
	            var /** @type {?} */ parentCtor = Object.getPrototypeOf(typeOrFunc.prototype).constructor;
	            var /** @type {?} */ ownAnnotations = this._ownAnnotations(typeOrFunc, parentCtor) || [];
	            var /** @type {?} */ parentAnnotations = parentCtor !== Object ? this.annotations(parentCtor) : [];
	            return parentAnnotations.concat(ownAnnotations);
	        };
```

On the second line. `typeOrFunc` is my `() => Module`. It does not have `prototype` property.

**Expected behavior**
No idea how it worked before, but it did. I was able to navigate between modules, no errors were thrown.

**Minimal reproduction of the problem with instructions**
I used this scheme in my previous submission about DI. The repo is the same:
https://github.com/peku33/angular2-dependency-injection-failure

**What is the motivation / use case for changing the behavior?**
I want to use `loadChildren()` to logically separate parts of my app. I'm not using "lazy loading".

**Please tell us about your environment:**
Node v7.2.0
Npm 3.10.9
@angular/ [everything] @2.4.1
webpack@1.14.0

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Same on Chrome and Firefox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] Version 2.1.4, ES6

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Sounds like duplicate of https://github.com/angular/angular/issues/13565

**Comment by vicb** [comment]
@DzmitryShylovich is right, this should be fixed in the next release

**Comment by peku33** [comment]
Any update to this. I updated all libraries to 2.4.4 and there is no change to the problem.

**Comment by DzmitryShylovich** [comment]
@peku33 reproduce in plunkr and file a new issue

**Comment by peku33** [comment]
I posted reproduction in my first post. I just re-launched it and still get 'Cannot convert undefined or null to object'

**Comment by peku33** [comment]
```
	    function getParentCtor(ctor) { //ctor = PlatformRef_(_injector)
	        var /** @type {?} */ parentProto = Object.getPrototypeOf(ctor.prototype); // Error here: prototype is undefined
	        var /** @type {?} */ parentCtor = parentProto ? parentProto.constructor : null;
	        // Note: We always use `Object` as the null value
	        // to simplify checking later on.
	        return parentCtor || Object;
	    }
```

**Comment by peku33** [comment]
@vicb May I ask for reopening?

**Comment by DzmitryShylovich** [comment]
Reproduce on Plunkr. Nobody has time to clone and install apps from github.
You can use https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5 as a starting point

**Comment by peku33** [comment]
Plunkr with 2.4.1 uses SystemJS, and I'm not able to reproduce the problem.
https://plnkr.co/edit/dIEcS059sF518Yu73QMf?p=preview

I use webpack

**Comment by DzmitryShylovich** [comment]
Then it's not an angular issue and something wrong with local config.

**Comment by peku33** [comment]
The problem is, as in #13565, that at some point angular tries to access `prototype` property of each parameter supplied to route. For local anonymous function, the `prototype` property does not exist. I have no idea, why this is not throwing an error on plunkr. If, instead of anonymous `() => Module` i use `function() { return Module; }` everything is fine.

I have no idea how plunkr affects behavior of execution.

**Comment by DzmitryShylovich** [comment]
It was fixed this is why it works on plunkr

**Comment by peku33** [comment]
Ehh... I used plunkr with 2.4.1, exactly the same version as I used on my local machine when I was posting the issue. **Today** I updated to 4.0.0-beta4 **before** posting, that the issue still exists

**Comment by staeke** [comment]
@DzmitryShylovich this is still an issue as of Angular 4.4.6. BUT...it only occurs when targeting es2015 or later, i.e. lambda functions. Writing 
```
loadChildren: function() {...}
```
works, whereas 
```
loadChildren: () => {...}
```
doesn't. Hence, normally transpiling "fixes" your problem for you.
