### ISSUE TITLE
Secondary child outlet inside empty primary segment does not match

### ISSUE THREAD

**Issue by daeschlerdavid** [angular/angular#14662]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
A secondary child named outlet inside an empty primary outlet does not match.

**Expected behavior**
A secondary child named outlet inside an empty primary outlet should match.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/O4XNG3FHhWM0m1XRwX0p?p=preview

Just click on link "show bar in secondary outlet".
Going to http://.../(foo:bar) **does not init** the Bar component inside the foo named router-outlet
Going to http://.../(foo:bar) **should** init Bar component inside the foo named router-outlet

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
* **Angular version:** 4.0
* **Browser:** [all]
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AoEmaster** [comment]
can someone take a look at my plunker, and at least tell me if I am doing something wrong ?

**Comment by denisyilmaz** [comment]
i think our issues are the same. #14896 any updates on this?

**Comment by bennadel** [comment]
Yeah, I'm definitely running into this as well. I have a named-outlet that is a sibling to a primary outlet, both of which are inside a pathless wrapper component: https://plnkr.co/edit/4sKU9I9YurG05Kmv4H0l

**Comment by Meligy** [comment]
I also can confirm this issue, using @bennadel example.

Take a look at this config:

```ts
    RouterModule.forRoot(
      [
        {
          path: "",
          component: StandardLayout,
          children: [
            {
              path: "layout-a",
              component: LayoutA
            },
            {
              path: "layout-b",
              component: LayoutB
            },
            {
              outlet: "widget", // <---- This is the named outlet.
              path: "thing",
              component: Widget
            }
          ]
        }
      ])
```

When you add a have the named router outlet and a router link inside `StandardLayout` component like 
```html
<a [routerLink]="[{ outlets: { widget: [ 'thing' ] } }]">Open Widget</a>
<router-outlet name="widget"></router-outlet>
```
And you click the link, you get
```
Error: Cannot match any routes. URL Segment: 'thing'
```

This is reproducible here: https://stackblitz.com/edit/angular-khsgga?file=app%2Fapp.module.ts

----

Now, take that `thing` named outlet route outside of the empty path route, like:

```ts
    RouterModule.forRoot(
      [
        {
          outlet: "widget", // <---- This is the named outlet.
          path: "thing",
          component: Widget
        },
        {
          path: "",
          component: StandardLayout,
          children: [
            {
              path: "layout-a",
              component: LayoutA
            },
            {
              path: "layout-b",
              component: LayoutB
            },
          ]
        }
      ])
```

When you try again (make sure to reset the URL to `/` in the browser every time you test this, to avoid false results), and click that link, you get:

- No error
- Nothing showing (nothing filling the named outlet)

The reason for nothing showing is that now because the named outlet route is top level, we can no longer put the named router outlet tag inside `StandardLayout` anymore. We have to put it top level (in `AppComponent`), which breaks the original use case of using it inside the `StandardLayout` component route (the one with empty path here), with either of its child routes setting the named outlet route as they wish.

A working case can be shown at: https://stackblitz.com/edit/angular-qas6hg?file=app%2Fapp.module.ts

In this particular example, I can use `AppComponent` directly instead of `StandardLayout` component, but remember:

- This is just a demonstration. Any real world scenario of this case may not be achievable. It's also bad in case I need `AppComponent` for anything else (general nav or whatever). It's not clean.
- The functionality is still broken, whereas the functionality is routing to named outlet as a child of a route with empty string path.

**Comment by Meligy** [comment]
As @bennadel mentioned on Twitter, another workaround is to prefix the entire app routes, something like:

```ts
    RouterModule.forRoot(
      [
        {
          path: "",
          pathMatch: "full",
          redirectTo: "app" // <-- prefix
        },
        {
          path: "app", // <-- prefix
          component: StandardLayout,
          children: [
            {
              path: "layout-a",
              component: LayoutA
            },
            {
              path: "layout-b",
              component: LayoutB
            },
            {
              outlet: "widget", // <---- This is the named outlet.
              path: "thing",
              component: Widget
            }
          ]
        }
      ])
```

A silly side effect of that is that all routes have to include the prefix if they are root-relative, or change to be relative to current route, like:

```html
      <a routerLink="./layout-a">Layout A</a> |
      <a routerLink="/app/layout-b">Layout B</a>
```

Working example showing this: https://stackblitz.com/edit/angular-hdhh8a?file=app/app.module.ts

**Comment by bennadel** [comment]
@Meligy very excellent! Thanks for putting that together -- I was gonna try after work.

**Comment by bennadel** [comment]
It looks like this bug manifests if the parent segment is pathless, even if there is an ancestor with a path. For example, this still breaks:

```js
{
	path: "app",
	children: [
		{
			path: "",
			component: StandardLayout,
			children: [
				{
					path: "layout-a",
					component: LayoutA
				},
				{
					outlet: "widget", // <---- will not work
					path: "widget",
					component: Thing
				}
			]
		},
		{
			path: "console",
			component: ConsoleLayout,
			children: [
				// ....
			]
		}
	]
}
```

Even though the entire route-set is wrapped in the prefix `/app`, the named-outlet will still break because its local parent segment is empty. So, it's not just the route can't be empty, it's that the direct parent can't be empty.

**Comment by wdumlao** [comment]
Is this issue fixed with the latest router package?

**Comment by DaSchTour** [comment]
This is still an issue. Don't close this like https://github.com/angular/angular/issues/10726

**Comment by atscott** [comment]
Duplicate of #10726, which is reopened now.
