### ISSUE TITLE
Always include the NoopAnimationsModule in ServerModule

### ISSUE THREAD

**Issue by vikerman** [angular/angular#14784]
This will let animations work as a no-op on the server side when the AnimationModule included in the client app module.

**Comment by kukjevov** [comment]
`NoopAnimationsModule` included in server side results in error see https://github.com/angular/angular/issues/15098 :)

**Comment by vikerman** [comment]
Dupe of #15098

**Comment by ysus** [comment]
@kukjevov can you fix the problem?

**Comment by kukjevov** [comment]
It was already fixed

**Comment by diestrin** [comment]
@kukjevov what version was it fixed? I'm using 4.1.3 and it still throws an error.
cc: @TheloniousSF

**Comment by kukjevov** [comment]
Sorry for late answer, but i think it was fixed in one of 4.0.x releases. Not sure thou.
