### ISSUE TITLE
ngOnDestroy not firing when provide is an abstract class

### ISSUE THREAD

**Issue by colinkahn** [angular/angular#14821]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When specifying a provider where `provide` is an abstract class and `useClass` is a concrete one, `ngOnDestroy` will never be called in the concrete class.

**Expected behavior**
`ngOnDestroy` should be called.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/eIs7pjvldhcFrMmaJ4IV?p=preview

1. Open the console.
2. Click the "Create Component" button one or many times
3. After a 2 second delay the component will be destroyed, but no console output will be seen.

**What is the motivation / use case for changing the behavior?**
Providing abstract classes with concrete implementations that utilize `ngOnDestroy` to do cleanup.

**Please tell us about your environment:**

* **Angular version:** 2.4.8

* **Browser:** Chrome 56.0.2924.87

 
* **Language:** TypeScript 2.0

* **Node (for AoT issues):** `node --version` =

**Comment by splincode** [comment]
@DzmitryShylovich What is the status of the task?

**Comment by LaniMoo** [comment]
Is there a workaround for this?

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/14818, has been fixed by https://github.com/angular/angular/pull/23755

**Comment by tapthoppe** [comment]
what status of this?

**Comment by andreyjamer** [comment]
The problem is still reproduced on v 6.1.0 where it was fixed.
If provide service in component with useClass, then onDestroy is not fired.
If provide service directly, then everything is ok.

**Comment by andreyjamer** [comment]
Prepared example on v 7.0.1 to show the problem - https://stackblitz.com/edit/angular-qxrald?embed=1&file=src/app/hello.component.ts

Click the "toggle" button one or many times
`Direct provided service` will be created and destroyed. 
`Factory provided service` and `Use class provided service` will be created and never destroyed.

It may cause memory leaks, i guess.

**Comment by andreyjamer** [comment]
Any update on this issue? 
I guess all services provided in components are affected. 
Not sure if it causes memory leaks, but it definitely could.

**Comment by Rush** [comment]
Any update on this issue?

**Comment by distante** [comment]
Is this bug active for almost two years now or did I saw something wrong?

**Comment by free-easy** [comment]
+1

**Comment by kara** [comment]
This is a real View Engine bug. See updated Stackblitz with v9 here:
https://stackblitz.com/edit/angular-ivy-ir1nzk?file=src%2Fapp%2Fhello.component.ts

The `useClass` issue is fixed with Ivy, though:

https://stackblitz.com/edit/angular-ivy-bsnzpz?file=src/app/hello.component.ts

**Comment by distante** [comment]
@kara this also happens when the service is provided locally using a factory. And it is not fixed by ivi. Or that is another bug?

**Comment by kara** [comment]
@distante I view them as separate issues because factories would be more complicated to support. That one is tracked [here](https://github.com/angular/angular/issues/28738)
