### ISSUE TITLE
Errors are not readable / prevent sourcemaps in console because of Zone.js

### ISSUE THREAD

**Issue by tbosch** [angular/angular#15185]
Zone.js replaces the global `Error` function.
This breaks logging of errors:

- if a user calls `new Error(...)`, the error is shown as an object instead of showing its stack
- for SyntaxErrors, stack traces don't work correctly with sourcemaps.
- source maps don't work on stack traces when long-strack-trace zones is used

**Comment by tbosch** [comment]
for the long stack traces issue, see https://github.com/angular/zone.js/issues/661

**Comment by tbosch** [comment]
Long-stack-trace zone is not fixed yet...

**Comment by Martin-Wegner** [comment]
I don't know if this is related... When I use `require('zone.js/dist/long-stack-trace-zone');` then I get this console output in Chrome (not in Firefox):

```
long-stack-trace-zone.js?fcc3:149 >>>>>>  Error: STACKTRACE TRACKING
long-stack-trace-zone.js?fcc3:149 >>>>>>     at __SEP_TAG__ (eval at <anonymous> (http://localhost:8080/polyfills.js:3091:1), <anonymous>:128:37) [<root>]     at captureStackTraces (eval at <anonymous> (http://localhost:8080/polyfills.js:3091:1), <anonymous>:128:37) [<root>]
```

**Comment by cdupetit** [comment]
@Martin-Wegner Same console output for me (zone.js: 0.8.4) :
```
long-stack-trace-zone.js:149 >>>>>>  Error: STACKTRACE TRACKING
long-stack-trace-zone.js:149 >>>>>>     at __SEP_TAG__.54 (http://10.3.60.13:3000/index.js:1122:1) [<root>]     at Object.54 (http://10.3.60.13:3000/index.js:1122:1) [<root>]
long-stack-trace-zone.js:149 >>>>>>     at __SEP_TAG__.54 (http://10.3.60.13:3000/index.js:1122:1) [<root>]     at eval (webpack:///./src/polyfills.browser.ts?:9:93) [<root>]
```
my polyfills.browser.ts:
```
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
import 'core-js/client/shim';
import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';
import 'ts-helpers';

```

**Comment by tbosch** [comment]
Note: This is already fixed in https://github.com/angular/zone.js/commit/6010557df0d2e640c2ba5836bedb7b6fc70028c9 and will be released soon.

**Comment by helzgate** [comment]
I'm still getting @Martin-Wegner's issue even after installing 0.8.8.  Anyone else?

**Comment by shwedberlin** [comment]
Just installed 0.8.12 - still getting this in VS console

**Comment by sebastianrothbucher** [comment]
a hint (I think it was mentioned above): including 
```
npm install source-map-support --save-dev
```
and
```
import 'source-map-support/register';
```
into the root test.ts gets back the mapped exceptions. Did not check deeply for side effects - but maybe that helps already
