### ISSUE TITLE
ViewWrappedDebugErrors prevent root cause inspection of http errors

### ISSUE THREAD

**Issue by bedag-moo** [angular/angular#15926]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The [factory method for viewWrappedDebugErrors](https://github.com/angular/angular/blob/master/packages/core/src/view/errors.ts#L25) invokes toString() on exceptions that are not Errors, but the HttpModule communicates http errors by throwing a Response. As a consequence, the Response object is converted to a String before it gets to the exception handler, which prevents a custom ErrorHandler from inspecting the cause of that error.

**Expected behavior**
Custom ErrorHandlers should be able to inspect a HTTP error, so they can extract backend error messages and correlation ids.

**Minimal reproduction of the problem with instructions**

1. unpack the [attached zip file](https://github.com/angular/angular/files/917299/testcase.zip)
2. `npm install`
3. `ng serve`
4. browse to localhost:4200
5. use the "Report issue" link to switch to another view, 
6. use the "Dashboard" link to switch back to the original view, whose activation will fail with a viewWrappedDebugError caused by a thrown Response due to missing backend.

**What is the motivation / use case for changing the behavior?**
- Enable correlation of front- and backend errors. 
- Relaying backend exception messages to the user (if the UI does not have a dedicated handler for this exception).

**Please tell us about your environment:**
* **Angular version:** 4.0.0 and master

* **Browser:** all
 
* **Language:** all

**Comment by bedag-moo** [comment]
Looks fixed in the HttpClient API.

**Comment by Tegyr** [comment]
I don't think the HttpClient API fixed this... I know this might seem unrelated, but if I use an interceptor to customly handle HttpEvents and then throw a (custom) error, I still have the same problem.

As far as I can backtrace, the real problem in case of the HttpClient is that the HttpErrorResponse class is not instance or Error, which causes viewWrappedDebugError to call toString() on the HttpErrorResponse. This causes the HttpErrorReponse to be logged as "[object Object]".

If needed, I can elaborate with actual code.

**Comment by bedag-moo** [comment]
My apologies; yes, @Tegyr is right that the HttpErrorResponse is not instanceof Error. 

However, my tests seem to indicate that a viewWrappedDebugError is only applied if the Observable yields an error immediately, for instance because a circuit breaker cached the error response. If the observable yields an error asynchronously (which is the usual case), I do not see a viewWrappedDebugError applied.

**Comment by Tegyr** [comment]
@bedag-moo you are absolutely right! I just tested it quick and dirty and by making the code run asynchronously the viewWrappedDebugError is not applied. I kind of understand the reasoning, but it's a shame the general logic isn't at least documented anywhere.

**Comment by alxhub** [comment]
Hmm. This is something we never considered in the design of `HttpClient`. I'm tagging this as a `use-case` so we can discuss it.

**Comment by JoostK** [comment]
Closing as `ViewWrappedDebugErrors` is no longer a thing in Ivy
