### ISSUE TITLE
Language Service: does not work with "paths" from .tsconfig

### ISSUE THREAD

**Issue by karptonite** [angular/angular#16382]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Set "paths" and "baseUrl" in tsconfig. for example:
```
"compilerOptions": {
  "baseUrl": "src",
  "paths": {
    "@myapp/*": [
        "app/*"
      ]
    },
}
```
Then import a component in a module using the path set via `paths`.
```
import {HeaderComponent} from  "@myapp/header/header.component";
```

Add `{{foo}}` to header.component.html. The error reported is "Unresolved variable or type foo".
The import seems to work fine, otherwise.

**Expected behavior**
The error should be: "Angular: Identifier 'foo' is not defined. The component declaration, template variable declarations, and element references do not contain such a member". This is the error that is reported if the import is done via a relative link, e.g, "./header/header.component"

**Minimal reproduction of the problem with instructions**
As described above.

**What is the motivation / use case for changing the behavior?**
To get proper errors via language service when using absolute paths for imports.

**Please tell us about your environment:**
PhpStorm 2017.1.3, MacOS 10.12.4.

* **Angular version:** 4.1.0

* **Browser:** N/A

* **Language:** Typescript

* **Node (for AoT issues):** `node --version` =   7.9.0

**Comment by karptonite** [comment]
Hold off on this--I'm not able to reproduce it at the moment. It may have been user error. I'm also unable to get the language service working at all, but that may be a PHPStorm issue.

**Comment by karptonite** [comment]
OK, I can now confirm that I can reproduce this bug.

I was temporarily unable to Language Service working at all due to this bug in Typescript, https://github.com/Microsoft/TypeScript/issues/15433, but that is now fixed, and I'm still seeing the behavior described in my initial report.

**Comment by Outruller** [comment]
Is there any further info about this issue?

**Comment by jusefb** [comment]
I have the same problem would appreciate a fix for this

**Comment by karptonite** [comment]
Just to confirm This is still an issue in Angular 4.2.0.

**Comment by karptonite** [comment]
Here is a repo that anyone can pull down to reproduce the error:
https://github.com/karptonite/angular-test-language-service/commit/478748d304c14ed5e89138227dc6f0b20b81cc80

In this case, the issue is in `app.component.ts`. When I import TestService with a path base on the `paths` param in tsconfig, as shown, I get the error message shown in the comments. If I replace the import with the relative path (commented out), no error.

This is with PHPStorm EAP 2017.2, although I hope that wouldn't make a difference.

**Comment by karptonite** [comment]
In case this is a PHPStorm issue, I've also reported this here:
https://youtrack.jetbrains.com/issue/WI-36836

**Comment by aitboudad** [comment]
not sure if it's related to `PHPStorm` as I've got the same issue using `vscode`

**Comment by aitboudad** [comment]
https://github.com/angular/vscode-ng-language-service/issues/99

**Comment by ylibrach** [comment]
Can confirm that this is an issue using VSCode as well. Using a `baseUrl` property in tsconfig (along with `paths`, although I think the root issue is the `baseUrl`), and I cannot resolve anything imported from locations defined by the baseUrl+paths.

**Comment by ClementVidal** [comment]
I also have this issue with:
```
Angular version: 4.3.2
 
- Node version: 6.11.0
- Platform:  Linux

- VsCodde 1.14.2
- Angular language service plugin 0.1.4
- Angular language service 4.1.0-beta
```

**Comment by meriturva** [comment]
Still present on angular 4.3.6. On vscode 1.15.1 i have few errors related to: `Error encountered resolving symbol values statically` of symbols declared through `paths` property on `tsconfig.json` file . Any eta here? Thanks.

**Comment by karptonite** [comment]
Still present in Angular 5.0.0-beta.7. I've updated the Angular version in my reproduction, here: https://github.com/karptonite/angular-test-language-service

**Comment by deebloo** [comment]
I have the same problem. Trying to dig into it a bit more to see if I can find why

**Comment by aitboudad** [comment]
for a workaround try to create a symbolic link in node_modules for each defined path:
```json
"compilerOptions": {
  "baseUrl": "src",
  "paths": {
    "@myapp/*": [
        "app/*"
      ]
    },
}
```

```console
ln -s src/app node_modules/@app
```

@chuckjaz any chance to look to this issue ?

**Comment by aitboudad** [comment]
***Note***: using symlink may remove your project files when updating npm, so use it at your own risk!

**Comment by karptonite** [comment]
@aitboudad That is quite a warning!

**Comment by pearpages** [comment]
do not use the "@", it seems to work for me just now using the "@".

`"compilerOptions": {
  "baseUrl": "./src",
  "paths": {
    "myapp/*": [
        "app/*"
      ]
    },
}`

**Comment by karptonite** [comment]
@pearpages removing the "@" does not fix my reproduction of this issue: https://github.com/angular/angular/issues/16382#issuecomment-308539213

**Comment by mmukarram** [comment]
I'm with @karptonite, removing the `@` does not fix issue.

**Comment by thecp** [comment]
Funny thing because removing the `@` DID FIX the issue for me (in VS Code). This raises the question if there is more than one issue...

**Comment by atinepro** [comment]
Just to confirm, I am having the same problem with Angular service (Angular v4.4.6) in WebStorm. It has nothing to do with "@". I am trying to figure out the root cause.

**Comment by mjamin** [comment]
@thecp thank you! I can confirm that it works when path and alias are the same.

If anyone still has trouble, make sure you use `tsconfig.json` not `tsconfig.app.json` in your source folder.

`./src/tsconfig.json` should look something like this:

```
{
    "extends": "../tsconfig.json",
    "compilerOptions": {
        "baseUrl": ".",
        "outDir": "../out-tsc/app",
        "module": "es2015",
        "types": [],
        "paths": {
            "@foo/*": [
                "@foo/*"
            ]
        }
    },
    "exclude": [
        "test.ts",
        "**/*.spec.ts"
    ]
}
```

**Comment by aitboudad** [comment]
I think this has been fixed by #20222, to try it install the snapshot build of `language-service`:
```
npm install --save-dev angular/language-service-builds
```

**Comment by karptonite** [comment]
Cool, when it comes out in a point release, I'll give it a try!

**Comment by darrenmothersele** [comment]
I was having the same issue in PhpStorm with Angular 5 and CLI 1.5.
Installing snapshot build of `language-service` fixed it - as per https://github.com/angular/angular/issues/16382#issuecomment-343603683

**Comment by karptonite** [comment]
It does look like this has been fixed by #20222. Everything seems to work properly with language-service 5.1.0-beta.1, so I'm going to close this issue. Thanks, @kyliau!

**Comment by trojanc** [comment]
Happiness in IntelliJ using 5.1.0-rc.1 ! No more "Can't resolve all parameters for xxx"

**Comment by davidwuerfel** [comment]
This is still showing up in VS Code (V1.18.1). No problem when using WebStorm, but my editor of choice is VS Code. Is there anyone else with the same problem or a fix? (see also: https://github.com/nrwl/nx/issues/73).

**Comment by reaction1989** [comment]
Workaround:

your module names must match the path.

Assuming your tsconfig.json has this properties

`"baseUrl": "src"
"paths": {
            "@modules/*": ["@modules/*"]
        }`

Then you need following directory structure

src
-app
-modules
--module1
--module2

**Comment by davidwuerfel** [comment]
I think this should be correct:
`"baseUrl": ".", "paths": { "@mynamespace/*": ["libs/*"] }`

Having the following directory structure:
```
apps
 -app1
  --src
   ---app
libs
 -lib1
  --src
   ---lib.module.ts
tsconfig.json
```

This works well in Typescript when referring to `@mynamespace`.
However, this does not work for the template html, which gives the following error:
```'my-button' is not a known element:
1. If 'my-button' is an Angular component, then verify that it is part of this module.
2. If 'my-button' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.```

**Comment by shenchaoran** [comment]
Can `@angular/language-service@5.1.0-beta.1` use in Angular 4 ?
I had tried update the language-service to 5.1.0-beta.1 but it doesn't make sense. My angular version is 4.4.4.

**Comment by thismarcoantonio** [comment]
I was getting this error, for the fix in `tsconfig.json` in root folder, I needed to set baseUrl to "src" and in the "path" the same paths in `src/tsconfig.app.json`. In `src/tsconfig.app.json` I've just added the paths and the baseUrl should be './'... Now it's everything working fine.

**Comment by davidwuerfel** [comment]
FYI: I had a problem when using VSCode extension for language service. This has been fixed with newer versions. Tested it with v0.1.9. It is now working as expected. (https://github.com/angular/vscode-ng-language-service/issues/211)

**Comment by matheo** [comment]
Well, I've installed `"@angular/language-service": "^5.2.8"` on my Angular 4.4 project and it seems to work properly :D thanks a lot

**Comment by pajarraco** [comment]
I still have this issue, I try using paths but is not working

I using: 
vscode 1.21.1
angular 5.2.9
"@angular/language-service": "^5.2.9"

**Comment by armandoaepp** [comment]
### Como Configurar Path absolut0 in angular 5.2.0 ?
Buenas estoy tratando de configurar el path para cuando importe un component, servicio y otro pueda utlizar el path absoluto. 

```
**import { foo } from ‘../bar’;**  
se de la forma 
**import { foo } from ‘app/bar’;** 
 
```

alguien puede ayudarme intente con **"baseUrl": "src",**  de los archivos **tsconfig.json** y t**sconfig.app.json**

**Comment by radiumrasheed** [comment]
anyone having the issue should make sure the `baseUrl` and `paths` are not overridden by any other file
