### ISSUE TITLE
Router Guards not listed in router.config

### ISSUE THREAD

**Issue by Karasuni** [angular/angular#16630]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The [Angular.io guide on routing](https://angular.io/docs/ts/latest/guide/router.html#!#inspect-config) suggests logging `@angular/router`'s `router.config` to see the configuration of your router tree. In the [example provided](https://angular.io/resources/live-examples/router/ts/eplnkr.html) you see
```typescript
  {
    "path": "admin",
    "loadChildren": "app/admin/admin.module#AdminModule",
    "canLoad": [
      null
    ]
  },
```
Even though a guard is registered the `canLoad` parameter is `null`, implying the service is not resolved and registered for callback.

**Expected behavior**
```typescript
  {
    "path": "admin",
    "loadChildren": "app/admin/admin.module#AdminModule",
    "canLoad": [
      "AuthGuard"
    ]
  },
```

**Minimal reproduction of the problem with instructions**
Open [the official example app](https://angular.io/resources/live-examples/router/ts/eplnkr.html) and look at the console log.

**What is the motivation / use case for changing the behavior?**
Incorrect / confusing logging complicates development.

**Please tell us about your environment:** Angular.io

* **Angular version:** 4.1.1

**Comment by jasonaden** [comment]
The `AuthGuard` should be an injectable symbol, not a string. That should fix this issue.

**Comment by Karasuni** [comment]
@jasonaden Are you saying there is a fix for this issue? I've loaded up the official [example](https://angular.io/generated/live-examples/router/eplnkr.html) and still see `"canLoad": [ null ]` even though there is an AuthGuard set.

**Comment by gkalpak** [comment]
This is a `docs` issue, not a `router` issue. The logged `null` value is a result of how `JSON.stringify()` stringifies functions inside an array. In order to avoid confusion, one could use a custom `replacer` in `JSON.stringify()` that uses the function's name instead:

```diff
-console.log('Routes: ', JSON.stringify(router.config, undefined, 2));
+const replacer = (key, value) => (typeof value === 'function') ? value.name : value;
+console.log('Routes: ', JSON.stringify(router.config, replacer, 2));
```

This should be changed in:

https://github.com/angular/angular/blob/8c5208834671a8a1f29cf28a5a4e7f16a816e21e/aio/content/examples/router/src/app/app.module.ts#L52-L54

**Comment by kapunahelewong** [comment]
@jenniferfell This issue needs an update in the example as well as the doc.

**Comment by jenniferfell** [comment]
It looks like this has been resolved. The example now looks like the "expected behavior" above, only without the AuthGuard being a string: 

path: 'admin',
loadChildren: 'app/admin/admin.module#AdminModule',
canLoad: [AuthGuard]

@brandonroberts @gkalpak @jasonaden What do you think? Can we close this as resolved? Thanks!

**Comment by brandonroberts** [comment]
I'm still seeing the same behavior being logged to the console in the stackblitz example
