### ISSUE TITLE
Not work live example in documentation

### ISSUE THREAD

**Issue by splincode** [angular/angular#16789]
If you go to the link and open the example, you will notice that it does not work

https://angular.io/docs/ts/latest/cookbook/dynamic-component-loader.html

**Comment by zoechi** [comment]
"does not work" means

```
ng:///AppModule/HeroProfileComponent.ngfactory.js:23 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'Bombasto'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?
```

**Comment by echonax** [comment]
Possibly related with: https://github.com/angular/angular/issues/16765

**Comment by wardbell** [comment]
Fixed.

**Comment by stason4ik** [comment]
Still not work:
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'Bombasto'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook
