### ISSUE TITLE
Router: skipLocationChange is routing to root.

### ISSUE THREAD

**Issue by damiandennis** [angular/angular#16981]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The skipLocationChange in the router used to change the component and keep the url as it was.
**Expected behavior**

The skipLocationChange in the router would change the component without changing the route.
**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/F2YVpAV1EtNUolNgFClR?p=preview
**What is the motivation / use case for changing the behavior?**

Redirections to 404's etc should not change the url
**Please tell us about your environment:**

* **Angular version:** 4.0.X

Was working correctly in 2.0.X
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript
* **Node (for AoT issues):** `node --version` =

**Comment by zoechi** [comment]
I guess this needs a Plunker to reproduce to become a valid bug report.

**Comment by sunild** [comment]
I'm having this problem too.

The problem with trying to make a Plunker for this issue is that in Plunker the URL will not change like it would if you were running the app normally (w/out Plunker). For example, this Plunker from the Routing & Navigation tutorial: https://angular.io/resources/live-examples/router/ts/eplnkr.html

**Comment by sunild** [comment]
Trying to come up with a simple reproduction of the problem... In the meantime, this seems to be what's happening in my scenario:

App is launched by going to a url like "/abc", where "abc" is a route parameter.

There is a guard for the this route, and it may decide to navigate and skip the location change. 

Before navigating, the `url` property of `Router` is "/", however, the `Location` service returns the url as "/abc" (via `Location.path()`).

So in this scenario, the router thinks the current URL is "/" when it's really not. So I'd say that the skip location change logic is working, but somehow the router seems to be misguided about the current url.

**Comment by damiandennis** [comment]
My issue is also from a guard so it might be guard related.Trying to do a plunk up at the moment.

**Comment by damiandennis** [comment]
Actually getting a different issue in my plunker, run out of time to work on this but this is a start: http://plnkr.co/edit/F2YVpAV1EtNUolNgFClR?p=preview @sunild You can open it up in a separate window if you have time to complete my plunker.

**Comment by damiandennis** [comment]
The above plunker shows that there is an issue with the skipLocationChange, however it is not exactly the same as the problem I am experiencing where the navigation happens in the guard and the url changes to / ; the route correctly changes where as in this plunker example its changing route and then changing back (unless there is an error in my code and I am not seeing it)

**Comment by damiandennis** [comment]
ok my mistake, the above actually works so it must be specific to the redirect happening in the guard. I will try and reproduce

**Comment by damiandennis** [comment]
ok http://plnkr.co/edit/F2YVpAV1EtNUolNgFClR?p=preview demonstrates the issue, in component two I have a navigate in the guard, the url should be that of component 2 (it was in angular2).

**Comment by damiandennis** [comment]
@zoechi any update on this getting fixed? I have attached a preview to show the issue.

**Comment by damiandennis** [comment]
actually I have found a workaround, there must be an easier way to get the current url though:
```typescript
route.pathFromRoot.map((routes: any) => {
   return routes.url.map((urlSegment: UrlSegment) => {
     return urlSegment.toString();
   }).join('/');
}).join('/')
```

**Comment by vapits** [comment]
Any news on this issue? I do have exactly the same behavior.

**Comment by Sebubu** [comment]
+1
Same issue here. Version 4.4.6

**Comment by NickGeek** [comment]
Running into the same thing here too.

**Comment by jasonaden** [comment]
This should have been fixed with #20803. Can you please verify?

**Comment by bilel-noomene** [comment]
@jasonaden It not resolve the problem for me.

**Comment by mkarthik90** [comment]
@jasonaden I am facing the same issue. I am using angular version `5.2.0`. The issue is occurring when I do an AOT build. When I test in my local region, this doesn't happen.

**Comment by andyfri** [comment]
+1
Same issue here. Version 5.2.3

**Comment by lehoffma** [comment]
Doesn't work for me either @ version 5.2.7

**Comment by surensubhu** [comment]
I am also facing this issue. Do we have any workaround for this?

**Comment by Carlosamouco** [comment]
I was having the same problem when I tried to call `this.router.navigate` inside a resolve function.
So I end up returning `Observable.of(null);` on the resolve function and in the constructor of the requested component I call `this.router.navigate` whenever the `route.snapshot.data['data']` is null.

**Comment by Karolis92** [comment]
I think I found a workaround, in the guard before "false" is returned:
`
canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean>
<...>
this.router.navigate(['404']);
setTimeout(() => this.location.replaceState(state.url));
`
This navigates to 404 page but replaces url back to what user was trying to reach
`location` is https://angular.io/api/common/Location, not `window.location`

**Comment by vatsalpande** [comment]
did anyone find a solution for this? I am facing same issue with Angular 6

**Comment by bilel-noomene** [comment]
@vatsalpande Try [the solution](https://github.com/angular/angular/issues/16981#issuecomment-397218203) proposed by karolis92

**Comment by shivack** [comment]
Same here, is there any update on if this issue is going to be fixed? The solution by karolis92 did not work in my case though.

**Comment by vatsalpande** [comment]
Somehow this issue is happening only for me when I try to redirect from resolve block. However, it works as expected if its a normal method inside component.

**Comment by bgBond** [comment]
Any update? it also happens to me, but only in the first time of the navigation.

**Comment by bgBond** [comment]
Any update? I am using angular 7 and it still happens, but only in the first time of the navigation.

**Comment by ZBAGI** [comment]
2 years later and the issue seems to still be there. Any update ?

**Comment by ccondrup** [comment]
working off of the [comment by karolis92](https://github.com/angular/angular/issues/16981#issuecomment-397218203):
`.navigate()` returns a Promise, so no need to setup a new subscription.

    this._router.navigate(['404']).then(() => {
      this._location.replaceState(state.url);
    });

**Comment by borjapazr** [comment]
@jasonaden, any update? What is the status of this?

Thanks in advance.

**Comment by atscott** [comment]
This appears to have been resolved at some point. I copied the example to stackblitz and ran with v9: https://stackblitz.com/edit/angular-ivy-gvrcne?file=src/app/app.module.ts
Clicking the route2 link results in the component for route 3 being shown (and the url remains the same). I believe this is the expected behavior.

If after upgrade the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by RainnyX** [comment]
> 
> 
> This appears to have been resolved at some point. I copied the example to stackblitz and ran with v9: https://stackblitz.com/edit/angular-ivy-gvrcne?file=src/app/app.module.ts
> Clicking the route2 link results in the component for route 3 being shown (and the url remains the same). I believe this is the expected behavior.
> 
> If after upgrade the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

It hasn't actually, in your example when manually routing to /route2 you see it redirects to root, not route3 nor route2.
problem still exists in angular 9.1.11

**Comment by atscott** [comment]
> It hasn't actually, in your example when manually routing to /route2 you see it redirects to root, not route3 nor route2. Problem still exists in angular 9.1.11

I see. So the issue being reported is that direct navigations reset the url to the root if a guard returns false? This is a separate issue from `skipLocationChange` is really working as intended. By returning `false` from a guard, the navigation to the route is cancelled and the URL is reset. If there is no previous URL to reset to, the router falls back to the root. The navigation with `skipLocationChange` is a _separate_ navigation and shouldn't use the URL from a cancelled navigation. 

* Guards prevent navigation to a route. The expectation that the router _not_ reset the URL if a guard returns false is not how it's intended to work.
* If a second navigation is called during an in-flight navigation, the first is cancelled and the URL is also reset. Behavior would otherwise be very unpredictable.

I'm re-opening this as a feature request to provide some way of redirecting from a guard while keeping the browser URL the same. Returning a `UrlTree` from the guard is _close_ but doesn't provide the ability to use `skipLocationChange` to keep the URL of the attempted navigation.

**Comment by xavadu** [comment]
Arrive here having the same issue, manual navigate from a guard change path to root, angular version 9.

**Comment by adestis-ds** [comment]
> I'm re-opening this as a feature request to provide some way of redirecting from a guard while keeping the browser URL the same. Returning a UrlTree from the guard is close but doesn't provide the ability to use skipLocationChange to keep the URL of the attempted navigation.

**Is there a solution to this issue?** 

I am using Angular 11 and need exactly this feature. I want to implement a 403 (Forbidden) component but the URL must stay the same when the guard returns false (or UrlTree). So the user can just reload by F5 when provided correct permissions.

**Comment by atscott** [comment]
> > I'm re-opening this as a feature request to provide some way of redirecting from a guard while keeping the browser URL the same. Returning a UrlTree from the guard is close but doesn't provide the ability to use skipLocationChange to keep the URL of the attempted navigation.
> 
> **Is there a solution to this issue?**
> 
> I am using Angular 11 and need exactly this feature. I want to implement a 403 (Forbidden) component but the URL must stay the same when the guard returns false (or UrlTree). So the user can just reload by F5 when provided correct permissions.

Unfortunately not a good one at the moment, no. #27148 has some more discussion about workarounds other devs have created.
Closing as duplicate of  #27148
