### ISSUE TITLE
Bad failure mode when missing module import for router destination

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#17446]
### Problem
When routing to a component where its NgModule is not imported, the application fails in an unexpected way (that is, it _should_ fail, but in a more expected way). Ultimately this is a case of bad error reporting. 

### Reproduction
https://github.com/jelbourn/material2-app/tree/router-bad-error
* Clone the repo
* `npm i`
* `ng serve --aot`
* Visit http://localhost:4200 and click the "Other page" link

### Current behavior
In this production, you will see the error `No provider for FocusOriginMonitor!`. 

The provider is missing because `MdCheckbox` injects `FocusOriginMonitor`, but the `MdCheckboxModule` was never imported anyway (even transitively).

### Expected behavior
The error message should be something like "Hey, you defined a route with component "Other" but it's not in any NgModule imported". 

Overall the very strange thing here is that even though the `Other` component here is never imported anywhere into the bootstrapped module, the application will currently _work_ so long as there are no missing providers, which is quite unexpected. 

#### Versions
```
@angular/cli: 1.0.6
node: 6.9.0
os: linux x64
@angular/animations: 4.2.0
@angular/common: 4.2.0
@angular/compiler: 4.2.0
@angular/core: 4.2.0
@angular/forms: 4.1.3
@angular/http: 4.2.0
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.2.0
@angular/platform-browser-dynamic: 4.2.0
@angular/platform-server: 4.2.0
@angular/router: 4.2.0
@angular/tsc-wrapped: 4.2.0
@angular/cli: 1.0.6
@angular/compiler-cli: 4.2.0
```

**Comment by jelbourn** [comment]
Chatted w/ @tbosch and he agrees that this should actually be a compiler error (since this can be detected at compile-time). This would need to be behind a flag because technically it is a breaking change (even though it is catching an error state that previously going ignored).

**Comment by vicb** [comment]
We probably need to apply [this logic](https://github.com/angular/angular/blob/2447bd1bac2d2d8581260c5d93e7029fb905e75e/packages/compiler/src/aot/compiler.ts#L381-L392) to router components.

The plan would be:
- Raise a warning when the routed component is not reachable in 4.x,
- Raise an Error in 5.x (= strict mode),
- Add a flag to opt-in strict mode for 4.x, default to non-strict.

**Comment by jelbourn** [comment]
@vicb I know it's unlikely, but any chance this could get attention? It's by far the most common issue I see people get stuck on in Google.

**Comment by EricBeach** [comment]
I just ran into this today internally.

**Comment by jelbourn** [comment]
Encountered again today by @josephperrott working on some of our internal components. Probably 30 - 45 minutes wasted debugging.

**Comment by atscott** [comment]
Surprisingly, this seems to work in v9:
https://github.com/atscott/noimport
https://stackblitz.com/edit/angular-ivy-dhacqg?file=src%2Fapp%2Fapp.module.ts
The things that do cause an error are:
1. Removing the `MatCheckboxModule` from the imports
2. Removing the `Other` component from the declarations
3. Deleting the `OtherModule` completely

The resulting error is:
```
'mat-checkbox' is not a known element:
1. If 'mat-checkbox' is an Angular component, then verify that it is part of this module.
2. If 'mat-checkbox' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

**Comment by jelbourn** [comment]
@atscott that's pretty weird / surprising. How do the providers for the omitted module end up in the injector?

**Comment by alxhub** [comment]
@atscott I think what you're seeing in v9 is actually unrelated. The example works now because `MatCheckbox` no longer relies on its NgModule for providers - `FocusMonitor` and other services are now declared module-less with `@Injectable({providedIn: "root"})`. So there is no runtime need for `MatCheckboxModule` to be present at all.

**Comment by jelbourn** [comment]
Ah, in that case you'd probably see this issue with `<mat-menu>` since `Overlay` isn't provided in root.

**Comment by jelbourn** [comment]
Saw this again today with another Googler.

**Comment by jelbourn** [comment]
Encountered another victim of this issue again today.

**Comment by devoto13** [comment]
This also caused issues for `angular-fontawesome` library users - https://github.com/FortAwesome/angular-fontawesome/issues/312#issuecomment-884614475.

The developer attempted to route to the `TestComponent`, which is not part of the `AppModule` and instead of getting a clear error message that `TestComponent` is not part of the `AppModule` they saw a completely misleading error message about a not known element used inside the `TestComonent` (which is also incorrect as element is actually known):

```
Error: src/app/test/test.component.html:4:1 - error NG8001: 'fa-icon' is not a known element:
1. If 'fa-icon' is an Angular component, then verify that it is part of this module.
2. If 'fa-icon' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

4 <fa-icon [icon]="['fas', 'coffee']"></fa-icon>
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/app/test/test.component.ts:5:16
    5   templateUrl: './test.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component TestComponent.
```

**Comment by jessicajaniuk** [comment]
We can't address this in the world of ngmodules, but this is being addressed with standalone components.

**Comment by jelbourn** [comment]
I am leaving this open because the issue still impacts Angular devs.

**Comment by atscott** [comment]
Closing again per https://github.com/angular/angular/issues/17446#issuecomment-1032087891
