### ISSUE TITLE
Deprecation in Router Documentation

### ISSUE THREAD

**Issue by ralemy** [angular/angular#17905]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In the router documentation page, under [adding animations](https://angular.io/guide/router#adding-animations-to-the-routed-component),

the code sample should be refactored, since AnimationEntryMetadata is deprecated and the rest have moved to angular/animations.

    import { animate, AnimationEntryMetadata, state, style, transition, trigger } from '@angular/core';
    export const slideInDownAnimation: AnimationEntryMetadata

## Expected behavior

Should read:

      import { animate, state, style, transition, trigger } from '@angular/animations';
      export const slideInDownAnimation 

## Please tell us about your environment

<pre><code>
Angular version: X.Y.Z

4.2.5
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by realappie** [comment]
I think it's safe to just remove `AnimationEntryMetadata` from the documentation.

**Comment by jasonaden** [comment]
@matsko Can you make a suggestion on this one?

**Comment by brandonroberts** [comment]
This should be resolved once #19630 lands

**Comment by jasonaden** [comment]
Resolved with #20334

**Comment by mmatlock-shr** [comment]
This is still an issue in current documentation for v5.2.8, #20334 is still an open pull request it looks like?
