### ISSUE TITLE
Router not reusing parent component when changing only the child route

### ISSUE THREAD

**Issue by sinedied** [angular/angular#18374]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The use case is basic:
- I have an application shell (header, menu...) used as the base for all screens once the user is logged in
- Following Angular style guide, `Home` and `About` screens each use a dedicated module, each with their own routes declaration
- The `/home` and `/about` routes are child routes of the shell component

When navigating from `home` to `about`, I expected the shell component to be reused, but it's not the case:
![image](https://user-images.githubusercontent.com/593151/28668697-652b60a0-72d1-11e7-9e50-18b045cf49be.png)

The shell component is destroyed and reinstanciated when navigating between the child routes.

## Expected behavior
Since the parent component does not change (the `shell`) when navigating between child routes, I expect it to be reused by the router.

## Minimal reproduction of the problem with instructions

See this repo, based on angular-cli: https://github.com/ngx-rocket/starter-kit
- `npm start`
- log in with any user/pass
- navigate between home and about screens

## What is the motivation / use case for changing the behavior?

Since the parent component is the same, its state should be persisted between child route change or behavior will be inconsistent.

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [X] Chrome (desktop) version 59
 

</code></pre>

**Comment by kvanberendonck** [comment]
I am also experiencing this bug.

I am using `RouterModule.forChild` with feature routing modules are recommended to be the "bleeding edge best practice" for feature modules, but all the feature modules aren't actually reusing their components between routes .

I put a `console.log('here')` in each of my `ngOnInit` and it is being called every route change in every component and they don't take route params, which sounds like OPs issue.

**Comment by buctwbzs** [comment]
It is the children attribute that determines the routing hierarchy，not forchild().In your code,all  routes are first level.shell is not parent of other.

**Comment by sinedied** [comment]
@alxhub Any news on this?

I am currently using a custom `RouteReuseStrategy` as a workaround, but that still feel... workaround-ish.

The use case seems basic, as I have an authenticated app with 2 possibilities here:
- user not authenticated => display a login page
- user is authenticated => show the app, where all screens are child of a `Shell` component (containing the header/side menu navigation)

Every app screen is a separate feature module, declaring their custom routes so they are completely decoupled from the `Shell` feature module, and here lies the root issue. Seems like current router behavior is against best practices promoted by the Angular Style Guide or did I missed something? (Feel free to correct me if I'm wrong)

**Comment by jasonaden** [comment]
@sinedied Thanks for the issue. Can you produce a smaller reproduction? I understand it's broken in this project, but it will help to see a small use case. Something like a single parent component with two children, and no other helpers/services involved.

You can use [StackBlitz](https://stackblitz.com) to produce the repro.

**Comment by sinedied** [comment]
@jasonaden I'll put up a minimal stackblitz when I find some time, this is easy to reproduce

**Comment by sinedied** [comment]
@jasonaden Here is a minimal stackblitz for the issue: https://stackblitz.com/edit/angular-router-noreuse?file=app%2Fparent.component.ts

- 2 child components or a parent component, in separate feature modules
- when navigating from 1 child to another you can see that the parent component is recreated as its instance ID changes

**Comment by ahmed-anas** [comment]
@sinedied can you share the `RouteReuseStrategy` you used to fix this issue?

**Comment by sinedied** [comment]
@ahmed-anas you can find it hereL https://github.com/ngx-rocket/starter-kit/blob/master/src/app/core/route-reusable-strategy.ts

**Comment by dangngoctau** [comment]
@ahmed-anas You don't need a work around anymore. This issue is resolved you can check it out at: [https://github.com/angular/angular/blob/9141424ac69f8ff9702485e7f00e58fa503d8c42/packages/router/src/route_reuse_strategy.ts#L65](https://github.com/angular/angular/blob/9141424ac69f8ff9702485e7f00e58fa503d8c42/packages/router/src/route_reuse_strategy.ts#L65)

**Comment by jcphlux** [comment]
@sinedied You saved me with your route-reusable-strategy.ts. Once I looked over your repo for a few min it was easy to get working on my site. 
Thanks!!

**Comment by pvelez-bp3** [comment]
is there any update to this issue to be fixed in the core of Angular?

**Comment by pablovelezvidal** [comment]
is there any update to have this issue fixed in the Angular core?

**Comment by kherP** [comment]
Actually I think it depends on how you defined your route. [Here](https://stackblitz.com/edit/angular-router-noreuse-9vgzwu)'s how I defined the routes to resolve the issue without needing to define a custom routeReuseStrategy.

**Comment by sinedied** [comment]
@kherP I think you missed the point here: it works on simple cases where on define all you children in the same routing module, but in big apps you want to split your app into features modules, with different routing modules (as in style guide) which does not work then.

**Comment by mmubasher** [comment]
Experiencing the same issue in Angular 6.0.8

**Comment by ruiqi** [comment]
Any news on this?

**Comment by dpinheiro** [comment]
Any update? Still having the same issue on 8.2.7

**Comment by elie29** [comment]
@sinedied I checked your [stackblitz](https://stackblitz.com/edit/angular-router-noreuse) and the problem is not related to lazy/eager modules. You linked Child1Module and Child2Module to a same empty path:

![image](https://user-images.githubusercontent.com/11255270/66699890-1c6ebd80-eceb-11e9-8f03-439b0bc62495.png)

I forked your app and made two corrections by using one empty path access to the parent as follow: 
[correction1](https://stackblitz.com/edit/angular-router-noreuse-correction) and [correction2](https://stackblitz.com/edit/angular-router-noreuse-correction2):

![image](https://user-images.githubusercontent.com/11255270/66700083-0b26b080-eced-11e9-9dac-ca25672c728b.png)

Parent ID in both solution does not change anymore. Hope it helps 😄

**Comment by sinedied** [comment]
@elie29 sorry but this is not helping. The whole point is that we should be able to declare routes it's separate feature modules, but reusing the same parent component. Having all the child routes declared in the parent component works for small apps, but it's not scalable for big apps.

**Comment by pravinchandankhede** [comment]
I am facing this issue even with 9.1.3, why its not being fixed so long?

**Comment by kzay** [comment]
Same here

**Comment by Ignaciojeria** [comment]
I have the same bug

**Comment by atscott** [comment]
Confirmed in v9 with Ivy as well: https://stackblitz.com/edit/angular-router-noreuse?file=app%2Fparent.component.ts

**Comment by ishener** [comment]
+1

**Comment by piskula** [comment]
still no progress on this?

**Comment by jimbarrett33** [comment]
I think this should be much higher than a P4 or it will never get fixed. Ultimately, it is a performance issue and not just an inconvenience. There are several related issues that date back as far as 2016 where devs are requesting the ability to configure the router to not destroy (parent) components. All require workarounds with custom `RouteReuseStrategy`'s that don't completely work for routes with child routes, especially if lazy loaded from a different module.

Although Angular's DOM binding is fast etc etc etc, for complex screens like dashboards, re-initializing the dashboard component after navigating away to see some detail view is really inefficient (crazy?) in most cases.

Related issues (there may be more):
https://github.com/angular/angular/issues/5275
https://github.com/angular/angular/issues/6634
https://github.com/angular/angular/issues/13869

**Comment by atscott** [comment]
After further review, this is working as intended. The two modules are not sharing a parent route config but are instead defined as separate objects so the component is not reused. This is because default route reuse strategy only reuses the route when the configs are equal. A custom `RouteReuseStrategy` is the correct approach to accomplish the desired goal here: https://stackblitz.com/edit/angular-ivy-ksf9cm?file=src%2Fapp%2Fapp.module.ts. The default strategy is intended to be simple. Custom strategies should be implemented on a per-project basis in response to project requirements. 

For an alternative approach, please refer to this comment https://github.com/angular/angular/issues/18374#issuecomment-541312422 for the correct approach.

> @elie29 sorry but this is not helping. The whole point is that we should be able to declare routes it's separate feature modules, but reusing the same parent component. Having all the child routes declared in the parent component works for small apps, but it's not scalable for big apps.

I think this really depends on the project. In most cases, the only route you have to define is the single route to the child feature module.  The difference in the number of properties you define in the router config between the not working and working approach is 1. Additionally, the second approach benefits from lazy loading feature modules while the first does not:
```
const ROUTES: Routes = [];
const child1Routes: Routes = [{
  path: '',
  component: ParentComponent,
  children: [{
    path: 'child1',
    component: Child1Component
  }]
}]
const child2Routes: Routes = [{
  path: '',
  component: ParentComponent,
  children: [{
    path: 'child2',
    component: Child2Component
  }]
}]
// versus:
const child1Routes: Routes = [
  {
    path: "",
    component: Child1Component
  }
];
const child2Routes: Routes = [
  {
    path: "",
    component: Child2Component
  }
];
const ROUTES: Routes = [{
    path: "",
    component: ParentComponent,
    children: [{
        path: "child1",
        loadChildren: "./child1/child1.module#Child1Module"
      },
      {
        path: "child2",
        loadChildren: "./child2/child2.module#Child2Module"
      }]
  }]
```

**Comment by sinedied** [comment]
Thanks for coming back to this @atscott .
While I can understand the desire for simplicity in the default implementation, unfortunately this leads to obscure and non-intuitive developer experience as a result. Comparing the route objects makes no sense here, whereas doing the same comparison (ie object ref) on the *component* instead of the whole *route* is what we would expect to determine is the component should be reused or not. And it would work for case 1 & 2.

Moreover, if it was only a matter of implementing a custom `RouteReuseStrategy` (which I did) I would be fine, however it leads to more non-trivial issues with lazy loading, routing animations and more.

Finally what I have a hard time understanding is that the default implementation here and suggestion with approach 2 contradicts what's advertised as best practices everywhere else. When implementing the [App Shell](https://angular.io/guide/app-shell) pattern, that means that all your app routes should be declared at the same place, which is not really scalable for large projects and definitely not practical when multiple teams works on the same app. This defeats completely the whole purpose of being able to declare routes in features modules to me.
The only alternative approach I can think of to implement the App Shell pattern and not having this routing issue is not using routing at all and use the Shell component in all the page templates, but with this you cannot use Angular universal to pre-render the App Shell, again defeating its purpose.

Do you have any guidance on how we should implement the App Shell pattern while not having all your routes declared at the same place, and keeping the ability to mix & match lazy loaded and eager modules? Approach 2 in this example works only if you lazy load all your child modules, which is most of the time not what's desired or even best performance-wise.

**Comment by atscott** [comment]
> While I can understand the desire for simplicity in the default implementation, unfortunately this leads to obscure and non-intuitive developer experience as a result. 
This would be the same case if we unilaterally changed the default to compare against the component. There are plenty of applications which use the same component in different routes.

> Comparing the route objects makes no sense here, whereas doing the same comparison (ie object ref) on the _component_ instead of the whole _route_ is what we would expect to determine is the component should be reused or not. And it would work for case 1 & 2.

This is why a custom `RouteReuseStrategy` is the solution here. That's exactly what is done in the [example above](https://stackblitz.com/edit/angular-ivy-ksf9cm?file=src%2Fapp%2Fapp.module.ts).

> Moreover, if it was only a matter of implementing a custom `RouteReuseStrategy` (which I did) I would be fine, however it leads to more non-trivial issues with lazy loading, routing animations and more.

Please provide a reproduction for this.

> Finally what I have a hard time understanding is that the default implementation here and suggestion with approach 2 contradicts what's advertised as best practices everywhere else. When implementing the [App Shell](https://angular.io/guide/app-shell) pattern, that means that all your app routes should be declared at the same place, which is not really scalable for large projects and definitely not practical when multiple teams works on the same app. This defeats completely the whole purpose of being able to declare routes in features modules to me.

It's not clear to me why you believe this to be the case. You _can_ define routes in the feature modules. You only need __one__ route in the root for the feature module itself. Arguably, doing it another way is not scalable because you allow developers on different teams to create routes which conflict with each other. 

> The only alternative approach I can think of to implement the App Shell pattern and not having this routing issue is not using routing at all and use the Shell component in all the page templates, but with this you cannot use Angular universal to pre-render the App Shell, again defeating its purpose.
> 
> Do you have any guidance on how we should implement the App Shell pattern while not having all your routes declared at the same place, and keeping the ability to mix & match lazy loaded and eager modules? Approach 2 in this example works only if you lazy load all your child modules, which is most of the time not what's desired or even best performance-wise.

* Option 0: Use a custom `RouteReuseStrategy`. Without a reproduction to the issues you mentioned, I can't tell why that doesn't work.
* Option 1: Is there a reason you can't put the `route-outlet` in the app-shell component? This kind of seems like what you want here if all the child routes are going to share the same parent as would be the case in the "app shell pattern": https://stackblitz.com/edit/angular-router-noreuse-bwrt26?file=app%2Fapp.component.html
* Option 2: Use `router.resetConfig` in the feature modules to modify the existing config https://stackblitz.com/edit/angular-ivy-texrnp?file=src%2Fapp%2Fchild2%2Fchild2-routing.module.ts. A couple caveats:
  *  This option is only going to work for non-lazy loaded feature modules. Otherwise, the route won't be available on initial load so you wouldn't be able to navigate directly to it. 
  * This option only works with Ivy enabled.
  * This seems kind of scary, but so is allowing `forChild` feature modules to define root routes, imo.
* Option 3: Define all your routes in the root for these cases. Sort the routes by name to avoid merge conflicts. (I didn't say all the options were good... 😄 )
