### ISSUE TITLE
"Too much recursion" with lazy loading route on FF 44/45 maybe others but not 36

### ISSUE THREAD

**Issue by Spanja** [angular/angular#18811]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I get a blank page with a lazy loading module declaration on older firefox version.
Strangely, the error occurs on (at least) FF 44.0 & 45.0 but not on FF 36.0 for example.

Here is the stack trace on FF 45.0 :

```
ERROR Error: Uncaught (in promise): InternalError: too much recursion
.get@https://unpkg.com/@angular/router/bundles/router.umd.js:2402:35
parentLoadedConfig@https://unpkg.com/@angular/router/bundles/router.umd.js:4790:31
ActivateRoutes.prototype.activateRoutes@https://unpkg.com/@angular/router/bundles/router.umd.js:4757:51
ActivateRoutes.prototype.activateChildRoutes/<@https://unpkg.com/@angular/router/bundles/router.umd.js:4715:52
ActivateRoutes.prototype.activateChildRoutes@https://unpkg.com/@angular/router/bundles/router.umd.js:4715:9
ActivateRoutes.prototype.activate@https://unpkg.com/@angular/router/bundles/router.umd.js:4608:9
Router.prototype.runNavigate/</<@https://unpkg.com/@angular/router/bundles/router.umd.js:4184:1
Observable.prototype.forEach/</subscription<@https://unpkg.com/rxjs/Observable.js:224:21
SafeSubscriber.prototype.__tryOrSetError@https://unpkg.com/rxjs/Subscriber.js:247:13
SafeSubscriber.prototype.next@https://unpkg.com/rxjs/Subscriber.js:187:22
Subscriber.prototype._next@…
Trace de la pile :
resolvePromise@https://unpkg.com/zone.js/dist/zone.js:783:31
resolvePromise@https://unpkg.com/zone.js/dist/zone.js:754:17
scheduleResolveOrReject/<@https://unpkg.com/zone.js/dist/zone.js:831:17
ZoneDelegate.prototype.invokeTask@https://unpkg.com/zone.js/dist/zone.js:424:17
forkInnerZoneWithAngularBehavior/zone._inner<.onInvokeTask@https://unpkg.com/@angular/core/bundles/core.umd.js:3913:24
ZoneDelegate.prototype.invokeTask@https://unpkg.com/zone.js/dist/zone.js:423:17
Zone.prototype.runTask@https://unpkg.com/zone.js/dist/zone.js:191:28
drainMicroTaskQueue@https://unpkg.com/zone.js/dist/zone.js:595:25
ZoneTask.invokeTask@https://unpkg.com/zone.js/dist/zone.js:502:21
patchEventTarget/invokeTask@https://unpkg.com/zone.js/dist/zone.js:1370:1
patchEventTarget/globalZoneAwareCallback@https://unpkg.com/zone.js/dist/zone.js:1388:17
```

## Expected behavior
The page should load correctly

## Minimal reproduction of the problem with instructions
Here is a stackblitz : https://stackblitz.com/edit/angular-zgcqhp?file=app%2Fapp.module.ts

## What is the motivation / use case for changing the behavior?
Being able to display app with older browsers.

## Environment

<pre><code>
Angular version: 4.4.6

Browser:
- [ x ] Firefox version 45 x86
 
For Tooling issues:
- Node version: 8.4.0
- Platform:  Windows
</code></pre>

**Comment by FrankiePo** [comment]
There is the same closed issue with a bit more information.
https://github.com/angular/angular/issues/18344

I stumbled over same recursion on Firefox 45 under Windows 10.

**Comment by Spanja** [comment]
I updated the stackblitz with ng 4.4.6

**Comment by FrankiePo** [comment]
Actually, I found that this error appear on FF when route path is empty: `{path: '', component: AppComponent}`

**Comment by jasonaden** [comment]
Closing as this has been resolved.

**Comment by Spanja** [comment]
It seems not.

I updated stackblitz with 5.1.0 and I still get this error in FF45 console with blank page :

```
ERROR Error: Uncaught (in promise): InternalError: too much recursion
listenToElementOutputs@https://unpkg.com/@angular/core@5.1.0/bundles/core.umd.js:10644:61
createViewNodes@https://unpkg.com/@angular/core@5.1.0/bundles/core.umd.js:13783:17
callViewAction@https://unpkg.com/@angular/core@5.1.0/bundles/core.umd.js:14250:13
execComponentViewsAction@https://unpkg.com/@angular/core@5.1.0/bundles/core.umd.js:14159:13
createViewNodes@https://unpkg.com/@angular/core@5.1.0/bundles/core.umd.js:13844:5
createRootView@https://unpkg.com/@angular/core@5.1.0/bundles/core.umd.js:13705:5
callWithDebugContext@https://unpkg.com/@angular/core@5.1.0/bundles/core.umd.js:15130:39
debugCreateRootView@https://unpkg.com/@angular/core@5.1.0/bundles/core.umd.js:14413:12
ComponentFactory_.prototype.create@https://unpkg.com/@angular/core@5.1.0/bundles/core.umd.js:11304:37
ComponentFactoryBoundToModule.prototype.create@https://unpkg.com/@angular/core@5.1.0/bundles/core.umd.js:4073:16
ViewContainerRef_.prototype.createComponent…
Trace de la pile :
resolvePromise@https://unpkg.com/zone.js@0.8.18/dist/zone.js:824:31
resolvePromise@https://unpkg.com/zone.js@0.8.18/dist/zone.js:795:17
scheduleResolveOrReject/<@https://unpkg.com/zone.js@0.8.18/dist/zone.js:873:17
ZoneDelegate.prototype.invokeTask@https://unpkg.com/zone.js@0.8.18/dist/zone.js:425:17
forkInnerZoneWithAngularBehavior/zone._inner<.onInvokeTask@https://unpkg.com/@angular/core@5.1.0/bundles/core.umd.js:4786:24
ZoneDelegate.prototype.invokeTask@https://unpkg.com/zone.js@0.8.18/dist/zone.js:424:17
Zone.prototype.runTask@https://unpkg.com/zone.js@0.8.18/dist/zone.js:192:28
drainMicroTaskQueue@https://unpkg.com/zone.js@0.8.18/dist/zone.js:602:25
[607]/E/</<@https://a.staticblitz.com/assets/packs/common-27b7dadcc6632177d375.js:1:35475
[607]/E/<@https://a.staticblitz.com/assets/packs/common-27b7dadcc6632177d375.js:1:35345
[563]/t.exports/a@https://a.staticblitz.com/assets/packs/common-27b7dadcc6632177d375.js:1:26331
```

**Comment by MariamCast** [comment]
The problem has any solution?
Now I have the same problem when routing in angular.
