### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError - HostBinding and Animations `.done`

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#18917]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I am using `HostBinding` and Animation `.done` and I update an property that is being using in HostBinding I am getting `ExpressionChangedAfterItHasBeenCheckedError` when the value is changed too quickly, even though I am using `markForCheck`.

```ts
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'true'.
    at viewDebugError (errors.ts:30)
    at expressionChangedAfterItHasBeenCheckedError (errors.ts:29)
    at checkBindingNoChanges (util.ts:145)
    at checkNoChangesNodeInline (view.ts:477)
    at checkNoChangesNode (view.ts:568)
    at debugCheckNoChangesNode (services.ts:557)
    at debugCheckRenderNodeFn (services.ts:500)
    at Object.eval [as updateRenderer] (AppComponent_Host.html:1)
    at Object.debugUpdateRenderer [as updateRenderer] (services.ts:477)
    at checkNoChangesView (view.ts:383)
```

## Expected behavior
No error

## Minimal reproduction of the problem with instructions
Below please find a simple reproduction;
https://stackblitz.com/edit/expressionchangedafterithasbeencheckederror-hostbinding

To get the error, simply click the `button` quickly several times.

## What is the motivation / use case for changing the behavior?
I believe that this shouldn't be happening, I don't have bidirectional data flow which might cause such issues, And I am explicitly saying that there are changes, as I am using `markForCheck`.

## Environment
Angular 4.3.4

**Comment by alan-agius4** [comment]
Any feedback?

**Comment by b-mi** [comment]
Same problem

**Comment by matsko** [comment]
OK I see the issue here, looking into it.

**Comment by exequiel09** [comment]
I see the same issue on Angular 5.x (5.0.0)

**Comment by AdJesumPerMariam** [comment]
Still an issue on Angular 6.1
https://stackblitz.com/edit/expressionchangedafterithasbeencheckederror-hostbinding-hxphbt

**Comment by simeyla** [comment]
This isn't even just for animations (albeit harder to workaround for animations), and can occur when a parent component sets a property on a child that then updates a @HostBinding property. 

https://stackoverflow.com/questions/43375532/expressionchangedafterithasbeencheckederror-explained/51662105#51662105

**Comment by AlexAegis** [comment]
Still an issue in 7.2

```typescript
	@HostBinding('style.width') get widthCalc(): string {
		return `calc(100% - ${this.width}px)`;
	}
```

**Comment by DionatanGG** [comment]
Still an issue on 12.1.3

```
  @HostBinding('class.has-scroll') public get hasRemainingScroll(): boolean {
    const { scrollWidth, clientWidth, scrollLeft } = this.elementRef.nativeElement.querySelector('.ed-table-body');
    return scrollLeft + clientWidth < scrollWidth;
  }
```

**Comment by reduckted** [comment]
Still an issue on Angular 17. Has anyone found a workaround?

```
Angular: 17.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.0
@angular-devkit/build-angular   17.1.0
@angular-devkit/core            17.1.0
@angular-devkit/schematics      17.1.0
@schematics/angular             17.1.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by atscott** [comment]
Closing as working as expected. This _is_ `ExpressionChangedAfterItHasBeenCheckedError` when updating the value of host bindings after they have been checked. 

The way to fix this would be to use a `signal` for the host binding instead or to update the value outside of the current round of change detection (i.e. `Promise.resolve().then(() => doUpdate())`).

**Comment by reduckted** [comment]
> The way to fix this would be to use a `signal` for the host binding instead

Unfortunately that doesn't work (or I'm doing it wrong). It still produces the `ExpressionChangedAfterItHasBeenCheckedError`.

I can put together a reproduction if you're interested in investigating it.

**Comment by b-mi** [comment]
> > The way to fix this would be to use a `signal` for the host binding instead
> 
> Unfortunately that doesn't work (or I'm doing it wrong). It still produces the `ExpressionChangedAfterItHasBeenCheckedError`.
> 
> I can put together a reproduction if you're interested in investigating it.

Maybe help use setTimeout for code where the error occurs....

**Comment by atscott** [comment]
@reduckted a reproduction would be helpful. I have a suspicion about the cause but would like to verify.

**Comment by reduckted** [comment]
Here's a reproduction: https://github.com/reduckted/repro-angular-18917

It demonstrates six different techniques:
* `@HostBinding` with a `boolean` property. ❌
* `@HostBinding` with a `Signal<boolean>` property. ❌
* `{ host }` metadata with a `boolean` property. ❌
* `{ host }` metadata with a `Signal<boolean>` property. ❌
* Using `Promise.resolve()` to set the host binding property ✔
* Using `setTimeout` to set the host binding property ✔

Here's a summary of what it does:
* The component has two animation stations - "on" and "off".
* When the state is "on", the background color is `red`, and when the state is "off", the background color is `cornflowerblue`.
* The transition between the states is 3 seconds.
* When the animation from "off" to "on" completes, the height of the component is reduced via a host binding. When the animation from "on" to "off" starts, the height of the component is restored via a host binding. In other words, the height is only reduced when the background color is exactly `red`.
* Clicking the button will toggle the state. While the animation from "off" to "on" is in progress, toggling the state will throw an `ExpressionChangedAfterItHasBeenCheckedError`.
* While the animation from "on" to "off" is in progress, toggling the state will _not_ throw an error. 🤔 

Possibly related to the issue with signals: #53888

**Comment by b-mi** [comment]
Your (very nice) reproduction does not show me any error (in console) during any changing state through Toggle button. Node.js version 18.19.0.

**Comment by reduckted** [comment]
Hmm, that's interesting. Are you running in development mode (`ng serve` or `npm start`)? This is what I see:

![18917](https://github.com/angular/angular/assets/10321525/d8964bcf-b37b-4c78-b268-f00e4a11f96d)

**Comment by b-mi** [comment]
Ok, to trigger the problem is needed to click on the button during the animation. But the last two methods work without the mentioned error, so they are not the solution?

**Comment by atscott** [comment]
@reduckted thanks for the reproduction. I have confirmed that _all scenarios_ in your example work at head on the 17.1.x and main branches. This would have been fixed by https://github.com/angular/angular/commit/432afd1ef41e0bfd905e71e8b15ec7c9ab337352 and will be included in this week's release.

**Comment by reduckted** [comment]
> @atscott I have confirmed that all scenarios in your example work at head on the 17.1.x and main branches.

I've updated to 17.1.3, and I've also tried 17.2.0-rc.1. I'm still seeing errors for the non-`Signal` cases.

* `@HostBinding` with a `boolean` property. ❌
* `@HostBinding` with a `Signal<boolean>` property. ✔
* `{ host }` metadata with a `boolean` property. ❌
* `{ host }` metadata with a `Signal<boolean>` property. ✔
* Using `Promise.resolve()` to set the host binding property ✔
* Using `setTimeout` to set the host binding property ✔

![18917-17 1 3](https://github.com/angular/angular/assets/10321525/480a8fbc-fc23-4ec4-9633-cabee8f745a6)

Personally, the fact that I can now use a `@HostBinding` backed by a `Signal` without needing to use `Promise.resolve()` or `setTimeout` to change the value is good enough for me, so if using a plain old `boolean` property never works, then it's not a big deal. Others may have other opinions though. 😄
