### ISSUE TITLE
BrowserAnimationsModule prevents Angular to recover from an error

### ISSUE THREAD

**Issue by KrisztianNagy** [angular/angular#19093]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
 A component throws a runtime error when the model and the template are not compatible. For example: <div>{{foo[barr]}}</div> and the foo is undefined. This is handled by Angular and it doesn't break the application.
Unfortunately, this is not the case when the BrowserAnimationsModule is provided. Angular is not able to remove old html elements anymore. The router-outlet keeps the old pages and the stack grows as I navigate. The same is true for *ngIf. 

## Expected behavior
Providing the BrowserAnimationsModule shouldn't have this effect.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/u2JTEbzQeI41uGLPeyuv?p=preview

Removing BrowserAnimationsModule will make this work.

## What is the motivation / use case for changing the behavior?
This bug makes the dynamic component creation almost impossible. The compileModuleAndAllComponentsAsync only throws compile errors. The only way to validate the model against the templates if I handle the runtime errors. But this bug doesn't allow us to have runtime errors.

## Environment

<pre><code>
Angular version: 4.3.6 and 4.4.0-RC.0

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 3.10.10
- Platform:  Windows 

Others:
</code></pre>

**Comment by ramadurgarao** [comment]
Can you plz provide me any workaround for this issue.

**Comment by Agrumas** [comment]
This issue causes a lot of trouble if there is a small error, content gets duplicated and application becomes more or less unusable. The fix is highly anticipated for this one.

**Comment by leetharris** [comment]
Is this seriously labeled "inconvenient?"

ROUTING IS BROKEN WHEN YOU USE THIS MODULE AT ALL. Our entire application can't use this version of Angular (causing an enormous amount of headaches). I'd say it goes far beyond "inconvenient."

Insane that this was reported weeks ago and we still don't have a hotfix.

**Comment by sean1504** [comment]
I thought the same when I read that classification.  All I can think is that animation is considered non-essential.

**Comment by didii** [comment]
I have a variation on this bug. For me everything is fine when navigating, but components get stacked on top of each other when angular rebuilds when it detects changes. When I add for example a `console.log('blah')` anywhere, the module rebuilds and then stacks another `<app>` component on top of the already existing one. Below is a screenshot of the elements after rebuilding a couple of times.

This is an ASP.NET with angular project and I tested it with the following browsers and all have the same problem.
* Chrome
* Firefox
* Edge
* IE

Just as above: only including either BrowserAnimationsModule or NoopAnimationsModule is enough to trigger this bug.

![image](https://user-images.githubusercontent.com/2774842/31119300-c17aaa48-a830-11e7-9025-55f504c39714.png)

**Comment by shruti1006** [comment]
Any solution or workaround?

**Comment by bmercier-manakin** [comment]
Any news from Angular team ? This is marked as broken but still open since early september. Some people using AngularMaterial for instance can't get rid of BrowserAnimationsModule

**Comment by isylhdin** [comment]
I'm also facing the same problem. Any news ?

**Comment by aamirkhan-91** [comment]
How is this still Open after more than 2 months of being reported? This is **breaking** change!

**Comment by mhevery** [comment]
> How is this still Open after more than 2 months of being reported? This is a breaking change!

this is not a tone of voice which is constructive. Yes I understand you are frustrated, but this is not the way to get action out of people. Perhaps you could help by getting to the root cause, and submitting a PR.

**Comment by IAMtheIAM** [comment]
@aamirkhan-91 I'm sure they are planning to work on it,. They have a lot of issues open to deal with, give them some time.

**Comment by IAMtheIAM** [comment]
I think people forget that this is FREE software we get to use, thanks to the people working on Angular. We should be grateful that they are fixing these bugs at NO cost to us, and allowing us to use this software commercially or in any way we please. Rather than acting like children and demanding fixes immediately.

**Comment by wahd6** [comment]
I am getting the same issue.! **Does anyone found the solution for it...??????????**                                     For me it is happening but from the external link (Gmail) it is happening I have raised the question in StackOverflow:  [Stackoverflow question](https://stackoverflow.com/questions/48001792/angular-router-appends-component-data-instead-of-replacing-the-component)

**Comment by bmercier-manakin** [comment]
@wahd6 As you can see, question has been resolved, try update your Angular to the latest version, I've seen this has been merged since version 5.1.0

**Comment by imilyutkin** [comment]
Hi, Guys. It's strange but I still have this issue. I've updated till 5.1.1 And this issue reproduced on empty application with 2 component, which render simple html. Also I got version 5.2.0 and it also reproduce. Maybe I did smth wrong?

**Comment by solael** [comment]
Upgraded to 5.2.0, still not fixed.

**Comment by imilyutkin** [comment]
@solael Hey. DId you test in google chrome? Maybe some extensions block this behaviour, alos you can check it in other browsers. For me this problem not reproduce

**Comment by vinnu-313** [comment]
Not working for me on 5.2.1.

**Comment by trotyl** [comment]
It's possible for different problems (causes) behaving the same, in that case one should open a new issue linking to the original one (with new reproduction).

**Comment by jainvishal520** [comment]
Is this issue fixed?
Please somebody provide the solution.

**Comment by matsko** [comment]
Hello everyone. The issue with the plnkr has been resolved, but it still sounds like some of you are experiencing the issue. If this is the case, please provide a working reproduction of this in stackblitz so that I can investigate. Otherwise there's nothing that can be done right now.

**Comment by ReverendDG** [comment]
I'm having the same issue in Angular2. I need BrowserAnimationsModule for Toastr to work, but I'm having the same issue, where an error doesn't allow the previous content to be destroyed when navigating elsewhere. The issue goes away when I leave out the module, but then I get an error from Toastr since it needs it.

**Comment by selipso** [comment]
@BryanSummers14 Updating to one of the later point releases of v6 seems to fix this issue

**Comment by alfonsoaranzazu** [comment]
@selipso what version of angular 6 are you using, can you post your enivornment info?

**Comment by selipso** [comment]
@alfonsoaranzazu Here's the same stackblitz as above with the updated version numbers: https://stackblitz.com/edit/angular-jw3gtz

**Comment by antontemchenko** [comment]
I am facing exact same issue with Angular 8.2.0
Does anyone still have same problem?

**Comment by thegeett** [comment]
I am having same issue, I am using Angular 8.1.3. Please take a look my stackblitz. I am able to reproduce there. I am not using BrowserAnimationsModule.
https://stackblitz.com/edit/angular-a8lmjs
