### ISSUE TITLE
(bug): httpClient is automatically parsing error responses to string since 4.4.0-RC.0

### ISSUE THREAD

**Issue by rafaelss95** [angular/angular#19103]
## I'm submitting a...

<pre><code>
[ X ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When a post (I've only tested this _method_) request returns an error, like this:

```
{
  "base": [{
    "error": "something invalid"
  }]
}
```

... the `error` is parsed to string even the server returns a valid `JSON` as above.

## Expected behavior
The error response shouldn't be parsed to `string`.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/IjmDdiM0BwFJlpk1JLkR?p=info

Just click "Send post" and take a look in the console (specifically in error... it's parsed to string).

## Environment
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.0
node: 8.1.1
os: linux x64
@angular/animations: 4.4.0-RC.0
@angular/cdk: 2.0.0-beta.10
@angular/common: 4.4.0-RC.0
@angular/compiler: 4.4.0-RC.0
@angular/core: 4.4.0-RC.0
@angular/forms: 4.4.0-RC.0
@angular/http: 4.4.0-RC.0
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.4.0-RC.0
@angular/platform-browser-dynamic: 4.4.0-RC.0
@angular/platform-server: 4.4.0-RC.0
@angular/router: 4.4.0-RC.0
@angular/cli: 1.4.0
@angular/compiler-cli: 4.4.0-RC.0
@angular/language-service: 4.4.0-RC.0
typescript: 2.5.2
```

Others:
It was working on 4.3.6 [as you can see here](http://plnkr.co/edit/em9mQfgPsWW2mLQiElng).

**Comment by rafaelss95** [comment]
Cc @alxhub

**Comment by Toxicable** [comment]
Looks like a bug to me, likely due to https://github.com/angular/angular/commit/452a7ae88b3b1144369f884c10de044502dc3c65
Since we're now handling all the JSON parsing but we aren't parsing the response in either position
https://github.com/angular/angular/blob/master/packages/common/http/src/xhr.ts#L210
or 
https://github.com/angular/angular/blob/master/packages/common/http/src/xhr.ts#L225
where those would have been parsed by the browser previously

**Comment by rafaelss95** [comment]
@alxhub can you check this and maybe apply labels here? Thanks.

**Comment by spock123** [comment]
This is also present in the 5.0.0-betas.. I just found this issue after 2 days of bugfixing my application :)

**Comment by Spanja** [comment]
Same issue with 4.4.3

**Comment by schmitch** [comment]
Issue is still  broken in 4.4.4

**Comment by Agadar** [comment]
Unfortunately, @schmitch 's solution does not work in Angular 4.3.5. `response.error` is already undefined when it reaches the interceptor.

**Comment by ernitishkumar** [comment]
I am also facing the same issue even with GET request which fails with error. 
Only the body of Error response is parsed to Json not the successful requests.
It was working fine till the version 4.3.6. All Error Handling code went haywire after updating my project to Angular version 4.4.3 !

Don't want to apply patch, I hope Team Angular will fix this in coming builds. Till the downgrading to working 4.3.6

**Comment by Linskeyd** [comment]
@dherges you may want to update this comment as it seems to still assume that only 'ok' results are being processed: https://github.com/angular/angular/pull/19477/files#diff-26683cfb34fa97883213282055aef1e7R189

Additionally, you may want to add a test which explicitly checks for XSSI prefix support in the error response: https://gist.github.com/Linskeyd/df32564d539862350e927721ffad86df

**Comment by rafaelss95** [comment]
Fixed in 4.4.6 (pull #19773).

**Comment by sebek64** [comment]
Well, I still see the bug in 4.4.6 - typeof err.error is string, but subsequent JSON.parse(err.error) succeeds.

**Comment by sebek64** [comment]
Ok, so I discovered what's wrong. I had to add 'responseType: text' due to https://github.com/angular/angular/issues/19555. Without responseType, the error is parsed correctly. So this bug is fixed, but is it still impossible to have error json parsed automatically, and have empty response parsed as null.

**Comment by b0rgbart3** [comment]
I'm using Angular 5.0.0 - but also having this error

**Comment by malkoto1** [comment]
WTF... I am with 5.1.0 and this is still present... Why is this bug closed...?

**Comment by ranouf** [comment]
Version 6.4.2, still have the issue. When do you plan to fix it?

**Comment by xMarkusSpringerx** [comment]
I'm also waiting for this to be resolved.

**Comment by sandraisrael** [comment]
Please how was this error resolved

**Comment by danday74** [comment]
I THOUGHT I had this issue.

In the end, however, it was caused by someone doing something horrible inside our HTTP interceptor.

instead of:

import { throw } from 'rxjs/observable/throw'

return throw(error) // inside interceptor

they were doing:

return throw(error.message) // inside interceptor

Why? why? why?
