### ISSUE TITLE
Angular Router does not destroy component if an error was thrown

### ISSUE THREAD

**Issue by IAMtheIAM** [angular/angular#19273]
## I'm submitting a...

```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

## Current behavior

 If component 1 throws an error, and then a user navigates to component 2, the error in component 1 will prevent component 1 from being destroyed by the router.

## Expected behavior

Components should be destroyed by the angular router whether they throw an error or not.

## Minimal reproduction of the problem with instructions

[Link to Reproduce here](http://atlas-dashboard-dev.azurewebsites.net/)

1. Notice error on Developer console on `Login` Component
2. Click login button using `diagnosebug` for the username and no password. 
2. Scroll down page. 
3. See that `Login` component is still visible beneath `Dashboard` component
4. Click Logout button.
5. Scroll up and notice another duplicate copy of `Login` component, and `Dashboard` component still visible.
6. Can be repeated to infinite resulting in more duplicate components never being destroyed.

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [x ] Chrome (desktop) version 63
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by IAMtheIAM** [comment]
Anybody there?

**Comment by victorguimaraessilva** [comment]
i'm having this issue too

**Comment by upmauro** [comment]
same problem here

**Comment by IAMtheIAM** [comment]
23 days goes by, can anyone from angular take a look at this? Or give an estimate of when they could?

**Comment by Eikc** [comment]
I am also seeing this issue, i have tried to create a reproducable stackblitz but i havent been able to recreate the issue..

So if any of you can recreate the bug in a very very simple app then i'm sure it will be helpful for the angular team :)

**Comment by sunnyvilles** [comment]
Same problem here
I am using BrowserAnimations module in my project .
These links might help identifying more about problem . 

https://stackoverflow.com/questions/45622453/angular2-router-appends-component-instead-of-replacing-it?rq=1

https://stackoverflow.com/questions/45762690/angular-4-router-is-appending-components-on-routerlink-navigation-instead-of-des

**Comment by DedSec49** [comment]
Same problem here!

**Comment by victorguimaraessilva** [comment]
Some problem here tooooo =)

**Comment by rk-7** [comment]
I'm having the same problem here! :(
Any workarounds?

**Comment by Eikc** [comment]
Hmm, i still haven't been able to reproduce the bug in a very simple stackblitz, but i'm still trying to figure out whats going on when it happens... 

I use angular-cli, and when i build in --prod mode, this issue doesn't happen.. not that i think its related, but it might be a possible workaround. 

I hope i can give it another shot this weekend :)

**Comment by jnsn** [comment]
I had a similar issue in my app, and removing the `BrowserAnimationModule` from the `app.modules.ts` file fixed the problem, as mentioned before.

It turned out the issue was because the second component was throwing an error. When we resolved the error in the second component the appended routing issue was resolved.

**Comment by bmercier-manakin** [comment]
I also have same error but can't get rid of BrowserAnimationModule (cause whole app is based on angular material components... ).
I really think this happen only when there is an error thrown by Angular due to a DOM problem (something wrong in {{ }} templating or in a custom directive). I couldn't reproduce it in another case.

I really hope Angular team could have a look on it soon, as soon as they release Angular 5

**Comment by rk-7** [comment]
I'm trying to log error and navigate the user to an ErrorComponent through a custom ErrorHandler. Right now, If the component throws error, any subsequent route navigation will cause components to append. It's happening due to `BrowserAnimationModule`. When the `BrowserAnimationModule` is removed from `app.module.ts` (and animations are removed from respective files), everything works fine.

In our app, we need the `BrowserAnimationModule` too for certain animations. I don't know how to get rid of this problem. Any workarounds?

**Comment by jnsn** [comment]
Attached you can find a simple sample application which reproduces the problem.

The setup was done using angular-cli as follows:

```
$ ng new AngularIssue -sg -st --style=scss -sc --routing
$ cd AngularIssue\src\app\
$ mkdir components
$ cd components
$ ng g component ExampleOne --spec=false
$ ng g component ExampleTwo --spec=false
```

I added the `BrowserAnimationsModule` and the `ReactiveFormsModule` in the `app.module.ts` file and I updated the routing to include two routes to each component.

The `app.component.html` file was altered as follows: 

```
<h1>Example App</h1>

<div>
  <ul>
    <li><a [routerLink]="['one']">One</a></li>
    <li><a [routerLink]="['two']">Two</a></li>
  </ul>
</div>

<div style="border: 2px solid red;">
  <router-outlet></router-outlet>
</div>
```

Component "One" was left as-is, component "Two" was changed to include the following HTML:

```
<p>
  example-two works!
</p>

<form [formGroup]="formGroup"></form>
```

The form group does not exists. When using `ng serve` or `ng build` to run the application, when clicking on the link to component "Two" it will crash and the content will be appended to the div.

Note that running `ng build --prod` will throw an error saying that "Property 'formGroup' does not exist on type 'ExampleTwoComponent'.", so a production build is covered.

[issue-19273.zip](https://github.com/angular/angular/files/1421818/issue-19273.zip)

**Comment by bmercier-manakin** [comment]
@jnsn To be more precise, a production build correct the case you show here, but not every cases

**Comment by noblezilla** [comment]
Is there any other work arounds (say manually destroying the component) without removing BrowserAnimations?

**Comment by mortarboyz** [comment]
I've also got the same issue here.

**Comment by bmercier-manakin** [comment]
So this is a duplicate of an older bug issued here #19093 
But I think someone of Angular team just looked at it a week ago

**Comment by jasonaden** [comment]
Yes, we have been doing some testing with the fix to #19093 and this issue should be fixed when that gets merged. Trying to get that into the release for tomorrow.

**Comment by ReverendDG** [comment]
As commented over on 19093, I'm still seeing this issue in Angular2. Am I SOL since it's ng2, or am I missing a fix?
