### ISSUE TITLE
Async in unit tests does not handle unresolved promises

### ISSUE THREAD

**Issue by kenborge** [angular/angular#20827]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Writing tests using async does not seem to wait for all promises to resolve. 
```
it('should fail', async(() => {
    const promise = new Promise(() => {});
    promise.then(() => {
        expect(false).toBe(true);
    });
  }));
```
This test should fail, but because the promise is never resolved and the test does not wait for it to be resolved it passes as success. 

## Expected behavior
The test should fail or timeout because the promise is never resolved.

Base on the documentation for async test function here https://angular.io/api/core/testing/async and https://angular.io/guide/testing it seems like the intended behaviour of async is to not complete the test until all async calls are completed. 

Not sure if this is a documentation problem or a bug with unresolved promises.
If this is the intended behaviour it should be described more clearly what situations async can actually be used in and what types of async calls it handles. 

## Minimal reproduction of the problem with instructions
See current behaviour for a simple example using a promise that is never resolved. 

This looks to be the same issue as observed in a issue from 2.0 beta when async was introduced https://github.com/angular/angular/issues/8736.  But the submitter closed the issue when he found a workaround by not using async.

## What is the motivation / use case for changing the behaviour?
It currently seems unsafe to use async in tests when one is never sure if a test passed because there was no problems or because the async expect was never run.
Currently recommended our developers to stay away from async and write tests using fakeAsync so they can be written in a sync way to ensure all expects are actually executed.

## Environment

<pre><code>
Angular version: 5.0.5
</code></pre>

**Comment by JiaLiPassion** [comment]
@kenborge , this is not a bug, and your test case.

```javascript
it('should fail', async(() => {
    const promise = new Promise(() => {});
    promise.then(() => {
        expect(false).toBe(true);
    });
  }));
```

will not fail, because the `promise` will never resolve, and the `then expect`  logic will never run.
And it will not timeout either, because `async` will not wait for all promise to be resolved, but wait for all `async operations` finished. `non resolved promise` not equals to `non finished async operations`, in your case, `const promise = new Promise(() => {});` is not `async`, it is a simple `statement`. so this case will just passed as `OK`.

**Comment by kenborge** [comment]
I figured this could be the case that it's not really intended to work. 
I do however think that the documentation doesn't make this very clear. A promise is an asynchronous function.
And the documentation states that async wraps the test in a zone, and zones are promise aware so it seems logical that it might work.

Take the example shown on the API documentation for async https://angular.io/api/core/testing/async:
```
it('...', async(inject([AClass], (object) => {
  object.doSomething.then(() => {
    expect(...);
  })
});
```
It seems really scare to me to do this if it's not aware of the promise resolution> I assume the idea is that this will work if doSomething is doing a setTimeout that resolved the promise for instance, as the zone will wait for the setTimeout to resolve. So at the time the test is written it will work, but if someone changes the implementation of doSomething and makes a mistake so the promise is not resolved your test is now completely worthless and will report no issues.

**Comment by gkalpak** [comment]
@kenborge, does the following pass or fail?

```ts
it('should fail', async(() => {
  Promise.resolve().then(() => expect(false).toBe(true));
}));
```

@JiaLiPassion, should it pass or fail?

**Comment by kenborge** [comment]
That fails, so the promise is resolved and the expect runs before the test finishes.

**Comment by gkalpak** [comment]
So, it seems that @JiaLiPassion is right. It might seem unintuitive at first (at least to me), but thinking about it, an unresolved Promise is not a pending async task. The promise might never resolve and that is perfectly fine :smiley:
Resolving or rejecting a promise creates an async (micro)task (which will invoke the then callbacks asynchronously) and that is what `async` can (and will) wait for.

So, in this case where you want to verify that a promise _will be resolved_, you should use other means:
- Jasmine's `done` calback.
- Returning a promise (if using jasmine 2.8+).
- Using `async/await`.

Maybe we could add a mention in the docs about that.

**Comment by kenborge** [comment]
You can't use done together with angular async right? But i guess i can't think of a reason you would need that.

**Comment by JiaLiPassion** [comment]
@gkalpak 

```javascript
it('should fail', async(() => {
  Promise.resolve().then(() => expect(false).toBe(true));
}));
```

this will fail,because `promise.resolve().then()` will really `schedule` an async operations.
and `AsyncZone` will know that and wait for the `then` callback to do `expect(false).toBe(true)` to run.

**Comment by webmaster128** [comment]
> but thinking about it, an unresolved Promise is not a pending async task.

Maybe yes, but what about an async function call waiting for an unresolved promise?

This test passes, which I find highly dangerous
```typescript
it('async should work', async(inject([MyService], (service: MyService) => {
  (async () => {
    let nonResolvingPromise = new Promise((resolve, reject) => {
      // I never call resolve() or reject()
    });
    await nonResolvingPromise;

    fail("should fail")
  })();
})));
```

**Comment by JiaLiPassion** [comment]
@webmaster128 , @kenborge , @gkalpak , in the next version of `zone.js` (0.8.21), this issue will be fixed. https://github.com/angular/zone.js/pull/1014

the test cases such as 
```javascript
it('should fail', async(() => {
    const promise = new Promise(() => {});
    promise.then(() => {
        expect(false).toBe(true);
    });
  }));
```
and 

```javascript
it('async should work', async(inject([MyService], (service: MyService) => {
  (async () => {
    let nonResolvingPromise = new Promise((resolve, reject) => {
      // I never call resolve() or reject()
    });
    await nonResolvingPromise;

    fail("should fail")
  })();
})));
```

will work as expected.

**Comment by kenborge** [comment]
@JiaLiPassion Awesome, that is great news! This will make a lot of tests more foolproof

**Comment by jenniferfell** [comment]
@gkalpak : Hi. Since you were on this thread, can I ask you...is this now resolved?

**Comment by gkalpak** [comment]
I am not sure. According to @JiaLiPassion's comment, it should have been fixed, but from a quick look it doesn't seem to be. @JiaLiPassion, can you confirm whether the following would indeed fail with latest Zone.js:

```ts
import { async } from '@angular/core/testing';
...
it('should fail', async(() => {
  const promise = new Promise(() => {});
  promise.then(() => {
    expect(false).toBe(true);
  });
}));
```

**Comment by DW8Reaper** [comment]
I guess this may be a bit hacky but I made a function that forces an async task. We use ngrx so there are lots of tests that call the store which is async but not necessarily http. Another use case is if you really do TDD and want your test to fail before writing the implementation. This is how you would use it:
```
it('should fail', async(() => {
    const promise = new Promise(() => {});
    createAsyncTask(promise).then(() => {
        expect(false).toBe(true);
    });
}));
```

and it is implemented as: 
```
import { Observable } from 'rxjs';
import { finalize, tap } from 'rxjs/operators';


export function createAsyncTask<T>(observable: Observable<T>): Observable<T>;
export function createAsyncTask<T>(promise: Promise<T>): Promise<T>;

export function createAsyncTask<T>(query: Observable<T> | Promise<T>): Observable<T> | Promise<T> {
  if (!query) {
    throw new Error(`requested task is null`);
  }
  const timer = new AsyncTimer(new Error(`async task didn't complete`));

  timer.next();

  if (query instanceof Promise) {
    return query.then(
      result => {
        timer.completed();
        return result;
      },
      reason => {
        timer.completed();
        return Promise.reject(reason);
      }
    );
  } else {
    let emitCount = 0;
    return query.pipe(
      tap(() => {
        emitCount++;
      }),
      finalize(() => {
        if (emitCount > 0) {
          timer.completed();
        }
      })
    );
  }
}

class AsyncTimer {
  private static readonly maxCycles = 30;

  public cycles = 0;
  private done = false;
  private readonly timer = null;

  public constructor(private readonly exception: Error) {
    this.timer = setInterval(this.next.bind(this), 10);
  }

  public next() {
    if (!this.done) {
      this.cycles++;
      if (this.cycles > AsyncTimer.maxCycles) {
        this.completed();
        throw this.exception;
      }
    }
  }

  public completed() {
    clearInterval(this.timer);
    this.done = true;
  }
}
```

**Comment by dmurvihill** [comment]
Hi @JiaLiPassion, this still isn't working.

test.ts:
```typescript
// This file is required by karma.conf.js and loads recursively all the .spec and framework files

import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy.js';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';

(window as any).__zone_symbol__supportWaitUnResolvedChainedPromise = true;

// Unfortunately there's no typing for the `__karma__` variable. Just declare it as any.
declare const __karma__: any;
declare const require: any;

// Prevent Karma from running prematurely.
__karma__.loaded = function () {};

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);
// Then we find all the tests.
const context = require.context('./', true, /\.spec\.ts$/);
// And load the modules.
context.keys().map(context);
// Finally, start Karma to run the tests.
__karma__.start();
```

spec:
```typescript
describe('this test', () => {
  it('should fail', async(() => {
    const promise = new Promise(() => {});
    promise.then(() => {
      expect(false).toBe(true);
    });
  }));
});
```

package.json:
```
"zone.js": "^0.9.1"
```

But the test is still passing. Thoughts?

**Comment by JiaLiPassion** [comment]
@dmurvihill, I am currently doing some improvements of this part. 
To make your sample work, here is the steps.
1. create a file `zone-flag.ts`.
```
(window as any).__zone_symbol__supportWaitUnResolvedChainedPromise = true;
```
2. Here is the `test.ts`.

```
// This file is required by karma.conf.js and loads recursively all the .spec and framework files
import './zone-flag';
import 'zone.js/dist/zone-testing';
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';

declare const require: any;

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);
// Then we find all the tests.
const context = require.context('./', true, /\.spec\.ts$/);
// And load the modules.
context.keys().map(context);
```

Then it will work, those steps are not ideal and not documented, I am trying to make some improvement of the API and setup steps docs later.

**Comment by dmurvihill** [comment]
Thanks @JiaLiPassion, worked like a charm!

Test:
```
describe('this test', () => {
  it('should fail', async(() => {
    const promise = new Promise((_, reject) => reject(new Error('test')));
  }));
});
```

Result:
```
this test > should fail
Failed: Uncaught (in promise): Error: test
Error: test
    at http://localhost:9876/_karma_webpack_/src/app/shared/components/affidavit-table.component.spec.ts:38:55
    at new ZoneAwarePromise (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone.js:931:1)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/src/app/shared/components/affidavit-table.component.spec.ts:38:21)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone.js:391:1)
    at AsyncTestZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.AsyncTestZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:770:1)
    at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:305:1)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone.js:390:1)
    at Zone../node_modules/zone.js/dist/zone.js.Zone.runGuarded (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone.js:161:1)
    at runInTestZone (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:898:1)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:832:1)
```

**Comment by AndrewKushnir** [comment]
Closing this ticket based on the comments above from @JiaLiPassion (from Jun 4, 2018). Feel free to reopen or create a new ticket if the problem still exists. Thank you.
