### ISSUE TITLE
When following the "Services" tutorial and you get to https://angular.io/tutorial/toh-pt4#see-it-run the application does not run.

### ISSUE THREAD

**Issue by david-ghikas** [angular/angular#21137]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When following the "Services" tutorial and you get to https://angular.io/tutorial/toh-pt4#see-it-run the application does not run.

## Expected behavior

When following the "Services" tutorial and you get to https://angular.io/tutorial/toh-pt4#see-it-run the application should run.

## Minimal reproduction of the problem with instructions

Follow the tutorial to reproduce the problem.
## What is the motivation / use case for changing the behavior?

The motivation to fix this issue is that people will not get lost following the tutorial.

## Environment

<pre><code>
Angular version: 5.1.2

Browser:
- [x] Chrome (desktop) version 63.0.3239.84
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.3  
- Platform: Windows 

Others:

</code></pre>

Remove the "MessageService" from the providers array in the following code that appears prior to the run.

providers: [ HeroService, MessageService ]

**Comment by eltrhn** [comment]
"It doesn't run" is woefully vague. This is legitimate, but your title should mention the specific issue rather than leaving it to mention it as an afterthought -- said issue being not that it "doesn't run", but that the tutorial instructs the user to add the MessageService to the providers list two sections before actually introducing the service.

**Comment by gilessmart** [comment]
Duplicate of #20398

**Comment by jenniferfell** [comment]
docsarea=tutorial

Update: We recently went through the tutorial end-to-end for v6, and the instructions worked correctly, but I want to keep this open to recheck that this specific issue is resolved.

**Comment by edwin-hendriks** [comment]
This issues is still active in the current tutorial (of today). When you come to [https://angular.io/tutorial/toh-pt4#see-it-run](url) the app is not working with the following message in the console of the browser:
> NullInjectorError: No provider for HeroService
A possible solution at that point would be to add the provider to **app.component.ts** by adding:
`providers: [HeroService],`
to:
```
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
```
(I placed it below the line starting with **selector:** to make it work again).

By the way: it may have been a duplicate of #20398 in the past, but now it isn't anymore.

**Comment by jenniferfell** [comment]
@edwin-hendriks Thanks for rechecking this and providing info about a possible solution. We appreciate the help!

**Comment by edwin-hendriks** [comment]
I found a better solution and I also found the real cause of the problem. The solution is to do nothing because in the current angular 6.0.0 version everything works fine (as @jenniferfell already thought so). 

The issue was caused because I started doing the tour-of-heroes tutorial just a few days ago (when all was in version 5.2.0). When I came to the tutorial on [https://angular.io/tutorial/toh-pt4](Services) the tutorial was changed to reflect version 6.0.0. At that point the CLI generates a service by default with
`providedIn: 'root'` (a flag I like a lot by the way). But of course my version didn't. 

In the mean time I have:

- updated everything to 6.0.0
- removed the solutions as I described in a previous comment of this issue
- added the `providedIn: 'root'` flag to **hero.service.ts** manually. 

Now my work matches the tutorial and everything is working just fine. 

For my part you can close this issue.

**Comment by chembu** [comment]
The issue does not exist in the current tutorial.
