### ISSUE TITLE
Move all triaged issues to backlog

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21635]
If an issue meets the following criteria it should be move into the [Backlog milestone](https://github.com/angular/angular/milestone/82):

1. The issue is not assigned to any milestone AND

    1. The issue is of "type: bug" and has the following additional labels:
        - "severity: *"
        - "frequency: *"

    2. OR the issue is of "type: feature".

All the other "type: *" labels and any other labels should be ignored for now, leaving those issues in the current milestone.

**Comment by IgorMinar** [comment]
This should not apply to pull requests for now. Just issues.

**Comment by IgorMinar** [comment]
ah.. one more important thing. If the milestone or labels on the issue change, we should reevaluate the rules above and if the issue is currently in no milestone, move it to the backlog if it matches the criteria *OR* if the issue is already in the backlog milestone but no longer matches the criteria for backlog (e.g. a label is missing), it should be moved out of the backlog milestone into a state with no milestone (the default, untriaged state).

**Comment by ocombe** [comment]
Code is ready and deployed, we just need to add the permissions to the bot to read/write issues and to receive events when an issue is labeled

**Comment by IgorMinar** [comment]
node: during the code review we also noticed that "comp: " was missing in the spec. @ocombe added it.

**Comment by IgorMinar** [comment]
Olivier, use "Ref #XXX" instead of "Close #XXX" or "Fix #XXX" in the future
if you don't want the commit to close the issue yet.

**Comment by IgorMinar** [comment]
- [ ] the bot doesn't seem to be triaging new issues: https://github.com/angular/angular/issues/21663
- [ ] part of this issue was to also triage old issue, which hasn't been done. ideally the robot should reevaluate all the preexisting issues after redeployment and ensure that they are in a state corresponding the the rule configuration.
- [ ] even better would be if the robot reeavluated also when there is no redeployment, but the config in the repo has changed

**Comment by ocombe** [comment]
After the config was merged, it was reading the milestone id as a string, and github expects a number. I've fixed the code, it doesn't throw any error anymore but it doesn't seem to set the milestone either...

**Comment by ocombe** [comment]
Ok points 1 and 2 are done.
About point 3 (reevaluate): should it also remove issues from the backlog when it happens? Or just check if new issues match the new rules?

**Comment by IgorMinar** [comment]
I've just triaged https://github.com/angular/angular/issues/21525 and it was assigned to backlog (great!), but then I removed the "type: bug" label, and the issue remained in the backlog. Only issues that match all the backlog criteria should be in the backlog.

Can you please look into this? thanks!

**Comment by IgorMinar** [comment]
"type: *" label missing: 
<img width="294" alt="screen shot 2018-01-23 at 8 30 50 am" src="https://user-images.githubusercontent.com/216296/35287673-c50ba678-0017-11e8-97ca-bbd8c8702461.png">

**Comment by IgorMinar** [comment]
similarly, if someone manually assigns the issue to the backlog milestone and the issue doesn't qualify, it should be kicked out.

**Comment by ocombe** [comment]
Ahhh you didn't say those rules earlier!
Ok I'll add an auto remove function too

**Comment by IgorMinar** [comment]
![It's only logical](https://memegenerator.net/img/instances/28183633/its-only-logical.jpg)

**Comment by ocombe** [comment]
Be careful with the logic:
> A programmer is going to the grocery store and his wife tells him, "Buy a gallon of milk, and if there are eggs, buy a dozen." So the programmer goes, buys everything, and drives back to his house. Upon arrival, his wife angrily asks him, "Why did you get 13 gallons of milk?" The programmer says, "There were eggs!"

**Comment by IgorMinar** [comment]
:)

**Comment by ocombe** [comment]
Finally took the time to finish this one. It'll keep the milestone status updated.

**Comment by IgorMinar** [comment]
thanks
