### ISSUE TITLE
Angular2 Does not work on safari on OSX / iOS

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2275]
http://mhevery.github.io/github_issues/ does not load

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (favicon.ico, line 0)
[Error] Parser Error: Unexpected token . at column 42 in [ng-for var assignee of milestoneAssignees.items] in null

BaseException@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:7159:34
error@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:21761:36
parsePrimary@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:21639:25
parseCallChain@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:21589:43
parsePrefix@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:21585:41
parseMultiplicative@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:21564:42
parseAdditive@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:21552:50
parseRelational@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:21536:44
parseEquality@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:21520:46
parseLogicalAnd@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:21513:44
parseLogicalOr@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:21506:46
parseConditional@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:21491:45
parseExpression@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:21474:47
parsePipe@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:21465:46
parseTemplateBindings@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:21744:43
parseTemplateBindings@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:21341:102
_parseTemplateBindings@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:14832:62
process@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:14813:44
internalProcess@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:14054:27
_process@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:20558:67
_process@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:20568:32
_process@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:20568:32
_process@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:20568:32
_process@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:20568:32
process@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:20553:26
_compileTemplate@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:22989:51
https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:22971:43
run@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:115:22
https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:12418:43
zoneBoundFn@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:88:22
lib$es6$promise$$internal$$tryCatch@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:479:24
lib$es6$promise$$internal$$invokeCallback@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:491:52
https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:1036:54
https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:195:17
microtask@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:12438:25
run@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:115:22
https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:12418:43
zoneBoundFn@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:88:22
flush@https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:1208:13
	logError (angular2.dev.js, line 17335)
	defaultErrorReporter (angular2.dev.js, line 24768)
	_onError (angular2.dev.js, line 12456)
	onError (angular2.dev.js, line 12404)
	run (angular2.dev.js, line 118)
	(anonymous function) (angular2.dev.js, line 12418)
	zoneBoundFn (angular2.dev.js, line 88)
	lib$es6$promise$$internal$$tryCatch (angular2.dev.js, line 479)
	lib$es6$promise$$internal$$invokeCallback (angular2.dev.js, line 491)
	(anonymous function) (angular2.dev.js, line 1036)
	(anonymous function) (angular2.dev.js, line 195)
	microtask (angular2.dev.js, line 12438)
	run (angular2.dev.js, line 115)
	(anonymous function) (angular2.dev.js, line 12418)
	zoneBoundFn (angular2.dev.js, line 88)
	flush (angular2.dev.js, line 1208)
```

**Comment by caitp** [comment]
Looks like the same issue as #2163 to me

![screen shot 2015-06-02 at 12 11 18 am](https://cloud.githubusercontent.com/assets/2294695/7928315/f17fa30e-08bb-11e5-9668-5b305b1eb7b6.png)

**Comment by mhevery** [comment]
fixed in alpha 27

**Comment by janneromell** [comment]
Got the feeling this problem is back with alpha37+ (not sure which version).
I can't load any Angular 2 webs in Safari on iOS8.4

**Comment by mcgear** [comment]
Yea, this seems back for me in the Beta:
http://pedalr.azurewebsites.net/home/menu
