### ISSUE TITLE
Bug in angular compiler (ng build) when using npm's link

### ISSUE THREAD

**Issue by costescuandrei** [angular/angular#23411]
## I'm submitting a...
[x] Bug report

## Current behavior
'ng build' gives an incorrect error in scenario detailed below. If I do 'ng serve --open' it also fails to compile initially but if I remove a bracket, save and undo + save again in app.module.ts for example then compile will pass and app runs normally. So there seems to be a glitch in ng build the first time it runs, because the second time it works correctly although the contents are identical.

## Expected behavior
'ng build' should pass as it is just a default new app generated using CLI
'ng serve' should work from the start without the workaround described above

## Minimal reproduction of the problem with instructions
Environment vars set below make npm packages be installed in a specific 'global' location and using the link setting to reuse packages and avoid 300 MB downloaded and installed for each separate app. This way each default CLI new app will use 50-60 KB of disk space instead of ~300 MB each. So for example with those set the cli install would be equivalent to a `npm install --link --prefix D:\angularCLI\alternateGlobalNPMRepo -g @angular/cli` command.

To reproduce it run the following commands inside an empty dir (in my case 'D:\angularCLI') (I am on windows 10, using cmd):

set npm_config_link=true
set npm_config_prefix=D:\angularCLI\alternateGlobalNPMRepo
set PATH=%PATH%;%npm_config_prefix%

npm install -g @angular/cli

ng new my-new-app

cd my-new-app

ng build
ng serve --open

Both `ng build` and `ng serve --open` will give an error: 
> ERROR in No NgModule metadata found for 'AppModule'.

But if you change something in app.module.ts, save, change it back, save then `ng serve` compiles successfully and refreshing the browser will show the app.

## What is the motivation / use case for changing the behavior?
Npm link basically creates OS symbolic links in the node_modules folder towards the global npm folder - so I don't know why ng build fails first time. Please fix this so I don't have to download and store the same 300 MB multiple times when I don't need to.

## Environment

<pre><code>Angular CLI: 1.7.4
Node: 8.9.4
OS: win32 x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
typescript: 2.5.3
webpack: error
 
For Tooling issues:
- NPM version: 5.8.0
- Platform:  Windows 10
</code></pre>

**Comment by trotyl** [comment]
1. This is not a problem of Angular compiler;
2. Wrong repo: https://github.com/angular/angular-cli;
3. Try [preserveSymlinks](https://github.com/angular/angular-cli/wiki/angular-cli) option.

**Comment by splincode** [comment]
@costescuandrei Please move to another tracker

**Comment by costescuandrei** [comment]
No change with preserveSymlinks.
Ok so for ng build bugs I should use Angular CLI. I will create an issue there and link to this one...

**Comment by costescuandrei** [comment]
Created: https://github.com/angular/angular-cli/issues/10368

**Comment by jasonaden** [comment]
Closing as the bug was addressed in the CLI project.

**Comment by front-end-developer** [comment]
this is not address I still see the problem in angular 5 and 6:
ERROR in No NgModule metadata found for 'AppModule'

**Comment by shanemac10** [comment]
So maybe it's a VS Code thing or npm thing, I don't know, but somehow the file paths to our symlink'ed modules had their direct paths added (../../../patient/node_modules/*). We spent quite awhile trying to hunt down this issue, and apparently an automated process re-wrote the file paths in app.module.ts.

SHOULD BE:
```
import { BrowserModule } 		from '@angular/platform-browser';
import { NgModule } 			from '@angular/core';
import { RouterModule, Routes } 	from '@angular/router';
import { HttpClientModule } 		from '@angular/common/http';
import { BrowserAnimationsModule }	from '@angular/platform-browser/animations';
import { FlexLayoutModule } 		from '@angular/flex-layout';
import { FormsModule }			from '@angular/forms';
```
OVERWRITTEN FILE PATHS:
```
import { BrowserModule } 		from '../../../patient/node_modules/@angular/platform-browser';
import { NgModule } 			from '../../../patient/node_modules/@angular/core';
import { RouterModule, Routes } 	from '../../../patient/node_modules/@angular/router';
import { HttpClientModule } 		from '../../../patient/node_modules/@angular/common/http';
import { BrowserAnimationsModule }	from '../../../patient/node_modules/@angular/platform-browser/animations';
import { FlexLayoutModule } 		from '../../../patient/node_modules/@angular/flex-layout';
import { FormsModule }			from '../../../patient/node_modules/@angular/forms';
 ```

**Comment by costescuandrei** [comment]
Weird. Thanks for looking into it. It would be nice if it worked without using lots of space on duplicates with the standard package manager.

Meanwhile (see related issue) I did succeed in a manner of speaking with **pnpm** instead of **npm** with the option **--shamefully-flatten**, although even pnpm emphasized that --shamefully-flatten should not be needed if modules find their paths in the right way or something like that.
