### ISSUE TITLE
Service worker updates do not work on latest chrome (Chrome 66.0.3359.117 )

### ISSUE THREAD

**Issue by MichalK6677** [angular/angular#23526]
I generated empty angular application via ng new appName --service-worker and implemented swUpdate:

<pre><code>
export class AppComponent {
  title = 'test';
  
  constructor(private swUpdate: SwUpdate) {
    }

    ngOnInit() {

        if (this.swUpdate.isEnabled) {

            this.swUpdate.available.subscribe(() => {
				console.log("New version available.");
                if(confirm("New version available. Load New Version?")) {

                    window.location.reload();
                }
            });
        }        
    }
}
</code></pre>
![2018-04-24_1901](https://user-images.githubusercontent.com/3100059/39202363-f40886e0-47f1-11e8-9377-aa8080170b8e.png)

When service worker detects new version and I reload a page (via confim ok of F5) then I see an exception in console:
![2018-04-24_1852](https://user-images.githubusercontent.com/3100059/39201930-cfaf84fc-47f0-11e8-9d13-501292d345ab.png)
and chrome displayes "This page can't be reached". It works if I refresh via ctrl+F5. Refresh via F5 work again after clearing data via dev. tools -> application tab.
It worked fine on older chrome 65.0.3325.181. It stopped working imediately I updated chrome. It is tested on 2 independent computers.

## Current behavior
All sites in application displays "This page can't be reached" after Chrome update to latest 66.0.3359.117 version when service worker detects new version.

## Expected behavior
Application should load latest version with refresh page.

## Minimal reproduction of the problem with instructions
1. create new angular app with service worker via cli
2. implement swUpdate
3. test on chrome 66.0.3359.117 

Browser:
- [ ] Chrome (desktop) version 66.0.3359.117

**Comment by gkalpak** [comment]
This is a duplicate of #23296. It sounds like a Chrome bug (see https://github.com/angular/angular/issues/23296#issuecomment-382984073).
Could be related to https://bugs.chromium.org/p/chromium/issues/detail?id=832105.

There is also a chance it has been fixed by #22883. Can you try with the latest 6.x version (currently 6.0.0-rc.5)?

**Comment by MichalK6677** [comment]
I've tried the latest 6.x version. It seems like the issue is still present.

**Comment by gkalpak** [comment]
Wait. Are you saying that your GMail login status makes a difference in how the ServiceWorker works in an Angular app?

**Comment by MichalK6677** [comment]
No. Sorry my mistake in testing. It does not matter on gmail status.

**Comment by zh99998** [comment]
I got into same problem

![2018-04-25 11 54 38](https://user-images.githubusercontent.com/359622/39257418-09678e08-48e4-11e8-92f5-f6029e052920.png)

chrome says `clientId` is `""` (empty string), so `clientId !== null` check passed but this.scope.clients.get(clientId) got `undefined`.

a simple work-around is to check other false value. `if (clientId) { ... }`

**Comment by NathofGod** [comment]
I'm getting the same issue which is stopping my site being accessible

The problem is client.id in the following area

![image](https://user-images.githubusercontent.com/1936466/39258138-204f7650-48ab-11e8-8ee3-425da649e117.png)

My issue happens on my live site here https://spark.ricoh.co.uk/welcome when updating

`async updateClient(client) {
        // Figure out which version the client is on. If it's not on the latest,
        // it needs to be moved.
        const existing = this.clientVersionMap.get(client.id);
        if (existing === this.latestHash) {
            // Nothing to do, this client is already on the latest version.
            return;
        }
        // Switch the client over.
        let previous = undefined;
        // Look up the application data associated with the existing version. If there
        // isn't any, fall back on using the hash.
        if (existing !== undefined) {
            const existingVersion = this.versions.get(existing);
            previous = this.mergeHashWithAppData(existingVersion.manifest, existing);
        }
        // Set the current version used by the client, and sync the mapping to disk.
        this.clientVersionMap.set(client.id, this.latestHash);
        await this.sync();
        // Notify the client about this activation.
        const current = this.versions.get(this.latestHash);
        const notice = {
            type: 'UPDATE_ACTIVATED',
            previous,
            current: this.mergeHashWithAppData(current.manifest, this.latestHash),
        };
        client.postMessage(notice);
    }`

**Comment by patrickmichalina** [comment]
Ahh same issue here!

**Comment by meowhunter** [comment]
Same issue guys, 
![image](https://user-images.githubusercontent.com/5663121/39692366-57cedf84-51e9-11e8-9dbb-60689ef9a826.png)

Got the same on service worker update.
Does anybody have workaround on that while angular team working on fix?

**Comment by webmaxru** [comment]
Hi @meowhunter! Please, confirm that you use the latest (release) version of NGSW. This issue should ne fixed via https://github.com/gkalpak/angular/commit/2ff1be0479718be033c8654f5a320bb0be22e395

**Comment by zh99998** [comment]
@webmaxru I have tried latest release but problem still exists.
```
"dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/cdk": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/material": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/pwa": "^0.6.0",
    "@angular/router": "^6.0.0",
    "@angular/service-worker": "^6.0.0",
    ...
  },
```

**Comment by gkalpak** [comment]
This should be fixed by #23625, but it hasn't been merged yet.
