### ISSUE TITLE
Improve error message: `TypeError: Cannot read property 'type' of null`

### ISSUE THREAD

**Issue by thefliik** [angular/angular#24143]
## I'm submitting a...
<pre><code>
[x] Feature request
</code></pre>

## Current behavior

If a custom library module, lets call it `library-a`, imports another custom library module, `library-b`, and the `library-b` module exports components/modules which are *not also* exported via typescript/javascript (i.e. `library-b` has `@NgModule({exports: [...]})` but **not** `export { ... }`), then a very non-descriptive `BUILD ERROR TypeError: Cannot read property 'type' of null` is thrown with the following trace when performing `ng build library-a`.

```
BUILD ERROR
Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at /Users/John/apps/tests/service-work/node_modules/@angular/compiler/bundles/compiler.umd.js:15378:27
    at Array.forEach (<anonymous>)
    at removeSummaryDuplicates (/Users/John/apps/tests/service-work/node_modules/@angular/compiler/bundles/compiler.umd.js:15377:11)
    at TemplateParser.tryParseHtml (/Users/John/apps/tests/service-work/node_modules/@angular/compiler/bundles/compiler.umd.js:14806:34)
    at TemplateParser.tryParse (/Users/John/apps/tests/service-work/node_modules/@angular/compiler/bundles/compiler.umd.js:14799:21)
    at TemplateParser.parse (/Users/John/apps/tests/service-work/node_modules/@angular/compiler/bundles/compiler.umd.js:14780:27)
    at AotCompiler._parseTemplate (/Users/John/apps/tests/service-work/node_modules/@angular/compiler/bundles/compiler.umd.js:20483:43)
    at AotCompiler._createTypeCheckBlock (/Users/John/apps/tests/service-work/node_modules/@angular/compiler/bundles/compiler.umd.js:20250:23)
    at /Users/John/apps/tests/service-work/node_modules/@angular/compiler/bundles/compiler.umd.js:20220:27
    at Array.forEach (<anonymous>)
```

This made the problem very difficult to debug.

## Expected behavior

Provide a better, more descriptive error message to aid in debugging.

## Environment

<pre><code>
Angular CLI: 6.0.5
Node: 8.9.1
OS: darwin x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.5
@angular-devkit/build-angular      0.6.5
@angular-devkit/build-ng-packagr   0.6.5
@angular-devkit/build-optimizer    0.6.5
@angular-devkit/core               0.6.5
@angular-devkit/schematics         0.6.5
@angular/cdk                       6.1.0
@angular/cli                       6.0.5
@angular/material                  6.1.0
@angular/material-moment-adapter   6.1.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.5
@schematics/angular                0.6.5
@schematics/update                 0.6.5
ng-packagr                         3.0.0
rxjs                               6.2.0
typescript                         2.7.2
webpack                            4.8.3
</code></pre>

**Comment by splincode** [comment]
Add repo for example and add about info for repro steps

**Comment by GeorgeKnap** [comment]
getting this as well a lot. very difficult to find the actual problem.

**Comment by dherges** [comment]
I opened an issue on ng-packagr ng-packagr/ng-packagr#1087

**Comment by dherges** [comment]
@GeorgeKnap Can you share some code? doesn't need to be the full code base, only the parts related to this issue

**Comment by GeorgeKnap** [comment]
@dherges 
easy. Let's consider a setup as in original post above with `library-a` and `library-b` modules.

```
@NgModule({
  imports: [
    TranslateModule.forChild(),
    CommonModule,
    ReactiveFormsModule,
    TranslateModule,
    FlexLayoutModule,
    MatButtonModule,
    MatCheckboxModule,
    MatProgressSpinnerModule,
  ],
  declarations: [
    CustomButtonComponent,
    CustomHeaderButtonComponent,
    LoadingOverlayComponent,
    NoRowsOverlayComponent
  ],
  exports: [
    CommonModule,
    ReactiveFormsModule,
    TranslateModule,
    FlexLayoutModule,
   CustomButtonComponent, // <--
    CustomHeaderButtonComponent, // <--
    LoadingOverlayComponent, // <--
    NoRowsOverlayComponent // <--
  ],
  entryComponents: [
    LoadingOverlayComponent
  ],
  providers: [
    ConfigService,
    { provide: APP_INITIALIZER, multi: true, useFactory: configServiceInitializerFactory, deps: [ConfigService] }
  ],
})
export class LibraryBModule {}
```

if you import this module into `library-a` module you get the error while building `library-a`. But if you don't export the components (marked with `<--`) from the module the build will work.
And of course to be able to import them elsewhere you need to export them from the library `public_api.ts` barrel:
```
export * from './lib/components/ag-grid/cell/custom-button.component';
export * from './lib/components/ag-grid/header/custom-header-button.component';
export * from './lib/components/ag-grid/loading-overlay.component';
export * from './lib/components/ag-grid/no-rows-overlay.component';
```

**Comment by thefliik** [comment]
@GeorgeKnap nice detective work! I shutter to think how long this took you to pin down...I'm reopening the issue now that there's a reproduction.

**Comment by dherges** [comment]
But how can that be the cause of error?

There must be something in `CustomButtonComponent`, `CustomHeaderButtonComponent` (and so on) that cuases the build failure. Any error in the template validation?

**Comment by GeorgeKnap** [comment]
@dherges 
No, the LibraryB always builds fine into --prod. If the problem was with the components the error would probably not go away because they are still declared in that module.

**Comment by Ventzy** [comment]
I would love to hear from someone who knows angular internals confirming that proposed workaround - removing components from module's exports array and keep components exported on library level - is valid and safe way to deal with that issue.

**Comment by Ventzy** [comment]
I couldn't get this working. Yes, if components are removed from module's exports both libraries build, but only until component from library-b is used in template of library-a. Then I get that component is unknown. Which is expected if it is not part of module exports.

**Comment by Ventzy** [comment]
The issue seems to be with symlinked libraries in node_modules (I am on Windows). I am building library as usual into ./dist and then do npm link dist/library-b, which creates symlink node_modules/library-b -> dist/library-b. If library-b is installed that way, then ng build library-a fails with "Cannot read property 'type' of null" (only if components are listed in module exports). If I copy dist/library-b into node_modules, then ng build library-a is fine.

The reason behind npm link is to be able to build libraries with --watch and get changes propagated to the app, which won't happen with copy. The only workaround that seems to be working so far is to list libraries in tsconfig.json paths like so
```
      "library-b": [
        "dist/library-b"
      ],
      "library-b/*": [
        "dist/library-b/*"
      ]
```
"ng g library" adds this automatically btw, but I had removed added paths each time. Up until now, "npm link" approach worked for libraries which does not export components used directly in templates of other libraries. I have libraries which export classes, services, and components which are dynamically instantiated and used by the app. It seems it chokes in above cross-library use case however.

**Comment by tanejamohit4** [comment]
@Ventzy  Solution given by you is not working for me. its been a long time.. i am struggling with this issue but no luck. 
Is there any other solution for this? 
Problem is same, i have two libraries say A and B. B is getting build successfully. Library B is getting used in library A using npm link. What should i do?

**Comment by pfeigl** [comment]
I had some time looking into the compiler to find out, what is actually going on here. Also posted some details over at ng-packagr/ng-packagr#1087, but I think my findings make better use in the angular repo here.

@Ventzy was on the right track already.

The problem is actually related to yarn/npm link. 
* Build Library A
* yarn link Library A from dist folder, because Library B depends on it
* Build Library B (which depends on A)

Internally the following happens:
* While Library B is built, it refers to A (node_modules/library-a)
* While identifing the internal dependencies of A, a recursive process searches for everything relevant
* This process falls back into the real folder (.../dist/...) and not the symlinked folder
* However: The Code which loads the Metadata for everything does NOT
* => End result is, that there are Types (it's failing on Pipes in my case) for which no meta data could be found and the removeDuplicates call fails, because there are `null` objects in the list of pipes ...

Ultimately this is something the compiler team has to fix. Without further testing, I would expect that this only happens on Windows and the way symlinks work on this OS.

One important point:
* This started happening for us after the upgrade von Angular 6 to 7
* We have this project structure since Angular 2 and could build this
* So there probably was some change in how file paths are resolved in dependencies

For possible solutions / workarounds I could think of:
* As @Ventzy mentioned already, do not use yarn/npm link and instead copy everything into the node_modules (i.e. build Library A, copy into node_modules)
* No other ideas for now :-(

**Comment by thefliik** [comment]
@pfeigl that's some excellent detective work

**Comment by alxhub** [comment]
Nice job debugging this, @pfeigl.

The good news is that Angular Ivy completely removes `.metadata.json` (and greatly simplifies path handling in the compiler in general), so this problem should be fixed completely with the Ivy compiler.

**Comment by Rambou** [comment]
Any idea for the moment expect the one that @pfeigl proposed? Did anyone understood the problem that npm/yarn link is causing?
In my case was `npm install <local-path-to-libary>` but the outcome was still the same.

**Comment by woppa684** [comment]
Not sure whether it is relevant but I don't use yarn/npm link and I still get this error. I only get it when I use
```json
skipTemplateCodegen: false
```
If I skip the template code generation it builds fine.

**Comment by Rambou** [comment]
@woppa684 same case here.

**Comment by harishrathor** [comment]
> We've found the solution working for our project. Removing the components from the `exports` array in `library-b`'s module and keeping them exported only in `public_api.ts`.

Worked for me too.

**Comment by electric-ladyland** [comment]
Is this planned to be fixed for non-Ivy? Also does anyone happen to know before I check if different CLI versions don't have this issue? Our team depends heavily on linking for cross project development.

**Comment by macotonio** [comment]
The previous solution of removing exports, allows the application to compile, however, does not allow the use of components in other libraries.

The problem occurs because in the package.json the library is accessed through the dist ("@xdf/commons": "file:dist/xdf-commons" --> here are the latest changes), however, the changes in the library that contains the components that are exported have not yet been published (they are not in node-modules), this difference does not allow compilation.

The solution is:
1. Include exports, compile and publish.
2. Install that version with: npm -i
3. If you wish you can change the package.json again to use from the dist

**Comment by panagiotis-nicolaou** [comment]
Thus - so far - and based on @pfeigl answer (thanks @pfeigl), what we do to automatically build a library (i.e. iri-loader), that is a dependency to another library, is to use the following alias in our package.json:

`"iri-loader:build": "ng build iri-loader && npm i dist/iri-loader --save && rmdir node_modules\\@iri\\loader && xcopy /E /I dist\\iri-loader node_modules\\@iri\\loader"`

**Comment by bitflower** [comment]
Thanks @panagiotis-nicolaou, this works for us too.

**Comment by SantiagoIlli** [comment]
Hello, in my case I had the same error and this solutions did not worked for me.

I was working on a windows pc, and the error appear when i tried to ng build --prod or ng serve --prod:

TypeError: Cannot read property 'type' of null

But this didn't happen when i run ng serve.

I tried to serve my project on ubuntu, and then the error appear, i was referencing a file out of my project and that was causing the error.

If you are looking for something like that check the long paths, in my case:

import {MyClass} from '../../../../../../../other-folder/src/app/models/types';

Hope this helps someone!

**Comment by alxhub** [comment]
> Is this planned to be fixed for non-Ivy? Also does anyone happen to know before I check if different CLI versions don't have this issue? Our team depends heavily on linking for cross project development.

No, it won't be.

In Ivy, the compiler will yell at you if you try to export a module (from an Angular Package Format library) that isn't exported from the entrypoint.
