### ISSUE TITLE
compiler.js included in bundle after update to 7.0.0-beta.2

### ISSUE THREAD

**Issue by jponeill** [angular/angular#25645]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

1) ng new "foo" using  @angular/cli: 6.2.0-rc.0 
2) change all @angular versions to "7.0.0-beta.1"
3) delete package-lock.json and node_modules
4) npm i
5) ng build --prod --stats-json
6) webpack-bundle-analyzer dist/foo/stats.json 

... no compiler.js shown in analyzer

7) change all @angular version to "7.0.0-beta.2"
8) delete package-lock.json and node_modules
9) npm i
10) ng build --prod --stats-json
11) webpack-bundle-analyzer dist/foo/stats.json 

... compiler.js shown in analyzer (and code is included when look at js bundles)

## Expected behavior

don't expect compiler.js code to be there

## Environment
"ng new proj" using @angular/cli: 6.2.0-rc.0 
no other changes except @angular version updates described above.

<pre><code>
Angular version: 7.0.0-beta.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by naveedahmed1** [comment]
Could that be the reason when I now run `uglifyjs` for server bundle (after updating Angular version).

`uglifyjs main.js --output main1.js`

I receive below error:

```
Parse error at main.js:144560,23
module.exports = class NodeList extends Array {
                       ^
ERROR: Unexpected token: name (NodeList)
    at JS_Parse_Error.get (eval at <anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\uglify-js\tools\node.js:20:1), <anonymous>:71:23)
    at fatal (C:\Users\User\AppData\Roaming\npm\node_modules\uglify-js\bin\uglifyjs:291:53)
    at run (C:\Users\User\AppData\Roaming\npm\node_modules\uglify-js\bin\uglifyjs:235:9)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\uglify-js\bin\uglifyjs:160:5)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
```

I generate server bundles using below command:

`ng run MyProject:server:production`

Below are the configuration for my server project in `angular.json` file:

```
"server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist-server",
            "main": "src/main.server.ts",
            "tsConfig": "src/tsconfig.server.json"
          },
          "configurations": {
            "production": {
              "optimization": false,
              "outputHashing": "media",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "bundleDependencies": "all",

              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
        }
```

**Comment by alxhub** [comment]
I've traced this to 14ac7ad6, specifically to https://github.com/angular/angular/commit/14ac7ad6b4118d68644d3b04b93f41d5cc8af904#diff-7f9dee5940dc64ac33bcc00e804d80b2R124.

These `render3/jit` symbols have compiler dependencies and were previously only included in `core` via the `ivy_switch`. The impact on bundle size seems to be negligible, as they're not referenced and thus the tree-shaker can remove them along with the majority of `@angular/compiler`.

`webpack-bundle-analyzer` here seems to be reporting on relative sizes prior to tree-shaking, which gives a misleading picture of what's actually in the bundle.

**Comment by jponeill** [comment]
Thanks for tracking the problem down, Alex. I noticed this first in my real world app and there the difference in the main bundle size between 7.0.0-beta.1 and 7.0.0-beta.2(or 3) is ~200K. Maybe other dependencies crept in as well?

**Comment by naveedahmed1** [comment]
@alxhub can you please also share your thoughts on my comment?

**Comment by jponeill** [comment]
Just FYI since it looks like we're seeing size impact differences:  I compared my app using 7.0.0-beta.4 and 7.0.0-beta.1 (no other changes). 7.0.0-beta.4 is 1.31MB on disk and 7.0.0.beta.1 is 1.09 MB.

**Comment by alxhub** [comment]
Good morning @jponeill,

Thank you for the data point. Can you provide details on how you're building the main bundle? Is it Angular CLI? `--prod`? If so, can you paste the output of `ng version` and the version of Uglify you have installed?

Thanks!

**Comment by jponeill** [comment]
I'm using Angular CLI --prod, Alex. 

I've pasted in ng version info for 7.0.0-beta.1 and 7.0.0-beta.4, below, and the uglify version at the bottom.

**  7.0.0-beta.1 
Angular CLI: 6.2.0-rc.0
Node: 10.7.0
OS: darwin x64
Angular: 7.0.0-beta.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.0-rc.0
@angular-devkit/build-angular     0.8.0-rc.0
@angular-devkit/build-optimizer   0.8.0-rc.0
@angular-devkit/build-webpack     0.8.0-rc.0
@angular-devkit/core              0.8.0-rc.0
@angular-devkit/schematics        0.8.0-rc.0
@angular/cdk                      6.4.6
@angular/cli                      6.2.0-rc.0
@angular/material                 6.4.6
@ngtools/webpack                  6.2.0-rc.0
@schematics/angular               0.8.0-rc.0
@schematics/update                0.8.0-rc.0
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.17.1


Angular CLI: 6.2.0-rc.0
Node: 10.7.0
OS: darwin x64
Angular: 7.0.0-beta.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.0-rc.0
@angular-devkit/build-angular     0.8.0-rc.0
@angular-devkit/build-optimizer   0.8.0-rc.0
@angular-devkit/build-webpack     0.8.0-rc.0
@angular-devkit/core              0.8.0-rc.0
@angular-devkit/schematics        0.8.0-rc.0
@angular/cdk                      6.4.6
@angular/cli                      6.2.0-rc.0
@angular/material                 6.4.6
@ngtools/webpack                  6.2.0-rc.0
@schematics/angular               0.8.0-rc.0
@schematics/update                0.8.0-rc.0
rxjs                              6.3.0
typescript                        3.0.3
webpack                           4.17.1

npm view uglify-es

uglify-es@3.3.9 | BSD-2-Clause | deps: 2 | versions: 50
JavaScript parser, mangler/compressor and beautifier toolkit for ES6+
https://github.com/mishoo/UglifyJS2/tree/harmony

keywords: uglify, uglify-es, uglify-js, minify, minifier, javascript, ecmascript, es5, es6, es7, es8, es2015, es2016, es2017, async, await

bin: uglifyjs

dist
.tarball: https://registry.npmjs.org/uglify-es/-/uglify-es-3.3.9.tgz
.shasum: 0c1c4f0700bed8dbc124cdb304d2592ca203e677
.integrity: sha512-r+MU0rfv4L/0eeW3xZrd16t4NZfK8Ld4SWVglYBb7ez5uXFWHuVRs6xCTrf1yirs9a4j4Y27nn7SRfO6v67XsQ==

dependencies:
commander: ~2.13.0 source-map: ~0.6.1 

maintainers:
- alexlamsl <alexlamsl@gmail.com>

dist-tags:
latest: 3.3.9  

published 7 months ago by alexlamsl <alexlamsl@gmail.com>

**Comment by mhevery** [comment]
I think this may be a fix (or at least partial) https://github.com/angular/angular/pull/25531 I will try to reproduce it and see how much it improves things.

**Comment by naveedahmed1** [comment]
@mhevery can you please comment on this as well https://github.com/angular/angular/issues/25645#issuecomment-415811263

**Comment by jponeill** [comment]
Just an FYI - I updated to Angular: 7.0.0-beta.5 and compiler.js is still in the main bundle and the on disk size for my app is ~1.3MB vs. 1.09MB in beta.1.

**Comment by jponeill** [comment]
Also, if I do ng build --prod using 7.0.0-beta.5 and after deleting the contents of node_module's' esm2015/compiler.js, the on disk size of the main bundle is ~1.11mb (vs ~1.3 mb w/out deleting). So it looks like in my case, a lot of the compiler is being pulled in and not uglified out starting w/ 7.0.0-beta.2.

**Comment by jponeill** [comment]
Hi @alxhub  - was wondering if you were able to reproduce the file size difference using WebPack (instead of using the closure compiler)? If it were 8K, it wouldn't matter too much to me but ~200K is a pretty big bump.
Thanks,
Jim

**Comment by naveedahmed1** [comment]
Any update on this?

**Comment by jponeill** [comment]
I just tried 7.0.0-rc.1 and the main (WebPack) bundle size is still ~200K larger than building w/ 7.0.0-beta.1. Maybe there's a workaround of some sort that I could do? I don't think I'd be able to move to 7.0 w/ this increase.

**Comment by theodorejb** [comment]
I updated from 6.1.6 to 7.0.0-rc.0 and my minified bundle size increased by 541 KB (from 2771 KB to 3312 KB)! I'm not using Angular CLI - just the `ngc` command and `webpack --mode production`. Here's a screenshot after running Webpack Bundle Analyzer:
![bundle size](https://user-images.githubusercontent.com/3053271/46483473-5abecc00-c7bd-11e8-9b0d-b7957e83d8a2.PNG)

**Comment by IgorMinar** [comment]
we can't reproduce this any more. I think it was fixed in rc.1 can you please verify? thanks

**Comment by jponeill** [comment]
It's still an issue for me w/ rc.1 (after deleting package-lock.json and node_modules and reinstalling). Let me know if there's anything I can do to help isolate the problem.

**Comment by IgorMinar** [comment]
if you are using pure webpack without anything else, then your build will be much bigger than that coming from cli. having said that, the compiler files should not appear in the bundle.

can you create a minimal reproduction as a clean github repo?

**Comment by michael42** [comment]
I did also see my application bundle (with a custom webpack build) growing ~478 KiB (pre compression) when switching from Angular 6.1 to 7.0.0-rc.1 while a freshly created `ng build --prod --aot --build-optimizer` is just 208 KiB.

I tried comparing how the cli uses `@angular-devkit/build-optimizer/webpack-loader` and `@ngtools/webpack`, found that I had the loader for the build analyzer wrong.

I had (simplified)
```
{test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/, loader: "@angular-devkit/build-optimizer/webpack-loader"}
```
while the correct configuration (as per [@angular-devkit/build-optimizer/README.md](https://github.com/angular/angular-cli/blob/87db956cab0b722a7556fe96f50ea777fb9787f7/packages/angular_devkit/build_optimizer/README.md#webpack-loader-usage)) is to apply to all .js files:
```
{test: /\.js$/, loader: "@angular-devkit/build-optimizer/webpack-loader"}
```

@jponeill Maybe that's your issue, too?

**Comment by emilio-martinez** [comment]
I'm also getting a bundle increase, showing the compiler in the final bundle for Angular 7.0.0-rc.1. Not using the CLI for this particular project, but the size bump is very clearly tied to the compiler.
 
<img width="975" alt="screenshot 2018-10-17 00 43 41" src="https://user-images.githubusercontent.com/9163179/47070382-e82ef280-d1a5-11e8-8a56-cdf53adafc9b.png">

**Comment by jponeill** [comment]
This is not fixed for me in Angular 7.0. My bundle size remains ~1.32mb vs ~1.10MB in 7.0.0-beta.1. My version info is below:

**Comment by jponeill** [comment]
Also, compiler.js still isn't being "tree shaken" out for me in a clean ng cli project in version Angular 7.0 but is if I revert the project to 7.0.0-beta.1.

**Comment by emilio-martinez** [comment]
@mhevery This hasn't changed for me on 7.0.0. See the output of the webpack reasons for `@angular/compiler`: https://gist.github.com/emilio-martinez/7656a290f39fe636188e868068eef132.

> If it is not tree shaking for you and you are not using CLI than you probably do not have the code optimizer set up properly which prevents the uglify to do proper tree shaking

Note that all the module reasons are passed by the `@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js`. I'm getting the same result using Uglify or Terser—which the CLI recently moved to as well.

**Comment by hakimio** [comment]
@mhevery it is NOT fixed in Angular 7.0 stable and Angular CLI 7.0.2. It's still adding extra ~200KB to the bundle. Please reopen the issue until it's actually fixed.

**Comment by jponeill** [comment]
Looks like this fix hasn't been released, yet? I'll try again in the next patch.

**Comment by alexzuza** [comment]
@jponeill @ColinCCAL @100cm @hakimio @theodorejb 
I can't reproduce it on latest cli.
Can you show us simple github repo with this issue?

**Comment by 100cm** [comment]
@alexzuza the latest version is  7.0.2   or RC version?

**Comment by alexzuza** [comment]
@100cm I meant Angular CLI 7.0.2 with @angular/*@7.0.0 dependencies

**Comment by 100cm** [comment]
@alexzuza  i really confused for this, two projects, same dependence, one included but other not , can't reproduce the problem projects (My compony's).

**Comment by jponeill** [comment]
Here's a repo created via "ng new foo" w/ no other changes. [https://github.com/jponeill/compilerjs.git](url). "ng build --prod --stats-json" then "webpack-bundle-analyzer dist/foo/stats.json" shows compiler.js in bundle. Version info is below: 

Angular CLI: 7.0.2
Node: 10.7.0
OS: darwin x64
Angular: 7.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.2
@angular-devkit/build-angular     0.10.2
@angular-devkit/build-optimizer   0.10.2
@angular-devkit/build-webpack     0.10.2
@angular-devkit/core              7.0.2
@angular-devkit/schematics        7.0.2
@angular/cli                      7.0.2
@ngtools/webpack                  7.0.2
@schematics/angular               7.0.2
@schematics/update                0.10.2
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1

**Comment by alexzuza** [comment]
What if you would use [source-map-explorer](https://www.npmjs.com/package/source-map-explorer) instead of webpack-bundle-analyzer?

Here's an instruction
https://github.com/angular/angular-cli/issues/12646#issuecomment-431780437

On my machine it looks like this
![bundle](https://user-images.githubusercontent.com/4223314/47362725-22d4e580-d6e6-11e8-99d9-ff148d313d95.png)

Also we can check for compiler code in `main.js` manually. I couldn't find any compiler related stuff

Only one strange thing I noticed: source-map-explorer gives me the error:

Unable to map 147 / 172740 bytes (0.09%)
And I can see sourcemap code in chrome
![bundle2](https://user-images.githubusercontent.com/4223314/47363757-a1cb1d80-d6e8-11e8-8f43-f86d6a37dd14.png)

**Comment by jponeill** [comment]
compiler.js isn't showing up in source-map-explorer for me either in the repo project, @alexzuza . It is in my real project though. Let me see if I can narrow it down further...

**Comment by jponeill** [comment]
Thanks @filipesilva. This is really helpful.

**Comment by emilio-martinez** [comment]
Perhaps helpful for people with a custom config:

What fixed this for me was a comment by @filipesilva on the thread he mentioned above where the [Webpack `node` builtins](https://webpack.js.org/configuration/node/) need to be set to `false` to properly treeshake.

Perhaps this is worth documenting somewhere since the Webpack default is not `false`?

**Comment by 100cm** [comment]
@jponeill @ColinCCAL @alexzuza 

hey guys, i have fixed this temporary by using custom webpack config

add the dependency :

`    "@angular-builders/custom-webpack": "2.4.1",`

then config the angular.json

![image](https://user-images.githubusercontent.com/12691638/47403245-54e45700-d77b-11e8-995f-4b6d97d38ee2.png)

edit the extra-webpack.config.js

```
'use strict';
module.exports = {
  externals: {
    "@angular/compiler": JSON.stringify("@angular/compiler")
  },
};
```

then i solve my problem 

[more info](https://github.com/angular/angular-cli/issues/12646#issuecomment-432388624)
