### ISSUE TITLE
Only initialized variables and constants can be referenced in decorators

### ISSUE THREAD

**Issue by nhhockeyplayer** [angular/angular#25684]
I am receiving this now with latest angular 6+

```
ERROR in src\server\model\app\App.ts(4,2): Error during template compile of 'App'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler in 'pre'
    'pre' references 'pre'
      'pre' is not initialized at typegoose\lib\hooks.ts(3,22).

```

any help is greatly appreciated cannot build prod

ng build --aot --prod

```
Angular CLI: 6.1.1
Node: 8.11.2
OS: win32 x64
Angular: 6.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package Version
@angular-devkit/architect 0.7.1
@angular-devkit/build-angular 0.7.1
@angular-devkit/build-optimizer 0.7.1
@angular-devkit/build-webpack 0.7.1
@angular-devkit/core 0.7.1
@angular-devkit/schematics 0.7.1
@angular/cdk 6.4.1
@angular/cli 6.1.1
@angular/flex-layout 6.0.0-beta.16
@angular/material 6.4.1
@ngtools/webpack 6.1.1
@schematics/angular 0.7.1
@schematics/update 0.7.1
rxjs 6.2.2
typescript 2.9.2
webpack 4.9.2
```

This is the applied usage of the decorator
```
import {pre, prop, Typegoose} from 'typegoose'
import * as mongoose from 'mongoose'

@pre<App>('save', (next) => {
    if (!this.createdAt) {
        this.createdAt = this.updatedAt = new Date()
    }
    next()
})
export class App extends Typegoose {

    @prop()
    _id?: mongoose.Types.ObjectId

    @prop({required: true})
    name: string


    @prop()
    owner?: mongoose.Types.ObjectId

    @prop()
    createdAt?: Date = new Date()
    @prop()
    updatedAt?: Date = new Date()
}

export const model = new App().getModelForClass(App, {schemaOptions: {collection: 'app'}})



```
This is the implementation of the decorator
```
import { MongooseDocument } from 'mongoose';

import { hooks as hooksData } from './data';

type DocumentMethod = 'init' | 'validate' | 'save' | 'remove';
type QueryMethod = 'count' | 'find' | 'findOne' | 'findOneAndRemove' | 'findOneAndUpdate' | 'update';
type ModelMethod = 'insertMany';

type ClassDecorator = (constructor: any) => void;
type HookNextFn = (err?: Error) => void;

type PreDoneFn = () => void;

type TypegooseDoc<T> = T & MongooseDocument;

type DocumentPreSerialFn<T> = (this: TypegooseDoc<T>, next: HookNextFn) => void;
type DocumentPreParallelFn<T> = (this: TypegooseDoc<T>, next: HookNextFn, done: PreDoneFn) => void;

type SimplePreSerialFn<T> = (next: HookNextFn) => void;
type SimplePreParallelFn<T> = (next: HookNextFn, done: PreDoneFn) => void;

type DocumentPostFn<T> = (this: TypegooseDoc<T>, doc: TypegooseDoc<T>, next?: HookNextFn) => void;
type ModelPostFn<T> = (result: any, next?: HookNextFn) => void;

type PostNumberResponse<T> = (result: number, next?: HookNextFn) => void;
type PostSingleResponse<T> = (result: TypegooseDoc<T>, next?: HookNextFn) => void;
type PostMultipleResponse<T> = (result: TypegooseDoc<T>[], next?: HookNextFn) => void;

type PostNumberWithError<T> = (error: Error, result: number, next: HookNextFn) => void;
type PostSingleWithError<T> = (error: Error, result: TypegooseDoc<T>, next: HookNextFn) => void;
type PostMultipleWithError<T> = (error: Error, result: TypegooseDoc<T>[], net: HookNextFn) => void;

type NumberMethod = 'count';
type SingleMethod = 'findOne' | 'findOneAndRemove' | 'findOneAndUpdate' | DocumentMethod;
type MultipleMethod = 'find' | 'update';

interface Hooks {
  pre<T>(method: DocumentMethod, fn: DocumentPreSerialFn<T>): ClassDecorator;
  pre<T>(method: DocumentMethod, parallel: boolean, fn: DocumentPreParallelFn<T>): ClassDecorator;

  pre<T>(method: QueryMethod | ModelMethod, fn: SimplePreSerialFn<T>): ClassDecorator;
  pre<T>(
    method: QueryMethod | ModelMethod,
    parallel: boolean,
    fn: SimplePreParallelFn<T>): ClassDecorator;

  // I had to disable linter to allow this. I only got proper code completion separating the functions
  post<T>(method: NumberMethod, fn: PostNumberResponse<T>): ClassDecorator;
  // tslint:disable-next-line:unified-signatures
  post<T>(method: NumberMethod, fn: PostNumberWithError<T>): ClassDecorator;

  post<T>(method: SingleMethod, fn: PostSingleResponse<T>): ClassDecorator;
  // tslint:disable-next-line:unified-signatures
  post<T>(method: SingleMethod, fn: PostSingleWithError<T>): ClassDecorator;

  post<T>(method: MultipleMethod, fn: PostMultipleResponse<T>): ClassDecorator;
  // tslint:disable-next-line:unified-signatures
  post<T>(method: MultipleMethod, fn: PostMultipleWithError<T>): ClassDecorator;

  post<T>(method: ModelMethod, fn: ModelPostFn<T> | PostMultipleResponse<T>): ClassDecorator;
}

const hooks: Hooks = {
  pre(...args) {
    return (constructor: any) => {
      addToHooks(constructor.name, 'pre', args);
    };
  },
  post(...args) {
    return (constructor: any) => {
      addToHooks(constructor.name, 'post', args);
    };
  },
};

const addToHooks = (name, hookType: 'pre' | 'post', args) => {
  if (!hooksData[name]) {
    hooksData[name] = { pre: [], post: [] };
  }
  hooksData[name][hookType].push(args);
};

export const pre = hooks.pre;
export const post = hooks.post;

```
Thank you for any feedback on how to resolve the constants for pre seem to be initialized

references
https://github.com/angular/angular/issues/14323

https://github.com/szokodiakos/typegoose/issues/174

**Comment by mhevery** [comment]
That is because they are resolved statically at compiled time, hence they need to be static/constant.

**Comment by edwinquaihoi** [comment]
I just upgraded from NG5 to NG7 and am having a similar issue with the ng-animate lib. This worked in NG5 what has changed?

**Comment by nhhockeyplayer** [comment]
Its still not fixed... obviously

the true field test is with typegoose as I provided

nobody brave enough to fix that

**Comment by nhhockeyplayer** [comment]
edwin, have you found a solution?
