### ISSUE TITLE
order loading bundle of elements and change detection issue

### ISSUE THREAD

**Issue by valentin78** [angular/angular#27002]
I made bundle for my custom ng elements
and if this bundle load, as ex in head, before elements load in DOM, in this case change detection not work
I made demo
https://codepen.io/valentin78/project/editor/AEyxdq
there bundle.js loaded before my element and title not updating
if you try move bundle to bottom line 11 -> 15 then all work fine

**Comment by meriturva** [comment]
you could use `async` script tag attribute.
See:

https://codepen.io/meriturva/project/editor/APrYeJ

**Comment by valentin78** [comment]
> you could use `async` script tag attribute.
> See:
> 
> https://codepen.io/meriturva/project/editor/APrYeJ

it resolve issue, because in fact script will load after DOM initialization, but if I will create elements dynamically in DOM issue persist

**Comment by AndrewKushnir** [comment]
It looks like the issue is resolved, so I close this ticket.

**Comment by valentin78** [comment]
you see this issue demo?
https://codepen.io/valentin78/project/editor/AEyxdq
issue NOT resolved
