### ISSUE TITLE
Service Worker Push requestSubscription error on SAFARI 12

### ISSUE THREAD

**Issue by robinComa** [angular/angular#27889]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/service-worker

### Is this a regression?
I don't know

### Description
The swPush requestSubscription break on SAFARI browser

## 🔬 Minimal Reproduction
```javascript
import { Optional, Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { SwPush } from '@angular/service-worker';
import { Observable } from 'rxjs';

import { environment } from '../../environments/environment';
import { PushNotification } from './notification';

@Injectable({
  providedIn: 'root'
})
export class NotificationService {

  constructor(
    private http: HttpClient,
    @Optional() private swPush: SwPush
  ) { }

  activate(): Observable<void> {
    return Observable.create((observer) => {
      this.swPush.requestSubscription({
        serverPublicKey: environment.webPush.publicKey
      }).then((subscription: PushSubscription) => {
        this.http.post(`${environment.serverUrl}/subscription`, subscription).subscribe(() => {
          observer.next();
          observer.complete();
        }, (err) => {
          observer.error(err);
        });
      }).catch((err) => {
        console.log(err): // => Here an error occurs on Safari : TypeError: undefined is not an object (evaluating 't.subscribe')
        observer.error(err);
      });
    });
  }

  sendNotification(notification: PushNotification): Observable<void> {
    return this.http.post<void>(`${environment.serverUrl}/notification`, notification);
  }

  messages(): Observable<PushNotification> {
    return <Observable<PushNotification>>this.swPush.messages;
  }
}

```

## 🔥 Exception or Error
<pre><code>
TypeError: undefined is not an object (evaluating 't.subscribe')
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.1.4
Node: 8.11.3
OS: darwin x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@angular/cdk                      7.2.0
@angular/material                 7.2.0
@angular/pwa                      0.11.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
</code></pre>

**Anything else relevant?**
This issue is on Safari browser Version 12.0.2 (13606.3.4.1.4)

**Comment by gkalpak** [comment]
This is similar to #25781. It seems that on some browsers that otherwise support ServiceWorkers, `ServiceWorkerRegistration#pushManager` can be (under certain circumstances?) undefined.

As a work-around, you could do one of the following:

- Handle the error on `this.swPush.subscription`.
- Check if `pushManager` is supported before trying to subscribe (e.g. `'PushManager' in window` or `'pushManager' in ServiceWorkerRegistration.prototype` or `(await navigator.serviceWorker.getRegistration()).pushManager`).

##
Interestingly, MDn gives contradicting info on browser support, claiming that `window.PushManager` is [not supported on Safari][1] but `ServiceWorkerRegistration#pushManager` is [supported on Safari][2] 😕 

In any case, I think it makes sense to handle this more gracefully in `@angular/service-worker` (e.g. throw a more descriptive error if `pushManager` is not defined). Leaving this open as a feature request for that.

[1]: https://developer.mozilla.org/en-US/docs/Web/API/PushManager#Browser_compatibility
[2]: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/pushManager#Browser_compatibility

**Comment by robinComa** [comment]
Hello @gkalpak thanks for quick reply !

This workaround is to avoid the error on console, exact ? You mean that @ angular/service-worker cannot be used with the latest version of Safari? (this is the only way to do a PWA on IOS) 😞

**Comment by robinComa** [comment]
Another thing : @angular/service-worker is not on the ng version result list

**Comment by gkalpak** [comment]
> You mean that @ angular/service-worker cannot be used with the latest version of Safari?

No, you can use `@angular/service-worker`, but if Safari does not (always?) support `PushManager`, then you can't use Push notifications on Safari. (You can still use the rest of the SW features.

> Another thing : @angular/service-worker is not on the ng version result list

This sounds like an issue for https://github.com/angular/angular-cli (although it may be intentional).

**Comment by robinComa** [comment]
Ok I understand for the Safari case, do you know if Chrome on IOS will works for push notification in the future ?

@angular/service-worker doesn't implement [this kind of notification](https://pushalert.co/documentation/creating-safari-web-push-certificate) ? 

I create an [issue ](https://github.com/angular/angular-cli/issues/13359)on cli for the ng version "issue"

**Comment by gkalpak** [comment]
> do you know if Chrome on IOS will works for push notification in the future ?

I am pretty confident that both Chrome and Safari will fully support push notifications (at some point).

> @angular/service-worker doesn't implement this kind of notification ?

No idea what this is (or even if it is different than regular notifications - the content seems outdated too).

**Comment by robinComa** [comment]
Ok thanks for informations about support of push notification on IOS Chrome and Safari :-)
This is the official page of Safari push notification (the last link was a demo that's work when you open the site with safari) : 

- [https://developer.apple.com/notifications/safari-push-notifications](https://developer.apple.com/notifications/safari-push-notifications/)
- [http://devstreaming.apple.com/videos/wwdc/2013/614xax5x602jmihlq4c4edtrl/614/614.pdf?dl=1](http://devstreaming.apple.com/videos/wwdc/2013/614xax5x602jmihlq4c4edtrl/614/614.pdf?dl=1)

**Comment by gkalpak** [comment]
I wonder if this iss till an issue (it's been ~1.5year - maybe this has been fixed on latest Safari).

**Comment by jpsthome** [comment]
Actually no, Safari still isn't supporting Push API. They have their own Push Notification API and it seems that Angular doesn't support it.

**Comment by zedL** [comment]
I also stated to use push notifications with Angular 10. "undefined is not an object (evaluating 't.getSubscription')" exeption is still there.

**Comment by zedL** [comment]
![image](https://user-images.githubusercontent.com/12039628/98437525-1d873f80-20e3-11eb-8a95-d7ffca76254d.png)

**Comment by yansokalau** [comment]
any update on this? does anyone have workarounds?

**Comment by cghislai** [comment]
@yansokalau There are workarounds suggested above, but as far as I can tell, the bug is in the SwPush constructor, and injecting it in a service constructor in your app will trigger it. However, you an use angular Injector, and obtain an instance after checking it is supported by the browser. Something like

```
constructor(private injector: Injector) {
  if (this.isSwPushSupported()) {
    this.swPush = this.injector.get(SwPush, undefined);
  }
}
```

**Comment by genevpd** [comment]
It would be great to have this fixed, especially now when Safari iOS 16 supports push notifications.

**Comment by hernays** [comment]
Hello my friends , not solutions in the topic?

Hola amigos alguna solucion para Este tema me funciona Bien en todos Las plataformas Menos en safari - iphone

**Comment by twmobius** [comment]
Are there any updates to this? It appears that this issue still exists on angular 16, which comes up on mobile Safari versions 16.6 and 17.2

**Comment by JeanMeche** [comment]
With https://github.com/angular/angular/pull/63364 we've announced that the service-worker package in now in maintenance mode and will not receive feature PRs and feature requests.

The message is also visible here: https://angular.dev/ecosystem/service-workers
