### ISSUE TITLE
Missing documentation for viewencapsulation.native

### ISSUE THREAD

**Issue by o-t-w** [angular/angular#28135]
### Description

The documentation does not explain what viewencapsulation.native is, or how it differs from viewencapsulation.ShadowDom

<img width="677" alt="screen shot 2019-01-14 at 19 00 04" src="https://user-images.githubusercontent.com/29547922/51134185-bf62db80-182e-11e9-83c3-1c4850dcd93d.png">

### What's the affected URL?**
https://angular.io/api/core/ViewEncapsulation

If it is deprecated or no longer recommended, I suggest that is added to the documentation.

**Comment by manklu** [comment]
ViewEncapsulation.Native is Shadow DOM v0 and soon there is no browser left that supports it.

**Comment by o-t-w** [comment]
If you google the topic most of the top-ranking google-hits are blog posts that show `ViewEncapsulation.Native`, so it is worth making it _very clear_ in the documentation that it is deprecated. Those older resources will hang around for a long time.

**Comment by trotyl** [comment]
Seems to be a docs-infra issue, in the jsdoc it's indeed marked as deprecated with explanation:

https://github.com/angular/angular/blob/f983e99fb245532b41125672447a7d6756e9da06/packages/core/src/metadata/view.ts#L31-L39

**Comment by ChristianUlbrich** [comment]
The thing is, _currently_ `ViewEncapsulation.Native` does not differ from `ViewEncapsulation.ShadowDom`, see [platform-browser/src/dom/dom_renderer.ts](https://github.com/angular/angular/blob/5c5fe34241947e8b583c790d4b7354180171e721/packages/platform-browser/src/dom/dom_renderer.ts#L85) on _platform-browser_.

So your are right in a way, the docs are wrong, as of now `ViewEncapsulation.Native` defaults to `ViewEncapsulation.ShadowDom`.

**Comment by manklu** [comment]
@ChristianUlbrich If you look a bit deeper you will see that there is a difference between the two.

See [ShadowDomRenderer](https://github.com/angular/angular/blob/5c5fe34241947e8b583c790d4b7354180171e721/packages/platform-browser/src/dom/dom_renderer.ts#L262)

**Comment by ChristianUlbrich** [comment]
@manklu I should have read the fine print. You are right! Bad code practice, if you ask me. :)

**Comment by jenniferfell** [comment]
Thanks. Fixed by PR #26361, which has been released into master (next), and is pending to be released into stable (v7.2.x). That PR marks viewencapsulation.native as deprecated.

**Comment by brandonroberts** [comment]
Fixed via #26361

**Comment by TheNuttyMaker** [comment]
@brandonroberts @jenniferfell @o-t-w @trotyl 
Looks like this issue still exists. 
<img width="495" alt="view1" src="https://user-images.githubusercontent.com/1430449/58781619-0d1f8b00-85fa-11e9-94cb-aea7c31b65e6.png">
