### ISSUE TITLE
Repeated navigation attempts not possible when canDeactivate guard turns down initial navigation and urlUpdateStrategy set to "eager"

### ISSUE THREAD

**Issue by larrifax** [angular/angular#28561]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router

### Is this a regression?

Yes, the previous version in which this bug was not present was: 7.2.0

### Description
NB! I'm running with the Router's urlUpdateStrategy set to "eager". 

I have a modal outlet, in which the routes have a canDeactivate guard preventing the user from closing the modal when there is pending changes. Until version 7.2.1, the user would be able to attempt to close the modal as many times as they wanted, triggering the guard every time. In version 7.2.1 and onwards, the guard is triggered the first time, but not on subsequent navigation attempts.

As far as I can see, this unexpected behavior is due to https://github.com/angular/angular/commit/6ae7aee. It seems like the following change is a bit aggressive: https://github.com/angular/angular/blob/6ae7aee2c397f0454f1fe9395ca769ee2efd8198/packages/router/src/router.ts#L510

If you debug the above mentioned code in the reproduction, you'll see that the browserUrlTree is updated before the guard runs, and the changes aren't being undone when the guard denies navigation. This behavior will cause subsequent attempts to close the modal to stop at the following check: https://github.com/angular/angular/blob/6ae7aee2c397f0454f1fe9395ca769ee2efd8198/packages/router/src/router.ts#L466

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-issue-repro2-yq1jm2

## 🔥 Exception or Error
None

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**
Only happens when the Router's urlUpdateStrategy is set to "eager".

**Comment by jasonaden** [comment]
This should be fixed with a PR landing shortly: https://github.com/angular/angular/pull/30344

Please let me know if this fixes it, and close this issue if so.

**Comment by larrifax** [comment]
@jasonaden The bug is still present in `8.1.0-beta.0`, which seems to be the first release in which #30344 is included.

I've updated the repro to `8.1.0-beta.0` (https://stackblitz.com/edit/angular-issue-repro2-yq1jm2).

**Comment by FDIM** [comment]
I've just bumped into this issue - Looks like it is still present in 8.2.9 and based on changelog probably in 8.2.12 as well

**Comment by atscott** [comment]
Additional reproduction due to dueling `routerLink` navigations: https://stackblitz.com/edit/angular-ivy-db9ngv?file=src%2Fapp%2Fapp-routing.module.ts (`routerLink` is applied to both the wrapper and the inner anchor, causing duplicate navigation attempts)

**Comment by atscott** [comment]
This is happening because the Router fails to reset the `browserUrlTree` when a navigation is rejected. This is resolved in the (currently private option) `canceledNavigationResolution: 'computed'`. 

Demo: https://stackblitz.com/edit/angular-issue-repro2-qzg9nn?file=src%2Fapp%2Fapp.component.ts

**Comment by atscott** [comment]
Closing as resolved by `canceledNavigationResolution: 'computed'` which will be available in v13
