### ISSUE TITLE
RouterLink does not support state property (but RouterLinkWithHref does)

### ISSUE THREAD

**Issue by akonieczka** [angular/angular#28652]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular\router\esm2015\src\directives\router_link.js

### Description
RouterLink line 158 DOES NOT have the correct code. It should be...
    state: this.state

RouterLinkWithHref line 312 DOES have the correct code.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.2.1
Node: 10.13.0
OS: win32 x64
Angular: 7.2.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.12.1
@angular-devkit/build-angular      0.12.1
@angular-devkit/build-ng-packagr   0.12.1
@angular-devkit/build-optimizer    0.12.1
@angular-devkit/build-webpack      0.12.1
@angular-devkit/core               7.2.1
@angular-devkit/schematics         7.2.1
@angular/cdk                       7.2.1
@angular/cli                       7.2.1
@angular/flex-layout               7.0.0-beta.22
@angular/material                  7.2.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.2.1
@schematics/angular                7.2.1
@schematics/update                 0.12.1
ng-packagr                         4.4.5
rxjs                               6.3.3
typescript                         3.2.2
webpack                            4.23.1
</code></pre>

**Comment by alexzuza** [comment]
I guess it could be a part of this PR https://github.com/angular/angular/commit/73f6ed9be1a3452d71a8d7cee9958f0076cdf0bb#diff-b9011c6f458af8057fdbc6893151846c

@jasonaden can help here

**Comment by jasonaden** [comment]
Yes, thanks. This is coming soon... should be available in Version 8.

**Comment by jasonaden** [comment]
Related to #27198.

**Comment by jasonaden** [comment]
This is addressed now with #27198. Closing.

**Comment by DWS-paris** [comment]
Hello there, I din't find the way to get my routes params while I try to use it with RouterLinkWithHref in my header (I use the 7.1.0 version with the CLI). It's strange for cause I do it really often but now, no params appear if I'm not in the main component page ( under the router-outlet in a lazy load router ). Is there a way to get the param in the same way that 

```
this.router.snapshot.params['_id']
```

Regards, Julien

**Comment by zbream** [comment]
This is still an issue with latest, judging by [this Stackblitz](https://stackblitz.com/edit/angular-routerlink-state). Notice that clicking Button (`RouterLink`) does not pass state, but clicking Anchor (`RouterLinkWithHref`) does.

Was this actually addressed with #27198 ? In fact, [someone's brought up this issue in that PR](https://github.com/angular/angular/pull/27198#issuecomment-476368545).
