### ISSUE TITLE
Upgrade zone.js => WAS: Heavy CPU usage over time with Zone and requestAnimationFrame

### ISSUE THREAD

**Issue by justindujardin** [angular/angular#2912]
I have a "game" that manages its own time loop using requestAnimationFrame. I have ported it to angular2, and it works really well except that I experience pretty severely degraded performance over time.  When I capture CPU profiles Zone ends up replacing the idle time that was there when the page loaded.  

I'm not sure what to make of it, but it's very easy to reproduce--just open the page and take a profile, then wait a minute and take another profile.

Example: http://justindujardin.github.io/angular2-rpg

**Comment by gdi2290** [comment]
you can run it outside of [zone.js](https://github.com/angular/angular/blob/c2efa23e94bf9ef3594bfa37aa30a0fc1dc2620a/modules/angular2/src/core/zone/ng_zone.ts#L130)
```
NgZone#runOutsideAngular(() => {
  requestAnimationFrame(() => console.log());
})
```

**Comment by justindujardin** [comment]
@gdi2290 that's an interesting idea, but it would exclude my app from change-detection then, yes?  

The reason I filed this issue is because my renderer was very stable in 1.x, but in 2.0 it degrades very quickly, which suggest to me some kind of resource leak in Zone.  I notice a large amount of time being spent on what appears to be patching get/set properties.

**Comment by justindujardin** [comment]
I dug into this a little bit, and it appears that the implementation that wraps requestAnimationFrame is flawed in zone.js.

I filed an issue over there: https://github.com/angular/zone.js/issues/143

**Comment by mhevery** [comment]
Should be assigned to @btford

**Comment by jomeier** [comment]
@mhevery @btford Any news on this one? I also try to use RequestAnimationFrame with Angular 2 and suffer from huge performance drops.

**Comment by mhevery** [comment]
I thought this was resolved. Can you verify?

**Comment by justindujardin** [comment]
My fix for patching requestAnimationFrame is still pending in the zone.js repo, so I don't think this is resolved.  I can compare against the latest release build of angular2 over the weekend to be sure.

**Comment by mhevery** [comment]
Ref: https://github.com/angular/zone.js/pull/147

**Comment by justindujardin** [comment]
@mhevery the zone.js issue has been merged and closed.

**Comment by mhevery** [comment]
Needs upgrade to latest zone.js to close this issue.

**Comment by btford** [comment]
I just released v0.5.4 with this fix, so this is no longer blocked.

**Comment by btford** [comment]
Pushing to presubmit now.

**Comment by labmorales** [comment]
This was realy fixed? My app uses Phaser.js (that uses requestAnimationFrame) inside a Angular2 component and the CPU usage is very high.

**Comment by harryjubb** [comment]
Same here, I am using NGL (https://github.com/arose/ngl) which calls `requestAnimationFrame` and have high CPU usage.

**Comment by mhevery** [comment]
Run your requestAnimationFrame outside angular zone by using
ngZone.runOutsideZone().
