### ISSUE TITLE
IVY doesn't working on Windows even in Angular 8.0.0-beta.7

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#29140]
# 🐞 bug report

### Affected Package
Angular IVY on Windows

### Description

I know there was a file path problem in Angular IVY compiler on Windows, but it seems that it has been fixed in Angular 8.0.0-beta.7 (https://github.com/angular/angular/pull/28752)

I tried compiling my project with latest version of Angular. ivy-ngcc postinstall script in package.json seem to be working fine. But it still doesn't recognizing the modules of the app and showing below error:

`ERROR in Unable to write a reference to MyDirective in D:/MyProject/src/app/shared/my-directive/my-directive.directive.ts from D:/MyProject/src/app/shared/my-directive/my-directive.module.ts`

I am following the instructions mentioned in https://next.angular.io/guide/ivy

I thought I could be missing something while updating my existing project. 

So I tried generating a new project using below command:

`ng new temp --enableIvy`

After generating the project I updated Angular to latest version Angular 8.0.0-beta.7.

When running npm install, I can see that after package installation ivy-ngcc postinstall script in package.json seem to be working fine.

But when I tried running the build command `ng build --prod`, it threw below error:

```
ERROR in Unable to write a reference to AppComponent in D:/MyProject/src/app/app.component.ts from D:/MyProject/src/app/app.module.ts
```

## 🔬 Minimal Reproduction

On windows machine generate a new project:

`ng new temp --enableIvy`

Update Angular to latest version i.e. Angular 8.0.0-beta.7

Run `npm install`

Then run `ng build --prod`

## 🔥 Exception or Error
<pre><code>
```
ERROR in Unable to write a reference to AppComponent in D:/MyProject/src/app/app.component.ts from D:/MyProject/src/app/app.module.ts
```

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.0-beta.4
Node: 8.11.4
OS: win32 x64
Angular: 8.0.0-beta.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.14.0-beta.4
@angular-devkit/build-angular     0.14.0-beta.4
@angular-devkit/build-optimizer   0.14.0-beta.4
@angular-devkit/build-webpack     0.14.0-beta.4
@angular-devkit/core              8.0.0-beta.4
@angular-devkit/schematics        8.0.0-beta.4
@angular/cli                      8.0.0-beta.4
@ngtools/webpack                  8.0.0-beta.4
@schematics/angular               8.0.0-beta.4
@schematics/update                0.14.0-beta.4
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.5
</code></pre>

**Comment by alexzuza** [comment]
`rootDirs` that come to the [LogicalFileSystem](https://github.com/angular/angular/blob/7060d9038b11a7c67cdce6b58464a935e9a340c5/packages/compiler-cli/src/ngtsc/path/src/logical.ts#L45-L60)  have absolute paths with leading slash, i.e.

`['/D/Angular/ivy-test/...']` where D is a name of driver.

due to the fact how Angular cli normalizes such paths https://github.com/angular/angular-cli/blob/fd5cb7a7f0c36e737fb3bb5e64fb2b66c2fef55d/packages/angular_devkit/core/src/virtual-fs/path.ts#L210

Because of that Windows version is broken here

https://github.com/angular/angular/blob/7060d9038b11a7c67cdce6b58464a935e9a340c5/packages/compiler-cli/src/ngtsc/path/src/logical.ts#L79-L83

```
physicalFile.startsWith(rootDir)

"D:/Angular/ivy-test/...".startsWith("/D/Angular/ivy/test...")
```

@alxhub please take a look

**Comment by alan-agius4** [comment]
Hi @alexzuza, that is indeed part of the problem, however another problem is that if you don't use the CLI the problem still persists because the moment `getCurrentDirectory` https://github.com/angular/angular/blob/master/packages/compiler-cli/src/ngtsc/util/src/typescript.ts#L79 is assumed to be posix separated which is not when using typescript compiler directly.

Will be landing a couple of PRs to fix these implementations soon.

**Comment by kukjevov** [comment]
As @alan-agius4  said it is not problem only with Angular CLI, here is webpack version and you can still see same problem 

https://github.com/kukjevov/ivy-code-size

**Comment by nitishk72** [comment]
This issue has been resolved. 
Check out this commit https://github.com/angular/angular-cli/commit/345ab4817ab6b5e76978d30110bd99e6efcfd126

**Comment by alan-agius4** [comment]
Hi @nitishk72, this issue is not yet resolved for non angular cli issues. Check this PR https://github.com/angular/angular/pull/29151

**Comment by pshurygin** [comment]
@alan-agius4 I am still having this issue with beta-8 with custom webpack config.

**Comment by sergey-morenets** [comment]
@pshurygin Tested today with "@angular-devkit/build-angular": "~0.800.0-beta.7". Issue didn't reproduce.

**Comment by dirkluijk** [comment]
I have the same issue on `"@angular-devkit/build-angular": "~0.800.0-beta.7"`. But not on Windows, I use mac OS.

```
ERROR in Unable to write a reference to AccordionDirective in /Users/dirkluijk/path/to/project/libs/widgets/src/lib/accordion/accordion.directive.ts from /Users/dirkluijk/path/to/project/libs/widgets/src/lib/accordion/accordion.module.ts
```
I think it has to do with Typescript paths and barrels.

My tsconfig.json:
```
{
  "paths": 
    "@p1/widgets": ["libs/widgets/src/index.ts"]
  }
}
```
I also tried `"@p1/widgets": ["libs/widgets/src/"]` and `"@p1/widgets": ["libs/widgets/src"]`. No success.

Should I report a new issue for this use case?
