### ISSUE TITLE
template type-checking in Ivy throws error for slice pipe

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#30086]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler-cli

### Is this a regression?

it appeared with ng `8.0.0-beta.14`

### Description

A component with an `ngFor` and  a `slice` like:
```html
<div *ngFor="let user of users | slice:0:1">{{ user.name }}</div>
```
with `users` declared as 

```typescript
interface UserModel { 
  name: string; 
};
//...
users: Array<UserModel> = [{ name: 'jane' }];
```

throws an error in Ivy when compiling with template type-check.

## 🔬 Minimal Reproduction

```
ng new ivy-slice --defaults --enable-ivy
```
Edit `tsconfig.app.json` to add:
```
"angularCompilerOptions": {
  "enableIvy": true,
  "fullTemplateTypeCheck": true
}
```
Update `app.component.html` and `app.component.ts` as above, and run `ng build --aot`

## 🔥 Exception or Error
<pre><code>
ERROR in __ng_typecheck__.ts(14,13): error TS2339: Property 'name' does not exist on type '{}'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0-beta.18
Node: 11.11.0
OS: darwin x64
Angular: 8.0.0-beta.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-beta.18
@angular-devkit/build-angular     0.800.0-beta.18
@angular-devkit/build-optimizer   0.800.0-beta.18
@angular-devkit/build-webpack     0.800.0-beta.18
@angular-devkit/core              8.0.0-beta.18
@angular-devkit/schematics        8.0.0-beta.18
@angular/cli                      8.0.0-beta.18
@ngtools/webpack                  8.0.0-beta.18
@schematics/angular               8.0.0-beta.18
@schematics/update                0.800.0-beta.18
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by cexbrayat** [comment]
Should be fixed by https://github.com/angular/angular/commit/79141f442404f60e620a767330948bebd4881915 which will be available in `8.0.0-rc.0`. I'll reopen if that's not the case.

**Comment by chacabuk** [comment]
Angular CLI: 8.0.1 Still broken.
Property 'name' does not exist on type '<T>'.

**slice_pipe.ts** line 65:
transform<T>(value: ReadonlyArray<T>, start: number, end?: number): Array<T>;

**Comment by cexbrayat** [comment]
@chacabuk SlicePipe is now more strictly typed and can catch errors with Ivy and fullTemplateTypeCheck that it couldn't previously. If you think this is a bug in Angular, and not an real error in your template, please open an issue with a reproduction, and we'll take a look.

**Comment by daileytj** [comment]
I'm having this same issue. Has anyone been able to find a workaround and/or is this issue being addressed by the Angular team?

**Comment by cexbrayat** [comment]
@daileytj The issue should be fixed in Angular 8.0.0, so if you still encounter it in recent versions, please open an issue with a minimal reproduction and ping me, and I or someone on the team will take a look.
