### ISSUE TITLE
Differential loading breaks in Safari 10.1.2 (12603.3.8)

### ISSUE THREAD

**Issue by mstawick** [angular/angular#31103]
# 🐞 bug report

### Affected Package
The issue is caused by package: not sure if this belongs to @angular/core or @angular/cli

### Is this a regression?
Yes, it worked fine before the introduction of differential loading

### Description
The application won't load in Safari 10.1.2 if building with differential loading. It works fine without it.

## 🔬 Minimal Reproduction
Visit angular.io with Safari 10.1.2.
It breaks with "Error: Zone.js has detected that ZoneAwarePromise ... has been overwritten.
I think it happens because of Safari first loading (runtime|polyfills)-es2015 scripts, and then (runtime|polyfills)-es5 scripts.

## 🔥 Exception or Error
<pre><code>
Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)
assertZonePatched — zone.js.pre-build-optimizer.js:58
t — core.js.pre-build-optimizer.js:26486
bootstrapModuleFactory — core.js.pre-build-optimizer.js:27202
zUnb — main.ts:11
c — bootstrap:83
(anonymous function) — location.service.ts:11
c — bootstrap:83
r — bootstrap:45
(anonymous function) — bootstrap:210
Module Code — bootstrap:215
evaluate
moduleEvaluation

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.1
Node: 10.15.3
OS: linux x64
Angular: 8.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by sod** [comment]
There is a fix for that in [@angular/cli 8.0.3](https://github.com/angular/angular-cli/releases/tag/v8.0.3)

https://github.com/angular/angular-cli/commit/56d9adc2a1949226a5ddba719f746f878ff3c7d8

**Comment by gkalpak** [comment]
Thx, @sod 👍 
Closing as fixed by angular/angular-cli#14716 and angular/angular-cli#14730.

**Comment by KurtGokhan** [comment]
@gkalpak  I am still experiencing this issue. 

Browser: Safari 10.1.2
Reproducing app: https://github.com/KurtGokhan/angular-31103-repro

Angular Version:
```
Angular CLI: 8.3.3
Node: 12.1.0
OS: win32 x64
Angular: 8.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.3
@angular-devkit/build-angular     0.803.3
@angular-devkit/build-optimizer   0.803.3
@angular-devkit/build-webpack     0.803.3
@angular-devkit/core              8.3.3
@angular-devkit/schematics        8.3.3
@angular/cli                      8.3.3
@ngtools/webpack                  8.3.3
@schematics/angular               8.3.3
@schematics/update                0.803.3
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
```

Tried with `zone.js` version `0.9.1` and `0.10.2`. None works.

**Comment by KurtGokhan** [comment]
Having Safari 10 in the browserlist solves the problem.
