### ISSUE TITLE
Custom decorators not working using AoT and Ivy

### ISSUE THREAD

**Issue by robisim74** [angular/angular#31495]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler-cli (I guess)

### Is this a regression?

 I had never tried AoT with Ivy

### Description

 I have a custom property decorator like this:
```
export function Language(): PropertyDecorator {
    function DecoratorFactory(target: any): void {
        const targetNgOnInit: () => void = target.ngOnInit;
        function ngOnInit(this: any): void {
            
            // Just for example
            console.log('onInit');

            if (targetNgOnInit) {
                targetNgOnInit.apply(this);
            }
        }
        target.ngOnInit = ngOnInit;
    }
    return DecoratorFactory;
}
```
used as:

```
@Language() lang: string;

ngOnInit() {
  // For aot
}
```

- With AoT compiler, _it works_ (it writes _onInit_ in console)
- If I enable Ivy and disable AoT, _it works_
- _If I enable Ivy and AoT, it doesn't work_

## 🔬 Minimal Reproduction

[angular-ivy-decorators](https://github.com/robisim74/angular-ivy-decorators)

## 🔥 Exception or Error
No errors during compilation or in console. The `ngOnInit `method in decorator function is ignored.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.1.1
Node: 10.14.2
OS: win32 x64
Angular: 8.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.1
@angular-devkit/build-angular     0.801.1
@angular-devkit/build-optimizer   0.801.1
@angular-devkit/build-webpack     0.801.1
@angular-devkit/core              8.1.1
@angular-devkit/schematics        8.1.1
@ngtools/webpack                  8.1.1
@schematics/angular               8.1.1
@schematics/update                0.801.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Anything else relevant?**
Tried without success also the _next_ version of Angular.

Thanks

**Comment by JoostK** [comment]
[Version 8.0.4 of the CLI](https://github.com/angular/angular-cli/releases/tag/v8.0.4) removed `emitDecoratorMetadata` from `tsconfig.json` by default, your project also doesn't have it enabled. Could you try again with that option enabled?

**Comment by robisim74** [comment]
I had not noticed the removal of `emitDecoratorMetadata`. However, no, it still doesn't work.

**Comment by alexzuza** [comment]
Appears the reason here is that Angular places `ngComponentDef` generated code before all `__decorate` calls for class. `ɵɵdefineComponent` function takes `onInit` as a reference to `Class.prototype.ngOnInit` and overridding it later has no any effect.

https://github.com/angular/angular/blob/58be2ff88400d7dc876d357f8cc3eb01b0912aae/packages/core/src/render3/definition.ts#L264

![dec](https://user-images.githubusercontent.com/4223314/61022503-295fd600-a3b7-11e9-8e3c-dcc897ecfa9a.png)


Here's a pseudo-code of what happens:
```
class Test {
  ngOnInit() {
    console.log('original')
  } 
}

const hook = Test.prototype.ngOnInit;

Test.prototype.ngOnInit = () => {
  console.log(1);
}

hook(); // prints 'original'
```

In case of JIT compilation `componentDef` is created lazily as soon as `getComponentDef` gets called. It happens later.

**Comment by alxhub** [comment]
Yeah, this is unfortunately WAI.

Angular's compiler btw has no say in the location of `ngComponentDef` vs the `__decorate` call - this is the way TypeScript naturally compiles static fields. See [this example](http://www.typescriptlang.org/play/?emitDecoratorMetadata=true#code/CYUwxgNghgTiAEYD2A7AzgF3gEXEmUG+AXPFCgJ4DcAUHSAB4AO+WkUaa8AYkkvAG8a8eAAFcyAkRgAKAJTwAZgEsQEYAEJS5anRGZCysPCYwkTEDAwV4AXngYYAVxC0AvkA).

**Comment by alxhub** [comment]
Transferring this to core as there's nothing we can do on this from the compiler side - the behavior in question is the snapshotting of `ngOnInit` prior to decorator execution.

**Comment by kerosin** [comment]
Any update on this issue?
Is there a workaround so far?

**Comment by stupidawesome** [comment]
Given a class decorator
```ts
function Mixin(value) {
    return function(target) {
        target.prototype.ngOnInit = function () {
            console.log("ngOnInit", value)
        }
    }
}

@Component({ ... })
@Mixin({ value: 123 })
export class AppComponent {}
```

This workaround should work in Ivy
```ts
const Extend = Mixin({ value: 123 })

@Component({ ... })
export class AppComponent {
    static mixins = Extend(AppComponent)
}
```

For ViewEngine compatibility, you also need to add a stub for ngOnInit

```ts
@Component({ ... })
export class AppComponent {
    public ngOnInit?()
    static mixins = Extend(AppComponent)
}
```

Assigning to a static property on the class forces the mixin to be executed before the runtime snapshots the class.

**Comment by kumaresan-subramani** [comment]
> Given a class decorator
> 
> ```ts
> function Mixin(value) {
>     return function(target) {
>         target.prototype.ngOnInit = function () {
>             console.log("ngOnInit", value)
>         }
>     }
> }
> 
> @Component({ ... })
> @Mixin({ value: 123 })
> export class AppComponent {}
> ```
> 
> This workaround should work in Ivy
> 
> ```ts
> const Extend = Mixin({ value: 123 })
> 
> @Component({ ... })
> export class AppComponent {
>     static mixins = Extend(AppComponent)
> }
> ```
> 
> For ViewEngine compatibility, you also need to add a stub for ngOnInit
> 
> ```ts
> @Component({ ... })
> export class AppComponent {
>     public ngOnInit?()
>     static mixins = Extend(AppComponent)
> }
> ```
> 
> Assigning to a static property on the class forces the mixin to be executed before the runtime snapshots the class.

I can't use your workaround in my condition. refer below - https://github.com/syncfusion/ej2-angular-ui-components/blob/master/components/grids/src/grid/grid.component.ts#L29

**Comment by JoostK** [comment]
@kumaresan-subramani From within your empty lifecycle methods, you should delegate into the mixin field.

**Comment by kumaresan-subramani** [comment]
@JoostK , Any update on this?

**Comment by kumaresan-subramani** [comment]
@JoostK , same issue in latest cli also?

**Comment by kumaresan-subramani** [comment]
HI @JoostK ,

Can you please provide timeline for this issue?

**Comment by Splaktar** [comment]
@kumaresan-subramani the team doesn't normally provide ETAs or timelines for issue resolution. Based on the milestone, this is not being considered for version 9 final. It's possible that it could go into a 9.x minor or patch, be pushed to version 10, or it could be pushed even later. 

If you feel like the priority needs to be raised, please provide a clear use case that demonstrates a significant issue that does not have a workaround. If this is a problem for a Syncfusion library, please explain the issue, impact, and workarounds attempted.

**Comment by kumaresan-subramani** [comment]
> Appears the reason here is that Angular places `ngComponentDef` generated code before all `__decorate` calls for class. `ɵɵdefineComponent` function takes `onInit` as a reference to `Class.prototype.ngOnInit` and overridding it later has no any effect.
> 
> https://github.com/angular/angular/blob/58be2ff88400d7dc876d357f8cc3eb01b0912aae/packages/core/src/render3/definition.ts#L264
> 
> ![dec](https://user-images.githubusercontent.com/4223314/61022503-295fd600-a3b7-11e9-8e3c-dcc897ecfa9a.png)
> 
> Here's a pseudo-code of what happens:
> 
> ```
> class Test {
>   ngOnInit() {
>     console.log('original')
>   } 
> }
> 
> const hook = Test.prototype.ngOnInit;
> 
> Test.prototype.ngOnInit = () => {
>   console.log(1);
> }
> 
> hook(); // prints 'original'
> ```
> 
> In case of JIT compilation `componentDef` is created lazily as soon as `getComponentDef` gets called. It happens later.

Hi @Splaktar , This is reason for our issue

**Comment by smnbbrv** [comment]
A 1-cent from me. Before Angular 9 I used a `Memoize` decorator across all my components in many apps and now it comes to the point that I can't use it anymore.

```
  @Memoize()
  getPermission(account: Account) {
    return this.permissions.find(p =>  account.permissions.includes(p.id));
  }
```

As one might see, the operation is quite heavy and I cache it after one run. Now it simply throws Reference error: Account is undefined in production build. I spent quite a lot of time until it became clear that the decorator was the reason.

Sad, but looks like I need to find another way now, probably less magical. 

However, this is a breaking change and it's not mentioned anywhere. Maybe it's worth to give at least some note that custom decorators will fail now on the components' members

**Comment by kumaresan-subramani** [comment]
HI Team,

Please give some high priority to this issue.

**Comment by dopsun** [comment]
> Angular's compiler btw has no say in the location of `ngComponentDef` vs the `__decorate` call - this is the way TypeScript naturally compiles static fields.

But reading the TypeScript spec [Class decorators](https://www.typescriptlang.org/docs/handbook/decorators.html#class-decorators):
> A Class Decorator is declared just before a class declaration. The class decorator is applied to the constructor of the class and can be used to observe, **modify**, or **replace** a class definition. 

In my case, I'm using a class decorator and doing same thing as this ticket, replacing ngOnInit with my own. And it does not work, exactly because the issue specified in this ticket.

I'm not expert to tell this is due to core or ivy, but to me, this behavior has been defined clearly in TypeScript, but Angular's lifecycle hooks cached too early to prevent class decorator working as TypeScript defined.

Hence, this is a bug somewhere in Angular. Would be great if this can be prioritized.

**Comment by kumaresan-subramani** [comment]
In typescript, we are not able to extend multiple class, To achieve this support we are using `mixins` and `custom decorators`. If those are not possible in angular 9, how should we achieve these support at least provide possible workarounds.

**Comment by smnbbrv** [comment]
This post will probably get million times downvoted, however my personal finding is since I use early beta versions of Angular 2: do not ever extend angular components and do not use decorators on angular components. This always led to the problems; during upgrades 2 -> @angular/cli -> 4 -> 5 -> 6 -> 7 -> 8 -> 9 I rewrote tons of components just because of these two things.

Here are similar AoT issues that are not fixed for years and it seems to not happen soon https://github.com/angular/angular/issues/23038 https://github.com/angular/angular/issues/16023 and many others.

I clearly understand the reasoning behind. The decorators are changing the content, behaviour and the lifecycle of the components; they can actually rewrite everything we now of the component in the runtime. It's really hard (impossible?) to catch this with the custom compiler and create a performant application. It's a very hard job that Angular team is already doing. Thank you for that!

Maybe problem is not in Angular. **Probably we should change the way we think.**

But, **Angular team, please help us**. The framework documentation is super-silent about all these issues. I will probably repeat myself here https://github.com/angular/angular/issues/31495#issuecomment-583767197 and ask for the easiest solution. Maybe politically it's not the best for angular, or there are some religious beliefs against that, but please add those two clear lines to the components' documentation:

> - we do not yet fully support components inheritance
> - we do not yet fully support custom decorators on components

And then the issues like this would be resolved. The StackOverflow answers would not propose to extend components. People would not be annoyed of rewriting their applications.

I am pretty sure everybody here will have no problems with using no decorators. The only thing that is missing: this should be properly communicated.

**Comment by BrainMaxxx** [comment]
I had the same problem as @smnbbrv, for me workaround was to set **emitDecoratorMetadata** to **false** in tsconfig

**Comment by ymchun** [comment]
Having the same problem, any update on this issue ?

**Comment by kumaresan-subramani** [comment]
HI @Splaktar ,

Can you please provide any update reg this

**Comment by l0co** [comment]
For me it's not about putting the custom decorator on component class or methods (like `ngOnInit`). With Angular 9 Ivy + Aot it also doesn't work to put the annotation to classes not related to Angular at all. For example:

```javascript
export let Algorithm = function(registry: []) {
  return function<T extends {new():{}}>(ctor:T) { 
    console.log('decorator executed');
  }
};

let registry = [];

@Algorithm(registry)
class MyClass { 
  // ...
}
```

This code logs `decorator executed` for `ng serve`, but doesn't log anything for `ng serve --prod`. For the latter one I need to make following changes to `angular.json` file: `aot: false` and `buildOptimizer: false`.

**Comment by LayZeeDK** [comment]
Expose component features and we'll be good 🙂

**Comment by dopsun** [comment]
While trying to find alternative way to implement what I did with decorator, actually, I discovered that the impact of this behavior much broader, not only limiting to decorator.

Here is what I'm trying to do in `activate` event handler of _router-outlet_, to rewrite the `ngOnInit`.
```
  onRouterOutletActivate(component: any) {
    const oldOnInit = component.ngOnInit;
    component.ngOnInit = function (this: any) {
      console.log('triggered');

      if (oldOnInit != null) {
        oldOnInit.bind(this)();
      }
    };
  }
```
While enabling Ivy, the original ngOnInit triggered, instead of my new one. It works while disabling Ivy (`"enableIvy": false`).

What I can see, the real issue is that lifecycle hooks for component is _NOT_ overwritable anymore while enabling Ivy, not just impacting the decorators.

**Comment by bryanrideshark** [comment]
This issue makes using Ivy impossible; We have used custom decorators extensively throughout our application, and the fact that they can't override lifecycle hooks is a real issue.

**Comment by bryanrideshark** [comment]
> This post will probably get million times downvoted, however my personal finding is since I use early beta versions of Angular 2: do not ever extend angular components and do not use custom decorators on angular components and their members. This always led to the problems; during upgrades 2 -> @angular/cli -> 4 -> 5 -> 6 -> 7 -> 8 -> 9 I rewrote tons of components just because of these two things.
> 
> Here are similar AoT issues that are not fixed for years and it seems to not happen soon #23038 #16023 and many others.
> 
> I clearly understand the reasoning behind. The decorators are changing the content, behaviour and the lifecycle of the components; they can actually rewrite everything we know of the component in the runtime. It's really hard (impossible?) to catch this with the custom compiler and create a performant application. It's a very hard job that Angular team is already doing. Thank you for that!
> 
> Maybe problem is not in Angular. **Probably we should change the way we think.**
> 
> But, **Angular team, please help us**. The framework documentation is super-silent about all these issues. I will probably repeat myself here [#31495 (comment)](https://github.com/angular/angular/issues/31495#issuecomment-583767197) and ask for the easiest solution. Maybe politically it's not the best for angular, or there are some religious beliefs against that, but please add those two clear lines to the components' documentation:
> 
> > * we do not yet fully support components inheritance
> > * we do not yet fully support custom decorators on components
> 
> And then the issues like this would be resolved. The StackOverflow answers would not propose to extend components. People would not be annoyed of rewriting their applications.
> 
> I am pretty sure everybody here will have no problems with using no decorators. The only thing that is missing: this should be properly communicated.

Angular can't have a philosophy of "Decorators for me, but not for thee". The entire library works by the elegance that decorators provide - `@Input()`, `@Output()` honestly there wouldn't even be an Angular if it weren't for decorators. Remember Atscript, and how that was discarded because Typescript jumped on the decorators bandwagon?

This is a failure of the Ivy team anticipating that many users are more savvy, and use custom decorators. Hopefully a mechanism can be found which will allow us to still use these incredibly powerful tools, with Ivy.

**Comment by bryanrideshark** [comment]
It appears that @mhevery is taking this seriously. That's much appreciated.

https://github.com/angular/angular/issues/30497
https://github.com/angular/angular/pull/35464

**Comment by otodockal** [comment]
@bryanrideshark 
> The entire library works by the elegance that decorators provide - @Input(), @Output() honestly there wouldn't even be an Angular if it weren't for decorators. Remember Atscript, and how that was discarded because Typescript jumped on the decorators bandwagon?

Yeah, Angular wouldn't be probably a thing without decorators(or comments or something like that), because the compiler needs them. The problem is Angular itself using decorators as annotations only and this is the difference(AtScript and Traceur implemented annotations only as well) https://twitter.com/IgorMinar/status/1231310929179971584.
I personally see it as must-have for compilers(Angular), but not that much for developers. Also as you can see from the decorators proposal(still Stage 2) and v8 team feedback https://github.com/tc39/proposal-decorators/issues/302, it might not be standardized at the end so I'm not sure whether end developers should be using them extensively for the reason before it's known.

But I understand you, it's BC or regression, so should be supported by the Angular team.
I also know metaprogramming is a thing, so no offense.

**Comment by bryanrideshark** [comment]
I fail to see why there should be two classes of developers. Library authors shouldn't get more elegant tools just because they work on the library part of the codebase.

Decorators are here to stay in Javascript.

**Comment by VagrantAI-c** [comment]
As for me, I override `ngOnDestroy` so a custom rxjs operator can be used in a pipeline for unsubscribing in a neat API:
```typescript
someObservable$
  .pipe(
    takeUntilDestroyed(this),
  )
  .subscribe();
```
My custom operator `takeUntilDestroyed` just wraps `ngOnDestroy` from object in first argument and unsubscribes upon destroy hook is called. New engine made this operator unusable and I have over 700 use cases of `takeUntilDestroyed` in my project...

**Comment by artaommahe** [comment]
@VagrantAI-c its funny that we are using `takeUntilDestroyed` too ;) Fixed it by adding decorator to Component/Directive classes like in this lib https://github.com/ngneat/until-destroy. You cant solve it only by operator now :(

**Comment by VagrantAI-c** [comment]
@artaommahe yeah, but it breaks all the declarativeness by adding decoratorish magic. Gotta disable Ivy for now I guess.

**Comment by JAspeling** [comment]
![Angular 9 upgrade](https://im2.ezgif.com/tmp/ezgif-2-0335c70df8b4.gif)

**Comment by yairtawil** [comment]
[AutoSubscriptions](https://www.npmjs.com/package/auto-subscriptions) is broken now when using Ivy!!! 😭😭😭 

```javascript
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.less']
})
@AutoSubscriptions()
export class AppComponent implements OnInit, OnDestroy {
  httpResult: object;
  
  @AutoSubscription
  httpResult$: Observable<Object> = this.http.get('HTTP_URL').pipe(
    tap((httpResult: object) => this.httpResult = httpResult)
  );
  
  constructor(protected http: HttpClient) {
  }
  
  ngOnInit() {
  }
 
  ngOnDestroy() {
  }
}
 constructor.prototype[metadata.init] = AutoAutoSubscriptionsInit(originalInit);
 constructor.prototype[metadata.destroy] = AutoAutoSubscriptionsDestroy(originalDestroy);
```

**Comment by ramtob** [comment]
> [AutoSubscriptions](https://www.npmjs.com/package/auto-subscriptions) is broken now when using Ivy!!! 😭😭😭
> 
> ```js
> @Component({
>   selector: 'app-root',
>   templateUrl: './app.component.html',
>   styleUrls: ['./app.component.less']
> })
> @AutoSubscriptions()
> export class AppComponent implements OnInit, OnDestroy {
>   httpResult: object;
>   
>   @AutoSubscription
>   httpResult$: Observable<Object> = this.http.get('HTTP_URL').pipe(
>     tap((httpResult: object) => this.httpResult = httpResult)
>   );
>   
>   constructor(protected http: HttpClient) {
>   }
>   
>   ngOnInit() {
>   }
>  
>   ngOnDestroy() {
>   }
> }
>  constructor.prototype[metadata.init] = AutoAutoSubscriptionsInit(originalInit);
>  constructor.prototype[metadata.destroy] = AutoAutoSubscriptionsDestroy(originalDestroy);
> ```

[Ansyn image analysis application](https://github.com/AnSyn/ansyn) is using the above mentioned **auto-subscription** decorators widely. And therefore this app is also blocked now from working with Ivy.

Solving the current issue is of high priority for us.

TIA

**Comment by fclmman** [comment]
Any news on this issue? steped into that too. Quite an annoying bug

**Comment by willisd2** [comment]
I ran into this issue as well trying to use Ivy and AoT to build my app... We have a custom decorator that is pretty crucial to the entire system. I've resorted to either turning off Ivy or AoT for now until there's a fix or workaround.

**Comment by ramtob** [comment]
@Splaktar @pkozlowski-opensource Hello, it was written above that we need to specify a use case in order to increase the priority of this issue. Well as you can see, a typical use case is for decorators which override component life-cycle hooks handlers (ngOnInit, ngOnDestrory) in order to more easily and safely subscribe to and unsubscribe from various streams. As you can see above, this feature has been in demand. And it has ceased to work in Ivy. This is not a matter of "regression", but of (significant) "convenience", and safely.

So can you raise the priority of this issue?

TIA

**Comment by klemenoslaj** [comment]
> @Splaktar @pkozlowski-opensource Hello, it was written above that we need to specify a use case in order to increase the priority of this issue. Well as you can see, a typical use case is for decorators which override component life-cycle hooks handlers (ngOnInit, ngOnDestrory) in order to more easily and safely subscribe to and unsubscribe from various streams. As you can see above, this feature has been in demand. And it has ceased to work in Ivy. This is not a matter of "regression", but of (significant) "convenience", and safely.
> 
> So can you raise the priority of this issue?
> 
> TIA

I beg to differ on this not being a regression. It worked in previous versions, Ivy breaks it  - regression. Furthermore, Ivy gets in the way of JS nature/features, like overwriting the prototype method. Make no mistake, this is not limited to the decorators only.

Another popular example is a custom `takeUntilDestroy` rxjs operator, which is nothing else than a function accepting an instance of component class.

This however should not reduce the priority of this issue.

---

In my custom operator I ended up relying on private `ɵcmp` property instead of prototype, in hope Angular will eventually fix this:

```ts
if (instanceConstructor.ɵcmp) {
  // Using private API until the corresponding Angular issues are resolved.
  // Issues: https://github.com/angular/angular/issues/31495, https://github.com/angular/angular/issues/30497
  // PR:    https://github.com/angular/angular/pull/35464
  destroy = <Function>instanceConstructor.ɵcmp.onDestroy ?? noop;
  instanceConstructor.ɵcmp.onDestroy = __takeUntilDestroy__destroy__;
} else {
  destroy = <Function>instanceConstructor.prototype.ngOnDestroy ?? noop;
  instanceConstructor.prototype.ngOnDestroy = __takeUntilDestroy__destroy__;
}
```

**Comment by abadakhshan** [comment]
I think my scenario is a little bit different.

Take a look at this:
https://github.com/abadakhshan/issue31495/blob/master/src/app/modules/share/general-list/general-list.component.ts

I have a class(GeneralListComponent ) with a decorator(@DynamicForm).
This class is not used anywhere and it is going to be used dynamically.

In this situation, the decorator does not work( It is removed by the compiler),  but if I add any code that uses this class( for example this [line](https://github.com/abadakhshan/issue31495/blob/master/src/app/modules/share/general-list/general-list.component.ts#L17)), everything is ok!

**Comment by JoostK** [comment]
@abadakhshan Please see #35314 for that scenario and how to make it work again.

**Comment by abadakhshan** [comment]
@JoostK 

Thank you.
#35314 is closed, but I think the problem still exists.

My scenario is exactly like [this ](https://github.com/angular/angular/issues/35314#issuecomment-584878705)

Add Dynamic Components to EntryComponents  Does not work anymore.

What should we do in this situation?

**Comment by JoostK** [comment]
@abadakhshan Please see https://github.com/angular/angular/issues/35314#issuecomment-584821399 for how to resolve the problem. The issue is closed because the framework is working as intended.

**Comment by willisd2** [comment]
It appears the issue I was running into was the same one that @abadakhshan describes [here](https://github.com/angular/angular/issues/31495#issuecomment-615191260). My app makes heavy use of dynamically instantiated components that often times aren't referenced by the app other than in the NgModule declarations. It appears the reason my custom decorator isn't working is because those components are being tree-shaken from the build. So in my situation this isn't a defect of angular, but rather an education on Ivy...

**Comment by vytautas-pranskunas-** [comment]
Any updates on this? We cannot move our project to ng9.

**Comment by masatada-kurihara** [comment]
This is a truly awful problem. Please fix it quickly as the version up of the internal project cannot be done.

**Comment by masatada-kurihara** [comment]
https://github.com/angular/angular/issues/37068#issuecomment-629173336

**Comment by petebacondarwin** [comment]
Please take a look at https://github.com/angular/angular/pull/35464. Hopefully this might resolve the issue for you?

**Comment by shadow1349** [comment]
I ran into the exact same problem. The solution for me was to turn off Ivy which sucks because I really want to take advantage of the Ivy compiler. Please fix this quickly!

**Comment by tinganho** [comment]
Ran into this today, You cannot even annotate a class unrelated to angular that's part of the angular build.

**Comment by ramtob** [comment]
See above, there is a PR on this problem.

**Comment by khiami** [comment]
Any update after v10 is out?

**Comment by hakimio** [comment]
@khiami you can track progress in PR #35464

**Comment by TinyMan** [comment]
> > @Splaktar @pkozlowski-opensource Hello, it was written above that we need to specify a use case in order to increase the priority of this issue. Well as you can see, a typical use case is for decorators which override component life-cycle hooks handlers (ngOnInit, ngOnDestrory) in order to more easily and safely subscribe to and unsubscribe from various streams. As you can see above, this feature has been in demand. And it has ceased to work in Ivy. This is not a matter of "regression", but of (significant) "convenience", and safely.
> > So can you raise the priority of this issue?
> > TIA
> 
> I beg to differ on this not being a regression. It worked in previous versions, Ivy breaks it - regression. Furthermore, Ivy gets in the way of JS nature/features, like overwriting the prototype method. Make no mistake, this is not limited to the decorators only.
> 
> Another popular example is a custom `takeUntilDestroy` rxjs operator, which is nothing else than a function accepting an instance of component class.
> 
> This however should not reduce the priority of this issue.
> 
> In my custom operator I ended up relying on private `ɵcmp` property instead of prototype, in hope Angular will eventually fix this:
> 
> ```ts
> if (instanceConstructor.ɵcmp) {
>   // Using private API until the corresponding Angular issues are resolved.
>   // Issues:  https://github.com/angular/angular/issues/31495, https://github.com/angular/angular/issues/30497
>   // PR:      https://github.com/angular/angular/pull/35464
>   destroy = <Function>instanceConstructor.ɵcmp.onDestroy ?? noop;
>   instanceConstructor.ɵcmp.onDestroy = __takeUntilDestroy__destroy__;
> } else {
>   destroy = <Function>instanceConstructor.prototype.ngOnDestroy ?? noop;
>   instanceConstructor.prototype.ngOnDestroy = __takeUntilDestroy__destroy__;
> }
> ```

I found out that this workaround create errors in JIT if your decorator is after `@Component()` like this: 

```ts
@CustomDecorator()
@Component({ ...})
export class Comp {}
```

because (my guess from debugging it) `ɵcmp` in JIT is a getter that compiles the component. But when the decorators are executed the compiler is not ready (I think imported modules are not yet availables, as I had errors on ngIf not being an input on div).

So the workaround is to check that we are in AOT before getting the `ɵcmp` property : 

```ts
export function getLifecycleHook(instanceConstructor: Function, hook: 'ngOnDestroy' | 'ngOnInit' | 'ngOnChanges') {
	const desc = Object.getOwnPropertyDescriptor(instanceConstructor, ɵNG_COMP_DEF);
	if (!!desc && !desc?.get) { // check for ivy AND aot
		// Using private API until the corresponding Angular issues are resolved.
		// Issues:  https://github.com/angular/angular/issues/31495, https://github.com/angular/angular/issues/30497
		// PR:      https://github.com/angular/angular/pull/35464
		return instanceConstructor[ɵNG_COMP_DEF]['o' + hook.slice(3)];
	} else {
		return instanceConstructor.prototype[hook];
	}
}
```
And this works both in AOT and JIT.

Also if you put your decorators after `@Component()` (so that yours is executed first), it works because `ɵcmp` is not yet defined.

Needed this because AOT is still unusable for development with large project.

**Comment by wsdt** [comment]
Using custom decorators with AoT and Ivy is also high priority for us.

**Comment by hakimio** [comment]
@wsdt This was already fixed in [Angular v10.0.5](https://github.com/angular/angular/blob/master/CHANGELOG.md#1005-2020-07-22).

**Comment by wsdt** [comment]
@hakimio Thank you ! :-)

**Comment by kumaresan-subramani** [comment]
> > Appears the reason here is that Angular places `ngComponentDef` generated code before all `__decorate` calls for class. `ɵɵdefineComponent` function takes `onInit` as a reference to `Class.prototype.ngOnInit` and overridding it later has no any effect.
> > https://github.com/angular/angular/blob/58be2ff88400d7dc876d357f8cc3eb01b0912aae/packages/core/src/render3/definition.ts#L264
> > 
> > ![dec](https://user-images.githubusercontent.com/4223314/61022503-295fd600-a3b7-11e9-8e3c-dcc897ecfa9a.png)
> > Here's a pseudo-code of what happens:
> > ```
> > class Test {
> >   ngOnInit() {
> >     console.log('original')
> >   } 
> > }
> > 
> > const hook = Test.prototype.ngOnInit;
> > 
> > Test.prototype.ngOnInit = () => {
> >   console.log(1);
> > }
> > 
> > hook(); // prints 'original'
> > ```
> > 
> > 
> > In case of JIT compilation `componentDef` is created lazily as soon as `getComponentDef` gets called. It happens later.
> 
> **reason** - [#30818 (comment)](https://github.com/angular/angular/issues/30818#issuecomment-543628872)
> 
> Hi @Splaktar , you can find reasons above
> 
> ### Workaround attempted
> [#31495 (comment)](https://github.com/angular/angular/issues/31495#issuecomment-549873125)
> [#31495 (comment)](https://github.com/angular/angular/issues/31495#issuecomment-555233912)


HI @hakimio ,

**I think issue not get fixed still facing same issue.**

My angular packages:

```
dependencies": {
    "@angular/animations": "~10.0.9",
    "@angular/common": "~10.0.9",
    "@angular/compiler": "~10.0.9",
    "@angular/core": "~10.0.9",
    "@angular/forms": "~10.0.9",
    "@angular/platform-browser": "~10.0.9",
    "@angular/platform-browser-dynamic": "~10.0.9",
```

**Comment by hakimio** [comment]
@kumaresan-subramani just use [ngx-observable-lifecycle](https://github.com/cloudnc/ngx-observable-lifecycle) if you can not get it to work.

**Comment by robisim74** [comment]
As reported by @hakimio, after over a year this issue was fixed in [Angular v10.0.5](https://github.com/angular/angular/blob/master/CHANGELOG.md#1005-2020-07-22). If there were other problems, I think more specific issues should be open, and therefore I am closing it.
