### ISSUE TITLE
ng serve in Ivy mode is dropping directives list when editing a template

### ISSUE THREAD

**Issue by vikerman** [angular/angular#31654]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Yes. 8.0.0

### Description
`ng serve`(watch mode) seems to be outputting invalid generated code for a simple component when the template is edited.

## 🔬 Minimal Reproduction

git clone git@github.com:vikerman/ivy-proj.git
cd ivy-proj

yarn installl

ng serve

<Edit src/app/app.component.html and add more !!! to Hello World>

The browser is refreshed but with the MatButton directive not applied.

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.2.0-next.0
Node: 10.15.3
OS: linux x64
Angular: 8.2.0-next.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0-next.0
@angular-devkit/build-angular     0.802.0-next.0
@angular-devkit/build-optimizer   0.802.0-next.0
@angular-devkit/build-webpack     0.802.0-next.0
@angular-devkit/core              8.2.0-next.0
@angular-devkit/schematics        8.2.0-next.0
@angular/cdk                      8.1.1
@angular/cli                      8.2.0-next.0
@angular/material                 8.1.1
@ngtools/webpack                  8.2.0-next.0
@schematics/angular               8.2.0-next.0
@schematics/update                0.802.0-next.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.3

</code></pre>

**Comment by kolkov** [comment]
+ loses code changes on reload

**Comment by petebacondarwin** [comment]
@kolkov - can you be more specific?

**Comment by kolkov** [comment]
I wanted to say that not only the directives do not fall, but the other code changed in the IDE is also not updated in the browser sometimes.

**Comment by petebacondarwin** [comment]
@kolkov - can you provide a reproduction? Specifically what changes do you make? What is the setup of the project you are testing it on?

**Comment by kolkov** [comment]
@petebacondarwin If I changes scss, browser is reloading, but page not changed. I try to create reproduction exapmle and create new issue for it. I tryed to serve this without Ivy enabled and this bug was present.

**Comment by petebacondarwin** [comment]
Great. Thanks @kolkov. The bug is that the recompilation doesn't happen properly for a change to any "resource", i.e template or styles.

**Comment by Ploppy3** [comment]
@petebacondarwin This is so far the worst issue I got with Angular, the need to recompile twice on big projects to see the CSS changes is real pain.

**Comment by kolkov** [comment]
@Ploppy3 I do not understand how they want to release version 8.2.0 without first closing this problem ...?

**Comment by petebacondarwin** [comment]
Does this affect all projects or only those with ivy enabled? I thought the latter - in which case this bug should only affect people trying out ivy.

**Comment by kolkov** [comment]
@petebacondarwin I have this issue with disabled Ivy on last RC.0. :((((

**Comment by petebacondarwin** [comment]
That's strange because incremental compilation is only available for ivy builds. Let me see if I can reproduce it for a ViewEngine project...

**Comment by kolkov** [comment]
@petebacondarwinI sent you an invitation to my private repo. Thanks!

**Comment by kolkov** [comment]
@petebacondarwin 
```
Angular CLI: 8.2.0-next.1
Node: 12.6.0
OS: win32 x64
Angular: 8.2.0-rc.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0-next.1
@angular-devkit/build-angular     0.802.0-next.1
@angular-devkit/build-optimizer   0.802.0-next.1
@angular-devkit/build-webpack     0.802.0-next.1
@angular-devkit/core              8.1.1
@angular-devkit/schematics        8.1.1
@angular/cli                      8.2.0-next.1
@angular/pwa                      0.801.1
@ngtools/webpack                  8.2.0-next.1
@schematics/angular               8.1.1
@schematics/update                0.802.0-next.1
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.35.3
```

**Comment by petebacondarwin** [comment]
I can't reproduce on a simple new CLI project or on that repository either. :-(

**Comment by kolkov** [comment]
@pedroclayman very strange situation... ( It's realy not working for me...
please post your ng version result

**Comment by petebacondarwin** [comment]
This is the version for @kolkov project that he shared with me that I tested.

```
Angular CLI: 8.2.0-next.1
Node: 10.16.0
OS: win32 x64
Angular: 8.2.0-rc.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0-next.1
@angular-devkit/build-angular     0.802.0-next.1
@angular-devkit/build-optimizer   0.802.0-next.1
@angular-devkit/build-webpack     0.802.0-next.1
@angular-devkit/core              8.1.1
@angular-devkit/schematics        8.1.1
@angular/cli                      8.2.0-next.1
@angular/pwa                      0.801.1
@ngtools/webpack                  8.2.0-next.1
@schematics/angular               8.1.1
@schematics/update                0.802.0-next.1
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.35.3
```

**Comment by kolkov** [comment]
@petebacondarwin thanks! only this difference `Node: 10.16.0` :(

**Comment by petebacondarwin** [comment]
I upgrade the node.js version and still the same.

**Comment by kolkov** [comment]
@petebacondarwin I can not understand what is wrong... (((

**Comment by kolkov** [comment]
@petebacondarwin Did you use AOT at `ng serve`?

**Comment by petebacondarwin** [comment]
In your app the `ng start` triggers AOT. But I tried it with and without :-/

**Comment by kolkov** [comment]
@petebacondarwin How can I debug this?

**Comment by kolkov** [comment]
@petebacondarwin This is somehow related to AOT, as soon as I turned off the AOT flag, everything began to work fine.

**Comment by petebacondarwin** [comment]
@kolkov are you 100% sure you are not running with ivy enabled? With AOT turned off we don't go through the ngtsc compiler so it would indeed not show these problems. With AOT turned on (and ivy enabled) then I would expect to hit this problem. Perhaps there is another tsconfig.json somewhere that is enabling ivy?

**Comment by kolkov** [comment]
@petebacondarwin that private project in actual state...

**Comment by kolkov** [comment]
![image](https://user-images.githubusercontent.com/3740898/62137144-1ffac700-b2ee-11e9-83fa-c89221833b3b.png)

**Comment by kolkov** [comment]
![image](https://user-images.githubusercontent.com/3740898/62137191-36088780-b2ee-11e9-9699-0875711b47e6.png)

**Comment by kolkov** [comment]
@petebacondarwin try to enable Ivy, serve project with Ivy, and then disable Ivy in `ui/projects/inframe-office/tsconfig.app.json`, and re serve again.

**Comment by petebacondarwin** [comment]
@kolkov sent you a message to your Gmail address.

**Comment by kolkov** [comment]
![image](https://user-images.githubusercontent.com/3740898/62137966-7fa5a200-b2ef-11e9-8812-9ad74c6f937a.png)

**Comment by kolkov** [comment]
@petebacondarwin it's not a permanent problem, it's time to time...
![image](https://user-images.githubusercontent.com/3740898/62138612-93053d00-b2f0-11e9-8aad-88ae7ad0f36c.png)

**Comment by kolkov** [comment]
@petebacondarwin building log from IDE
```
> ui@0.1.0 start D:\Go\inframe\ui
> ng serve --proxy-config proxy.conf.json --aot

 10% building 3/3 modules 0 activei ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //index.html
chunk {base-base-module-ngfactory} base-base-module-ngfactory.js, base-base-module-ngfactory.js.map (base-base-module-ngfactory) 12.6 kB  [rendered]
chunk {casting-casting-module-ngfactory} casting-casting-module-ngfactory.js, casting-casting-module-ngfactory.js.map (casting-casting-module-ngfactory) 61.7 kB  [rendered]
chunk {default~base-base-module-ngfactory~production-production-module-ngfactory~settings-settings-module-ngfactory} default~base-base-module-ngfactory~production-production-module-ngfactory~settings-settings-module-ngfactory.js, default~base-base-module-ngfact
ory~production-production-module-ngfactory~settings-settings-module-ngfactory.js.map (default~base-base-module-ngfactory~production-production-module-ngfactory~settings-settings-module-ngfactory) 30.1 kB  [rendered]
chunk {main} main.js, main.js.map (main) 512 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 130 kB [initial] [rendered]
chunk {production-production-module-ngfactory} production-production-module-ngfactory.js, production-production-module-ngfactory.js.map (production-production-module-ngfactory) 13.5 kB  [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 9.4 kB [entry] [rendered]
chunk {settings-settings-module-ngfactory} settings-settings-module-ngfactory.js, settings-settings-module-ngfactory.js.map (settings-settings-module-ngfactory) 15.6 kB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 318 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.53 MB [initial] [rendered]
Date: 2019-07-30T14:26:15.418Z - Hash: 0db388005755977ff9d0 - Time: 21244ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:27:45.149Z - Hash: 0db388005755977ff9d0
10 unchanged chunks

Time: 3914ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:34:32.087Z - Hash: d6f2e6f598764a310756
9 unchanged chunks
chunk {casting-casting-module-ngfactory} casting-casting-module-ngfactory.js, casting-casting-module-ngfactory.js.map (casting-casting-module-ngfactory) 61.7 kB  [rendered]
Time: 3029ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:34:50.297Z - Hash: d6f2e6f598764a310756
10 unchanged chunks

Time: 1883ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:35:34.357Z - Hash: 0db388005755977ff9d0
9 unchanged chunks
chunk {casting-casting-module-ngfactory} casting-casting-module-ngfactory.js, casting-casting-module-ngfactory.js.map (casting-casting-module-ngfactory) 61.7 kB  [rendered]
Time: 2370ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:35:43.567Z - Hash: 0db388005755977ff9d0
10 unchanged chunks

Time: 2135ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:38:12.042Z - Hash: 0db388005755977ff9d0
10 unchanged chunks

Time: 2985ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
 50% building 0/5 modules 5 active D:\Go\inframe\ui\node_mo
Date: 2019-07-30T14:38:14.245Z - Hash: 0db388005755977ff9d0
10 unchanged chunks

Time: 1900ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:38:31.074Z - Hash: 0db388005755977ff9d0
10 unchanged chunks

Time: 2053ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:38:36.714Z - Hash: 0db388005755977ff9d0
10 unchanged chunks

Time: 1859ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:38:55.138Z - Hash: 0db388005755977ff9d0
10 unchanged chunks

Time: 1954ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: wait until bundle finished: /casting

Date: 2019-07-30T14:38:57.411Z - Hash: 0db388005755977ff9d0
10 unchanged chunks

Time: 1704ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:39:17.639Z - Hash: 0db388005755977ff9d0
10 unchanged chunks

Time: 1698ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:39:41.527Z - Hash: 0db388005755977ff9d0
10 unchanged chunks

Time: 1441ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:39:55.912Z - Hash: 0db388005755977ff9d0
10 unchanged chunks

Time: 1424ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:40:03.736Z - Hash: 0db388005755977ff9d0
10 unchanged chunks

Time: 1404ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:40:40.938Z - Hash: 55280d8bde3e883ec8f2
9 unchanged chunks
chunk {casting-casting-module-ngfactory} casting-casting-module-ngfactory.js, casting-casting-module-ngfactory.js.map (casting-casting-module-ngfactory) 61.7 kB  [rendered]
Time: 2324ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:40:53.751Z - Hash: 55280d8bde3e883ec8f2
10 unchanged chunks

Time: 1773ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:41:06.573Z - Hash: 0db388005755977ff9d0
9 unchanged chunks
chunk {casting-casting-module-ngfactory} casting-casting-module-ngfactory.js, casting-casting-module-ngfactory.js.map (casting-casting-module-ngfactory) 61.7 kB  [rendered]
Time: 1616ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:41:16.597Z - Hash: 0db388005755977ff9d0
10 unchanged chunks

Time: 1666ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:41:22.638Z - Hash: 0db388005755977ff9d0
10 unchanged chunks

Time: 1651ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:41:28.591Z - Hash: 0db388005755977ff9d0
10 unchanged chunks

Time: 1493ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:41:46.626Z - Hash: 254a057a65cea74ec920
9 unchanged chunks
chunk {casting-casting-module-ngfactory} casting-casting-module-ngfactory.js, casting-casting-module-ngfactory.js.map (casting-casting-module-ngfactory) 61.7 kB  [rendered]
Time: 1781ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-07-30T14:42:00.181Z - Hash: 254a057a65cea74ec920
10 unchanged chunks

Time: 1642ms
i ｢wdm｣: Compiled successfully.


```

**Comment by kolkov** [comment]
@petebacondarwin I change styles at lazy module... maybe this can help.
![image](https://user-images.githubusercontent.com/3740898/62140703-1ffdc580-b2f4-11e9-893e-a9a1ea22d682.png)

**Comment by Ploppy3** [comment]
@petebacondarwin It does not seem to affect every projects so far, can't find the source of the problem though, I have both problems on my main project:

1. Ivy mode dropping directives list
2. CSS needing 2 recompilation

If you need any information, please ask.

**Comment by Ploppy3** [comment]
@petebacondarwin I noticed my versions weren't in sync, which seems to be the case for @kolkov , I updated my dependencies and now the CSS part of the problem seems to be gone. Ivy recompilation still broken when update template.

**Comment by Ploppy3** [comment]
Also the `ng version` report by the OP @vikerman had the same problem, mismatched versions.

**Comment by kolkov** [comment]
@Ploppy3 yes this fixed in latest CLI rc.0

**Comment by petebacondarwin** [comment]
The problem with the IVY incremental builds is still broken... we are working on a fix - see https://github.com/angular/angular/pull/31655, which fixes it but not the correct way.

@kolkov's problem was not IVY related and was fixed in `@angular-devkit/build-angular@0.802.0-rc.0` as he reports by this commit: https://github.com/angular/angular-cli/commit/6649483d86a27abb1eb2392a612f4d1bdf7a8cfc

**Comment by Ploppy3** [comment]
@petebacondarwin Ok thanks for the explanation. Please keep in mind that the 3 of us got mismatched versions as there is no warning whatsoever when you use `ng update` on the beta branch. Do you feel like I should open an issue or is it OK since it is only related to the beta?

**Comment by kolkov** [comment]
Thanks!

**Comment by petebacondarwin** [comment]
@Ploppy3 - yes please open an issue on the CLI repo. I think there should at least be peerDependency warnings...
