### ISSUE TITLE
IVY issue?: Can't bind to 'ngStyle' & 'ngClass' since it isn't a known property of img

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angular#31981]
### Is this a regression?
Mèh, not really, it's more a change to IVY issue.
Angular version: 9.0.0-next.0

### Description
I have in my code a lot of:
<img [ngClass]="{ black: isBlack }" [ngStyle]="{ right: firstRight + 'vw' }">
code.

When upgrading/changing to IVY, this fails with the error message:
Can't bind to 'ngStyle' since it isn't a known property of img
Can't bind to 'ngClass' since it isn't a known property of img

Seems that if I change to [class.black]='isBlack' and so on it works.
But seems to me that this is possibly not the intention?

I have an other issue as well (injecting into a pipe) but I don't want to spam you guys/gals.
Are IVY issues like this appreciated for now or do I just wait until IVY is more advanced for trying further?

**Comment by AndrewKushnir** [comment]
Hi @LanderBeeuwsaert,

I've tried to reproduce this problem and created the following TestBed test case (based on your report):

```
    it('should work with ngClass and ngStyle', () => {
      @Component({
        selector: 'app',
        template: `
          <img [ngClass]="{ black: isBlack }" [ngStyle]="{ right: firstRight + 'vw' }">
        `
      })
      class MyApp {
        isBlack = true;
        firstRight = '10';
      }

      TestBed.configureTestingModule({declarations: [MyApp]});

      const fixture = TestBed.createComponent(MyApp);
      fixture.detectChanges();

      const element = fixture.nativeElement.firstChild;
      expect(element.classList.contains('black')).toBeTruthy();
      expect(element.style.right).toBe('10vw');
    });
```

and this test works correctly with Ivy. Could you please perform additional investigation to see if there are some extra conditions that trigger the problem?

> I have an other issue as well (injecting into a pipe) but I don't want to spam you guys/gals.
> Are IVY issues like this appreciated for now or do I just wait until IVY is more advanced for trying > further?

It's great that you check your app with Ivy and share problems/issue found. Feel free to create a separate ticket regarding pipes issue that you've faced, so the team and community members can
help look into it.

Thank you.

**Comment by LanderBeeuwsaert** [comment]
Hey @AndrewKushnir,

So I've went to the same branch again and ran it again. Same error, so at least it's consistent.
I'm attaching some screenshots:
error & devtools config & compiled code point where it breaks:
![image](https://user-images.githubusercontent.com/1098243/62416878-21f0bd00-b643-11e9-824e-b5c7aa1589e0.png)

source code:
![image](https://user-images.githubusercontent.com/1098243/62416889-49478a00-b643-11e9-8940-5199c3080a3d.png)

so it really goes into a method that says: createUnknownPropertyError()
does this help?

**Comment by AndrewKushnir** [comment]
@LanderBeeuwsaert, could you please try to update the template to the one I have in my test:
```
<img [ngClass]="{ black: isBlack }" [ngStyle]="{ right: firstRight + 'vw' }">
```
to see how the most minimal case works.

**Comment by LanderBeeuwsaert** [comment]
Hey, so yeah, I've mucked around a little bit.

The minimal case to BREAK it is:
![image](https://user-images.githubusercontent.com/1098243/62496358-fa335d80-b7d8-11e9-9259-8d9bf291852f.png)
If I now remove both: styles="height... => it will start to work
If I now remove both: [ngClass]=" => it will start to work

**Comment by AndrewKushnir** [comment]
Hi @LanderBeeuwsaert,

Thanks for additional investigation. I just tried it again using a template similar to what you have on the screen shot:

```
    it('should work with ngClass and ngStyle', () => {
      @Component({
        selector: 'app',
        template: `
          <div class="one">
            <div class="two">
              <img [src]="'/assets/' + file + '.svg'" [ngClass]="{ black: isBlack }" style="height:100px;" />
            </div>
            <div>
              <img [src]="'/assets/' + file + '.svg'" [ngClass]="{ black: isBlack }" style="height:150px;" />
            </div>
          </div>
        `
      })
      class MyApp {
        isBlack = true;
        firstRight = '10';
        file = 'my-img'
      }

      TestBed.configureTestingModule({declarations: [MyApp]});

      const fixture = TestBed.createComponent(MyApp);
      fixture.detectChanges();

      const element = fixture.nativeElement.querySelector('img');

      expect(element.classList.contains('black')).toBeTruthy();
      expect(element.style.height).toBe('100px');
    });
```

and it works fine. Do you still see the same error message? Also it'd be helpful if you could create a repro using an instruction that @JoostK shared in another thread here: https://github.com/angular/angular/issues/31990#issuecomment-518413782, because it looks like there is some additional configuration/code that is needed to reproduce the issue.

Thank you.

**Comment by LanderBeeuwsaert** [comment]
@AndrewKushnir hello Andrew, can I send you the repro zipped somewhere? (I Prefer not to put it online)

**Comment by JoostK** [comment]
I was able to reproduce this issue using the code @LanderBeeuwsaert sent me. It is caused by a bug in directive matching, which was recently fixed in #31942 and will be in the next release.

**Comment by fr0** [comment]
Is the fix in `9.0.0-next.1`? I'm using that version and am still having this problem when Ivy is enabled.

(Although in my case, the error manifests in a few different ways:

`Error: Template error: Can't bind to 'ngIf' since it isn't a known property of 'div'.`
`Error: Template error: Can't bind to 'ngStyle' since it isn't a known property of 'div'.`
`Uncaught Error: Template error: Can't bind to 'ngForOf' since it isn't a known property of 'button'.`
