### ISSUE TITLE
Compile errors when using async pipe with enableIvy & strictNullChecks

### ISSUE THREAD

**Issue by james-schwartzkopf** [angular/angular#32051]
# 🐞 bug report

### Affected Package
@angular/compiler-cli, @angular/angular

### Is this a regression?

Yes, this works when Ivy is not used.

### Description

The problem is the async pipe returns T | null. My understand is Ivy uses code similar to Partial<Pick<ChildComponent, 'prop'>> to check property bindings in templates. That allows undefined, but not null. Similarly, ngForOf doesn't allow null, so that also doesn't work with async.

This causes templates that previously compiled without errors to fail.
```
    <!-- Must be built with strictNullChecks && enableIvy to see the errors below -->
    <ul>
      <!-- Type 'string[] | null' is not assignable to type 'string[] | Iterable<string> | undefined' -->
      <li *ngFor="let n of array$ | async">{{n}}</li>
    </ul>
    <!-- Type 'number | null' is not assignable to type 'number | undefined' -->
    <app-child [prop]="value$ | async"></app-child>
```

We use ngrx/store, so we use the async pipe a lot, and for the most part the observables from the store will always return a value immediately. But async's return type means we have to deal with the null somehow even if it will never be emitted.

I've come up with several workarounds, but I don't like any of them very much.  And even if this is seen as behaving as intended, documentation should be updated (e.g. the example in https://angular.io/api/common/NgForOf#local-variables wouldn't work with strictNullChecks && enableIvy).

Workarounds:
1) Using non null assertions [prop]=(value$ | async)!"

  I don't like this since I don't want developers to get used to throwing it around causally.

2) Use || to provide a default, *ngFor="let i of (array$ | async) || []"

  This works okay for the ngFor case, but doesn't work for the prop case if one of the valid values is falsey, or if there is no good default value.

3) Use ngIf with async, *ngIf="value$ | async as value"

  This is probably a good choice for the cases where the async pipe would legitimately be null, but is just needlessly cluttering template with ng-contianer or other elements in the cases where the async pipe will never return null.  It also doesn't work when the pipe will return a falsey value.

4) Create a "present" pipe that throws if it's input is null/undefined and converts T | null to just T

  Alternatively create a currentValue pipe that combines async & present, which could limit the input to Observable<T> (since the other options would just cause it to throw anyway).

  This works but it makes the template expressions longer, and if it's not built into @angular/angular its more for new devs on the team to understand.
 

## 🔬 Minimal Reproduction

I've created a repo showing this issue:
https://github.com/james-schwartzkopf/test-template/blob/master/src/app/app.component.ts

## 🔥 Exception or Error
See Above

## 🌍  Your Environment

**Angular Version:**
<pre><code>
$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.2.0
Node: 10.15.1
OS: win32 x64
Angular: 8.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0
@angular-devkit/build-angular     0.802.0
@angular-devkit/build-optimizer   0.802.0
@angular-devkit/build-webpack     0.802.0
@angular-devkit/core              8.2.0
@angular-devkit/schematics        8.2.0
@ngtools/webpack                  8.2.0
@schematics/angular               8.2.0
@schematics/update                0.802.0
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.38.0
</code></pre>

**Anything else relevant?**

<pre><code>
$ cat ./tsconfig.app.json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": []
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ],
  "angularCompilerOptions": {
    "enableIvy": true
  }
}

</code></pre>
<pre><code>
$ cat ./tsconfig.json
{
  "compileOnSave": false,
  "compilerOptions": {
    "strictNullChecks": true,
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}
</code></pre>

**Comment by alxhub** [comment]
I think the right way to fix this is to make `NgForOf` accept `null` in its typings, since it does at runtime (and must, in order for the code to work in the first place).

**Comment by pshurygin** [comment]
I'm having a similsar issues without using ngFor.

I'm using ng-select component like this:
`<ng-select [(ngModel)]="city" [items]="cities$ | async">...</ng-select>`
Here the cities$ have (non-nullable) type Observable<City[]> and [items] binding of the ng-select accepts (any[]|undefined), but async pipe changes type of cities$ into (City[]|null), and so we have a compile error.

Another problem of the same category is with the number pipe, as it returns string|null. The code i have is
`<div [matTooltip]="value|number">...</div>`
where value is non-nullable number, but it's type is converted into string|null, which causes compiler error with matTooltip binding accepting string|undefined.

**Comment by klemenoslaj** [comment]
If this issue is resolved by`NgForOf` getting fixed to accept the `null` in its typings that still means all the custom inputs we develop ourselves will have to accept `null` by default? I mean, all of them...Do I even have to mention how cumbersome that is?

```ts
@Input() values?: number[] | null.
```

or even worse, solving the issue within templates

```html
<component [values]="(valuesStream | async) || undefined"></components>
```

Angular get's in our way here by preventing us writing our code the way we want it.

Question: There is probably a technical reason why `async` and some other pipes return `null`, but is it really needed?
My reasoning: Subscribing to an observable directly will not give you null by default either...you will get nothing until the actual emission happens.

**Comment by pshurygin** [comment]
I wonder if this will be fixed before v9 release, because otherwise we'll have to somehow workaround these type errors all over our code and that is a massive amount of useless work, which could prevent us from using ivy in the nearest future.

I guess one simple way to workaround this in the framework is to add some kind of flag to angular Compiler Options, which allows to ignore type mismatch between null and undefined(allow null for bindings, which accept undefined as a value)

**Comment by Splaktar** [comment]
PR https://github.com/angular/angular/pull/31371 is attempting to fix this.

**Comment by james-schwartzkopf** [comment]
> Question: There is probably a technical reason why `async` and some other pipes return `null`, because if not, is it really needed?

The async pipe returns null because it has to return something until the subscribe gives it an initial value (there is actually no such thing as truly async pipe, it just fakes it by returning null till it gets a real value).  Like I said in the OP, some observables will callback as soon as you call subscribe (e.g. ngrx/store selectors), but others will not (e.g. HttpClient).  Unfortunately there is no way for the type system to tell the two apart.

**Comment by klemenoslaj** [comment]
> > Question: There is probably a technical reason why `async` and some other pipes return `null`, because if not, is it really needed?
> 
> The async pipe returns null because it has to return something until the subscribe gives it an initial value (there is actually no such thing as truly async pipe, it just fakes it by returning null till it gets a real value). Like I said in the OP, some observables will callback as soon as you call subscribe (e.g. ngrx/store selectors), but others will not (e.g. HttpClient). Unfortunately there is no way for the type system to tell the two apart.

That makes sense, but maybe returning `undefined` instead would be more natural. Mostly speculating here.

**Comment by Splaktar** [comment]
Fixed in https://github.com/angular/angular/commit/c1bb88603ebaf7a4bd5aaf7794e594609046cd2e and released in `9.0.0-next.10`.

I believe that this can be closed.

**Comment by JoostK** [comment]
Thanks @Splaktar, I agree. If any of you is still experiencing problems after updating to at least `9.0.0-next.10`, please open a new issue.

**Comment by james-schwartzkopf** [comment]
So only ngFor was changed?  This will still be an issue for @Inputs that don't include null in their type?

**Comment by klemenoslaj** [comment]
@JoostK can we get an official statement here, please? Is it now expected that all inputs in our applications accept `null`?

Right now due to this issue Ivy is not really backward compatible, since it throws errors where View Engine does not.

**Comment by JoostK** [comment]
@klemenoslaj Ivy's template type checker is far more advanced than the level of type checking that was previously done for templates, and in general the errors it produces are accurate. The problem is that they may be too accurate for someone's liking, especially because of cases like `ngFor` together with the `async` pipe where there has always been a type mismatch that has not been surfaced before because the type checking was not as accurate as it is becoming now.

> Is it now expected that all inputs in our applications accept null?

This is not the case. This issue in particular is about the `async` pipe, which includes `null` in its return type as it can't differentiate based on the type of `Observable` if it will emit synchronously, or whether there may be a gap between the time of subscribing and the first value emission (in which case the `async` pipe has to return `null`, because it doesn't have any other information)

The good news is that we recently introduced an internal template type checking option to effectively ignore typing issues around `null` and `undefined`. A public facing option will be added shortly, so that developers can disable certain areas of the template type checker. This is basically @pshurygin's suggestion in https://github.com/angular/angular/issues/32051#issuecomment-536285449.

<sup>Disclaimer: I am not entitled to make official statements :-) I'm just enthusiastic about Ivy and helping out whenever I can.</sup>

**Comment by klemenoslaj** [comment]
@JoostK thanks a lot for a quick reply :+1:

> This is not the case. This issue in particular is about the async pipe, which includes null in its return

Absolutely correct, however I was basing my thoughts on the fact that `async` is one of the most commonly used pipes and it's delivered by Angular itself. 
While developing libraries we don't know if a developer will be using `async` pipe on our component inputs, thus we would have to include a `null` type in order to support it, right?
This would look something like:

```ts
@Input() myNumber?: number | null;
```

Is there a  reason for `async` pipe not to return `undefined` instead?

> The good news is that we recently introduced an internal template type checking option to effectively ignore typing issues around null and undefined

🎉🎉

**Comment by JoostK** [comment]
@klemenoslaj 

> Absolutely correct, however I was basing my thoughts on the fact that `async` is one of the most commonly used pipes and it's delivered by Angular itself.

I realized you were only targeting the usage of `async` a bit too late ;)

> While developing libraries we don't know if a developer will be using `async` pipe on our component inputs, thus we would have to include a `null` type in order to support it, right?
> This would look something like:
> 
> ```ts
> @Input() myNumber?: number | null;
> ```
> 
> Is there a reason for `async` pipe not to return `undefined` instead?

I don't really know the answer to this question, but I'm afraid it can't really be changed at this point. Perhaps a `sync` pipe could work, which requires the Observable to emit synchronously (therefore avoiding the need to introduce the `null` type).

I have most certainly seen bugs because a host element for a component is using the `async` pipe and passing down a `null` value that is indeed not expected by the library. In that regard, a library should actually include `null` in its type to indicate it is able to deal with this state. And here I agree with you that a value of `undefined` would have avoided introducing yet another type to deal with, with the downside of not being able to differentiate missing inputs vs missing data.

> > The good news is that we recently introduced an internal template type checking option to effectively ignore typing issues around null and undefined
> 
> 🎉🎉

I think this option will be the way forward, at least for the V9 timeframe.

**Comment by james-schwartzkopf** [comment]
Thanks for the clarifications.  Any idea why undefined was treated differently than null?

**Comment by klemenoslaj** [comment]
@JoostK

> with the downside of not being able to differentiate missing inputs vs missing data.

That's right, totally forgot about it. Right now I am puzzled as well.

Based on that I would assume it will always be a good practice to include null in the types of public facing inputs.
Code will get a bit nasty but I don't see a way around it without loosing the differentiation benefit 🤔
