### ISSUE TITLE
ISO string support on date pipes

### ISSUE THREAD

**Issue by splintercode** [angular/angular#3261]
The new date pipe only supports date objects or numbers but not ISO strings. In ng1 this was valid and made displaying simple JSON from api's to the UI very easy with little conversion process. 

Plunker with ng1 behavior date filter [ng1 iso](http://plnkr.co/edit/P0P0VKhmnYyJNdBcVcvM?p=preview)

**Comment by zoechi** [comment]
dup of #6336

**Comment by mip1983** [comment]
The date pipe isn't liking this date string: "2015-05-11T17:39:39.6135279+01:00", 
Even though JS will take it as a date: var myDate = new Date("2015-05-11T17:39:39.6135279+01:00");

**Comment by laskoviymishka** [comment]
There is PR for these feature already created #8038, I need to adjust to rc1

**Comment by mneitzke** [comment]
ORIGINAL EXCEPTION: Invalid argument '1465495545311' for pipe 'DatePipe'

**Comment by zoechi** [comment]
@mneitzke you need to pass a `Date` not a string

**Comment by mneitzke** [comment]
@zoechi it also works fine in the above plunker.

**Comment by laskoviymishka** [comment]
@mneitzke you have to cast your string to number.

**Comment by mneitzke** [comment]
@laskoviymishka yes. I'm well aware that a number would work. Hence pointing out that a string does not work -- in a thread titled "string support on date pipes" -- which did work in ng1, not just limited to ISO strings. let validDate = 1465495545311, would work fine given that the date is being hard coded and not from some other source such as user input or object or json or a sqlite database that stores everything as strings anyways, or anything else that gives a string rather than a number.

**Comment by laskoviymishka** [comment]
@mneitzke understood your concern. Iso string alredy in code base, but still not in NPM.

**Comment by awerlang** [comment]
@mneitzke new Date('1465495545311') gives `Invalid Date`. So I wouldn't expect nor want this special case handled in core, considering that you can plugin a pipe for you case.

**Comment by mneitzke** [comment]
Whatever. Sorry for attempting to contribute.

**Comment by laskoviymishka** [comment]
@mneitzke don't worry, you doing it great!

**Comment by mhevery** [comment]
fixed

**Comment by razvanmitre** [comment]
Hello,

On Safari 9.1.2  it still throws this error. I am using angular rc5.
`Invalid argument '2016-08-05T04:50:42+0300' for pipe 'DatePipe'`

Thanks

**Comment by awerlang** [comment]
`'2016-08-05T04:50:42+0300'` is incorrect according to ECMA-262
`'2016-08-05T04:50:42+03:00'` is correct and parses in Safari, notice the `:` in the timezone offset

Reference: http://www.ecma-international.org/ecma-262/7.0/index.html#sec-date-time-string-format
