### ISSUE TITLE
ViewContainerRef.createEmbeddedView append wrong location

### ISSUE THREAD

**Issue by keatkeat87** [angular/angular#33679]
https://github.com/keatkeat87/ng-container-issue

![image](https://user-images.githubusercontent.com/8691013/68454186-d0a02d00-0232-11ea-9a1e-ec8becc3c7fe.png)

simple append a template to view container area

![image](https://user-images.githubusercontent.com/8691013/68454316-3096d380-0233-11ea-8d73-ec318d2a690d.png)

the location incorrect, if using template outlet, the location is correct.

![ng-container-issue](https://user-images.githubusercontent.com/8691013/68454406-705dbb00-0233-11ea-9e92-619bc9fc0cf3.gif)

angular 9.0.0 rc1

**Comment by pkozlowski-opensource** [comment]
I believe that this is fixed in master via f63e5d9 and will be part of the next RC. Still, let's keep this open to add an integration test for this particular case as clearly our test coverage wasn't sufficient to catch this.

**Comment by IgorMinar** [comment]
we should test this with the latest builds or rc.2 once it's released.

**Comment by pkozlowski-opensource** [comment]
Opened a PR #33755 to add a test for this particular case - a new test passes on master so we can assume that this issue is fixed now.

**Comment by keatkeat87** [comment]
@pkozlowski-opensource 
I just update to 9.0.0 rc2, but look like this issue doesn't fix.
and look at kara test, she only test for the ngTemplateOutlet but not ViewContainerRef.createEmbeddedView(). 
can have a look on this ?

**Comment by pkozlowski-opensource** [comment]
Thnx for coming back to me on this one @keatkeat87 - I can confirm that I can reproduce your exact use-case on master. Looking into it.

**Comment by pkozlowski-opensource** [comment]
Thnx again @keatkeat87 for testing RC.2 - I can confirm now that the issue you are experiencing is a bug that wasn't covered by the existing tests! I've created a new PR with a test + fix: #33816

Thnx so much for helping us improving v9!

**Comment by pkozlowski-opensource** [comment]
This just got fixed in master via  49c9f78 - will be part of the next RC release
