### ISSUE TITLE
Error creating application with @angular/bazel

### ISSUE THREAD

**Issue by fabriziodebortoli** [angular/angular#33710]
# 🐞 Bug report
I would like to try Angular with Bazel following the instructions of the page https://next.angular.io/guide/bazel but I have errors both during the **ng new** and during the **ng build**

### Command (mark with an `x`)
```
- [x] new
- [x] build
```

### Description

`ng new --collection=@angular/bazel` throws an error

EDIT: After installing @angular/bazel package, also **ng build** throws an [ERROR](https://github.com/angular/angular-cli/issues/16116#issuecomment-551775357)

## 🔬 Minimal Reproduction
```
npm i -g @angular/cli@next @angular/bazel@next

ng new --collection=@angular/bazel
```

## 🔥 Exception or Error
<pre><code>
An unhandled exception occurred: Cannot find module '@angular-devkit/schematics'
Require stack:
- C:\Users\Admin\AppData\Roaming\npm\node_modules\@angular\bazel\src\schematics\ng-new\index.js
- C:\Users\Admin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\Admin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\Admin\AppData\Roaming\npm\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\Admin\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js
- C:\Users\Admin\AppData\Roaming\npm\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\Admin\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\Admin\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
See "C:\Users\Admin\AppData\Local\Temp\ng-2XKNxH\angular-errors.log" for further details.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-rc.1
Node: 12.13.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.0-rc.1
@angular-devkit/core         9.0.0-rc.1
@angular-devkit/schematics   9.0.0-rc.1
@schematics/angular          9.0.0-rc.1
@schematics/update           0.900.0-rc.1
rxjs                         6.5.3
</code></pre>

**Anything else relevant?**
I tried to do
```
ng new bazel-project
# and
ng add @angular/bazel
```

but with this output:
<pre><code>
Installing packages for tooling via npm.
An unhandled exception occurred: spawnSync npm ENOENT
Package install failed, see above.
See "C:\Users\Admin\AppData\Local\Temp\ng-j3oYip\angular-errors.log" for further details.
</code></pre>

EDIT: `ng add @angular/bazel' throws an error but will be solved with angular/angular-cli#16112

**Comment by manklu** [comment]
@fabriziodebortoli From my limited experience it works better with yarn.

> bazel-0.28.1-windows-x86_64.exe failed with code 1.

Is the Visual C++ Redistributable for Visual Studio 2015 installed on your machine?
See https://docs.bazel.build/versions/1.1.0/install-windows.html

**Comment by IgorMinar** [comment]
I can't reproduce this with 9.0.0-rc.1 on mac.

But let's assume that the first part of this issue should be resolved by the next rc version of the CLI via angular/angular-cli#16112.

The second part seems to be related to invoking `ngcc` during npm `postinstall`.

can you try running `npm install` in the project folder and report any errors?

**Comment by fabriziodebortoli** [comment]
> The second part seems to be related to invoking `ngcc` during npm `postinstall`.
> 
> can you try running `npm install` in the project folder and report any errors?

`npm install` completed successfully with no errors.
But `ng build` error remains

**Comment by fabriziodebortoli** [comment]
> @fabriziodebortoli From my limited experience it works better with yarn.

I tried:
```
rimraf node_modules

yarn install # Completed successfully

ng build
```

with output:
<pre><code>
ERROR: error loading package '': Unable to load file '@io_bazel_rules_webtesting//web/versioned:browsers-0.3.2.bzl': file doesn't exist
ERROR: error loading package '': Unable to load file '@io_bazel_rules_webtesting//web/versioned:browsers-0.3.2.bzl': file doesn't exist
INFO: Elapsed time: 75.143s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
C:\Microarea\bazel\node_modules\@bazel\bazel-win32_x64\bazel-0.28.1-windows-x86_64.exe failed with code 1.
</code></pre>

**Comment by JiaLiPassion** [comment]
@fabriziodebortoli, I met the same issue before, 
could you try.
```
yarn bazel clean --expunge
rimraf node_modules
```

then build again.

**Comment by IgorMinar** [comment]
I can't reproduce this on mac with 9.0.0-rc.2 any more. Does the issue reproduce for you?

Steps I used:

```
yarn global add @angular/cli@next @angular/bazel@next
ng new --collection=@angular/bazel bazel-v9-test
cd bazel-v9-test
yarn ng serve
```

**Comment by JiaLiPassion** [comment]
I can reproduce this one with `9.0.0-rc.2` for both `@angular/cli` and `@angular/bazel`, but it seems the issue has been fixed in `9.0.0-rc.5`.

**Comment by fridoo** [comment]
When add `@angular/bazel` to an existing project I also get @fabriziodebortoli  build error.

```
ng new bazel-test-add --defaults
cd bazel-test-add
ng add @angular/bazel
ng build
```

Results in

```
Starting local Bazel server and connecting to it...
ERROR: error loading package '': Unable to load file '@io_bazel_rules_webtesting//web/versioned:browsers-0.3.2.bzl': file doesn't exist
ERROR: error loading package '': Unable to load file '@io_bazel_rules_webtesting//web/versioned:browsers-0.3.2.bzl': file doesn't exist
INFO: Elapsed time: 34.122s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
/Users/fridoo/SoftwareProjects/test/bazel-add-test/node_modules/@bazel/bazel-darwin_x64/bazel-0.28.1-darwin-x86_64 failed with code 1.
```

Wherease creating a project with `--collection=@angular/bazel` and building it works.

```
ng new --collection=@angular/bazel --defaults bazel-test
cd bazel-test
ng build
```

Using @angular/cli 9.0.0_rc6

**Comment by petebacondarwin** [comment]
It sounds from https://github.com/angular/angular/issues/33710#issuecomment-563276830 that this has been solved. On top of that the bazel Angular package is deprecated.
