### ISSUE TITLE
css @keyframes leak between components

### ISSUE THREAD

**Issue by neofuture** [angular/angular#33885]
Ive found that @keyframes are not component based and a @keyframes used in one component will work across multiple components, 

I found this our by trial as I had the same @keyframes in two different components, used the same CSS rules for an .active state and one components was over righting the other

**Comment by pkozlowski-opensource** [comment]
@neofuture could you please provide a minimal reproduce scenario so we can investigate and fix? There is not much we can do without more details / reproduce scenario...

**Comment by neofuture** [comment]
https://stackblitz.com/edit/angular-move4o

top box should cycle between red and white

bottom one should cycle between blue and white

result 

both cycle by the last defined @keyframes in the demo2 css

**Comment by pkozlowski-opensource** [comment]
@neofuture thnx for the reproduce scenario. Now, one more thing to clarify: in the issue title you've put "Ivy RC0" while your stackblitz:
* is running on Angular `Ivy RC0`
* it has _no_ ivy enabled (stackblitz doesn't run with ivy).

It doesn't seem like this issue is RC.0 / ivy specific as we can reproduce it with another Angular version / without ivy. So in this sense it doesn't seem to be a regression. Does it sound right?

Also a quick note here: it seems like the root cause here is that we are not doing anything to prevent collisions on the `@kayframes` identifier names.

**Comment by neofuture** [comment]
RC0 was just where i identified the issue, i think you are right i don't think it is regression as i tried with angular 8 also last night and the issue is there too, do my "RC0" May be a red herring

**Comment by dario-piotrowicz** [comment]
Hi all, @neofuture's stackblitz example seems to be down, I've created a new example at: https://github.com/dario-piotrowicz/angular-keyframes-leak-demo

( and you can see the deployed result here: https://angular-keyframes-leak-demo.netlify.app/ )

ps: With this I can confirm that the issue is still present as of Angular 12.0.1

**Comment by dario-piotrowicz** [comment]
Hello everyone, I just fixed the issue locally in the JIT compiler

Since keyframes are not hierarchical I don't believe this issue can't be solved without modifying the keyframes names, so the only thing possible I believe is to actually rename the keyframes using the host selector, I did so by prepending the host selector to the keyframes names like so:
![Screenshot at 2021-06-19 22-23-01](https://user-images.githubusercontent.com/61631103/122655766-f569bf80-d14c-11eb-9f02-4e96f311bf2d.png)

The way I did it is by scanning the css twice, in the first scan I modified/scoped the keyframes names in the way mentioned above and in the second I updated animation rules using such keyframes 
> note: animations containing keyframes not declared in the scoped file are not modified, allowing the use of globally defined keyframes too

Please let me know if mine is an acceptable solution and if that's the case, could I please be assigned to the issue so that I can implement the same for the AOT compiler and create a PR for the fix? 

( Also if my solution is not acceptable for some reason please let me know and I will be happy to discuss and change my solution accordingly )

**Comment by neofuture** [comment]
Thanks for looking at this, its quiet an old issue now, but as you say its still not fixed, I think the stackblitz expired

**Comment by dario-piotrowicz** [comment]
I actually finished working on it and created a PR, I hope you don't mind :stuck_out_tongue_winking_eye: 

(worst case scenario, if my solution is not ok, the PR will just be rejected)

**Comment by dylhunn** [comment]
Reopening -- we tried to merge the PR for this twice, and had to roll back unfortunately.
