### ISSUE TITLE
Angular do not raise an error when mutating an array during change detection

### ISSUE THREAD

**Issue by Crocsx** [angular/angular#34131]
### Affected Package
`@angular/core`

### Is this a regression?
Do not work in Angular 6+ (didn't tested before)

### Description

**EDIT :** I tried with only `.reverse()` and `trackBy` and this still appear, so async/observable isn't the reason. *ngFor can't track by a reversed array

In my template, I am doing an `*ngFor` over an `Observable<Array<Item>>`. I also reverse that array, in order to show first the most recent item. In order to keep track of this items, I use a `trackBy` function

template.html
```
<div *ngFor="let item of (items$ | async)?.reverse() ; trackBy:trackItemId">
  <div>{{item.name}}<div>
</div>
```

component.ts
```
import { Component, OnInit, TrackByFunction } from '@angular/core';
import { Observable } from 'rxjs';

interface Item {
  name: string;
  id: string;
}

@Component({
  selector: 'app-displayer',
  templateUrl: './displayer.component.html',
  styleUrls: ['./displayer.component.css']
})
export class DisplayerComponent implements OnInit {
  items$: Observable<Array<Item>>;
  trackItemId : TrackByFunction<Item> = (i, item) => item.id;

  constructor() { }

  ngOnInit() {
    this.items$ = this.generateItem();
  }

  generateItem(): Observable<Array<Item>>{
    const items = new Array<Item>();
    const itemName = 'my Item';
    const itemId = 'id-';
    let counter = 0;
    return new Observable((obs) => {
      setInterval(() => {
        counter++;
        items.push({
          name: `${itemName}${counter}`,
          id: `${itemId}${counter}`
        })
        obs.next(items)
      }, 1000)
    })
  }
}
```

This works perfectly in **developer** mode. the item are tracked and appear in order.
But, for some reason, in **production** mode, it fails. items are constantly moved each time a new Item is added to the observable.

## 🔬 Minimal Reproduction
* be care you need to reload every time you change prod/dev mode because it's stackblitz*
https://stackblitz.com/edit/angular-yf9zsk

## Prerequisite
Add in `main.ts`

```
  enableProdMode();
```

## 🌍  Your Environment

Angular8
Angular7
Angular6

**Comment by Crocsx** [comment]
I just report cause I don't know if it's a bug, or normal.

I believe the reason is that the double check of dev mode make the reverse working, and the single check in prod mode, will not track the reversed array. 

I just also found the `reverse` operator, so maybe it's not really a bug. In that case, my apologies

**Comment by dblVs** [comment]
@Crocsx It's actually how angular works. each check on the template would trigger the reverse (in dev mode it will be twice). It's recommended that you do that inside the component. That way you don't reverse the Array unnecessarily. you could even implement some kind of a Pipe but still I would recommend moving that logic inside your component. I can give an example if you want.

**Comment by Crocsx** [comment]
@dblVs fixing it is not a problem thanks ^^

The thing is the problem do not happen in dev mode, and I notice it only when I deployed in prod that the bug appear, so it looks kind of inconsistent to me.

**Comment by dblVs** [comment]
ah yes, Sorry i misunderstood you. Usually it throws an error, but in this case reverse is called twice but it returns the same array reference so angular thinks it's the same. so if you did `.slice().reverse()` (new array), it would tell you the error.

**Comment by dblVs** [comment]
@pkozlowski-opensource What do you think? The reference to the array is the same, hence the the code doesn't throw errors. Even if we do `.slice()` to create a new array it still won't error because the result from the pipe is the same i presume. I would expect angular to error with slice, but it doesn't. At the same time i have the feeling that if thats changed to throw error it will break a lot of people. 

@Crocsx maybe you want to change the title of the issue. Your issue is that angular doesn't raise errors when you use the framework incorrectly (mutating an array inside of change detection cycle)

**Comment by Crocsx** [comment]
Noted

**Comment by dblVs** [comment]
@Crocsx it's actually correct, BUT the answer contains `.slice()`. I wouldn't recommend using though. It creates a brand new array every time the value is checked. so if your array is big it can get pretty computationally expensive. 

In your case I would recommend doing something along the lines of 
```
someVariableToBeUsedInTemplate = item$.pipe(map(array => {
  return array.slice().reverse();
}));
```
that will run the reverse only once, every time you add new item to the array and not every change detection cycle.

Also note that Async pipe removes duplicates when emitting

**Comment by Crocsx** [comment]
Thanks, yes this is what I already did now in my app, wanted just to understand the previous point.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
