### ISSUE TITLE
Sourcemaps for .d.ts files break go to definition in vscode

### ISSUE THREAD

**Issue by tmair** [angular/angular#34446]
# 🐞 bug report

### Affected Package
All core packages

### Is this a regression?
This is new in version 9 of Angular

### Description
In version 9 of Angular the `core.d.ts` file contains a sourcemap link to the `core.d.ts.map` file. The sourcemap file itself also contains the source of the `d.ts` file itself. This throws off the vscode tsserver implementation with the result that go to definition is broken for angular projects.

## 🔬 Minimal Reproduction
Steps to Reproduce:
1. Install Angular CLI
1. Create new project ng new shiny-ivy-app --enable-ivy
1. Build project ng serve
1. Open the project with vscode
1. Open app.component.ts and try to go to definition for Component

## 🔥 Exception or Error
https://github.com/microsoft/TypeScript/issues/35014

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.5
Node: 12.10.0
OS: darwin x64

Angular: 9.0.0-rc.5
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.5
@angular-devkit/build-angular      0.900.0-rc.5
@angular-devkit/build-ng-packagr   0.900.0-rc.5
@angular-devkit/build-optimizer    0.900.0-rc.5
@angular-devkit/build-webpack      0.900.0-rc.5
@angular-devkit/core               9.0.0-rc.5
@angular-devkit/schematics         9.0.0-rc.5
@ngtools/webpack                   9.0.0-rc.5
@schematics/angular                9.0.0-rc.5
@schematics/update                 0.900.0-rc.5
ng-packagr                         9.0.0-rc.3
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2
</code></pre>
<pre><code>
Visual Studio Code

Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T17:58:38.338Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0
</code></pre>

**Anything else relevant?**
There is already an issue open for this issue in the TypeScript repository. However I believe it is relevant for everybody who is using vscode to develop their angular application.

**Comment by tmair** [comment]
The issue in the TypeScript repository has been resolved.

**Comment by xsegrity** [comment]
Yea, the issue (microsoft/TypeScript#35014) has been closed/resolved but it doesn't actually fix this problem. They opened another (microsoft/TypeScript#36407) to handle this.

**Comment by IgorMinar** [comment]
Hi there, there are several issues with our source maps, so I'm not sure if one of them is the root cause of the problem you reported, or if this is yet another one. 

Related issues:
- https://github.com/angular/angular/issues/14021
- https://github.com/angular/angular/issues/19841

**Comment by petebacondarwin** [comment]
This is an upstream issue for TS/VS Code in my opinion. It is perfectly reasonable to generate inline source content in source-map files. The fact that TS services cannot handle this is not the fault of the Angular build. The source-mapping works fine when debugging in the browser. Also, the half-fix that TS has provided in https://github.com/microsoft/TypeScript/pull/36384 appears to work well enough as far as I can tell.

So @jelbourn I would mark this more like P5.

**Comment by petebacondarwin** [comment]
Tracking the underlying problem in our build system at #14021
