### ISSUE TITLE
Styles from external components are included outside the scope of a shadow DOM component

### ISSUE THREAD

**Issue by Megadesty** [angular/angular#35039]
# 🐞 bug report

### Affected Package

The issue is caused by package `@angular/platform-browser`

### Is this a regression?

No

### Description

When deploying an Angular component with `encapsulation: ViewEncapsulation.ShadowDom`, everything regarding the component should be kept inside the `#shadow-root`. This includes all stylings.

#### Actual behavior

1. Styles added by `styleUrls` or `styles` in the `@Component` decorator are added to the `#shadow-root` ✔️ 
2. Styles coming from external components like @angular/material are added to the `#shadow-root` ✔️ 
3. Styles coming from external components are *also* added to document's `<head>` outside of the `#shadow-root` ❌ 

#### Expected behavior

Only 1. and 2. should happen.

#### Root cause analysis

As far as I can see, this is caused by the `ShadowDomRenderer` using the `DomSharedStylesHost` which adds `_doc.head` to its list of known `_hostNodes` in the constructor:
https://github.com/angular/angular/blob/d43187f7ef7e841d84ecf594e8e515a9d534daaa/packages/platform-browser/src/dom/shared_styles_host.ts#L39

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-material-shadowdom-styles

In the `<head>` section there are `<style>` tags of Material components, which should only be inside the shadow DOM.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.23
Node: 12.7.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.23
@angular-devkit/build-angular     0.803.23
@angular-devkit/build-optimizer   0.803.23
@angular-devkit/build-webpack     0.803.23
@angular-devkit/core              8.3.23
@angular-devkit/schematics        8.3.23
@angular/cdk                      8.2.3
@angular/cli                      8.3.23
@angular/material                 8.2.3
@ngtools/webpack                  8.3.23
@schematics/angular               8.3.23
@schematics/update                0.803.23
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Comment by alexeykostevich** [comment]
Thank for raising the issue and adding all the details, @Megadesty !

It seems that the issue is reproducible for both application and external components and depends only on components' `ViewEncapsulation` option (https://angular.io/api/core/ViewEncapsulation).

So, we could generalize the problem this way:
- Component with `ViewEncapsulation.Emulated` used inside Shadow DOM, add their styles to both document's <head> and a corresponding Shadow Root (if any).

Here is a slightly updated reproduction of the issue:
https://stackblitz.com/edit/angular-material-shadowdom-styles-zb72ry

**Comment by alexeykostevich** [comment]
Let me also share our use case to understand a possible impact better.

Our team is developing a browser extension and embed a panel in host pages. In order to isolate and encapsulate our styles, we bootstrap our app as a Web Component (https://angular.io/guide/elements) and use `ViewEncapsulation.ShadowDom` for the root component.

Due to this issue, components' styles leak from Shadow DOM to a host page. However, since these styles are still scoped (thanks to surrogate ids), they unlikely to interfere with a host's styles.

**Comment by Megadesty** [comment]
@alexeykostevich Your extended example is excellent and showcases the (faulty) behavior with components `ViewEncapsulation.Emulated` inside a `#shadow-root` as well, thanks!

I think if you are happy with the surrogate ids, that's fine. But as you can see in my and your example, the common Material styles (like `.mat-card {...}`) are also included in both the document and `#shadow-root`. Now think about having mulitple Web Components on one page, all are self-contained Angular apps using Material. What you get in the end is that each component injects its own Material style in the document and since they are always named the same, they are overwriting each other. This could lead to trouble if one Web Component uses an older Angular or Material version or another Material theme. And even if all Web Components are using the same Material version and the same theme, in my opinion this is not good at all.

In our case we already have multiple Web Components using Angular with Material on a page. The document's `<head>` looks like this:

![image](https://user-images.githubusercontent.com/5328560/78582989-7aadd080-7836-11ea-9760-2a3f625e62fe.png)

If the Angular team fixes this issue, I guess it won't have an impact on your project. Except you are using global styles from a Web Component outside the component, but that sounds like a bad practice anyway.

**Comment by courtney-regis** [comment]
@Megadesty 

We have encountered the same issue. One way we've worked around it is that we have a  project dedicated to creating web components. In the bootstrapped module where we declare our custom elements, we do the following in the constructor:

````typescript
import { Injector } from "@angular/core";
import { DomSharedStylesHost } from "@angular/platform-browser";

constructor(private injector: Injector) {
    this.injector.get(DomSharedStylesHost).removeHost(document.head);
}

````

**Comment by tuckerjt07** [comment]
> @Megadesty
> 
> We have encountered the same issue. One way we've worked around it is that we have a project dedicated to creating web components. In the bootstrapped module where we declare our custom elements, we do the following in the constructor of the NgModule:
> 
> ```ts
> import { Injector } from "@angular/core";
> import { ɵDomSharedStylesHost } from "@angular/platform-browser";
> 
> constructor(private injector: Injector) {
>     this.injector.get(ɵDomSharedStylesHost).removeHost(document.head);
> }
> ```

This worked like a charm. Thank you!

**Comment by samatawy** [comment]
@Megadesty You saved my life. I can't thank you enough.

**Comment by samatawy** [comment]
> We have encountered the same issue. One way we've worked around it is that we have a project dedicated to creating web components. In the bootstrapped module where we declare our custom elements, we do the following in the constructor of the NgModule:
> 
> ```ts
> import { Injector } from "@angular/core";
> import { ɵDomSharedStylesHost } from "@angular/platform-browser";
> 
> constructor(private injector: Injector) {
>     this.injector.get(ɵDomSharedStylesHost).removeHost(document.head);
> }
> ```

Absolute life-saver. I could not thank you enough.

**Comment by r1m** [comment]
I'm seeing a similar issue with custom elements declared with **Emulated** encapsulation.

If you use a custom element declared with Angular outside the Angular app itself, its style is added only in the document header, **not on the parent shadowRoot**. 

So their style are simply ignore because outside of the shadow tree.

https://stackblitz.com/edit/2fxyhh?file=src%2Fapp%2Fmy.component.ts

In this blitz the component display status
- ✔️ correctly displayed in its own the Angular app 
- ❌ **not styled** in the native container outside the app (for a component library) 
- ❌ **not styled** inside another app that does not share the same platform/injector (MFE approach).

**Comment by scottfwalter** [comment]
Perhaps this is fixed in Angular 17.  If I include a material theme in a ShadowDom component the material styles are added in the shadow dom:

![CleanShot 2024-02-09 at 20 48 05@2x](https://github.com/angular/angular/assets/1752854/fd4e2931-ca0a-4120-8ff9-1fa0ccdf9168)

**Comment by roshan-naralkar** [comment]
Unfortunately I still face same issue in Angular 17 as well. Do anyone can help me to understand what adjustment can be done?

**Comment by Ramesh-Mu** [comment]
I tried the following workaround, and it works well if the shadow DOM is the root element. However, let’s say my main app component contains a header component with ViewEncapsulation.None and a mainContainer with ViewEncapsulation.Shadow. When I add an element under the mainContainer, it works as expected and avoids duplicate styles in the root DOM.

But if I add an element under the headerComponent, no styles are applied properly. This happens because new changes are always adding styles under the shadow DOM.

```
import { Injector } from "@angular/core";
import { ɵDomSharedStylesHost } from "@angular/platform-browser";

constructor(private injector: Injector) {
    this.injector.get(ɵDomSharedStylesHost).removeHost(document.head);
}
```

I would appreciate any help to overcome this issue. Thank you!

**Comment by robert-isaac-sap** [comment]
shouldn't this be closed since it's fixed in https://github.com/angular/angular/pull/58482

**Comment by AStoker** [comment]
I think that's a different issue, "ghost". What I think they're describing here (and what I'm frustratingly experiencing myself) is that styles that belong to components that **aren't** used by the shadow dom component are being included. This means that for every shadow dom component in the dom, duplicate stylesheets are being included (in that shadow dom) for *every component in the application*, despite whether or not that component is used by the shadow dom component. 

So my situation is like this, I have about 30+ individual components, all just using the default emulated encapsulation. But I have **one** shadow dom component (it's used to render svg's, so it's minimal in code), but that component is used hundreds of times in the application. What's happening is that for **every** instance of the shadow dom component, it's also including 30+ stylesheets in that shadow dom (despite not needing, or wanting, any of them). This results in a substantial increase in dom size, despite just being a pain with styles.

The current behavior with shadow dom really renders it useless according how the ecmascript spec for shadow dom intends it to be used. If you want other component styles to be included, shadow dom *might* not be the approach you need.

**Comment by stephanebouget** [comment]
Hello,

Do you know if this issue still occurs with Angular 18 or 19? (My app is huge and migrating from Angular 17 is very heavy, I can't just test it) 

Thank you!

**Comment by ryan-bendel** [comment]
> Hello,
> 
> Do you know if this issue still occurs with Angular 18 or 19? (My app is huge and migrating from Angular 17 is very heavy, I can't just test it)
> 
> Thank you!

It does, this has still not been fixed. Loads of styles unrelated to the component are still included per component instance. Frustrating.

**Comment by nonodev96** [comment]
I just saw the following commit: [d24d5742db694604b09d57a3503e8c32751c4836](https://github.com/angular/angular/commit/d24d5742db694604b09d57a3503e8c32751c4836)

It looks like it addresses this issue.
Is it planned to be included in the next release?

**Comment by JeanMeche** [comment]
@nonodev96 We ship feature in minor releases. The next one, 20.2.0 is scheduled in 2 weeks (with the RC beeing shipped next week).

**Comment by JeanMeche** [comment]
Per above #62723 will ship in 21.0
