### ISSUE TITLE
Angular 9 - Angular core has no exported member ɵɵFactoryDef

### ISSUE THREAD

**Issue by reeceward-vpm** [angular/angular#35291]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?
Yes, the previous version in which this bug was not present was: 8

### Description

Running ng build/serve after updating to angular 9 produces a number of errors, all surrounding an export in angular/core

## 🔥 Exception or Error
<pre><code>

../node_modules/@angular/common/common.d.ts:180:25 - error TS2694: Namespace '"/home/reece/sites/portal-front-end/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

180     static ɵfac: ɵngcc0.ɵɵFactoryDef<CurrencyPipe>;
                            ~~~~~~~~~~~~
../node_modules/@angular/common/common.d.ts:340:25 - error TS2694: Namespace '"/home/reece/sites/portal-front-end/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

340     static ɵfac: ɵngcc0.ɵɵFactoryDef<DatePipe>;
                            ~~~~~~~~~~~~
../node_modules/@angular/common/common.d.ts:399:25 - error TS2694: Namespace '"/home/reece/sites/portal-front-end/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

399     static ɵfac: ɵngcc0.ɵɵFactoryDef<DecimalPipe>;
                            ~~~~~~~~~~~~
../node_modules/@angular/common/common.d.ts:434:25 - error TS2694: Namespace '"/home/reece/sites/portal-front-end/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

434     static ɵfac: ɵngcc0.ɵɵFactoryDef<DeprecatedCurrencyPipe>;
                            ~~~~~~~~~~~~
../node_modules/@angular/common/common.d.ts:506:25 - error TS2694: Namespace '"/home/reece/sites/portal-front-end/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

506     static ɵfac: ɵngcc0.ɵɵFactoryDef<DeprecatedDatePipe>;
                            ~~~~~~~~~~~~
../node_modules/@angular/common/common.d.ts:540:25 - error TS2694: Namespace '"/home/reece/sites/portal-front-end/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

540     static ɵfac: ɵngcc0.ɵɵFactoryDef<DeprecatedDecimalPipe>;
                            ~~~~~~~~~~~~
../node_modules/@angular/common/common.d.ts:579:25 - error TS2694: Namespace '"/home/reece/sites/portal-front-end/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

579     static ɵfac: ɵngcc0.ɵɵFactoryDef<DeprecatedPercentPipe>;
                            ~~~~~~~~~~~~
../node_modules/@angular/common/common.d.ts:1042:25 - error TS2694: Namespace '"/home/reece/sites/portal-front-end/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

1042     static ɵfac: ɵngcc0.ɵɵFactoryDef<HashLocationStrategy>;
                             ~~~~~~~~~~~~
../node_modules/@angular/common/common.d.ts:1073:25 - error TS2694: Namespace '"/home/reece/sites/portal-front-end/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

1073     static ɵfac: ɵngcc0.ɵɵFactoryDef<I18nPluralPipe>;
                             ~~~~~~~~~~~~
../node_modules/@angular/common/common.d.ts:1104:25 - error TS2694: Namespace '"/home/reece/sites/portal-front-end/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

1104     static ɵfac: ɵngcc0.ɵɵFactoryDef<I18nSelectPipe>;
                             ~~~~~~~~~~~~
../node_modules/@angular/common/common.d.ts:1153:25 - error TS2694: Namespace '"/home/reece/sites/portal-front-end/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

1153     static ɵfac: ɵngcc0.ɵɵFactoryDef<JsonPipe>;
                             ~~~~~~~~~~~~
../node_modules/@angular/common/common.d.ts:1202:25 - error TS2694: Namespace '"/home/reece/sites/portal-front-end/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

1202     static ɵfac: ɵngcc0.ɵɵFactoryDef<KeyValuePipe>;
                             ~~~~~~~~~~~~
../node_modules/@angular/common/common.d.ts:1350:25 - error TS2694: Namespace '"/home/reece/sites/portal-front-end/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

1350     static ɵfac: ɵngcc0.ɵɵFactoryDef<Location>;
                             ~~~~~~~~~~~~
../node_modules/@angular/common/common.d.ts:1428:25 - error TS2694: Namespace '"/home/reece/sites/portal-front-end/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

1428     static ɵfac: ɵngcc0.ɵɵFactoryDef<LowerCasePipe>;
                             ~~~~~~~~~~~~
../node_modules/@angular/common/common.d.ts:1468:25 - error TS2694: Namespace '"/home/reece/sites/portal-front-end/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

1468     static ɵfac: ɵngcc0.ɵɵFactoryDef<NgClass>;
                             ~~~~~~~~~~~~
../node_modules/@angular/common/common.d.ts:1564:25 - error TS2694: Namespace '"/home/reece/sites/portal-front-end/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

1564     static ɵfac: ɵngcc0.ɵɵFactoryDef<NgComponentOutlet>;
                             ~~~~~~~~~~~~
../node_modules/@angular/common/common.d.ts:1720:25 - error TS2694: Namespace '"/home/reece/sites/portal-front-end/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

1720     static ɵfac: ɵngcc0.ɵɵFactoryDef<NgForOf<any>>;
                             ~~~~~~~~~~~~
../node_modules/@angular/common/common.d.ts:1912:25 - error TS2694: Namespace '"/home/reece/sites/portal-front-end/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

1912     static ɵfac: ɵngcc0.ɵɵFactoryDef<NgIf>;

</code></pre>


## 🌍  Your Environment

**Angular Version:**
<pre><code>
<!-- run `ng version` and paste output below -->
<!-- ✍️-->
Angular CLI: 9.0.1
Node: 13.8.0
OS: linux x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router, upgrade
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@nguniversal/common               9.0.0
@nguniversal/express-engine       9.0.0
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**
<!-- ✍️Is this a browser specific issue? If so, please specify the browser and version. -->

<!-- ✍️Do any of these matter: operating system, IDE, package manager, HTTP server, ...? If so, please mention it below. -->

**Comment by seanlandsman** [comment]
I get this too - I'm in a monorepo (lerna) environment so perhaps symlinks are a problem here?

**Comment by kara** [comment]
@reeceward-vpm Can you provide a Github repro for this? It's hard to investigate without some code.

**Comment by mamacdon** [comment]
Here's a reproduction repository: https://github.com/mamacdon/ng-repro-lib.

It's a library project using Angular 9 and compiled with `ng build`. It compiles with no errors:

```console
$ cd ng-repro-lib
$ yarn build-lib                                                                                     130 ↵
yarn run v1.22.0
$ ng build gem-ui-common-ng
Building Angular Package
……………

Built Angular Package
 - from: /private/tmp/gem/ng-repro-lib/projects/gem-ui-common-ng
 - to:   /private/tmp/gem/ng-repro-lib/dist/gem-ui-common-ng
------------------------------------------------------------------------------
✨  Done in 9.05s.
```

…but when I actually use the compiled output from an app running Angular 8, I get similar errors as @reeceward-vpm:

```
19     static ɵfac: i0.ɵɵFactoryDef<MinDirective>;
                       ~~~~~~~~~~~~
../node_modules/@dpod/gem-ui-common-ng/lib/minmax/max.directive.d.ts:19:21 - error TS2694: Namespace '"/Users/mamacdon/code/my_application/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.
```

If I recompile the library project using @seanlandsman's workaround (i.e. disabling ivy), the errors go away.

Also, here's what one of the compiled files looks like:

```console
$ cat dist/gem-ui-common-ng/lib/minmax/max.directive.d.ts                                            130 ↵
import { OnInit } from '@angular/core';
import { AbstractControl, Validator, ValidationErrors } from '@angular/forms';
import * as i0 from "@angular/core";
 ……
export declare class MaxDirective implements Validator, OnInit {
    max: number;
    ngOnInit(): void;
    validate(control: AbstractControl): ValidationErrors | null;
    static ɵfac: i0.ɵɵFactoryDef<MaxDirective>;
    static ɵdir: i0.ɵɵDirectiveDefWithMeta<MaxDirective, "[max]", never, { "max": "max"; }, {}, never>;
}
```

**Comment by seanlandsman** [comment]
Good stuff @mamacdon - I came to exactly the same conclusion today (and with the same scenario - writing an angular library). Fine when the consumer users Angular 9, but not if they use Angular 8.

I was working on a repro of the issue but you've beat me to it :-)

**Comment by addsmoll** [comment]
**portal-front-end** in **gem-ui-common-ng**
Find the import from the old repository in current project and delete it.

**Comment by seanlandsman** [comment]
Anothe repro if it helps: https://github.com/seanlandsman/angular-ivy-library

**Comment by JoostK** [comment]
It seems to me that you are using Ivy compiled libraries in Angular 8. **This is not compatible**, and it's not meant to be.

As of right now, libraries **should be** published with Ivy disabled, otherwise their compatibility with Angular versions, both older and upcoming versions is highly crippled. The reason is that Ivy's generated code (its instruction set) is not set in stone yet, so changes are to be expected. At this moment there's no backwards compatibility guarantees on the generated code, so it should really not be shipped to NPM.

@reeceward-vpm From the issue description I cannot conclude that the errors occur in an Angular 8 app, so I'm not sure whether the version incompatibility is the root cause of your issue. As such, leaving this open with the "Needs repro" label.

**Comment by seanlandsman** [comment]
The problem - for me - was that I had (incorrectly) assumed that `ng build --prod` would perform a production build ready to deploy, but from what you've said (and looking at the tsconfig.lib files) but I see now that I need to explicitly state that I'm building for production `ng build --prod`

This caught me out, but I see that this is documented here: https://angular.io/guide/creating-libraries#publishing-your-library

**Comment by JayChase** [comment]
It looks like` ng build --prod` will fix the issue because the config used **tsconfig.lib.prod.json** has `"enableIvy": false`.

**Comment by Githamza** [comment]
I get this error after I tried to upgrade to angular 9 In a separate brunch but after I returned to v8 branch I get this error

**Comment by bryce13950** [comment]
I got the same problem while upgrading a project for angular 8 to 9

**Comment by nnamacha** [comment]
got the same problem while upgrading a project for angular 8 to 9  and that helped thanks

**Comment by IreeProg** [comment]
I fixed same problem by adding to ` tsconfig.json`
```
"compilerOptions": {
        ...
        "paths": { "@angular/*": ["./node_modules/@angular/*"] }
}
```

After deleting all code in AppService except :
```
    @Injectable({
	providedIn: 'root'})
     export class AppService {}
```

in Terminal I saw:
```
 Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'Injectable'
    'Injectable' calls 'ɵmakeDecorator'.

```
Look at Issues:
https://github.com/angular/angular-cli/issues/10832
https://github.com/angular/angular/issues/32694

**Comment by petebacondarwin** [comment]
Closing as it appears that using the documented `ng build --prod` for libraries produces the correct (non-ivy) distributables for libraries.

**Comment by grosch** [comment]
What about when it's *not* a library?  I just upgraded my Angular 8 website to Angular 9 and I'm getting this same error.  I removed node_modules and it still fails.  Doesn't matter whether I'm doing a production build or not.

**Comment by JoostK** [comment]
@grosch That may happen if there's multiple versions of Angular present in `node_modules`, i.e. some dependency has a direct dependency (instead of a peer dependency) on an older version of Angular. You can figure this out using `npm ls @angular/core`.

**Comment by grosch** [comment]
@JoostK Thank you so much!

**Comment by grosch** [comment]
@JoostK I removed the offending modules and now the `npm ls @angular/core` looks like this:

```
LaMP@0.0.0 C:\Users\grosch\documents\lamp\web
`-- @angular/core@9.1.3
```

But when I run the build, I still get those same errors.

**Comment by JoostK** [comment]
@grosch That I cannot explain without more info. Could you try removing `node_modules` and installing and building from scratch, then share all output?

**Comment by grosch** [comment]
@JoostK Seems to be a problem with a vendor library.  I'm working with them on a fix.  Thanks again.
