### ISSUE TITLE
Warning while building library

### ISSUE THREAD

**Issue by csbenjamin** [angular/angular#36518]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

When we create a library named **my-lib**, angular cli adds the following to tsconfig.json:

      "my-lib": [
        "dist/my-lib/my-lib",
        "dist/my-lib"
      ]

When we build the library using `ng build my-lib`, we see the following warning several times in the console:
```
Warning: The basePath "/somepath/my-workspace/dist/my-lib/my-lib.d.ts" computed from baseUrl "/somepath/my-workspace" and path mapping "/somepath/my-workspace/dist/my-lib/my-lib.d.ts" does not exist in the file-system.
It will not be scanned for entry-points.
```
In the end, the build succeeds, but the warning is annoying. It was printed 9 time while building.

## 🔬 Minimal Reproduction

```
ng new my-workspace --create-application=false
cd my-workspace
ng generate library my-lib
ng build my-lib
```

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.0
Node: 13.12.0
OS: linux x64

Angular: 9.1.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.0
@angular-devkit/build-angular      0.901.0
@angular-devkit/build-ng-packagr   0.901.0
@angular-devkit/build-optimizer    0.901.0
@angular-devkit/build-webpack      0.901.0
@angular-devkit/core               9.1.0
@angular-devkit/schematics         9.1.0
@angular/cli                       9.1.0
@ngtools/webpack                   9.1.0
@schematics/angular                9.1.0
@schematics/update                 0.901.0
ng-packagr                         9.1.0
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
</code></pre>

**Comment by alan-agius4** [comment]
@petebacondarwin, let's take this offline.

**Comment by csbenjamin** [comment]
> Does your path mapping contain: `/somepath/my-workspace/dist/my-lib/my-lib.d.ts`?

@petersalomonsen When we create a new project the folder `/somepath/my-workspace/dist` even doesn't exist. When we run `ng build my-lib` we see the warnings. But, even in a second running of `ng build my-lib` we see the warnings, because before building, `ng build` remove `/somepath/my-workspace/dist/my-lib` directory for then to recreate again.

OBS: Note the path missing is exactly what I want to create running `ng build my-lib` command.

**Comment by petebacondarwin** [comment]
Yep - my bad. I thought it would be helpful since we have had some issue in the past where the `paths` were incorrect and it broke ngcc processing. But I see that this is going to be really annoying. So I'll revert that bit.

**Comment by Annie-Huang** [comment]
Why is this issue closed? This is still happening. So this an warning I can ignore?
I am using "@angular/cli": "~9.1.1", 

and run this:
Annie@DESKTOP-BH46C1T MINGW64 /c/temp
$ **ng new my-angular9dot1-app --routing=true --style=scss**

Annie@DESKTOP-BH46C1T MINGW64 /c/temp/my-angular9dot1-app (master)
$ **ng generate library ea-ui --prefix=eui**

C:\Temp\my-angular9dot1-app>**npm run build**

And I got a whole bunch of warning:
```
WARNING in The basePath "C:/Temp/my-angular9dot1-app/dist/ea-ui/ea-ui" computed from baseUrl "C:/Temp/my-angular9dot1-app" and path mapping "dist/ea-ui/ea-ui" does not exis
t in the file-system.
It will not be scanned for entry-points.

WARNING in The basePath "C:/Temp/my-angular9dot1-app/dist/ea-ui" computed from baseUrl "C:/Temp/my-angular9dot1-app" and path mapping "dist/ea-ui" does not exist in the fil
e-system.
It will not be scanned for entry-points.
....
```

**Comment by alan-agius4** [comment]
@Annie-Huang, this has been closed as it was fixed via https://github.com/angular/angular/pull/36525

The fix will be available in 9.1.2

**Comment by Roaders** [comment]
What confuses me is that I still get the warning when I move the paths from the base tsconfig to tsconfig.app.json. I don't want the path mappings to be available to my library (I'll just use relative paths), I only want it available to my app.

In fact. it still happens if I remove all paths from all tsconfig files????

Why do I still get the warnings?

**Comment by hughanderson4** [comment]
This is happening to me when Lerna hoists the dependencies in my monorepo to a higher level, and uses symlinks.  There's no physical path there but there is a symlink to the actual path.

I also do not see this as fixed in 9.1.2 (installed yesterday).

```
WARNING in The basePath "C:/code/ace/packages/ace-shell/node_modules/rxjs" computed from baseUrl "C:/code/ace/packages/ace-shell" and path mapping "node_modules/rxjs" does not exist in the file-system.
It will not be scanned for entry-points.
```

**Comment by petebacondarwin** [comment]
This should be fixed in 9.1.2 - see https://github.com/angular/angular/commit/33eee43
Please can you check your version and update if necessary?

**Comment by Yohandah** [comment]
@petebacondarwin Hey, I have the following in my package.json
    ```
"@angular/animations": "~9.1.2",
    "@angular/cdk": "~9.2.1",
    "@angular/common": "~9.1.2",
    "@angular/core": "~9.1.3",
    "@angular/forms": "~9.1.2",
    "@angular/localize": "^9.1.2",
    "@angular/material": "~9.2.1",
    "@angular/platform-browser": "~9.1.2",
    "@angular/platform-browser-dynamic": "~9.1.2",
    "@angular/pwa": "^0.901.1",
    "@angular/router": "~9.1.2",
    "@angular/service-worker": "~9.1.2"
```

but I still have the following error :

> client:135 The basePath "C:/Users/me/folder/folder/folder/project/node_modules/core-js/proposals/reflect-metadata" computed from baseUrl "C:/Users/me/folder/folder/folder/project" and path mapping "node_modules/core-js/proposals/reflect-metadata" does not exist in the file-system.
> It will not be scanned for entry-points.

**Comment by petebacondarwin** [comment]
I believe that this is a warning not an error?

Does `C:/Users/me/folder/folder/folder/project/node_modules/core-js/proposals/reflect-metadata` exist? If not then the given path mapping `"core-js/es7/reflect": ["node_modules/core-js/proposals/reflect-metadata"],` will not match. This is not necessarily a problem, but we have found that occasionally people have invalid path mappings and ngcc then misses building potential libraries. Hence the warning message.

**Comment by Yohandah** [comment]
@petebacondarwin yes, I meant warning sorry. 

Yes the path exists in node_modules.

But it turns out I no longer need these mappings and these imports in polyfill.js, it was from when my app was on Angular 6 and needed to be run on IE11. After deleting the mappings in tsconfig.js and the following lines in polyfill.js I no longer have the warning ! 

```
import "core-js/es6/symbol";
import "core-js/es6/object";
import "core-js/es6/function";
import "core-js/es6/parse-int";
import "core-js/es6/parse-float";
import "core-js/es6/number";
import "core-js/es6/math";
import "core-js/es6/string";
import "core-js/es6/date";
import "core-js/es6/array";
import "core-js/es7/array";
import "core-js/es7/reflect";
import "core-js/es6/regexp";
import "core-js/es6/map";
import "core-js/es6/weak-map";
import "core-js/es6/set";
import "core-js/es6/reflect";
```
