### ISSUE TITLE
Solution tsconfig not working on library dev or monorepo setup

### ISSUE THREAD

**Issue by JohnnyDevNull** [angular/angular#37781]
# 🐞 bug report

### Affected Package

@angular/cli migration for solution tsconfig

### Is this a regression?

Angular 9 just worked fine

### Description

When the Angular project is used in workspace mode the tsconfig paths for libraries and local stuff will not work no more, because of the solution tsconfig setup.

## 🔬 Minimal Reproduction

```
ng new ng-test --create-application=false --skipInstall --skipGit
ng g library my-test --prefix=mt
ng g library my-test2 --prefix=mt2
ng g application
ng build --project=my-test
ng build --project=my-test2
```
After this setup reload your VSCode oder WebStorm and just try to import the Libraries Modules in the AppModule.

### The generated configs from the CLI:

tsconfig.json
```
/*
  This is a "Solution Style" tsconfig.json file, and is used by editors and TypeScript’s language server to improve development experience.
  It is not intended to be used to perform a compilation.

  To learn more about this file see: https://angular.io/config/solution-tsconfig.
*/
{
  "files": [],
  "references": [
    {
      "path": "./projects/my-test/tsconfig.lib.json"
    },
    {
      "path": "./projects/my-test/tsconfig.spec.json"
    },
    {
      "path": "./projects/my-test2/tsconfig.lib.json"
    },
    {
      "path": "./projects/my-test2/tsconfig.spec.json"
    },
    {
      "path": "./projects/my-tester/tsconfig.app.json"
    },
    {
      "path": "./projects/my-tester/tsconfig.spec.json"
    },
    {
      "path": "./projects/my-tester/e2e/tsconfig.json"
    }
  ]
}
```

tsconfig.base.ts
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "my-test": [
        "dist/my-test/my-test",
        "dist/my-test"
      ],
      "my-test2": [
        "dist/my-test2/my-test2",
        "dist/my-test2"
      ]
    }
  }
}
```

## 🔥 Exception or Error

All my Editors, VSCode & WebStorm do not recognize the paths and imports no more. Code Completion stoped working, but ng serve or ng build works just fine.

![image](https://user-images.githubusercontent.com/5759334/85901125-68be4700-b801-11ea-9096-86b4ec5a6542.png)

![image](https://user-images.githubusercontent.com/5759334/85901307-d4a0af80-b801-11ea-9ca1-281c68a1fa96.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.0
Node: 12.18.0
OS: linux x64

Angular: 10.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.0
@angular-devkit/build-angular      0.1000.0
@angular-devkit/build-ng-packagr   0.1000.0
@angular-devkit/build-optimizer    0.1000.0
@angular-devkit/build-webpack      0.1000.0
@angular-devkit/core               10.0.0
@angular-devkit/schematics         10.0.0
@ngtools/webpack                   10.0.0
@schematics/angular                10.0.0
@schematics/update                 0.1000.0
ng-packagr                         10.0.0
rxjs                               6.5.5
typescript                         3.9.5
webpack                            4.43.0
</code></pre>

**Anything else relevant?**

As i can read from the docs this should be a editor improvement, but can't realize whats the improvement then just them stopping to work. Angular names it as a enterprise framework, this is also true for enterprise setups just like libraries for sharing code. Especially in Monorepo setups with multiple apps and just them now not working with this setup.

**Comment by JoostK** [comment]
Please try again with 10.0.1, released in the last hour or so.

**Comment by JohnnyDevNull** [comment]
Nope still the same... just removing the solution setup back to the old works.

**Comment by JoostK** [comment]
Ah, it requires a release of the LS plugin. Please follow https://github.com/angular/vscode-ng-language-service/issues/824 for updates and relevant comments.

**Comment by kyliau** [comment]
This has been fixed in v0.1000.1 which just got released.
https://github.com/angular/vscode-ng-language-service/releases/tag/v0.1000.1
I'll close this issue for now, please open a new issue if you run into problem with solution-style tsconfig.

**Comment by JohnnyDevNull** [comment]
I don't know what you've done, but this is still not working. Wether with VSCode nore with WebStorm.

What i've done:

* Removed the node_modules folder and package-lock.json, so that a complete reinstall is done
* Reloaded VSCode and installed updated the Angular Language Service Plugin
* Opened the first TS file and waitet for initializing

Same picture as above... no library completion and the configured TS-Flags from the tsconfig.base.ts are also missing

**Comment by destus90** [comment]
I have the same exact problem with ng 10 in most IDEs. I have created an issue in the CLI repo and looking forward to a fix. https://github.com/angular/angular-cli/issues/18040

**Comment by alan-agius4** [comment]
@destus90, your issue in not related to the Angular LS, but rather to the fact that the file is not being picked up by any LS because it’s not part of any compilation.

**Comment by JohnnyDevNull** [comment]
Just to mention this here https://github.com/angular/vscode-ng-language-service/issues/824#issuecomment-650579235

This is still not working! The issue should be re-opened.
