### ISSUE TITLE
Angular-Cli 10.1.0-next.6 - extract-i18n - id is ignored

### ISSUE THREAD

**Issue by muehle28** [angular/angular#38590]
When extracting translations with the flag ivy=true for every template translation the id is beeing ignored and generated new.
`<h1 i18n="header|Header1@@oo.header">Header</h1>`

```
 <trans-unit id="db3e99094d8ff1d99fc6069acbc6c35d1ce70fa2" datatype="html">
        <source>Header</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/components/header.component.ts</context>
          <context context-type="linenumber">445</context>
        </context-group>
        <note priority="1" from="description">Header1</note>
        <note priority="1" from="meaning">header</note>
</trans-unit>
```

Code translations are working fine.
`$localize:header|Header1@@oo.header`

**Comment by petebacondarwin** [comment]
This should be fixed by https://github.com/angular/angular/pull/38498 which was released in `10.1.0-next.8`. Can you test with that version please?

**Comment by muehle28** [comment]
With the version 10.1.0-next.8 the error is gone.

I'm still getting following warning for every file when doing a i18n extract:

```
WARNING in ./src/app/app.component.ts
Module Warning (from ./node_modules/@angular-devkit/build-angular/src/extract-i18n/ivy-extract-loader.js):
(Emitted value instead of an instance of Error) Unable to fully load /home/m/development/projects/mm-app/src/app/app.component.ts for source-map flattening: Circular source file mapping dependency: /home/m/development/projects/mm-app/src/app/app.component.ts.map -> /home/m/development/projects/mm-app/src/app/app.component.ts.map
NonErrorEmittedError: (Emitted value instead of an instance of Error) Unable to fully load /home/m/development/projects/mm-app/src/app/app.component.ts for source-map flattening: Circular source file mapping dependency: /home/m/development/projects/mm-app/src/app/app.component.ts.map -> /home/m/development/projects/mm-app/src/app/app.component.ts.map
    at Object.emitWarning (/home/m/development/projects/mm-app/node_modules/webpack/lib/NormalModule.js:160:16)
    at Object.warn (/home/m/development/projects/mm-app/node_modules/@angular-devkit/build-angular/src/extract-i18n/ivy-extract-loader.js:32:27)
    at SourceFileLoader.loadSourceFile (/home/m/development/projects/mm-app/node_modules/@angular/compiler-cli/src/ngtsc/sourcemaps/src/source_file_loader.js:69:29)
    at /home/m/development/projects/mm-app/node_modules/@angular/compiler-cli/src/ngtsc/sourcemaps/src/source_file_loader.js:121:30
    at Array.map (<anonymous>)
    at SourceFileLoader.processSources (/home/m/development/projects/mm-app/node_modules/@angular/compiler-cli/src/ngtsc/sourcemaps/src/source_file_loader.js:118:32)
    at SourceFileLoader.loadSourceFile (/home/m/development/projects/mm-app/node_modules/@angular/compiler-cli/src/ngtsc/sourcemaps/src/source_file_loader.js:62:36)
    at MessageExtractor.updateSourceLocations (/home/m/development/projects/mm-app/node_modules/@angular/localize/src/tools/src/extract/extraction.js:59:42)
    at MessageExtractor.extractMessages (/home/m/development/projects/mm-app/node_modules/@angular/localize/src/tools/src/extract/extraction.js:49:22)
    at Object.localizeExtractLoader (/home/m/development/projects/mm-app/node_modules/@angular-devkit/build-angular/src/extract-i18n/ivy-extract-loader.js:69:32)
 @ ./src/app/app.module.ts 8:0-47 100:68-80 126:116-128 176:20-32 241:28-40
 @ ./src/main.ts
 @ multi ./src/main.ts


```

**Comment by petebacondarwin** [comment]
Hmm, we should talk to @clydin about that warning. I think it might be related to how we are providing the files to the extractor.

**Comment by petebacondarwin** [comment]
This should have been fixed by https://github.com/angular/angular-cli/commit/71360878d9e0b1b4c88c72b800692c6ce5f3422e which should be included in the next release.
