### ISSUE TITLE
Incremental AOT compilation is 5 times slower in Angular 11.1 comparing to 10.1

### ISSUE THREAD

**Issue by amakhrov** [angular/angular#40635]
# 🐞 bug report

### Is this a regression?
Yes, it was better in Angular 10.1.

### Description
After upgrading the app to 11.1 I observed regression in build time - both initial and incremental. While intial build time increased by 10% (150s to 165s), further incremental compilations in watch mode looks times slower.

There are two different cases I wanted to describe:
- Making an edit in a page-level component - it has a number of dependencies on its own, but relatively few other modules depend on it; it's imported directly by the routing module.
- Making an edit into a low-level shared module that is used by virtually every component in the app.

Here is the timing breakdown:

|                            | Angular 10.1 | Angular 11.1
|----------------------------|------------|------------
|initial                                | 150s       | 165s 
|incremental - page-level edit     | 3s         | 8s
|incremental - shared low-level edit   | 9s         | **40s** ❗️

CPU profile (via `node --inspect`) shows something very strange for Angular 11: a better half of the time it spends in `analyzingFileEmitter`
![Screen Shot 2021-01-29 at 2 52 37 PM](https://user-images.githubusercontent.com/1004015/106336678-49c6de00-6244-11eb-9abe-57c32efe09b0.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.1.2
Node: 12.14.1
OS: darwin x64

Angular: 11.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.2
@angular-devkit/build-angular   0.1101.2
@angular-devkit/core            11.1.2
@angular-devkit/schematics      11.1.2
@angular/cli                    11.1.2
@nguniversal/builders           11.1.1
@nguniversal/express-engine     11.1.1
@schematics/angular             11.1.2
@schematics/update              0.1101.2
rxjs                            6.6.3
typescript                      4.1.3
</code></pre>

**Anything else relevant?**
- I tried disabling source maps. While it does speed up compilation, it's still 24s (down from 40s with source maps) for the slow incremental case - way too long.
- Also `"showCircularDependencies": false`

<details>
  <summary>Complete `build` section from `angular.json`</summary>

  ```
  "build": {
    "builder": "@angular-devkit/build-angular:browser",
    "options": {
      "outputPath": "dist/browser",
      "index": "src/index.html",
      "main": "src/main.ts",
      "tsConfig": "src/tsconfig.app.json",
      "polyfills": "src/polyfills.ts",
      "preserveSymlinks": true,
      "assets": [
        "src/assets",
        "src/views"
      ],
      "aot": true,
      "progress": false,
      "styles": [
        "src/app/app.scss"
      ],
      "stylePreprocessorOptions": {
        "includePaths": [
          "node_modules"
        ]
      },
      "scripts": [
        {
          "input": "node_modules/browser-update/update.npm.full.js",
          "inject": false,
          "bundleName": "browser-update-3.0"
        },
        {
          "input": "src/browser-update-config.js",
          "inject": false,
          "bundleName": "browser-update-3.0"
        }
      ],
      "namedChunks": true,
      "showCircularDependencies": false,
      "allowedCommonJsDependencies": [
        "lodash",
        "numeral",
        "@splitsoftware/splitio",
        "fuzzysort",
        "hellojs",
        "stale-lru-cache",
        "card-validator",
        "graphql-tag",
        "getstream",
        "@babel/runtime-corejs3",
        "core-js-pure",
        "axios",
        "zen-observable",
        "utfx",
        "jwt-decode"
      ]
    },
    "configurations": {
      "production": {
        "budgets": [
          {
            "type": "anyComponentStyle",
            "maximumWarning": "6kb"
          }
        ],
        "optimization": true,
        "outputHashing": "all",
        "sourceMap": {
          "scripts": true,
          "styles": false,
          "hidden": true,
          "vendor": false
        },
        "extractCss": true,
        "namedChunks": true,
        "extractLicenses": true,
        "vendorChunk": true,
        "buildOptimizer": true,
        "statsJson": true,
        "fileReplacements": [
          {
            "replace": "src/environments/environment.ts",
            "with": "src/environments/environment.prod.ts"
          },
          {
            "replace": "src/environments/development-modules.ts",
            "with": "src/environments/development-modules.prod.ts"
          },
          {
            "replace": "src/environments/development-keys.ts",
            "with": "src/environments/development-keys.prod.ts"
          },
          {
            "replace": "src/main.ts",
            "with": "src/main.prod.ts"
          }
        ]
      },
      "es5": {
        "tsConfig": "src/tsconfig.es5.json"
      }
    }
  },
  ```
</details>

**Comment by JoostK** [comment]
Thanks for reporting. I suspect the difference is due to the CLI's new Webpack integration, as there haven't been any relevant changes on the framework side. If you set environment variable `NG_BUILD_IVY_LEGACY=1` the CLI will fallback to the previous Webpack integration implementation, perhaps you could try to see if using that would improve the times to what they were before. It could still be that the new CLI integration is limited by how the compiler operates, so I'll not move this issue to the CLI repo right away.

That said, do you think it would be possible to share a reproduction so that we can investigate further?

**Comment by amakhrov** [comment]
@JoostK thank you so much!
Indeed, `NG_BUILD_IVY_LEGACY=1` decreased the timings back to the original values we had in Angular 10.

As for the reproduction - I cannot just share the app as is, unfortunately. I think I could share some parts if you were willing to sign an NDA.

Alternatively - if you could let me know what kind of details from my side might be relevant. E.g I could send you the profiler output etc. Or I could investigate something at my side.

**Comment by JoostK** [comment]
@amakhrov I just realized that the profiler output would probably be plenty helpful at first, so that sounds like a good plan to start. I sent you an email to (hopefully) your GMail account.

**Comment by artaommahe** [comment]
Same here. Rebuild went up from 3s to 30s for all our project in monorepo. `NG_BUILD_IVY_LEGACY=1` helps, 3s again

**Comment by artaommahe** [comment]
Recorded a cpu profile for project1 and slow rebuild. Most time spent  in `analyzingFileEmitter` as for @amakhrov. But i also have a lot of dart-sass `compileStylesheet` calls during 15-20s before this (blue forest on the left).

![image](https://user-images.githubusercontent.com/1944061/106361219-d4373c80-632d-11eb-9749-2eb8d2d45dbc.png)

and this is the same rebuild for `NG_BUILD_IVY_LEGACY=1` mode, also no `compileStylesheet` calls (changed the same ts file for both modes)

![image](https://user-images.githubusercontent.com/1944061/106361443-f9787a80-632e-11eb-9440-719c78f0293f.png)

I saved both profiles and can send them to you @JoostK

**Comment by JoostK** [comment]
@artaommahe Thanks for investigation. I replied to @amakhrov by mail yesterday:

> I just had a quick look and I think I know what’s happening here. You mentioned that this was the result for a change within a highly reused NgModule, such that it’s visible to many importing NgModules. The compiler is currently quite pessimistic in reusing work from prior compilations, as it’s not capable of effectively determining what the impact of the change could be on all NgModules that “see” the change.
> 
> Now, in 11.1 the Ivy Webpack integration checks with the Angular compiler which files need to be emitted. This has changed compared to the earlier Webpack integration, which only emitted those files for which the watcher was triggered and their direct dependencies (at least that’s the gist of it; I’m not fully aware of how the mechanism works exactly). That approach was insufficient for certain changes, however, where the rebuilt module would not reflect all necessary changes resulting in buggy rebuilds. This is why the new Webpack integration now let’s the compiler decide which files have to be re-emitted, which could be a lot for a change within an NgModule with a high fan-in (due to the pessimistic strategy of computing the affected files).

In the profiler output he shared, though, there was only a difference in the "green forest" not the blue forest (btw, forests _are_ green! 🌳😄).

If you can share the profile dumps that would be helpful.

**Comment by artaommahe** [comment]
@JoostK here they are https://drive.google.com/drive/folders/1ePElZEoubw9CJ1T4aTKcUlG7bWbiM8Hf?usp=sharing

also i checked rebuild time on AppModule's file changes - it's the same 30s 😕

**Comment by JoostK** [comment]
@artaommahe thanks, I have downloaded them.

**Comment by artaommahe** [comment]
Checked new application (within the same monorepo) rebuild time for AppModule changes (added comment)

- default 250-300ms

![image](https://user-images.githubusercontent.com/1944061/106362588-bc16eb80-6334-11eb-9cc9-74ae978aa822.png)

- NG_BUILD_IVY_LEGACY=1 70-110ms

![image](https://user-images.githubusercontent.com/1944061/106362688-39426080-6335-11eb-9a65-c6fdf2da2f2d.png)

for the default mode there is a small `compileStylesheet` call righ after first `processTimers` block, i've added a scss files for the app.component, and it's called even for an empty scss file. There is no such function call for old mode at all.

**Comment by sod** [comment]
Shared profile in https://github.com/angular/angular/pull/40561#issuecomment-769136084

**Comment by Dosant** [comment]
Have the same issue, but it seems that regression is in **11.1.1** specifically. 
I started experience the slowness when upgrading from **11.1.0** -> **11.1.1**.

After downgrading `@angular-devkit/build-angular @angular/cli @angular/compiler-cli` back to **11.1.0** slowness disappeared. 

For me incremental build results for the same page level edit are: 


  | Angular Cli 11.1.0 | Angular Cli 11.1.1
-- | -- | --
lazy-module page level edit   | ~5s | ~55s

**Comment by JoostK** [comment]
Thanks everyone for the reports. I did some profiling of my own using the [ng9-aot-build-times](https://github.com/vaindil/ng9-aot-build-times) repo. What seems to be happening in comparison to the prior Webpack integration pipeline is that now the files that need to be updated according to the compiler are actually incorporated into to rebuilt bundle. This was done to fix bugs where an incremental rebuild did not result in a fully up-to-date bundle.

Unfortunately however, the Angular compiler is fairly pessimistic in its ability to determine which files need to be updated. I have some ideas to improve this situation but this effort is still underway.

**Comment by sergidt** [comment]
I am having same problem and is not acceptable. My minimum recompilint time is 60 seconds.

**Comment by reekoz** [comment]
Also for me after upgrading from Angular 10.x to 11.1 is very slow. Not on only first "ng serve" but also when changing some code, with webpack HMR re-build the entire project, not just the changes (as before). So for me and my dev team is quite impossible keep developing on the project

**Comment by mickdelaney** [comment]
These increased build times have destroyed our productivity with angular. 
i cant believe its getting worse. if your not google it seems your not really relevant. 
this is a years long problem of continued increase in compile times.

personally i'm done with angular now, it wasnt for the fact we have a huge investment in it, i'd dump the entire codebase. 
the cost of producing code with angular is unsustainable for us.

frankly it seems that the angular team is more interested in its own goals, and probably serving googles needs than the community at large. 

i guess i was naive to think it would ever be any different.

**Comment by tashoecraft** [comment]
@mickdelaney There's literally an option to reduce the times back to what they were whilst they try and find a fix. Calm down.

**Comment by mlc-mlapis** [comment]
@mickdelaney It's a temporary problem related to the webpack. It's not necessary to be nervous.

**Comment by sod** [comment]
> There's literally an option to reduce the times back to what they were whilst they try and find a fix.

To be fair, that option is hard to find. Angular should just release a patch with reverting to the old plugin by default.

**Comment by meriturva** [comment]
is set `NG_BUILD_IVY_LEGACY` environment difficult to find? mmmm...
Anyway, our project has also a performance build time decreased but we are still under 8 seconds rebuild time (was 2-4 seconds) with 80 libraries, 650 components, and 160k loc.

**Comment by mickdelaney** [comment]
i wasnt talking specifically about the 10x - 11x but rather the fact that 10x itself is horribly slow. our compile times on older angular versions were far better. and we've spent so much time trying to optimize it. we've looked and spent time using nrwl nx, caching, buildable libraries, all of that. the fact we need to spend so much time on it is crazy. 
i had hoped that the 11x version would start to improve the build times.

**Comment by JoostK** [comment]
@mickdelaney I'm sorry to hear that. In fact, there have been a lot of performance improvements over the past year after the default compilation mode has switched to AOT compilation in v9. It could be that AOT compilation is indeed a lot slower than the JIT compile times you were used to in older versions of Angular; the AOT compilation comes with the overhead of precompiling all components and doing template type checking, both of which is not done when using JIT. You can always go back to JIT compilations during development though: if you're using the CLI this is controlled by the `aot` flag in `angular.json`.

**Comment by daiyis** [comment]
can anyone point out where exactly to set the NG_BUILD_IVY_LEGACY=1 env? Is it in the angular.json file?

**Comment by gemron** [comment]
because the angular compilation speed is slow, in order to speed up the development speed, we upgraded the computer hardware to work normally. Hope the team can pay attention to this issue, thank you

**Comment by reekoz** [comment]
> can anyone point out where exactly to set the NG_BUILD_IVY_LEGACY=1 env? Is it in the angular.json file?

On Windows just set a new system environment variable, like this

![fig9](https://user-images.githubusercontent.com/29949267/106853075-67b79700-66b9-11eb-8b3c-7e0c39e29557.png)
![ooY6Z](https://user-images.githubusercontent.com/29949267/106853082-69815a80-66b9-11eb-8063-efd2d3400968.png)

**Comment by daiyis** [comment]
> > can anyone point out where exactly to set the NG_BUILD_IVY_LEGACY=1 env? Is it in the angular.json file?
> 
> On Windows just set a new system environment variable, like this
> 
> ![fig9](https://user-images.githubusercontent.com/29949267/106853075-67b79700-66b9-11eb-8b3c-7e0c39e29557.png)
> ![ooY6Z](https://user-images.githubusercontent.com/29949267/106853082-69815a80-66b9-11eb-8063-efd2d3400968.png)

ah cool, so we are talking about OS's env. Thank you!

**Comment by KrakenTyio** [comment]
`NG_BUILD_IVY_LEGACY=1 ng serve`

**Comment by Jelledb** [comment]
I guess with using `NG_BUILD_IVY_LEGACY=1` you lose all benefits of Hot Module Replacement (which was my main reason for upgrading to Angular 11)

**Comment by billdwhite** [comment]
I'm glad I'm not the only one that noticed the issue reported here.  My compile times on code within an individual module went from ~5s to about ~25 by doing nothing more than updating from Angular 11.0.x to 11.1.x.   With the NG_BUILD_IVY_LEGACY=1 option, that gets back down to about ~8s.  Better but still disappointing.

**Comment by sergidt** [comment]
I don't understand what kind of tests they pass. Is inapcetable. 

You have to fix this problems rather than release a version every 6 months.

I have bet everything for angular in my last project but receiving  nothing in return.

**Comment by mlc-mlapis** [comment]
@billdwhite @sergidt Be judicial and remember your last mistake and how surprised you were that it could have happened.

**Comment by sergidt** [comment]
@mlc-mlapis this kind of mistakes cannot occur in a framework like angular. 

If you release a new version the first think you have to test is the productivity of that tool. 

How many developers are using angular?

 Are you fully aware how a problem like that can kill your product?

**Comment by mlc-mlapis** [comment]
@sergidt Hmm, the first thing we do with any, even minor/patch release of everything is that we do our own tests. After successful results, we apply it to development teams. So you should agree with me that this case was also your fault.

**Comment by sergidt** [comment]
> @sergidt Hmm, the first thing we do with any, even minor/patch release of everything is that we do our own tests. After successful results, we apply it to development teams. So you should agree with me that this case was also your fault.

Sorry? My fault? Are you joking?  what a lack of professionalism is that? Am I an angular core member?

**Comment by Splaktar** [comment]
@sergidt the current recommendation for getting rebuild times back to sub-8 seconds is to disable AOT in dev mode and to also use the `NG_BUILD_IVY_LEGACY=1` environment variable.

I agree that we should probably look into making `NG_BUILD_IVY_LEGACY=1` the default value if this won't be fixed in the next patch release.

**Comment by Splaktar** [comment]
> Are you fully aware how a problem like that can kill your product?

@sergidt also please note that this is free and open source, it's not a paid product. If a problem is identified, it gets investigated and fixes are proposed. There is no guaranteed SLA on rebuild times or anything else. We're all here building and working to make things better and faster, together.

As @mlc-mlapis said above, it's a good idea to test your app and the dev experience with each new Angular version before you push out a commit that moves your whole team to the new version. I just did this in another project and we were able to  disable Ivy and AOT in dev mode so that developers could still be productive until this gets resolved. Thankfully these workarounds exist (thanks to the helpful community in this thread for helping share and test them) and we are able to get some of the other benefits included in 11.1 without having to roll back to 11.0.

**Comment by billdwhite** [comment]
> @billdwhite @sergidt Be judicial and remember your last mistake and how surprised you were that it could have happened.

@mlc-mlapis: my apologies if I came off as critical.  Not my intention.  Just happy that the issue is being worked on :)

**Comment by sergidt** [comment]
@Splaktar my attitude was not the best, I know, and please accept my apologies for that.

I know that Angular is a free and Open source project, but many companies based their products on this framework and spending a lot of money, and Is difficult to understand how this kind of performance issues can appear.

In my case, imagine our project with more than 8000 modules, how long it can take to recompile every single change?

Angular is an amazing product, I am a great supporter. Thanks to the angular team and, again, accept my apologies.

**Comment by appimpact** [comment]
With Angular 11.2.0, build times have increased even more.

We build and publish part of our code base as npm packages on internal repository. That entire process used to last 7-8 minutes including linking between packages with npm link for local development. After yesterday's upgrade, it now takes roughly 25 minutes for same compilation and linking process to complete.

We can deliver diagnostic logs if you provide us with instructions on how to collect them.

**Comment by rhum1-sakharov** [comment]
Using an optimization on scss transpilation can help a little bit : 

https://rhum1-dev.medium.com/angular-10-how-to-optimize-scss-compilation-826ac5cc7ba3

**Comment by Splaktar** [comment]
> In my case, imagine our project with more than 8000 modules, how long it can take to recompile every single change?

Yes, this is an area that is getting a lot of attention lately and there are follow up meetings scheduled with the team and the community to work towards a better solution here.

Additionally, a number of items on the [roadmap](https://angular.io/guide/roadmap) aim to address this issue with a longer-term strategy
1. https://angular.io/guide/roadmap#optimized-build-speed-and-bundle-sizes-with-angular-cli-webpack-5
1. https://angular.io/guide/roadmap#simplified-angular-mental-model-with-optional-ngmodules

The 2nd bullet here talks about a simplified mental model, but from what I understand talking to the team, this is also important for improving the incremental rebuild times of large code bases.

**Comment by th0r** [comment]
> Yes, this is an area that is getting a lot of attention lately and there are follow up meetings scheduled with the team and the community to work towards a better solution here.

@Splaktar I would suggest to work closer with @sokra on enabling Webpack's lazy compilation feature in Angular / Angular CLI: https://webpack.js.org/configuration/experiments/#experimentslazycompilation

IMO it should dramatically increase compilation speed in large projects.

Related PR: https://github.com/webpack/webpack/pull/12469

**Comment by JoostK** [comment]
Hello all,

with the release of Angular 11.2.5 just now these performance problems should have been resolved; it could be that you'll even see initial builds being a bit faster.

I have been doing some tests on a large project by changing a component that was used in many other components. With `NG_BUILD_IVY_LEGACY=1` this used to take about 10s, whereas `NG_BUILD_IVY_LEGACY=0` (or the default) would be ~15s. Now, with 11.2.5, this has been improved to 2-3s. So not only has the regression in 11.1 been resolved, this has been the largest improvement to incremental rebuild times since AOT was enabled by default in v9.

There are some cases where incremental rebuilds can take a bit longer. Changes to directive inputs, outputs, selectors and some other stuff causes all components that use the changed directive to be recompiled. This could mean that changing a directive/component that is used throughout an application can still result in rebuild times as they were (i.e. 15s), but the expectation is that most changes will not be as expensive.

I am super curious what these improvements mean for your applications, so please do update to 11.2.5 and share your experiences here! For anyone still seeing issues, please open new issues for us to investigate.

**Comment by Delagen** [comment]
@JoostK Still experiencing same performance problems with 11.2.5

|Mode|Cold|Hot|
|NG_BUILD_IVY_LEGACY=1|  ~120s | ~10s |
|NG_BUILD_IVY_LEGACY=0|  ~180s | ~50s |

**Comment by JoostK** [comment]
@Delagen I'm sorry to hear that :-( Please see angular/angular-cli#20235 for another report which shows a similar problem. I suspect it's due to Webpack's dependency graph and how that is used to drive incremental compilations; the registration of dependencies has changed in the Ivy Webpack pipeline. So that's a new root cause than what was addressed in #40947 and more investigation is needed to determine if there's something that can be done here.

**Comment by JoostK** [comment]
I wish dependabot wouldn't spam threads like this :(

@Delagen we have established an issue in the Ivy Webpack pipeline and this has been addressed in angular/angular-cli#20236. A PR to apply that to patch is pending; once that's been merged I'll post a link here of the build artefacts before it releases next week. Local testing shows that it does avoid the superfluous emits; we were incorrectly registering _transitive_ dependencies, not direct dependencies. In the repo I tested with this is only about 400ms so it wasn't a concern earlier, but certain projects may behave differently of course.

**Comment by artaommahe** [comment]
@JoostK 

Start/rebuild times for angular v11.2.4 with different aot plugins for one of our projects

| NG_BUILD_IVY_LEGACY | server start | AppComponent | shared service | lazy module component |
| ------------------- | ------------ | ------------ | -------------- | --------------------- |
| 1                   | 68s          | 3s           | 3s             | 3s                    |
| 0                   | 62s          | 16s          | 15s            | 16s                   |

It was ~30s with new aot plugin before v11.2.4, so looks like one issue was solved :)

Attached profiled snapshot and rebuild flamegraph screenshot

[CPU-20210311T191335.zip](https://github.com/angular/angular/files/6124385/CPU-20210311T191335.zip)

![image](https://user-images.githubusercontent.com/1944061/110818197-18f3b300-829e-11eb-8961-323c76a2bd18.png)

**Comment by JoostK** [comment]
@artaommahe thanks for the report. Perhaps you could also try with a snapshot build of `@ngtools/webpack`, see https://github.com/angular/angular-cli/issues/20235#issuecomment-796817790 for details.

**Comment by JoostK** [comment]
@artaommahe the profile you shared is _not_ on Angular 11.2.5, which is where the changes to the Angular compiler have landed. But even then I expect that you'll also need the snapshot build of `@ngtools/webpack` that will release next week (as mentioned in https://github.com/angular/angular/issues/40635#issuecomment-796637590).

**Comment by artaommahe** [comment]
@JoostK last release is 11.2.4 https://github.com/angular/angular-cli/releases/tag/v11.2.4 so i tried it. Oh.. i missed that you were talking about next release, sry. Will wait for next thursday to re-check than, thx.

**Comment by JoostK** [comment]
@artaommahe It's a bit confusing at the moment. Angular Framework 11.2.5 contains the framework's contribution to the improved incremental rebuilds, which was released at the same time as Angular CLI 11.2.4 (Framework has had to do one additional patch release). We've now identified more improvements on the CLI side, so these will release in Angular CLI 11.2.5 next week. What I meant to say about the AOT profile you shared is that it is not using Angular Framework 11.2.5, which means that it does not have _any_ of the improvements.

**Comment by artaommahe** [comment]
@JoostK

same for angular v11.2.5, angular/cli v11.2.4  
added updated ngtools case (used this build https://github.com/angular/angular-cli/issues/20235#issuecomment-796827112, installed with yarn resolutions), also tried latest ngtools and angular-devkit/build-angular (9714aa92b release tag) but it was the same as the previous one

| NG_BUILD_IVY_LEGACY | server start | AppComponent | shared service | lazy module component |
| ------------------- | ------------ | ------------ | -------------- | --------------------- |
| 1                   | 68s          | 2.7s         | 2.2s           | 2.6s                  |
| 0                   | 62s          | 16s          | 17s            | 15s                   |
| 0 + updated ngtools | 66s          | 18s          | 17s            | 17s                   |

Attached rebuild snapshot and flamegraph screenshot for the last case with the ngtools#ba719cf
[CPU-20210313T141100.zip](https://github.com/angular/angular/files/6134665/CPU-20210313T141100.zip)
![image](https://user-images.githubusercontent.com/1944061/111028186-23c95780-8406-11eb-9171-d2d45dd2b14a.png)

**Comment by JoostK** [comment]
@artaommahe It appears that that run did not use the snapshot `@ngtools/webpack` package in that case, because I see this in the profile:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/123679/111029934-ccc08400-83ff-11eb-9a36-74164db96603.png">

That `getAllDependencies` call is completely gone in the latest snapshots, so something is off.

There has been yet another improvement to `@ngtools/webpack` since https://github.com/angular/angular-cli/issues/20235#issuecomment-796827112. You can find the latest build hash here: https://github.com/angular/ngtools-webpack-builds/commits/11.2.x.

**Comment by artaommahe** [comment]
oh, thx.. i'll wait for official release, to be sure that everything done right (also check that there is no getAllDependencies in profiler), and recheck than

**Comment by JoostK** [comment]
@artaommahe The latest CLI containing the perf fixes has been released (11.2.5)

**Comment by sod** [comment]
Can confirm, the new plugin with 11.2.5 is super fast now. Unbelievable that you are working on your spare time on this @JoostK. Also thx to @clydin for improving the webpack integration.

**Comment by artaommahe** [comment]
@JoostK

angular v11.2.6, angular/cli v11.2.5 don't see many changes 😕 (~1s rebuild time drop relatively to previous patch version)

| NG_BUILD_IVY_LEGACY | server start | AppComponent | shared service | lazy module component |
| ------------------- | ------------ | ------------ | -------------- | --------------------- |
| 1                   | 67s          | 2.7s         | 2.5s           | 2.6s                  |
| 0                   | 63s          | 15.5s          | 14.3s            | 15s                   |

am i still missing smth?)

[CPU-20210319T175848.zip](https://github.com/angular/angular/files/6172161/CPU-20210319T175848.zip)

![image](https://user-images.githubusercontent.com/1944061/111800384-f2a4c780-88dc-11eb-9d4c-9cd6dc6372d2.png)

<details>
<summary>ng version</summary>
PS D:\projects\skyeng\skyeng-frontend\packages\vimbox-core\vimbox-boilerplate> yarn ng version
yarn run v1.22.10
$ ng version

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.5
Node: 12.18.1
OS: win32 x64

Angular: 11.2.6
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, localize, platform-browser       
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------     
@angular-devkit/architect       0.1102.5
@angular-devkit/build-angular   0.1102.5
@angular-devkit/core            11.2.5
@angular-devkit/schematics      11.2.1
@angular/cdk                    11.1.1
@angular/cli                    11.2.5
@angular/flex-layout            11.0.0-beta.33
@angular/material               11.1.1
@ngtools/webpack                11.2.5
@nguniversal/builders           11.1.1
@nguniversal/express-engine     10.1.0
@schematics/angular             11.2.5
@schematics/update              0.1102.5
rxjs                            6.6.2
typescript                      4.1.3
webpack                         4.46.0

Done in 1.09s.
</details>

**Comment by sod** [comment]
@artaommahe our profile looked exactly like your screenshot (with 11.2.5).

Do you happen to import typescript files from your project into another directory that also has a node_modules directory? If yes, then the new plugin struggles to deduplicate the typings and bounces back and forth between you default node_modules folder and the foreign node_modules folder. We fixed it by forcing dependency types into the main project via `paths` mapping in the tsconfig. Looks like:

```json
"paths": {
    "@angular/*": ["../node_modules/@angular/*"],
    "rxjs": ["../node_modules/rxjs"],
    "rxjs/*": ["../node_modules/rxjs/*"],
    "@ngrx/*": ["../node_modules/@ngrx/*"],
    "tslib": ["../node_modules/tslib"]
}

**Comment by artaommahe** [comment]
@sod nope, we have a monorepo with a single root folder's node_modules. I haven't move code anywhere, updated libs, removed node_modules and installed it again , started devserver

**Comment by cport1** [comment]
We also have multiple applications in an nx monorepo and are facing the same issue. I am wondering if this is a common denominator somewhere.

**Comment by JoostK** [comment]
With some additional information from @artaommahe we've established a scenario where the compiler bailed out of incremental reuse. It would happen when a package is present in multiple physical locations on disk (e.g. when a package hasn't been hoisted to the root `node_modules` but appears in multiple local `node_modules` directories), which are handled by TypeScript in a special way. This is being addressed in #41448.

**Comment by sod** [comment]
Isn't that what I described in https://github.com/angular/angular/issues/40635#issuecomment-802989789? :)

I like that with this change I can remove the `paths` workaround again. But @artaommahe said in https://github.com/angular/angular/issues/40635#issuecomment-803004517 he only has one node_modules directory, so it may not help him.

**Comment by JoostK** [comment]
> Isn't that what I described in [#40635 (comment)](https://github.com/angular/angular/issues/40635#issuecomment-802989789)? :)
> 
> I like that with this change I can remove the `paths` workaround again. But @artaommahe said in [#40635 (comment)](https://github.com/angular/angular/issues/40635#issuecomment-803004517) he only has one node_modules directory, so it may not help him.

I think it's not exactly as you described in https://github.com/angular/angular/issues/40635#issuecomment-802989789, but it might be that #41448 could help addressing that scenario as well.

Consider the following dependencies

```
A -> E@2.0
B -> E@2.0
C -> E@1.0
D -> E@1.0
```

Because of the incompatible version constraints, a maximum of one version of `E` can be hoisted and the others get their own local instance:

```
node_modules
  A
  B
  C
    node_modules
      E@1.0
  D
    node_modules
      E@1.0
  E@2.0
```

(it could also have hoisted `E@1.0` or not have hoisted `E` at all, that depends on the package manager and possibly the lock file)

When TypeScript includes `C` and `D` into the compilation unit, it notices that the source files for both copies of `E@1.0` correspond with the exact same version (as determined by their `package.json` file based on `name` and `version`) which results in a redirect from one of the `E@1.0` copies to the other one. This may also happen in the scenario you described with the totally foreign `node_modules`, so perhaps it does indeed avoid the need for the `path` mappings.

By the way, the long term plan is to remove the bailout for changed `.d.ts` files entirely but doing so requires a bit more work and testing effort than the simple change in #41448.

**Comment by artaommahe** [comment]
@JoostK  last update solved our issues, thanks

angular v11.2.10, angular/cli v11.2.9

| NG_BUILD_IVY_LEGACY | server start | AppComponent | shared service | lazy module component |
| ------------------- | ------------ | ------------ | -------------- | --------------------- |
| 0                   |  66s | 3s          | 3.2s            | 2.8s                   |

**Comment by lidi** [comment]
Hi,
I know this thread is officially closed, but I am hoping someone who was part of this discussion and managed to solve it could point me to the right direction.

We just upgraded to v11 and also experience significant issues with our built times. 

Current state:

Angular CLI: 11.2.11
Node: 14.16.0
OS: darwin x64

Angular: 11.2.12
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

@angular-devkit/build-angular@0.1102.11
│ └── webpack@4.44.2

| Package         |        Version |
| ------------- | ------------ |
@angular-devkit/architect     |  0.1102.11
@angular-devkit/build-angular |  0.1102.11
@angular-devkit/core           | 11.2.11
@angular-devkit/schematics |     11.2.11
@angular/cdk               |     11.2.11
@angular/cli                 |   11.2.11
@angular/material        |       11.2.11
@schematics/angular    |         11.2.11
@schematics/update      |        0.1102.11
rxjs                         |   6.6.7
typescript              |        4.0.7

| NG_BUILD_IVY_LEGACY | server start | AppComponent | lazy module component |
| ------------------------ | ------------ | ---------------- | ----------------------- | 
|  0  |  223.107s | 163.682s | 148.481s | 
| 1 | 274.018s | 138.859s |  111.629s| 

When we were on version 10

| server start | lazy module component |
| ------------ | ----------------------- | 
| 147.197s| 53.614s | 

Any ideas are welcome and thank you in advance!

**Comment by andreistoica994** [comment]
I have the exact same issue after I've upgraded from 6 to 12.

What before took max 2 seconds now -> Build at: 2021-05-21T14:26:05.866Z - Hash: c0358f2ca4f6ca3b67fa - Time: 32274ms

`Angular CLI: 12.0.1
Node: 16.2.0
Package Manager: npm 7.13.0
OS: linux x64

Angular: 12.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@angular/http                   6.1.10
@schematics/angular             12.0.1
rxjs                            6.6.7
typescript                      4.2.4
`

`✔ Browser application bundle generation complete.

Initial Chunk Files | Names         |      Size
main.js             | main          | 952.18 kB
polyfills-es5.js    | polyfills-es5 | 155.02 kB
styles.css          | styles        | 121.36 kB
polyfills.js        | polyfills     |  64.54 kB
runtime.js          | runtime       |   2.78 kB

                    | Initial Total |   1.27 MB

Lazy Chunk Files    | Names         |      Size
578.js              | -             |   1.99 kB

Build at: 2021-05-21T14:24:56.582Z - Hash: c23accb12dee32cf7e8d - Time: 80566ms
`

**Comment by amakhrov** [comment]
In our [project](https://github.com/angular/angular/issues/40635#issue-797267239) upgrading from 11.1 to 11.2 didn't show any performance difference with NG_BUILD_IVY_LEGACY.
More than that, disabling NG_BUILD_IVY_LEGACY didn't have any performance hits.

So with 11.2 we were able to get rid of NG_BUILD_IVY_LEGACY in our build scripts without any drawback.
