### ISSUE TITLE
Uglified UMD bundle for PlatformBrowser broken

### ISSUE THREAD

**Issue by flash-me** [angular/angular#40926]
# 🐞 bug report

### Affected Package

```@angular/platform-browser```

### Description

The minimized UMD bundle of `@angular/platform-browser` cannot be used. If any ngModule imports the `BrowserModule` an error will be thrown on bootstrap.
Somehow, the prototype of the global exports from platform-Browser will be mangled.

platform-browser.umd.js:
![image](https://user-images.githubusercontent.com/5240450/108565433-f573c300-7304-11eb-834c-37b7c40d708b.png)
platform-browser.umd.min.js:
![image](https://user-images.githubusercontent.com/5240450/108565449-fdcbfe00-7304-11eb-8458-92ca782620e6.png)
Which leads to the injection error shown below.
The other UMD bundles are fine so far.

### Is this a regression?

Since I'm probably the only human on earth that ~~uses~~ [used](https://github.com/angular/angular-cli/issues/20056#issuecomment-781899902) those UMD bundles, it's not that high priority I guess. 
To put it more precise, I stopped checking after **Angular 7**

![image](https://user-images.githubusercontent.com/5240450/108565557-2ce26f80-7305-11eb-9b90-f4cbeac2c59e.png)

Just wanted to mention this here. Maybe the bug can reveal something interesting to prevent further issues in the future related to minification.

## 🔬 Minimal Reproduction

Just bootstrap an application importing the minified UMD bundle, e.g. 
```
<script src="node_modules/@angular/platform-browser/bundles/platform-browser.umd.min.js"></script>
``` 

## 🔥 Exception or Error

```
definition.ts:753 Uncaught Error: Type t does not have 'ɵmod' property.
    at getNgModuleDef (definition.ts:753)
    at recurse (ng_module_factory_registration.ts:49)
    at recurse (ng_module_factory_registration.ts:61)
    at registerNgModuleType (ng_module_factory_registration.ts:45)
    at new NgModuleFactory (ng_module_ref.ts:121)
    at compileNgModuleFactory__POST_R3__ (application_ref.ts:66)
    at PlatformRef.bootstrapModule (application_ref.ts:401)
    at first.mfe.ts:29
    at angular-mfe-first.umd.js:4
    at angular-mfe-first.umd.js:5
``` 

## 🌍  Your Environment

![image](https://user-images.githubusercontent.com/5240450/108565360-d6753100-7304-11eb-8b91-3d6a6b830cc7.png)

**Anything else relevant?**
Both the usual bundle and the ivy-compiled bundle (running `ngcc`) have this issue

cheers
flash ⚡

**Comment by petebacondarwin** [comment]
So the error suggests that you are using Ivy. But since `@angular/platform-browser` is published in ViewEngine mode, then one needs `ngcc` to translate the bundle into Ivy mode. It is a known issue that ngcc cannot cope with most minified UMD bundles, and I expect the same is true of `@angular/platform-browser`. 

The error `Error: Type t does not have 'ɵmod' property.` supports this hypothesis, since this implies that the `t` (aka BrorwserModule` has not been transpiled by ngcc to Ivy, since `ɵmod` is an Ivy only property that is added by ngcc.

I think the approach, if you want minified UMDs to send to the browser, is to run `ngcc` on the non-minified bundle and then minify the result.

**Comment by flash-me** [comment]
Thank you for the detailed explanation. Indeed that's how we did it + concatenating e. g. for prod env's.
It's not a real issue, just wanted to mention that there is a case. 
AFAIK you're going to deprecate UMD anyway, right? 
Which is fine, the importmaps polyfill does the job to switch on ESM, so far. Sure, there are other options, but I like to keep things simple :)

For my side, this can be closed. Donno if you want to keep it open for tracking.

cheers
flash ⚡

**Comment by petebacondarwin** [comment]
Happy to close. UMD and ngcc are not things we want to spend our time on. Thanks for raising the issue.

**Comment by sviat9440** [comment]
@petebacondarwin I use `"@angular/compiler-cli": "~10.2.4"`, and i have this issue. What version of compiler-cli fixes this?

**Comment by petebacondarwin** [comment]
There is no fix for uglified UMD files. Please use the non-minified version. And if necessary minify after ngcc has processed it.

**Comment by sviat9440** [comment]
@petebacondarwin sorry. I talk about #40376, hmm, wrong tab...

**Comment by petebacondarwin** [comment]
So that PR landed in 11.1.0-next.5, so you would have the fix available from 11.1.0 onwards.

**Comment by sviat9440** [comment]
thank you

**Comment by sviat9440** [comment]
@petebacondarwin I update to version angular-cli ~11.2.3, but problem still here 
![image](https://user-images.githubusercontent.com/13107421/109311233-9a872200-7856-11eb-80eb-c757d640a989.png)
