### ISSUE TITLE
feat(http): add support for withCredentials

### ISSUE THREAD

**Issue by martinsik** [angular/angular#4231]
Hey, I'm trying to figure out how to send cookies throught CORS but since I can't access `XMLHttpRequest` objects directly I'm not able to set `withCredentials` option. I remember using it with [$http in Angular 1.4](https://docs.angularjs.org/api/ng/service/$http).
Maybe I could do this by writting custom `XHRBackend`? Or is there any easier way?

**Comment by PascalPrecht** [comment]
@martinsik there are currently `credentials` properties, but they are not used anywhere yet. In fact, there's a pending PR to remove those properties until they are actually properly implemented: https://github.com/angular/angular/pull/3823

**Comment by martinsik** [comment]
@PascalPrecht This explains why setting `mode = RequestModesOpts.NoCors` or `credentials = RequestCredentialsOpts.Include` had no effect at all :).

So, the only thing I can do not is to wait until the Fetch spec is properly defined and properties are re-implemented?

**Comment by PascalPrecht** [comment]
Yes I'm afraid that's the case. Maybe @jeffbcross has some thoughts on this.

**Comment by robwormald** [comment]
We're not actually using fetch at all, though in general we want the Http implementation to be fetch-like in its interfaces (of course, using Observables over Promises)

Once I finish RxNext porting (see: https://github.com/angular/angular/issues/4149), hopefully in the next couple of days, and then this sort of thing will be much easier to work with and improve on.

**Comment by vladimir-ivanov** [comment]
It is a bit unclear to me from this thread - is withCredentials going to be supported or not please?

**Comment by danipl** [comment]
@vladimir-ivanov me too, right now, and in the future, what can we do to set withCredentials?. At the moment, I should work with other JS libraries for the http requests, and is not the best way to make it.

**Comment by PascalPrecht** [comment]
Yay, mr. @robwormald has something in the workings ~ https://github.com/angular/angular/pull/5501

**Comment by robwormald** [comment]
i aim to please ;-)

**Comment by danipl** [comment]
Pleased succesfully done. Thank you! :)

**Comment by vladimir-ivanov** [comment]
Great work, thank you :-)

**Comment by brianaprince** [comment]
If this has been fixed, was it included with the Angular2 2.0.0-beta.0?  If so, how do I turn credentials on?  I see some comments in #5501 but cannot figure out how to set it and not knowing if it is the current release is a concern.

**Comment by icereval** [comment]
@brianaprince, here is a workaround I've been using for now...

```typescript
@Injectable()
export class Auth {
  isAuthenticated = false;
  user: User;

  constructor(@Inject(Http) private http: Http) {
    // TODO: Use official Angular2 CORS support when merged (https://github.com/angular/angular/issues/4231).
    let _build = (<any> http)._backend._browserXHR.build;
    (<any> http)._backend._browserXHR.build = () => {
      let _xhr =  _build();
      _xhr.withCredentials = true;
      return _xhr;
    };
  }
...
```

**Comment by brianaprince** [comment]
icereval, thanks for the workaround.

**Comment by yusugomori** [comment]
@brianaprince 
I don't know if it would help but I've modified BaseRequestOptions to handle `withCredentials`. Forked repository is [here](https://github.com/yusugomori/angular/tree/add-feature-withCredentials), and PR is https://github.com/angular/angular/pull/6236. It would be helpful till this feature is officially supported. 
```
class MyBaseRequestOptions extends BaseRequestOptions {
  headers: Headers = new Headers({
    'X-Requested-With': 'XMLHttpRequest'
  });
  withCredentials: boolean = true;
}

bootstrap(AppComponent, [ provide(RequestOptions, {useClass: MyBaseRequestOptions})] );
```

**Comment by gustavolira** [comment]
+1

**Comment by gustavolira** [comment]
@icereval  Sorry can you do more details how to use this workaround, will be very useful for me!

**Comment by gustavolira** [comment]
@icereval Thank you for you contribution, your workaround is working for me!
Please can you tell me how to add a custom header at that workaround?
Thank you

**Comment by icereval** [comment]
This is getting a bit off topic bit off but I'll try my best to answer w/ a clear example, @gustavolira you should be able to use the builtin Angular2 Headers class: https://angular.io/docs/ts/latest/api/http/Headers-class.html

e.g.
```typescript
import {Http, Headers} from 'angular2/http';
...
private fetchCurrentUser(): Promise<User> {
  return new Promise<User>((resolve) => {
    let headers = new Headers();
    headers.append('X-Api-Key', 'Foo');
    return this.http.get(`${Settings.API_BASE}users/me`, {headers: headers})
      .map(res => res.json())
      .subscribe(resolve);
  });
}
```

**Comment by robwormald** [comment]
note that you can just do `someObservable.toPromise()` rather than that
wrapping business.... you just need to `import
'rxjs/add/operator/toPromise'`

**Comment by smithrobs** [comment]
Is there a reason why this hasn't made it to master? I see that this is still open and #5501 from @robwormald was merged but there's no code included. Seems strange to me, but I'm not a core committer. Would be nice to have this.

**Comment by xealot** [comment]
The patch from @icereval works for me, very ugly though. This is sort of a must for CORS.

**Comment by sumigoma** [comment]
Would also love to have this for CORS support.

**Comment by michalstepien** [comment]
Yes, would be nice to have `withCredentials` flag .

**Comment by panKt** [comment]
Just stumbled upon the same problem, hope it will resolve soon

**Comment by ffsantos92** [comment]
+1

**Comment by robwormald** [comment]
This issue was moved to angular/http#65

**Comment by caffinatedmonkey** [comment]
Is this fixed or not? The link above is broken.

**Comment by caffinatedmonkey** [comment]
It looks like it was fixed by https://github.com/angular/angular/commit/95af14b97cccc1e6c73ef9306350e56240c574ef

**Comment by nahwinrajan** [comment]
still encountering this problem:

> XMLHttpRequest cannot load http://localhost:3000/api/v1/todos. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3001' is therefore not allowed access. The response had HTTP status code 403

Express back-end running on localhost:3000
Angular 2 front-end running on localhost:3001

my http request as following:
```
addTodo(todo: Todo) {
    let headers = new Headers({ "Content-Type": "application/json" });
    let options = new RequestOptions({ headers: headers, withCredentials: true  });

    return this._http.post(this.todosApiUrl, JSON.stringify(todo), options)
      .map(this.extractData)
      .catch(this.errorHandler);
  }
```

on express I'm already using cors package:
```
const originsWhiteList = {
  "http://localhost:3001": true   // front-end development port
};

const corsOptions = {
  origin: function(origin, callback) {
    callback(null, originsWhiteList[origin]);
  },
  credentials:true
}
.
.
.

app.use(cors(corsOptions));  //placed right before routes
```

**Comment by AntonScotte** [comment]
Also experiencing issues with this:

I'm using express backend in a similar fashion:
```
var cors = require('cors');

app.use(cookieParser());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

var whitelist = [
  'http://localhost:8080'
];

var corsOptions = {
  origin: function(origin, callback){
        var originIsWhitelisted = whitelist.indexOf(origin) !== -1;
        callback(null, originIsWhitelisted);
    },
    credentials: true
};

app.use(cors(corsOptions));
```

```
private login(user: User) {
    let headers = new Headers();
    headers.append('Content-Type', 'Application/json');
    
    let url = this.loginUrl;

    return this.http
      //.post(url, JSON.stringify(user), {headers:headers})
      .post(url, JSON.stringify(user), { headers: headers, withCredentials: true })
      .toPromise()
      .then(() => user)
      .catch(this.handleError);
  }
```

Getting this error:

> "login:1 XMLHttpRequest cannot load http://localhost/login. Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:8080' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute."


I don't really understand where the wildcard '*' comes into place here. I have not specified this anywhere in my code.

Has this issue been solved?

**Comment by caffinatedmonkey** [comment]
@AntonScotte @nahwinrajan Your errors seem to be caused by server side configuration issues.

@nahwinrajan Cross orgin requests require some server configuration also. [Check out this MDN article about the `Acess-Control-Allow-Origin` header.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Allow-Origin).

@AntonScotte You need to change the `Acess-Control-Allow-Origin` header your server is sending back to explicitly specify your origin.

**Comment by AntonScotte** [comment]
@caffinatedmonkey I'm aware of this and I have configured my server code before to Allow origins: both with wildcards and specifically my origin without any luck, as you can see in **my now updated** comment. I have tried a number of different ways to handle this with server configurations but none of them have proven to work out so far. As far as I can understand, the origin should be 'http://localhost:8080' in my configuration as it is where I'm trying to access my server from on the client side and as it is what's stated in my error message I receive as well.

**Comment by caffinatedmonkey** [comment]
That's strange. Here's a working example.

[Client Code:](https://github.com/caffinatedmonkey/downpour/blob/upgrade/app/deluge.service.ts#L24)

    let options = new RequestOptions({
      withCredentials: true,
    });

    this.http.post(serverURL, {
      method: method,
      params: payload,
      id: this.id++,
    }, options);

    // ...

Nginx Server Configuration
```nginx
server {
  listen 443 ssl;
  server_name deluge.drone.lan;

  location / {
    if ($http_origin ~* (https?://(.*\.)?drone\.lan(:[0-9]+)?)$) {
        set $cors "true";
    }

    if ($cors = "true") {
      add_header 'Access-Control-Allow-Origin' $http_origin;
      add_header 'Access-Control-Allow-Credentials' 'true';
    }

    if ($request_method = 'OPTIONS') {
        set $cors "${cors}OPTIONS";
    }

    if ($cors = "trueOPTIONS") {
      # Nginx Logical And
      # Preflight
      add_header 'Access-Control-Allow-Origin' $http_origin;
      add_header 'Access-Control-Allow-Credentials' 'true';
      add_header 'Access-Control-Allow-Headers' 'Content-Length, Content-Type';
      add_header 'Access-Control-Allow-Method' 'POST';

      # Time before checking again for new cors (making OPTIONS requests). This might be your issue.
      add_header 'Access-Control-Max-Age' '600';
      return 200;
    }

    proxy_pass http://localhost:8112/;
  }
}
```

It might be something to do with caching.

**Comment by scottie** [comment]
just usless really.... usless....
