### ISSUE TITLE
"ng test" : Unhandled promise rejection: Error: Injector has already been destroyed.

### ISSUE THREAD

**Issue by jlahare** [angular/angular#44186]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When running "ng test --code-coverage", keep getting this error "Unhandled promise rejection: Error: Injector has already been destroyed."

over karma dashboard if keep refreshing, this error goes away and code coverage appears.

i am not sure what is this error and where to look for what because error is not telling where is the problem, Spent number of days over it, please suggest if its angular version issue and if there is any patch available for now

attached screen shot as well error log.

![karmaError](https://user-images.githubusercontent.com/10416189/141978174-ea85fdcf-8f77-49e5-aab2-ed28726734f1.JPG)

### Please provide the exception or error you saw

```true
Chrome 96.0.4664.45 (Windows 10): Executed 23 of 24 SUCCESS (0 secs / 0.282 secs)
Chrome 96.0.4664.45 (Windows 10) ERROR
  An error was thrown in afterAll
  Unhandled promise rejection: Error: Injector has already been destroyed.
  Error: Injector has already been destroyed.
      at R3Injector.assertNotDestroyed (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11342:19)
      at R3Injector.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11270:14)
      at NgModuleRef.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:22189:33)
      at R3Injector.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11306:33)
      at injectInjectorOnly (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:4774:33)
      at Module.ɵɵinject (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:4778:12)
      at Object.factory (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/router/fesm2020/router.mjs:5893:1)
      at R3Injector.hydrate (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11476:35)
      at R3Injector.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11295:33)
      at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11333:55
  Unhandled promise rejection: Error: Injector has already been destroyed.
  Error: Injector has already been destroyed.
      at R3Injector.assertNotDestroyed (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11342:19)
      at R3Injector.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11270:14)
      at NgModuleRef.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:22189:33)
      at R3Injector.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11306:33)
      at injectInjectorOnly (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:4774:33)
      at Module.ɵɵinject (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:4778:12)
      at Object.factory (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/router/fesm2020/router.mjs:5893:1)
      at R3Injector.hydrate (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11476:35)
      at R3Injector.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11295:33)
      at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11333:55
Chrome 96.0.4664.45 (Windows 10): Executed 24 of 24 ERROR (0 secs / 0.284 secs)
Chrome 96.0.4664.45 (Windows 10) ERROR
  An error was thrown in afterAll
  Unhandled promise rejection: Error: Injector has already been destroyed.
  Error: Injector has already been destroyed.
      at R3Injector.assertNotDestroyed (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11342:19)
      at R3Injector.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11270:14)
      at NgModuleRef.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:22189:33)
      at R3Injector.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11306:33)
      at injectInjectorOnly (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:4774:33)
      at Module.ɵɵinject (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:4778:12)
      at Object.factory (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/router/fesm2020/router.mjs:5893:1)
      at R3Injector.hydrate (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11476:35)
      at R3Injector.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11295:33)
      at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11333:55
  Unhandled promise rejection: Error: Injector has already been destroyed.
  Error: Injector has already been destroyed.
      at R3Injector.assertNotDestroyed (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11342:19)
      at R3Injector.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11270:14)
      at NgModuleRef.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:22189:33)
      at R3Injector.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11306:33)
      at injectInjectorOnly (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:4774:33)
      at Module.ɵɵinject (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:4778:12)
      at Object.factory (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/router/fesm2020/router.mjs:5893:1)
      at R3Injector.hydrate (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11476:35)
      at R3Injector.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:11295:33)
Chrome 96.0.4664.45 (Windows 10): Executed 24 of 24 ERROR (0.36 secs / 0.284 secs)

=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.2
Node: 14.16.0
Package Manager: npm 8.1.0
OS: win32 x64

Angular: 13.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.2
@angular-devkit/build-angular   13.0.2
@angular-devkit/core            13.0.2
@angular-devkit/schematics      13.0.2
@angular/cdk                    12.2.13
@angular/cli                    13.0.2
@angular/material               12.2.13
@schematics/angular             13.0.2
rxjs                            6.6.7
typescript                      4.4.4
```

### Anything else?

Please let know if there any resolution of this issue.

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

Could you please create a GitHub repo with a minimal repro (as minimal as possible) so that we can take a look?

**Comment by ducthang-vu** [comment]
@jlahare Did you manage to find a solution for this bug?

**Comment by jlahare** [comment]
No @ducthang-vu , i am still looking for solution, its very strange to me that nobody getting this error.

i am not able to upload minimal set of code as per my company policy to reproduce, if you are facing same issue, then can you upload the code ?

**Comment by ducthang-vu** [comment]
> No @ducthang-vu , i am still looking for solution, its very strange to me that i am not getting resolution of this error anywhere.
> 
> i am not able to upload minimal set of code as per my company policy to reproduce, if you are facing same issue, then can you upload the code ?

Alas, I am also working on my company private repo. It seems, however, that after several "ng test" runs, it's working both locally and in the docker container. Hardly a satisfactory solution though.

**Comment by LorenzSLA** [comment]
I am having the same problem. It started after updating to Angular 13. The error does not occur on every test run but seems to pop-up randomly.

**Comment by thomasgainant-nmt** [comment]
Same thing for me, Angular 13, error which pops up randomly on tests.

**Comment by ducthang-vu** [comment]
I also confirm it starts happening after updating to Angular 13.

**Comment by jlahare** [comment]
@AndrewKushnir I am sure its angular 13 issue, Is it possible to investigate this issue for Angular 13 ? i cannot upload code(even minimal) from my organisation.

**Comment by fabio-bertone** [comment]
I'm seeing this as well. It only happens when I run all tests. If I run a particular spec, even the one it last failed on, it passes fine.

**Comment by chriscarpenter12** [comment]
> It only happens when I run all tests. If I run a particular spec, even the one it last failed on, it passes fine.

Same for me, but only noticed after updating a library from 11 -> 12.2.13

**Comment by fabio-bertone** [comment]
Not sure if this'll help but I finally got the tests to pass!! I played around by add `{ teardown: { destroyAfterEach: false } }` to `test.ts` file and it started working again. Looking into this option, it seems with v13, it was defaulted to true which would explain the behavior between versions. Hope this helps.

```
// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting(),
  {
    teardown: { destroyAfterEach: false }
  }
);
```

**Comment by mdantonio** [comment]
Thank you, it worked for me too!

**Comment by ducthang-vu** [comment]
Our tests start working again after we stop importing the following Angular material modules: SnackbarModule and MatDialogModule. Instead now we inject mock services.

We kept on test.ts

`teardown: { destroyAfterEach: true }`

**Comment by dofamine** [comment]
Same issue for me

**Comment by shifenis** [comment]
I'm facing off the same error, adding the `destroyAfterEach: false`, the test on my router will not pass, any chance to resolve this?

**Comment by MonaGamal** [comment]
The same for me.

**Comment by ojkey** [comment]
I have a little bit different issue: `Unhandled promise rejection: ObjectUnsubscribedError: object unsubscribed`
However, adding `teardown: { destroyAfterEach: true }` worked for me.

**Comment by dalejand** [comment]
Same Problem with 12.2.1

**Comment by mrsants** [comment]
> Não tenho certeza se isso vai ajudar, mas finalmente consegui passar nos testes!! Eu brinquei adicionando `{ teardown: { destroyAfterEach: false } }`ao `test.ts`arquivo e ele começou a funcionar novamente. Olhando para esta opção, parece que com a v13, o padrão foi true, o que explicaria o comportamento entre as versões. Espero que isto ajude.
> 
> ```
> // First, initialize the Angular testing environment.
> getTestBed().initTestEnvironment(
>   BrowserDynamicTestingModule,
>   platformBrowserDynamicTesting(),
>   {
>     teardown: { destroyAfterEach: false }
>   }
> );
> ```

this correction in angular 12 time my tests pass

**Comment by mrsants** [comment]
> Eu tenho um problema um pouco diferente após a atualização para o angular 13: `Unhandled promise rejection: ObjectUnsubscribedError: object unsubscribed` No entanto, a adição `teardown: { destroyAfterEach: true }`funcionou para mim.

sitting true works for you, very strange, it didn't work here

**Comment by mrsants** [comment]
is there any relation to this eero when omitting ngOnDestroy in the component ?

**Comment by jessicajaniuk** [comment]
We believe this is resolved by `destroyAfterEach: true`. If you're seeing failures that require `destroyAfterEach: false`, it's likely you have scope leakage in your tests. If you continue to see the original issue, please open a new issue for it.

**Comment by ake1996** [comment]
I have tried with `destroyAfterEach: true` but still the issue isn't solved and also tried to upgrade the project from angular 12 to 13, the result is same, so is there any other alternatives to solve this issue?

**Comment by hamidberdous** [comment]
if you use throwError() like this will cause the problem 
try to use throwError(() => new Error("error message"))
