### ISSUE TITLE
Polymer paper-menu-button and paper-dropdown-menu don't work

### ISSUE THREAD

**Issue by robisim74** [angular/angular#4670]
Hi,
these two elements don't work fine: anomalies and errors are different in every browser I tested (Chrome, Firefox, Edge). In the same app there are other Polymer elements and Angular directives that work fine instead.
Thanks!

**Comment by Zyzle** [comment]
Went ahead and tried this myself in my app, I'm seeing slightly different behaviour from you.  Visually the component appears OK however when I click it to open the dropdown I get the error:

```
Uncaught TypeError: Cannot read property 'toString' of null
  obj.addEventListener @ angular2.dev.js:1068
  Gestures.add @ polymer.html:683
  Polymer.IronOverlayBehaviorImpl._toggleListener @ iron-overlay-behavior.html:268
  (anonymous function) @ iron-overlay-behavior.html:286
  fnNames.map.forEach.global.zone.(anonymous function).arguments.(anonymous function) @ angular2.dev.js:487
  (anonymous function) @ angular2.dev.js:118
  run @ angular2.dev.js:138zoneBoundFn @ angular2.dev.js:111
```

And when an item is selected from the dropdown:

```
Uncaught TypeError: Cannot read property '_zone$boundFns' of null
  obj.removeEventListener @ angular2.dev.js:1099
  Gestures.remove @ polymer.html:706
  Polymer.IronOverlayBehaviorImpl._toggleListener @ iron-overlay-behavior.html:274
  (anonymous function) @ iron-overlay-behavior.html:286
  fnNames.map.forEach.global.zone.(anonymous function).arguments.(anonymous function) @ angular2.dev.js:487
  (anonymous function) @ angular2.dev.js:118
  run @ angular2.dev.js:138
  zoneBoundFn @ angular2.dev.js:111
```

I notice the second error here is coming from zone, could this be related to #4531 ?

**Comment by robisim74** [comment]
I don't know if my app has other problems, but e.g. on Chrome (latest version) I see this:
* I clean the browser cache
* I launch the app
* The two elements are not rendered fine (whereas the other elements yes)
* I refresh the browser and only dropdown is rendered fine (why?)
* On menu-button, there is this error:
```
Uncaught TypeError: Cannot read property 'ANIMATION_CUBIC_BEZIER' of undefinedPolymer.properties.openAnimationConfig.value @ paper-menu-button.html:233Polymer.Base._addFeature._configureProperties @ polymer.html:1757Polymer.Base._addFeature._configure @ polymer.html:1746Polymer.Base._addFeature._beforeClientsReady @ polymer.html:1737Polymer.Base._addFeature._ready @ polymer-mini.html:63Polymer.Base._addFeature._tryReady @ polymer-mini.html:56Polymer.Base._addFeature._initFeatures @ polymer.html:3189Polymer.Base.createdCallback @ polymer-micro.html:151run @ angular2.dev.js:138zoneBoundFn @ angular2.dev.js:111document.registerElement @ angular2.dev.js:917window.Polymer @ polymer-micro.html:64(anonymous function) @ paper-menu-button.html:123(anonymous function) @ paper-menu-button.html:371
```
Then, when I click on dropdown and an item is selected, I see the same errors that you have described.

**Comment by Zyzle** [comment]
@robisim74 I'd suggest using the full version of `webcomponents.js` not `webcomponents-lite.js` also i believe you still need to force polymer to use native shadow DOM:

```html
<script type="text/javascript">
    var Polymer = Polymer || {};
    Polymer.dom = 'shadow';
</script>
```

Try this and see if it fixes your component display problems.

**Comment by robisim74** [comment]
Thanks @Zyzle this has fixed my display problems!
Now remain errors when you click or select the menu and dropdown.

**Comment by Zyzle** [comment]
@robisim74 good to know :+1: 
@vicb sorry to ping you for this but I know you looked at the previous Zone/Polymer issue I raised.  This one seems to be component specific (`iron-overlay-behavior.html`) as I've not come across it with any other polymer component.

**Comment by mhevery** [comment]
resolved

**Comment by Zyzle** [comment]
@mhevery  is there a fix on master for this? I'm still seeing the same behaviour in alpha-44.

**Comment by robisim74** [comment]
Me too

**Comment by tbosch** [comment]
Polymer needs everybody that uses it to use their DOM wrappers so they know when things change. See here: https://github.com/dart-lang/polymer-dart/issues/630

If we want to have good support for Polymer components, we need to detect whether Polymer is on the page and go through their API...

**Comment by tbosch** [comment]
Also see https://github.com/PolymerLabs/polymer-experiments/blob/master/patch-dom.html for a generic polyfill that allows to use Polymer components with any framework without needed to use their special DOM api.

**Comment by robisim74** [comment]
Hi @tbosch, I have made several attempts with the patch you've recommended, but it doesn't solve the errors reported in this issue regarding Zone.

**Comment by robisim74** [comment]
@Zyzle @vicb @tbosch I close this issue, because will be fixed here: https://github.com/angular/zone.js/commit/26e7f5177a06b28e9c4478eab5c6b95cd79da37f with the next Zone version. I tested the commit, and it works fine.

**Comment by vicb** [comment]
@robisim74 thanks for reporting !
