### ISSUE TITLE
Unexpected behaviour for falsy values when using arrays in class binding

### ISSUE THREAD

**Issue by undsoft** [angular/angular#48473]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

```html
<div 
  [class]="['as-array', 'as-array2']" 
  [class.specific]="true"
></div>
// Applied: All classes are applied

<div
  [class]="['as-array', '', 'as-array2']" 
  [class.specific]="true"
></div>
// Applied: .specific

<div 
  [class]="['as-array', false, 'as-array2']" 
  [class.specific]="true"
></div>
// Applied: .as-array .false .as-array2 .specific

<div 
  [class]="['as-array', undefined, 'as-array2']" 
  [class.specific]="true"
></div>
// Applied: .as-array

<div 
  [class]="['as-array', null, 'as-array2']" 
  [class.specific]="true"
></div>
// Applied: No classes were applied.
```

My expectation is basically that falsy values in an array will not be printed and will not affect other class declarations.
Basically I always expect to get `.as-array .as-array2 .specific`.

I cannot find logic in how it current works. There are 4 different behaviours based on what falsy value is used.
This can lead to unexpected behaviour and hard to diagnose errors.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-amqsbq?file=src/app/app.component.htmlpp%2Fapp.component.html

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 15.0.2
Node v16.16.0
```

**Comment by pkozlowski-opensource** [comment]
Fixed stackblitz: https://stackblitz.com/edit/angular-ivy-g2fcyh?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

This is a confirmed bug. What is going on here is that the styling algorithm doesn't seem to account for non-string and empty string values. Those unchecked values are propagated to the other parts of the framework and throw exceptions in other parts (DOM etc.).

While this might look like a corner cases, I can understand how people might want to use ternary expressions to have conditional classes (and evaluate to an empty string / null / undefined if a given class  should not be applied).

We should fix it, although I'm not sure what is the best approach here: throw for "invalid" values or just ignore them.

**Comment by pritam-chowdhury** [comment]
@undsoft  I think that any null or falsy value shouldn't affect the other class declaration. We can still show warning like "class declaration shouldn't contain any null or falsy values".. After showing this warning we should ignore falsy values and continue to apply other class declaration
