### ISSUE TITLE
Angular15 standalone component

### ISSUE THREAD

**Issue by jiangyh1024** [angular/angular#48594]
### Which @angular/* package(s) are the source of the bug?

forms, Don't known / other

### Is this a regression?

Yes

### Description

I want to export reactiveFormModule & a custom  standalone directive using an array. and then Import the array into the components.

<img width="936" alt="image" src="https://user-images.githubusercontent.com/34930870/209640714-8cc78151-19a9-4e03-8806-76f5a5979b8d.png">
<img width="835" alt="image" src="https://user-images.githubusercontent.com/34930870/209640758-8d75e7f5-609c-4a89-961e-45cb73821abd.png">

But the strange thing is the compiler will throw an error

<img width="720" alt="image" src="https://user-images.githubusercontent.com/34930870/209640842-5296c4dd-d7b5-43c2-a1c9-a8f6333d4147.png">

However, removing the directive from the array and directly importing the directive do the trick. I really don't know what's the difference..

<img width="761" alt="image" src="https://user-images.githubusercontent.com/34930870/209641102-b0dc3c5b-50c7-473c-ae61-fba2c0dca0fe.png">

<img width="857" alt="image" src="https://user-images.githubusercontent.com/34930870/209641081-14f0d9dc-65f5-45eb-a459-81e07a531a7f.png">

### Please provide the exception or error you saw

```true
as desc
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
angular15
```

**Comment by JeanMeche** [comment]
This has been reported already by #48089 and fixed #48091. 

The fix will be release with Angular 15.1 in circa 2 weeks 👍

**Comment by alxhub** [comment]
Closing as fixed by #48091

**Comment by jiangyh1024** [comment]
err, I've upgraded ng to 15.1.0, but the problem still exists.

**Comment by jiangyh1024** [comment]
hi anybody ? this fix seems not included in  15.1.0
