### ISSUE TITLE
SwPush.subscription & SwPush.requestSubscription not emitting after hard reload

### ISSUE THREAD

**Issue by DoomDesign** [angular/angular#48702]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

No

### Description

I discovered this problem on Angular 13, but it also appeared on v14 and v15.

We've implemented Push Notifications with SwPush.
On initialization of a component, I want to subscribe to SwPush.subscription (the Observable) to get the current subscription (or null, if there is none).
Equally, I want to call SwPush.requestSubscription (the Promise) when I finally want to ask the user for permission.

Both of these methods are NOT emitting any value (or resolving, for the Promise) when I hard reload the application (STRG+F5). They don't throw any error, they just stay silent and never complete.

When I soft-reload the application (regular refreshing the page), only THEN these methods work and will emit corresponding values.

**Expected behaviour:**
Emit values when subscribing to the .subscription Observable or when using the requestSubscription() Promise, or throw an error if there is something wrong / if it fails.

**Current behaviour:**
Nothing is ever emitted, no errors are thrown, the user will be waiting forever.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.0
Node: 16.14.2
Package Manager: npm 8.5.5
OS: win32 x64

Angular: 15.1.0
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.0
@angular-devkit/build-angular   15.1.0
@angular-devkit/core            15.1.0
@angular-devkit/schematics      15.1.0
@angular/cdk                    14.2.7
@schematics/angular             9.1.15
rxjs                            6.6.7
typescript                      4.8.4
webpack                         4.46.0
```

**Comment by zerefel** [comment]
Using Angular 15 and I can reproduce this. Both `this.swPush.subscription` and `this.swPush.requestSubscription` stay silent, no matter how I refresh or reload the page. `this.swPush.isEnabled` returns `true`. Forcefully registering the service worker using `navigator.serviceWorker.register('/ngsw-worker.js');` doesn't work either.

**Comment by jamsjordn** [comment]
I'm also having this issue. I've made a reproduction here https://github.com/jamsjordn/angular-push-request-hard-reload-issue

Boilerplate made from `ng new` and `ng add @angular/pwa`

**Comment by mmjr-x** [comment]
We also ran into this issue on angular v16. Did some extensive debugging and found the root cause to be filter in 
[this piece of code](https://github.com/angular/angular/blob/c3b00959659ca20d3f798820dfcb4dee250a32ac/packages/service-worker/src/low_level.ts#L139-L145):
```ts
      const currentController = defer(() => of(serviceWorker.controller));
      const controllerWithChanges = concat(currentController, controllerChanges);

      this.worker = controllerWithChanges.pipe(filter((c): c is ServiceWorker => !!c));

      this.registration = <Observable<ServiceWorkerRegistration>>(
          this.worker.pipe(switchMap(() => serviceWorker.getRegistration())));
```

The issue here is that `currentController` will emit `null` when you come into the app from a hard refresh. This is in line with the spec as described [here](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/controller).

However that the controller is null does not necessarily mean that there are no registrations, and no emits of registrations means no emits of the pushManager which cause the SwPush.subscription & SwPush.requestSubscription to not emit or resolve anything even though there is an existing subscription.

My suggested fix would be as followed:
```ts
      const currentController = defer(() => of(serviceWorker.controller));
      const controllerWithChanges = concat(currentController, controllerChanges);

      this.worker = controllerWithChanges.pipe(filter((c): c is ServiceWorker => !!c));

      this.registration = <Observable<ServiceWorkerRegistration>>(
          concat(
              currentController, 
              controllerChanges.pipe(
                  filter((c): c is ServiceWorker => !!c)
              )
          ).pipe(
              switchMap(() => serviceWorker.getRegistration()),
              filter((swr): swr is ServiceWorkerRegistration => !!swr)
          )
      );
```

This effectively makes it try to get the ServiceWorkerRegistration even if the currentController is null. While this works the only doubt I have is that I do not know enough about Angular's service worker implementation to judge whether this has any unintended side effects. If a more knowledgeable dev could chime in it would be much appreciated! :)

In the meantime I made this hacky method that can be used in the component/service where you inject your swPush service to apply this fix:
```ts
private fixSwPush(): void {
    if (!this.swPush.isEnabled) {
      return;
    }

    const serviceWorker: ServiceWorkerContainer | undefined = this.swPush?.['sw']?.['serviceWorker'];

    if (!serviceWorker) {
      return;
    }

    // Adapted from original code:
    // https://github.com/angular/angular/blob/c3b00959659ca20d3f798820dfcb4dee250a32ac/packages/service-worker/src/low_level.ts#L137
    const controllerChangeEvents = fromEvent(serviceWorker, 'controllerchange');
    const controllerChanges = controllerChangeEvents.pipe(map(() => serviceWorker.controller));
    const currentController = defer(() => of(serviceWorker.controller));

    const registration = concat(
      // The actual fix, here we don't do the falsy filtering for the currentController (as it is null on a hard refresh)
      currentController,
      controllerChanges.pipe(
        filter((c): c is ServiceWorker => !!c),
      )
    ).pipe(
      // Instead just try to get the ServiceWorkerRegistration here
      switchMap(() => serviceWorker.getRegistration()),
      // And filter out any falsy ServiceWorkerRegistration at the end
      filter((c): c is ServiceWorkerRegistration => !!c)
    );

    // Adapted from original code:
    // https://github.com/angular/angular/blob/c3b00959659ca20d3f798820dfcb4dee250a32ac/packages/service-worker/src/push.ts#L151
    const pushManager = registration.pipe(map(registration => registration.pushManager));

    // Overwrite the original pushManager
    this.swPush['pushManager'] = pushManager;

    const workerDrivenSubscriptions = pushManager.pipe(switchMap(pm => pm.getSubscription()));

    // Overwrite the original subscriptionChanges
    (this.swPush.subscription as Observable<PushSubscription | null>) = merge(workerDrivenSubscriptions, (this.swPush['subscriptionChanges'] as Subject<PushSubscription | null>));

  }
```

And do execute this before anything else (even field initializers):
```ts
@Injectable({
  providedIn: 'root'
})
export class WebPushService implements OnDestroy {

  // TODO: There is a problem with this not emitting after a hard reload https://github.com/angular/angular/issues/48702
  // this is a hacky way to fix this. At some point reevaluate this solution
  private readonly runThisFirst = this.fixSwPush();
```

I hope this will help people stuck on this, and I hope this gets fixed properly at some point :) (and if there is anything I can do to help this issue along please let me know?)

**Comment by milen-yordanov** [comment]
See:
https://developer.chrome.com/docs/workbox/improving-development-experience#shift_and_reload
https://web.dev/articles/service-worker-lifecycle#shift-reload

`When a service worker is active, a forced refresh will also bypass the service worker entirely.`

**Comment by andriwandres** [comment]
Thank you @mmjr-x  for providing a short term fix for this. Works like a charm.
I also hope this will be properly fixed in the near future.

**Comment by edvinv** [comment]
Just to confirm, this issue still persist in Angular 18. Hoping for some official fix from angular team.

**Comment by marcalj** [comment]
Using v21.

With a domain with service worker and HTTPS, with manually allowing notifications, it's showing this error:

```console
Uncaught (in promise) TypeError: Failed to execute 'showNotification' on 'ServiceWorkerRegistration': No notification permission has been granted for this origin.
    at Driver.handlePush (ngsw-worker.js:1688:37)
```

From this code:

```console
this.swPush.subscription.subscribe((response) => console.log("A", response, JSON.stringify(response)));
    this.swPush.pushSubscriptionChanges.subscribe(({oldSubscription, newSubscription}) => console.log("B", oldSubscription, newSubscription, JSON.stringify(oldSubscription), JSON.stringify(newSubscription)));
```

When disabling the notification permission it never shows the permission dialog. Never (accessing the page, reloading or hard reloading).

Push notifications are working correctly through DevTools, and from the backend.

If using a Web APIs directly it's working perfectly fine.

```ts
  async requestPushNotifications(): Promise<void> {
    try {
      // 1. Get the raw service worker registration
      const reg = await navigator.serviceWorker.getRegistration();
      console.log('Native Registration:', reg);

      if (!reg) {
        console.error('No service worker registration found!');
        return;
      }

      // 2. Call the native browser subscription manager
      const sub = await reg.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: this.urlB64ToUint8Array(environment.push_notifications_vapid_public_key)
      });

      console.log('Native Subscription Success:', sub, JSON.stringify(sub));
    } catch (err) {
      console.error('Native Subscription Failed with Error:', err);
    }
  }

  // Helper to convert VAPID key strings for native pushManager
  urlB64ToUint8Array(base64String: string) {
    const padding = '='.repeat((4 - base64String.length % 4) % 4);
    const base64 = (base64String + padding).replace(/\-/g, '+').replace(/_/g, '/');
    const rawData = window.atob(base64);
    const outputArray = new Uint8Array(rawData.length);
    for (let i = 0; i < rawData.length; ++i) {
      outputArray[i] = rawData.charCodeAt(i);
    }
    return outputArray;
  }
```
