### ISSUE TITLE
signals: TypeScript and nullability

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#49161]
### Which @angular/* package(s) are the source of the bug?

core, Don't known / other

### Is this a regression?

No

### Description

The current implementation of signals uses a function to access the value, and TypeScript has issues with type guards in that case:

```ts
const count = signal(null as null | number);
const total: number = count() !== null ? count() : 0;
// Error: Type `number | null` is not assignable to type `number`
```

This can be workaround by storing the value in a temporary variable or with an explicit cast, but this could be a bit cumbersome, as I imagine the same would happen with `ngIf` in templates:

```ts
const count = signal(null as null | number);
const value = count();
const total: number = value !== null ? value : 0;
// Works
```

**Comment by cexbrayat** [comment]
Side note: this is not a big deal, the issue is just to trace a discussion we had with @pkozlowski-opensource on Slack

**Comment by kbrilla** [comment]
Won’t this work:
```typescript
const count = signal(null as null | number);
const total: number = count() ?? 0;
```
or maybe add mapper

```typescript
count((val)=> val !== null ? val : 0)
```
but this would not work well in templates as there is no support for arrow functions there

**Comment by JeanMeche** [comment]
The issue is more about narrowing. In a template with 

<div *ngIf="count()">
  // count still number | null. 
</div>

That wouldn't happen if the value wasn't acced via a function !

**Comment by kbrilla** [comment]
Well there is not only a nullability problem but any kind of type guard 
```typescript
type Shape = {kind: 'Circle', r: number} | {kind: 'Square': a: number};
shape= Signal<>;
```
```html
<span *ngIf="shape().kind === ''Circle">
This is a circle with r={{shape().r}} //type error
</span>
```
You would need to do
```html
<ng-container *ngIf="shape() as shape">  //ngIf hack as with | await
 <span *ngIf="shape.kind === 'Circle'">
    This is a circle with r={{shape.r}} //now ok
  </span>
</ng-container>
```
The same can be used for null | undefined as long as we are not expecting any of '', 0, false so null | undefined is bigger problem as no full workaround for it
```html
<ng-container *ngIf="shapeOrNull() as shape">  //ngIf hack as with | await
 <span *ngIf="shape">
This is a circle with r={{shape.r}} //now ok
</span>
</ng-container>
```

```html
<span *ngIf="numberOrNull() as num">  //will not show answer work for 0
This number is {{num}}
</span >
```

**Comment by Harpush** [comment]
It all boils down to how deep signals should go... Theoretically you could create a computed called `circleShapeRadius` but I am not sure about it. It is also the point of maybe nested signals are needed?
One more option is `ngIf` would produce a casted signal with `as`.
For example a new directive (Maybe it can be done inline in template?):
```html
<div *ngSignalIf="let circleShapeSignal when shapeSignal match checkFn">
  Radius is: {{circleShapeSignal().radius}}
</div>
```

```ts
function checkFn(shape: Shape): shape is CircleShape {
  return shape.kind === 'circle';
}
```
And simplified code to how it works:
```ts
type Shape =
  | { type: 'circle'; radius: number }
  | { type: 'rectangle'; size: number };
const shapeSignal = signal<Shape>({ type: 'circle', radius: 10 });

function test<T, K extends T>(
  signal: Signal<T>,
  checkFn: (value: T) => value is K
) {
  const castedSignal = computed(() => {
    const value = signal();
    return checkFn(value) ? value : undefined;
  });

  effect(() => {
    const casted = castedSignal();

    if (casted) {
      renderView(castedSignal); // pass context to template
    } else {
      destroyView();
    }
  });
}
```

**Comment by flevi29** [comment]
I'm just here to add my vote on some solution that would extract the value from the signal into the template somehow. The current `*ngIf="asd() as asd"` is very limited and unsatisfactory.

Something like:
```
@using val() as val { // or val$ | async as val
  @if { ... }
  @else { ... }
  ...
}
```

Although most likely this wouldn't be simple to implement, and probably has many flaws, it would feel nice.

**Comment by montella1507** [comment]
> Side note: this is not a big deal, the issue is just to trace a discussion we had with @pkozlowski-opensource on Slack

it is big deal. It is really HARD to use for real-world projects.

**Comment by JesseZomer** [comment]
Lets say I have the following template:  (query is either a succesfull response or an error response type with an error field)
```HTML
        @switch (query().status) {
            @case ('pending') {
                <span>...loading</span>
            }
            @case ('error') {
                <span>Error: {{ query().error.message }}</span>
            }
        }
```
Currently this is not allowed because error might be null. Of course I could do error(?/!).message but I'm wondering if there is another way. Is the only other alternative currently:
```HTML
    @if (query(); as query) {
        @switch (query.status) {
            @case ('pending') {
                <span>query.status</span>
            }
            @case ('error') {
                <span>Error: {{ query.error.message }}</span>
            }
        }
    }
```
?  
something like 
```HTML
        @switch ((query() as query).status) {
            @case ('pending') {
                <span>...loading</span>
            }
            @case ('error') {
                <span>Error: {{ query.error.message }}</span>
            }
        }
```
would be nice

**Comment by SeraphCoding** [comment]
@JesseZomer - in your idea, your error could still possibly be null and you wouldn't be catching that possibility. It's code that can very easily break if someone just introduces a new status that assumes an error without a message. If they don't know you simply "expect" data to be there without checking whether it is, you end up with error-prone code.

All it takes is checking for the error to exist and while you're at it you can deal with a scenario where no error message is given.
```HTML
@switch(query().status) {
  @case (pending) {
    <span>...loading</span>
  }
  @case (error) {
    @if (query().error; as error) {
      <span>Error {{error.message}}</span>
    } else {
      <span>An unknown error occurred</span>
    }
  }
}
```
Hope this helps 🙂

It all boils down to writing code that is technically more fail-safe in a reactive paradigm. You ensure that your data exists. The reactive paradigm here simply dictates that your query could change at any point in time.

Signals are not observables. Don't use them as a replacement for what should be observables. 

There are also more alternatives (especially for other hurdles) that "simply" require you to utilize computed signals that provide you with un-ambiguous data that is safe to use. As I said - observables and signals are not the same and should be treated differently.

I disagree with the sentiment that this is somehow a "huge problem" - it honestly just feels like people are misusing signals for things that should be observables. If you really want to or need to use signals, then you have to ensure type/null safety in a signal supported manner.

**Comment by montella1507** [comment]
It is not only about nullablity... it is about type guards too.

**Comment by JesseZomer** [comment]
@SeraphCoding Maybe I've should've included the types, but it's something along the lines of:
```
type queryresult = SuccesfullQuery | ErrorQuery | LoadingQuery

type SuccessfullQuery {
 status: 'succes';
 data: Data;
 error: null;
}

type ErrorQuery {
 status: 'error';
 error: Error;
 data: null;
}
```
so checking for status 'error' is the same as checking if error exists or not. The whole problem is that I want to get rid of that extra if, because it shouldn't need to be there. It should narrow the query result to ErrorQuery.

> Signals are not observables. Don't use them as a replacement for what should be observables.

I'm not.

**Comment by montella1507** [comment]
> @SeraphCoding Maybe I've should've included the types, but it's something along the lines of:
> 
> ```
> type queryresult = SuccesfullQuery | ErrorQuery | LoadingQuery
> 
> type SuccessfullQuery {
>  status: 'succes';
>  data: Data;
>  error: null;
> }
> 
> type ErrorQuery {
>  status: 'error';
>  error: Error;
>  data: null;
> }
> ```
> 
> so checking for status 'error' is the same as checking if error exists or not. The whole problem is that I want to get rid of that extra if, because it shouldn't need to be there. It should narrow the query result to ErrorQuery.
> 
> > Signals are not observables. Don't use them as a replacement for what should be observables.
> 
> I'm not.

Yeah.. discriminated unions.

**Comment by compeek** [comment]
I ran into this problem almost immediately when I started trying out signals. I also think it's crucial that Angular somehow support type narrowing for signals in templates. It would improve the developer experience tremendously.

**Comment by henryli17** [comment]
There is a hacky workaround to this, which is using a getter function to wrap the signal value.



```ts
export class AppComponent {
	public _num: WritableSignal<LoadState<number>> = signal({ state: "idle" });

	public get num() {
		return this._num();
	}
}
```

```ts
// Property 'data' does not exist on type 'WritableSignal<LoadState<number>>'
@if (_num().state !== 'idle') {
	{{ _num.data }}
}

// This works fine
@if (num.state !== 'idle') {
	{{ num.data }}
}
```

**Comment by SeregPie** [comment]
We have an `$any()` helper available in the templates. Maybe something like this as a proxy for the signals?

```ts
@Component({
  template: `
    @if ($.foo != null) {
      <span>{{ $.foo }}</span>
    }
  `,
})
export class MyComponent {
  foo = input<null | number>(null);
}
```

---

Could be done with something like this.

```ts
import {Component, Signal, isSignal} from '@angular/core';

export type UnwrapSignal<T> = T extends Signal<infer V> ? V : T;

export type UnsignalifyProxy<T extends object> = {
  [K in keyof T]: UnwrapSignal<T[K]>;
};

const unsignalifyProxyHandler: ProxyHandler<any> = {
  get: (target, key, receiver) => {
    const value = Reflect.get(target, key, receiver);
    return isSignal(value) ? value() : value;
  },
  set: (target, key, newValue, receiver) => {
    // todo
  },
};

export function unsignalify<T extends object>(target: T): UnsignalifyProxy<T> {
  return new Proxy(target, unsignalifyProxyHandler);
}
```

**Comment by MikaStark** [comment]
I played around with SolidJS and it has the same issue. The only answer to this problem is nesting `@if` (Show component for SolidJS) control.

```html
@if (somethingNullable() as something) {
  @if (something.list.length > 0) {
    <div>Something has items!</div>
  }
}
```

**Comment by montella1507** [comment]
> I ran into this problem almost immediately when I started trying out signals. I also think it's crucial that Angular somehow support type narrowing for signals in templates. It would improve the developer experience tremendously.

Yeah i wonder if someone has really tried the signals before tagging them as bright future.

**Comment by MikaStark** [comment]
The problem arises from the need to "call" signals to retrieve their values, preventing TypeScript from effectively type guarding the returned value. I believe this is more of a design flaw than an inherent issue. If signals had a "value" getter, this problem would likely be mitigated.

```html
@if (somethingNullable.value && somethingNullable.value.list.length > 0) {
  <div>Something has items!</div>
}
```

**Comment by csisy** [comment]
I could live with a solution that would solve other, non signal related problems:

Provide a built-in mechanism to create a scoped variable in a template without using an if statement, as the current community solution. Something like this:

```
@let (mySignal() as myCurrentValue) {
}
```

The problem with the `@if` solution is that if you have `null` or any `falsy` value as a valid value in your signal / function call / whatever, then the condition will evaluate to false and the code section will be omitted.

**Comment by compeek** [comment]
> [EDIT] Angular team seems to prefer relying on non-null assertion according to angular.dev code (cf.
> 
> https://github.com/angular/angular/blob/8dea3b58880d7966ec3b6b6f424173ee3fee2142/adev/src/app/features/docs/docs.component.html#L4
> 
> )

That's a good point. I guess the non-null assertion operator is a workaround for now, but it's prone to mistakes, and I'm in the habit of avoiding it unless absolutely necessary, so I'm still hoping for a more proper solution.

**Comment by MikaStark** [comment]
@csisy your proposal could seems appropriated but IMO it would leads to a nesting nightmare if used with multiples signals just like @if control flow with « as » aliasing does already.

For me, there is two viable options :
- signals calls return type is inferred directly in template : nothing to change on developer side but I don’t know how Angular team can twist Typescript to make it works
- signals « callability » is replaced by a value property which has exactly the same behavior (getter function) : requires to migrate every signal but not requires to modify anything in Angular Language Service

I think Angular Signals are too much inspired from solidjs but the frameworks are so much different. Thanks to JSX, solidjs provides the possibility to use a callback directly in control flow components to extract a signal value as good old variable and so mitigate this typing issue.

Definitely, the core problem is the « callability » of signals.

**Comment by TimUnderhay** [comment]
After working with signals for a while now, I'm convinced that the issue is the underlying design choice to make signal unwrapping function-based rather than getter-based.  This choice is forcing developers to either write verbose, ugly, harder to maintain template code, or to write less safe code by using ! or just switching off strict null checks and / or strict templates altogether to make the red ocean of bogus template errors go away.

Please Angular team, reconsider this design choice.  It isn't too late.

**Comment by stefnotch** [comment]
Would something like this work, as a temporary fix until the Angular team gracefully decides to look at this issue?
Essentially, it replaces the Angular Signal API with something more akin to what Vue.js does. I'm not sure if this is guaranteed to work, or if it might subtly change the reactivity.

```ts
type Ref<T> = {
  value: T;
  update: (mapFn: (old: T) => T) => void;
  asReadonly: () => ReadonlyRef<T>;
};

type ReadonlyRef<T> = {
  readonly value: T;
  asReadonly: () => ReadonlyRef<T>;
};

function makeRef<T>(signal: WritableSignal<T>): Ref<T> {
  return {
    get value() {
      return signal();
    },
    set value(newValue: T) {
      signal.set(newValue);
    },
    update<U extends T>(mapFn: (old: T) => U) {
      signal.update(mapFn);
    },
    asReadonly(): ReadonlyRef<T> {
      return {
        get value() {
          return signal();
        },
        asReadonly() {
          return this;
        },
      };
    },
  };
}
```


Usage examples
```ts
@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  count = makeRef(signal<number | null>(10));

  nextValue = computed(() =>
    this.count.value !== null ? this.count.value + 1 : 0
  ); // Look at how this just works

  update(event: Event) {
    const input = event.target as HTMLInputElement;
    this.count.value = parseInt(input.value);
  }
}
```

```html
<!-- Typescript is happy! -->
<p>Next value with ngIf:</p>
<p *ngIf="count.value !== null">{{ count.value + 1 }} cups</p>
```

**Comment by TimUnderhay** [comment]
@stefnotch Your solution sounds quite plausible, though I also wonder if it will subtly alter the reactivity.  I suspect that it won't as signals are, for the moment, still dependent on change detection, and the getter references should be equal to the unwrap function's.  But it would satisfy Typescript's nullability mechanism.  The only downside is that unlike Vue, one would have to add `.value` to the template vars, but it would be a small price to pay.

Would you mind if I were to adopt your code into my ngx-signal-utils library at https://github.com/TimUnderhay/ngx-signal-utils ?

**Comment by TimUnderhay** [comment]
I've opened https://github.com/angular/angular/issues/54906 to hopefully get some attention on this from the Angular team.

**Comment by alxhub** [comment]
Hey all!

Type narrowing of signals in templates is a pain point at the moment, and is on our backlog. I've updated our [project tracker](https://github.com/orgs/angular/projects/31/views/2) to track this issue directly to make the progress more visible.

In the original design, we understood there would be challenges with type narrowing and function-based signals. We strongly preferred the functional design anyway (for reasons spelled out in the RFC) and hypothesized that we could address the DX challenges with narrowing using our compiler, which is the plan.

At a high level, our template type-checking engine can apply extra type narrowing to signals, so that the templates:

```typescript
@if (data()) {
  {{data().value}}
}
```

or

```typescript
@if (shape().kind === 'circle') {
  {{shape().radius}}
}
```

will narrow the type of `data()` correctly. We can go beyond TypeScript's narrowing semantics in templates because we know the value of a signal will not change between reads, as templates are executed synchronously and cannot set signals.

**Comment by csisy** [comment]
What do you think about extending the new control flow syntax a bit? Recently I've been using cpp where we can initialize variables inside the conditional part of the if statement. For example:
```cpp
if (auto myValue = ...; myValue > 5) {
  // executed if myValue > 5
}
// or
if (auto myValue = ...) {
  // executed if myValue is "truthy"
}
```
With signals and the new control flow syntax, is it possible to implement something similar?
```
@if (let data = data(); data > 5) {}
@if (let data = data()) {}
```
Not sure if this would be harder to implement than the type narrowing you mentioned. However, it would have use-cases outside of signals, where we want to render something conditionally.

**Comment by stefnotch** [comment]
@csisy 
For what it's worth, Svelte has a `@const` statement to define a local variable inside a template. That might be a more general and convenient solution.

https://svelte.dev/docs/special-tags#const

I personally think that implementing such a `@const` wouldn't make the improved narrowing obsolete in any way. And neither would the improved narrowing take care of all the use-cases for a template-local variable definition.

**Comment by Harpush** [comment]
I believe it is a tricky question... The compiler automatic type narrowing Alex mentioned is indeed handy and will solve the problem (any ETA btw?). What remains a bit of an issue is a case when we have nested checks or long properties access path. It might be nice having some way to alias in template (`@const` as mentioned here for example). In simple cases the compiler auto narrow is enough but sometimes in large objects it makes sense to create a variables and use it multiple times.
Let's assume we wanted to write `shape().width | number` and use it three times - interpolation, pass it as input and in a tooltip. Could be nice if I could assign it to a variable as use that one three times.

**Comment by flevi29** [comment]
`@const` might also work better with [`AsyncPipe`](https://angular.io/api/common/AsyncPipe) as well, maybe. Anyways this is the closest thing to what I was proposing https://github.com/angular/angular/issues/49161#issuecomment-1798469278 .

**Comment by JeanMeche** [comment]
Template variable declaration is a separate topic and is tracked by #15280 🙂

**Comment by c-harding** [comment]
I’ve just encountered this problem outside the template, in a computed signal:

```ts
computed(() => this.address() && this.getAsString(this.address())) // error TS2345: Argument of type Address | undefined is not assignable to parameter of type Address
```
I could have written:
```ts
computed(() => {
  const address = this.address();
  return address && this.getAsString(address))
```
but that seems unnecessarily verbose. With Vue this was never a problem, because TypeScript assumes that `address.value` never changes, unlike `address()`. Is there any way of convincing TypeScript that type narrowing works across function calls?

**Comment by c-harding** [comment]
@JeanMeche that PR is only for templates rather than in TypeScript

**Comment by Eduard20CR** [comment]
I have an issue, I need to set the value of the signal in the AfterViewInit because I need the component to be ready, after I check if the values is not undefined, it keeps saying it may be undefined. 

```typescript
  stage: WritableSignal<Konva.Stage | undefined> = signal(undefined);

  ngAfterViewInit(): void {
    this.initStage()
  }

  initStage() {
    const width = this.container.nativeElement.offsetWidth;
    const height = this.container.nativeElement.offsetHeight;

    this.stage.set(new Konva.Stage({
      container: 'container',
      width,
      height,
      scale: { x: this.getScale(), y: this.getScale() },
    }))

    if (!this.stage()) return;  // -> 'stage' is possibly 'undefined'.

    stage.on('click', (e) => {
      this.transformer().nodes([]);
      if (e.target === this.stage()) return;
      if (e.target instanceof Konva.Image) return;
      this.transformer().nodes([e.target]);
    })
}
``` 

I fixed it by putting stage in a local variable, but I dont think it is a great solution, am I doing something wrong?

```typescript
  stage: WritableSignal<Konva.Stage | undefined> = signal(undefined);

  ngAfterViewInit(): void {
    this.initStage()
  }

  initStage() {
      const width = this.container.nativeElement.offsetWidth;
    const height = this.container.nativeElement.offsetHeight;

    this.stage.set(new Konva.Stage({
      container: 'container',
      width,
      height,
      scale: { x: this.getScale(), y: this.getScale() },
    }))

    const stage = this.stage()
    if (!stage) return;

    stage.on('click', (e) => {
      this.transformer().nodes([]);
      if (e.target === this.stage()) return;
      if (e.target instanceof Konva.Image) return;
      this.transformer().nodes([e.target]);
    })
}
```

**Comment by amakhrov** [comment]
Is the official recommendation now - using `@let` (as per [this comment](https://github.com/angular/angular/pull/55456#issuecomment-2339782667))?

If so, should we now close this issue? Or is there anything else that the team is thinking of to further improve it?

**Comment by reduckted** [comment]
Using `@let` would only help in templates. It doesn't solve the problem in TypeScript.

https://github.com/angular/angular/issues/49161#issuecomment-2076825519

**Comment by Urinal-aft** [comment]
> It all boils down to how deep signals should go... Theoretically you could create a computed called `circleShapeRadius` but I am not sure about it. It is also the point of maybe nested signals are needed? One more option is `ngIf` would produce a casted signal with `as`. For example a new directive (Maybe it can be done inline in template?):
> 
> <div *ngSignalIf="let circleShapeSignal when shapeSignal match checkFn">
>   Radius is: {{circleShapeSignal().radius}}
> </div>
> function checkFn(shape: Shape): shape is CircleShape {
>   return shape.kind === 'circle';
> }
> And simplified code to how it works:
> 
> type Shape =
>   | { type: 'circle'; radius: number }
>   | { type: 'rectangle'; size: number };
> const shapeSignal = signal<Shape>({ type: 'circle', radius: 10 });
> 
> function test<T, K extends T>(
>   signal: Signal<T>,
>   checkFn: (value: T) => value is K
> ) {
>   const castedSignal = computed(() => {
>     const value = signal();
>     return checkFn(value) ? value : undefined;
>   });
> 
>   effect(() => {
>     const casted = castedSignal();
> 
>     if (casted) {
>       renderView(castedSignal); // pass context to template
>     } else {
>       destroyView();
>     }
>   });
> }





https://typescripts.space/questions/error-in-typescript-due-to-object-being-undefined

**Comment by JeanMeche** [comment]
Ideally this should be fixed by a language feature, this is currently being discussed here microsoft/TypeScript#60948

**Comment by baarney** [comment]
In a similar vein to https://github.com/angular/angular/issues/49161#issuecomment-1988728595, for those that don't mind using a value accessor you can just add it directly to the signal:
```
export function addValueAccessor<T>(sig: Signal<T>) {
  return Object.defineProperty(sig, 'value', {
    get() { return this(); }
  }) as Signal<T> & { value: T };
}
```
Usage:
```
type Foo = {
  name: string;
}

const f1 = signal<Foo | undefined>(undefined);
const f1Name = f1() ? f1().name : "unknown";                // Object is possibly undefined

const f2 = addValueAccessor(signal<Foo | undefined>(undefined));
const f2Name = f2.value ? f2.value.name : "unknown";        // correctly narrowed
```
If you want updates too then add a setter for `WritableSignal`s:
```
    set(val) { this.set(val); }
```
Some caveats:
1. My typescript is not good enough to add a single declaration for all signals. I tried `function addValueAccessor<T, S extends Signal<T>>(sig: S): S & { value: T }` but it loses the value of `T`. I just overloaded it for all the signals I wanted.
2. Cannot be used directly on `InputSignal` because of the compiler's static type checking: `TS-998110: Unsupported call to the input function...`.

**Comment by lky141319** [comment]
Claiming bounty. 
Wallet: 0xd2268DEDca16b08aF4bb6Ad20cBa877D10cf8Ac6
GitHub: @lky141319

**Comment by lky141319** [comment]
Claiming bounty. 
Wallet: 0xd2268DEDca16b08aF4bb6Ad20cBa877D10cf8Ac6
GitHub: @lky141319
