### ISSUE TITLE
fix(dev-tools): error injector configuration issue

### ISSUE THREAD

**Issue by NsdHSO** [angular/angular#52932]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide a screenshot if possible [Bug Report only]

![image](https://github.com/angular/angular/assets/37635083/65e532d6-487d-4c11-86de-722b3ad99336)

### Please provide the exception or error you saw [Bug Report only]

```true
zone.js:1681 Uncaught Error: ASSERTION ERROR: Could not determine where injector providers were configured.
    at throwError (core.mjs:392:11)
    at getEnvironmentInjectorProviders (core.mjs:31167:9)
    at Object.getInjectorProviders [as ɵgetInjectorProviders] (core.mjs:31208:16)
    at De (component-tree.ts:238:20)
    at cn (component-tree.ts:339:21)
    at sn (component-tree.ts:183:30)
    at pn (component-tree.ts:562:34)
    at Di (client-event-subscribers.ts:264:47)
    at kn (client-event-subscribers.ts:240:43)
    at kn (client-event-subscribers.ts:235:21)
throwError @ core.mjs:392
getEnvironmentInjectorProviders @ core.mjs:31167
getInjectorProviders @ core.mjs:31208
De @ component-tree.ts:238
cn @ component-tree.ts:339
sn @ component-tree.ts:183
pn @ component-tree.ts:562
Di @ client-event-subscribers.ts:264
kn @ client-event-subscribers.ts:240
kn @ client-event-subscribers.ts:235
kn @ client-event-subscribers.ts:235
kn @ client-event-subscribers.ts:235
(anonymous) @ client-event-subscribers.ts:77
n @ same-page-message-bus.ts:41
invokeTask @ zone.js:402
runTask @ zone.js:173
invokeTask @ zone.js:483
invokeTask @ zone.js:1631
globalCallback @ zone.js:1674
globalZoneAwareCallback @ zone.js:1695
postMessage (async)
emit @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:1
s @ content_script_bundle.js:1
Show 12 more frames
Show less
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version. [Bug Report only]

```true
arc
```

**Comment by jessicajaniuk** [comment]
@NsdHSO Thanks for the report! I think this is a duplicate and has already been fixed. The release of v17.0.3 should resolve it. @AleksanderBodurri can you confirm?

**Comment by AleksanderBodurri** [comment]
Thank you @NsdHSO for reporting this issue 🙏 

A fix for this bug has been merged in https://github.com/angular/angular/pull/52774. Upgrading to Angular 17.0.3 when it's released should resolve this problem

**Comment by NsdHSO** [comment]
Yes, after I updated the angular version to 17
.0.3 did not appear again, how nice.
![image](https://github.com/angular/angular/assets/37635083/fc6ee216-1c09-42c4-ba7e-93f07d66daba)

**Comment by kbrilla** [comment]
@jessicajaniuk hi, after updating to 17.0.3 this still happens for our app, should I open new issue or mayby reopen this one?

**Comment by NsdHSO** [comment]
> @jessicajaniuk hi, after updating to 17.0.3 this still happens for our app, should I open new issue or mayby reopen this one?
> 
> Could error provide information where the injector that cannot be resolved is used? or mayby 'just skip' it and try to build as good as possible tree and provide some 'toast' inside devtool that tree is not complete? Anything is better than nothing.

can you try with this stuff?
```   "dependencies": {
    "@angular/animations": "^17.0.3",
    "@angular/common": "^17.0.3",
    "@angular/compiler": "^17.0.3",
    "@angular/core": "^17.0.3",
    "@angular/forms": "^17.0.3",
    "@angular/platform-browser": "^17.0.3",
    "@angular/platform-browser-dynamic": "^17.0.3",
    "@angular/router": "^17.0.3",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.0.1",
    "@angular/cli": "~17.0.1",
    "@angular/compiler-cli": "^17.0.3",
    "@types/jasmine": "~4.3.0",
    "jasmine-core": "~4.6.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.2.2"
  }
```

**Comment by AleksanderBodurri** [comment]
> @jessicajaniuk hi, after updating to 17.0.3 this still happens for our app, should I open new issue or mayby reopen this one?
> 
> Could error provide information where the injector that cannot be resolved is used? or mayby 'just skip' it and try to build as good as possible tree and provide some 'toast' inside devtool that tree is not complete? Anything is better than nothing.

Hi @kbrilla, are you seeing the same error message that is present in the original post of this issue? The fix in #52774 should [remove that error message](https://github.com/angular/angular/pull/52774/files#diff-6622e3c54524c8e1eda0511fee5c85fb4d854470bb085cf81672bb54bdd503d2L417) entirely.

**Comment by kbrilla** [comment]
Hi after updates dev tools works partially now. `Components` and `Profiler` tabs works, but `Injectior Tree` fails without any information on reason both in main console nor on `devtools console`. If there is some kind of snapshot I can provide of Injector tree then I can provide it but as for creating some small repo with this error then there will be problem as without any error I don't even know whrere to start.
