### ISSUE TITLE
Cannot set signal input in tests with non-standard setup (Stackblitz/Jest preset without JIT transform) - NG0303

### ISSUE THREAD

**Issue by GeorgeKnap** [angular/angular#54013]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

In unit tests using this function to set signal based inputs
```
    fixture = TestBed.createComponent(ParagraphBlockComponent);
    component = fixture.componentInstance;
    fixture.componentRef.setInput('title', 'my title');
```
results in error 
`NG0303: Can't set value of the 'title' input on the 'ParagraphBlockComponent' component. Make sure that the 'title' property is annotated with @Input() or a mapped @Input('title') exists.`

this is the component:
```
@Component({
  standalone: true,
  selector: 'paragraph-block',
  templateUrl: './paragraph-block.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ParagraphBlockComponent {
  title = input<string>();
}
```

### Please provide the exception or error you saw

`NG0303: Can't set value of the 'title' input on the 'ParagraphBlockComponent' component. Make sure that the 'title' property is annotated with @Input() or a mapped @Input('title') exists.`

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 17.1.0
```

**Comment by JoostK** [comment]
What tooling are you using to run the tests?

**Comment by JeanMeche** [comment]
@JoostK I can reproduce the issue on stackblitz : https://stackblitz.com/edit/ng-jasmine?file=src%2Fapp%2Fapp.component.spec.ts

**Comment by JoostK** [comment]
I never know how Stackblitz' compilation pipeline works (the legacy one, without We containers), but the behavior is expected if the custom JIT transform that was added in 17.1 is not being used.

**Comment by JeanMeche** [comment]
You're right, the same test does pass locally.

**Comment by TarsisDragomir** [comment]
I have exactly same issue when using the new signal input api that 17.1 introduced. Using jest for testing but cannot use componentRef.setInput anymore (get same error as reporter of this issue). Somebody changed it to a stackblitz issue, but not sure if that is correct. Or maybe I am missing something that I should have upgraded/changed also after going to 17.1. Any help is welcome. Thanks!

**Comment by devversion** [comment]
@TarsisDragomir can you explain what setup you are using? Jest from the Angular CLI? Jest standalone etc. Maybe share some parts of your `package.json`, or a reproduction would be even better. I'd be happy to look more into it.

**Comment by JoostK** [comment]
If using `jest-preset-angular` this is because they don't perform the new JIT transform yet (https://github.com/thymikee/jest-preset-angular/tree/e728e37aae6279f242afa1d746b7cfc2178fe085/src/transformers).

**Comment by TarsisDragomir** [comment]
@devversion was trying to setup a stackblitz showing the error
@JoostK indeed, I'm using jest-preset-angular. I'm a bit confused, you're saying it cannot be done yet and I just have to wait for a newer version of jest-preset-angular?

**Comment by JoostK** [comment]
This would need to become supported in `jest-preset-angular`, indeed; you can't configure it yourself.

**Comment by devversion** [comment]
Thanks @TarsisDragomir, no worries. Thank you for giving feedback early. I'm in contact with the Jest preset maintainer to help enable signal inputs.

**Comment by bzehetmayer** [comment]
I have the same error when try to use setInput of the fixutre.componentRef using Jest. Except I am not using jest-preset but nx/jest within NX monorepo.

simplified package.json:
```
  "dependencies": {
    "@angular/animations": "17.1.0",
    "@angular/cdk": "17.1.0",
    "@angular/common": "17.1.0",
    "@angular/compiler": "17.1.0",
    "@angular/core": "17.1.0",
    "@angular/forms": "17.1.0",
    "@angular/material": "17.1.0",
    "@angular/platform-browser": "17.1.0",
    "@angular/platform-browser-dynamic": "17.1.0",
    "@angular/router": "17.1.0",
    "@nx/angular": "17.2.8",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "17.1.0",
    "@angular-devkit/core": "17.1.0",
    "@angular-devkit/schematics": "17.1.0",
    "@angular/cli": "17.1.0",
    "@angular/compiler-cli": "17.1.0",
    "@angular/language-service": "17.1.0",
    "@nx/devkit": "17.2.8",
    "@nx/jest": "17.2.8",
    "@nx/js": "17.2.8",
    "@nx/storybook": "17.2.8",
    "@nx/workspace": "17.2.8",
    "@schematics/angular": "~17.0.0",
    "@types/jest": "^29.4.0",
    "@types/node": "18.16.9",
    "autoprefixer": "^10.4.0",
    "jest": "^29.4.1",
    "jest-environment-jsdom": "^29.4.1",
    "jest-environment-node": "^29.4.1",
    "jest-preset-angular": "~14.0.0",
    "jsdom-testing-mocks": "^1.11.0",
    "jsonc-eslint-parser": "^2.1.0",
    "ng-packagr": "17.1.0",
    "nx": "17.2.8",
    "ts-jest": "^29.1.0",
    "ts-node": "10.9.1",
    "typescript": "~5.3.3"
  }
```

**Comment by devversion** [comment]
FYI: 

* Working with Stackblitz. WebContainer's from Stackblitz work naturally as those can use the Angular CLI.
* Sent a PR for the community Jest Angular preset to support signal inputs, queries, model etc. https://github.com/thymikee/jest-preset-angular/pull/2303

**Comment by JosefBredereck** [comment]
I found that it is possible to have a workaround for direct inputs if you would rather not use a wrapper component.

But these functionalities do not have any description, and I can only assume that they will be internal in the future.

```ts
import { SIGNAL, signalSetFn } from '@angular/core/primitives/signals';

signalSetFn(component.title[SIGNAL], 'title');
```

**Comment by JoostK** [comment]
> I found that it is possible to have a workaround for direct inputs if you would rather not use a wrapper component.
> 
> But these functionalities do not have any description, and I can only assume that they will be internal in the future.
> 
> ```ts
> import { SIGNAL, signalSetFn } from '@angular/core/primitives/signals';
> 
> signalSetFn(component.title[SIGNAL], 'title');
> ```

The entire `@angular/core/primitives/signals` is not public API, those symbols or their behavior may change in any version.

**Comment by timothee-dhenain-zenika** [comment]
The issue has been fixed for Jest: https://github.com/thymikee/jest-preset-angular/issues/2246

**Comment by maxfriedmann** [comment]
> The issue has been fixed for Jest: [thymikee/jest-preset-angular#2246](https://github.com/thymikee/jest-preset-angular/issues/2246)

You also need to update jest to the latest version, in v 29.5.x this issue still occurs.

**Comment by devversion** [comment]
Closing because:

- we've collaborated with Jest to support signal inputs, queries, model etc — this now works
- we've collaborated with Stackblitz to support non-Webcontainer instances— this now works

https://github.com/thymikee/jest-preset-angular/pull/2303
https://stackblitz.com/edit/ng-jasmine-wec9ye?file=src%2Fapp%2Fapp.component.ts

**Comment by dapperdandev** [comment]
@devversion Is this fixed for `@angular-devkit/build-angular:jest`?

**Comment by devversion** [comment]
@dapperdandev The official `jest` builder should have worked since we launched signal inputs. Do you see any issues? If so, please create an issue and link here.

**Comment by dapperdandev** [comment]
@devversion I'll hold of for a bit. We have a hybrid app that's moving toward shell/side-by-side. It's not ruining our day at the moment and I can assess it better once it's truly standing on it's own feet.
