### ISSUE TITLE
Locale fr-CH (still) wrong

### ISSUE THREAD

**Issue by phrei** [angular/angular#58773]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

In PRs #22308 and #20844 people tried to fix the locales for `fr-CH`. The answer was, that those are generated from CLDR and that a bug should be filed there.

According to https://www.unicode.org/cldr/cldr-aux/charts/23/summary/fr_CH.html though, their version (over 10 years old) seems to be correct - I'm talking especially about the "number group" symbol which is an apostrophe (') for `fr-CH` whereas it is a space ( ) for it's parent `fr`. 

I've compared the angular (generated?) `fr-CH` locale to `de-CH` which should have the same delimiters for decimals and grouping (thousands). It seems like `fr-CH` uses it's parents symbols instead of the specific ones:

![Image](https://github.com/user-attachments/assets/a242e93b-a96f-4c36-aad9-b032ff6cd8f1)

### Please provide the exception or error you saw

```true
The number `1234,56` in `fr-CH` is expected to show up as `1'234.56` but instead is shown as `1 234,56`
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.9
Node: 20.18.0
Package Manager: npm 10.8.2
OS: win32 x64

Angular: 17.3.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.9
@angular-devkit/build-angular   17.3.11
@angular-devkit/core            17.3.9
@angular-devkit/schematics      17.3.9
@angular/cdk                    17.3.10
@angular/cli                    17.3.9
@angular/material               17.3.10
@schematics/angular             17.3.9
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.10
```

**Comment by JeanMeche** [comment]
This was indeed fixed in the CLDR in v42 ([see blame](https://github.com/unicode-org/cldr-json/blame/main/cldr-json/cldr-numbers-full/main/fr-CH/numbers.json)). 

We're lagging several version behind on the CLDR update (we're using currently v41). 
The solution we're currently investigating is moving the implementation to using the `Intl` api, see : 
* #54470

**Comment by phrei** [comment]
I think it's still wrong in CLDR - even according to your blame the group is ` ` and the decimal `,` instead of `'` and `.`. Same with currencies.

**Comment by JeanMeche** [comment]
Then you'd how to report this issue to the Unicode consortium. By their latest definition, there is no group symbol defined for `fr_CH` : https://www.unicode.org/cldr/charts/43/by_type/numbers.symbols.html 

Also noticing that `new Intl.NumberFormat('fr-ch', { style: 'currency', currency: 'CHF' }).format(1234)` returns `'1 234.00 CHF'`.

**Comment by JeanMeche** [comment]
I'll close this as this is a CLDR issue, not an Angular issue.
