### ISSUE TITLE
Duplicate tbody in ngFor

### ISSUE THREAD

**Issue by ggmod** [angular/angular#5967]
If I write something like this:
```html
<tbody *ngFor="#item of [1,2,3]" myTableRow></tbody>
```

that uses the following component:
```typescript
@Component({
  selector: '[myTableRow]',
  template: '<tr><td>test</td></tr>'
})
export class MyTableRow {}
```
then it produces invalid HTML, there will be two nested tbody tags, like this:
```html
<tbody mytablerow="">
  <tbody>
    <tr><td>test</td></tr>
   </tbody>
</tbody>
```
(In the real application I use this to group together multiple tr tags in a tbody, and the table has many tbody tags after each other)

I get all kinds of malformed tables because of this, and it also breaks the usual `table > tbody > td` CSS rules, and is actually invalid HTML.
This worked fine with alpha.46, but has been broken since alpha.47.
Demo here: http://plnkr.co/edit/myYJZf6ZZj1ofhIcNj7E?p=preview

**Comment by ggmod** [comment]
Actually, the issue doesn't depend on ngFor at all, the same thing happens with a template like this:
```html
<tbody myTableRow></tbody>
```
The problem is caused by the fact that the template parser's required parent logic applies to the template's root elements too: but the parent element of the template's root element is unkown at the time when the template is compiled, it will only be revealed when the component is inserted into the page.

If I change angular's html parser to skip the required parent logic for the root element(s), then everything works fine. In <b>html_parser.ts</b>
```javascript 
if (tagDef.requireExtraParent(isPresent(parentEl) ? parentEl.name : null)) {
```
should be:
```javascript
if (isPresent(parentEl) && tagDef.requireExtraParent(parentEl.name)) {
```

**Comment by pkozlowski-opensource** [comment]
@ggmod what is the version of Angular2 that you are using? Could you please provide a reproduce scenario with plunker (or similar on-line tool)?

**Comment by ggmod** [comment]
Both the plunker and the version number are there in the original post, but here it is again:
http://plnkr.co/edit/myYJZf6ZZj1ofhIcNj7E?p=preview 
using the beta version, but the mistake appeared between alpha.46 and alpha.47

**Comment by pkozlowski-opensource** [comment]
Yes, I see, this is a bug. Thnx for reporting.

**Comment by filoucpp** [comment]
hi guys! any idea when this would be fixed? I am using 2.0.0-beta.3 and the issue is still there :)

**Comment by sasidhar** [comment]
+1 Need a fix for this bug

**Comment by thane421** [comment]
+1

**Comment by denodaeus** [comment]
+1, also need a fix for this bug (using beta.7)

**Comment by PascalPrecht** [comment]
Maybe someone is willing to try to fix it?

**Comment by sasidhar** [comment]
@PascalPrecht, already @ggmod mentioned a fix above. But it's not a pull request. I am currently using his fix with angular beta.7

**Comment by cagataycivici** [comment]
I seriously need the fix for this bug. +1

**Comment by adrianromanko** [comment]
+1

**Comment by denodaeus** [comment]
Is this going to make it into a release soon?

**Comment by mohsenvafa** [comment]
+1 I need also a fix for this.

**Comment by yassirj1** [comment]
+1 this needs to be fixed

**Comment by tscheinecker** [comment]
I just stumpled across the same issue (using beta.14)

The issue acutally seems to be that the template starts with a `<tr>` element:

**Comment by lukaszdechovan** [comment]
+1 I would like this bug fixed, as workaround I replaced all table elements with divs and created css classes (such as .table, .thead, .tr, .td, .th) but thats really ugly non-semantic solution.

**Comment by zoechi** [comment]
I guess that's a browser feature. Angular probably creates `documentFragment`s of the HTML (`<tr>`) before inserting and the browser automatically wrapps it with `<tbody>` and that is than inserted (just a guess).

**Comment by tscheinecker** [comment]
@zoechi i don't think that's the issue

if you execute

```js
var df = new DocumentFragment();
df.appendChild(document.createElement('tr'));
document.querySelector('body').appendChild(df);
```

you get exactly the dom you would expect:

```html
<body>
  <tr></tr>
</body>
```

not very useful or even valid but still exactly what you defined

**Comment by denodaeus** [comment]
Any update on this one?  It's a P2 with a fix attached to it -- but this bug still made it into the release candidate.

**Comment by andyrue** [comment]
+1 Also just ran into this with rc.1.

**Comment by fringd** [comment]
It seems like you're doing it wrong? here's the way I write this. I don't see any reference to your syntax in the docs at https://angular.io/docs/ts/latest/guide/template-syntax.html

```
<tbody>
  <myTableRow *ngFor="#item of [1,2,3]"></myTableRow>
</tbody>
```

**Comment by fringd** [comment]
your <tbody *ngFor... myTableRow>
gets translated into

```
<template [ngFor]...>
  <tbody myTableRow></tbody>
</template>
```

and your myTableRow component will be re-rendered, including it's host element, which is tbody the way you've constructed it. Maybe the syntax was different earlier, but i think this is how it's supposed to work?

**Comment by zoechi** [comment]
@fringd this should lead to
```
<tbody mytablerow="">
    <tr><td>test</td></tr>
</tbody>
<tbody mytablerow="">
    <tr><td>test</td></tr>
</tbody>
<tbody mytablerow="">
    <tr><td>test</td></tr>
</tbody>
```

but the result is
```
<tbody mytablerow="">
  <tbody>
    <tr><td>test</td></tr>
   </tbody>
</tbody>
<tbody mytablerow="">
  <tbody>
    <tr><td>test</td></tr>
   </tbody>
</tbody>
<tbody mytablerow="">
  <tbody>
    <tr><td>test</td></tr>
   </tbody>
</tbody>
```

**Comment by fringd** [comment]
oh weird. the example at the top is a confusing example then. why would anybody want multiple tbody elements?

**Comment by poke** [comment]
@pkozlowski-opensource Is there anything we can do to speed this up? There’s already a proposed fix [above](https://github.com/angular/angular/issues/5967#issuecomment-167429502). Would that be an acceptable fix? Do you need a pull request including that change? Can we please get this fixed soon?

**Comment by chrille112** [comment]
+1 on this. FYI, in rc1 this is fixed by:
`compiler/src/html_parser.js`, line 257 should be:
`if (lang_1.isPresent(parentEl) && tagDef.requireExtraParent(parentEl.name)) {`

**Comment by eapenjohn** [comment]
I am still facing the same issue even after applying the below.Its generate 2 duplicate items
` if (lang_1.isPresent(parentEl) && tagDef.requireExtraParent(parentEl.name)) {
            var newParent = new html_ast_1.HtmlElementAst(tagDef.parentToAdd, [], [el], el.sourceSpan, el.startSourceSpan, el.endSourceSpan);
            this._addToParent(newParent);`


template is 
 template: ` 
        <ul>
          <dataset-tile *ngFor='let dataset of datasets' [hidden]='dataset.hide==true' [dataset]='dataset'></dataset-tile> 
        </ul>
     `

**Comment by vicb** [comment]
fix is coming...
