### ISSUE TITLE
Injectables can't resolve in di from plug-in library using npm link

### ISSUE THREAD

**Issue by CaMoCBaJL** [angular/angular#63124]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

While refactoring the build scripts of a working project, I discovered strange behavior in resolving DI dependencies during local development of the plug-in library code. 
The code was divided into 2 separate applications - the code generator and the main application. The code generator creates a template code for the interaction of the backend with the main application. As a result of the work of the code generator, we get angular libraries for sending http requests as separate services to each api. 
To simplify local development, it was not possible to directly link the artifacts of the first application to the main one, because in the runtime, the main application code could not create an instance of the imported services for sending http requests. 
The application crashed with the error *NullInjectorError: R3InjectorError(Environment Injector)[_HttpService -> _HttpService...)*. In my opinion, the described behavior is a bug. Didn't found anything about issue on working with npm link during angular library development.
Found on Angular 12, node 16. Still actual on current versions.

### Please provide a link to a minimal reproduction of the bug

https://github.com/CaMoCBaJL/angular-issue

### Please provide the exception or error you saw

```true
ERROR NullInjectorError: R3InjectorError(Environment Injector)[_HttpService -> _HttpService]: 
  NullInjectorError: No provider for _HttpService!
    at NullInjector.get (core.mjs:1636:21)
    at R3Injector.get (core.mjs:3018:27)
    at R3Injector.get (core.mjs:3018:27)
    at ChainedInjector.get (core.mjs:5289:32)
    at lookupTokenUsingModuleInjector (core.mjs:5632:31)
    at getOrCreateInjectable (core.mjs:5678:10)
    at Module.ɵɵdirectiveInject (core.mjs:11577:17)
    at NodeInjectorFactory.AcdaMainPageComponent_Factory [as factory]
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.20
Node: 20.17.0
Package Manager: npm 10.8.2
OS: win32 x64

Angular: 18.2.13
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.20
@angular-devkit/build-angular   18.2.20
@angular-devkit/core            18.2.20
@angular-devkit/schematics      18.2.20
@angular/cli                    18.2.20
@schematics/angular             18.2.20
ng-packagr                      18.2.1
rxjs                            7.8.2
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by JoostK** [comment]
This is typical in such setups and due to how module resolution works, unrelated to Angular. Linked libraries are typically achieved using symlinks, and without `preserveSymlinks: true` those symlinks are resolved to their actual location on disk. From that location, module imports will also be resolved from that new location's perspective; making it likely that it "sees" a different node_modules directory and therefore a different/duplicate copy of imported libraries. This then results in duplicate instances of the "same" libraries being present in the application, which won't cooperate.

`preserveSymlinks` can be enabled to avoid rewriting symlinks to their actual location on disk.

**Comment by CaMoCBaJL** [comment]
Thank you, but `preserveSymlinks` flag doesn't solve the main problem in Angular DI dependency resolution. Later I will add repro of this problem with `preserveSymlinks` enabled.

**Comment by CaMoCBaJL** [comment]
@JoostK with [preserveSymlink option enabled](https://github.com/CaMoCBaJL/angular-issue/commit/d13e8ee5febc18519c03019a74ae3506538023f9) in main app, still getting same error:

<img width="538" height="293" alt="Image" src="https://github.com/user-attachments/assets/4c9a024e-da19-45d0-8478-cbd1a228e167" />

**Comment by JoostK** [comment]
Without runnable reproduction I'd be unable to provide any more meaningul insight.

**Comment by CaMoCBaJL** [comment]
You can reproduce it using code from [my repo](https://github.com/CaMoCBaJL/angular-issue), using the following steps:
1. clone repo
2. go to lib folder
3. build
4. go to dist folder with lib artifacts
5. link dist
6. go to activities-dashboard
7. link created lib
8. run serve script
9. open browser with served app and find errors in developer tools console section

**Comment by JoostK** [comment]
`HttpService` isn't registered as a provider in that repo, nor is `provideHttpClient` present, which is why that fails.
