### ISSUE TITLE
ngModel binding seems to be broken in Beta.1

### ISSUE THREAD

**Issue by born2net** [angular/angular#6413]
ngModel binding seems to be broken in Beta.1
getting errors such as EXCEPTION: No provider for e! (e -> e)  when [(ngModel)]=... used

I have a pretty heavy ng2 app that touches pretty much all the major areas of Angular2.
I recommend testing builds against it before realeasing major updates as it will be sure to fail if core features are broken.

you can check http://ng2.javascriptninja.io and simply change package.json to 2.0.0-beta.1 and run npm i to see all the errors introduced in this beta.1 build

regards

Sean

**Comment by ericmartinezr** [comment]
I can only reproduce the issue with minified bundles, but I don't get exactly that message. Here's my [repro](http://plnkr.co/edit/SJjoUidWJBIxkYwag7R5?p=preview), with no minified bundles works fine (I opened your site expecting it to be a repro...). 

Anyway if this is related to minification issues it should be resolved when https://github.com/angular/angular/pull/6397 lands.

**Comment by born2net** [comment]
I use System.js so no minification, uglification here... just transpiled TS

**Comment by born2net** [comment]
well it seems beta.1 is in pretty bad shape, will stick with beta.0 until beta.1 comes out of alpha :)

**Comment by born2net** [comment]
ericmartinezr did you resolve the issue?

**Comment by ericmartinezr** [comment]
@born2net like I told you, this is a known issue with minified bundles in beta.1, if you use the non minified bundles works ok. There's nothing from me to fix. It was fixed alread via https://github.com/angular/angular/commit/eda4c3eb4c823029b885fdfcd602a8c3c93f0d31

So you have three options : downgrade to beta.0, use non-minified bundles with beta.1 or wait for beta.2

**Comment by rschmukler** [comment]
@ericmartinezr just a heads up that I'm still seeing this issue w/ beta2 when using the minified source

**Comment by ericmartinezr** [comment]
@rschmukler yep, confirmed. I saw the same with all the issues related to minification.

**Comment by antonybudianto** [comment]
beta.2 still no good for minification (needs to turn off mangle to make it work)

**Comment by juristr** [comment]
This problem still persists.

![ng2model-minissue](https://cloud.githubusercontent.com/assets/542458/12866881/fc6649bc-ccdd-11e5-90de-b2870dfe6ae9.gif)

Here's the Plunker to reproduce: https://plnkr.co/edit/PjOFscdR8A36lnl62fYh?p=preview

**Comment by Futourism** [comment]
I can confirm that the problem persists in beta.7

**Comment by chrisdostert** [comment]
still exists in beta.9

**Comment by zoechi** [comment]
@chrisdostert the issue is still open, therefore this is expected.

**Comment by pkozlowski-opensource** [comment]
Seems to be fine with rc.4 minified bundles: https://plnkr.co/edit/WhpXYFrFyFpHizUCmjO8?p=preview

In any case bundles are not recommended for anything more than plunkers / quick experiments.
