### ISSUE TITLE
CssShim crashes browser when encountering a CSS import

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#654]
To reproduce, create a component with the following template and try to render it with EmulatedShadowDomStrategy.

```html
<style>
  @import url("radio.css");
</style>
```
This will land something in CssShim in an infinite loop that crashes the Chrome tab or Firefox instance.

If you add a comment immediately before the `@import`, the crash does not occur, but the `<style>` elements added to the `<head>` are empty.
```html
<style>
  /***/
  @import url("radio.css");
</style>
```

**Comment by mhevery** [comment]
@vicb Is this bug addressed in #669? Can it be closed?

**Comment by vicb** [comment]
@mhevery it is not fixed yet. I am working on `@import`currently. Hopefuly we can close this sometime this week. _I'm going to close 669 where `@import` is the only item left_
