### ISSUE TITLE
Angular 2 in IE11 development build works fine, but production build throws an exception.

### ISSUE THREAD

**Issue by jared83** [angular/angular#6695]
Hi there,
I am using 
[generator-angular2-webpack-starter](https://github.com/magarcia/generator-angular2-webpack-starter)
To get me up with angular 2.
Initially I was suffering from the #6450 issue (and #6516, and #6556), but fixed it with [this shim](https://github.com/angular/angular/blob/master/modules/angular2/src/testing/shims_for_IE.js). This made ie11 (ver. 11.0.9600.18161 under win8.1 64bit) run angular 2 without a hitch when served with 'npm run server' i.e. the default server for development. However, when I run the production server ( 'npm run server:prod' ) I am getting this error from ie:
```javascript
SyntaxError: Expected ')'
   {
      [functions]: ,
      __proto__: { },
      description: "Expected ')'",
      message: "Expected ')'",
      name: "SyntaxError",
      number: -2146827282,
      stack: "SyntaxError: Expected ')'
   at evalExpression (http://localhost:8080/vendor.8fc5d82b021700e458db.bundle.js:1:5145)
   at TemplateCompiler.prototype._createViewFactoryRuntime (http://localhost:8080/vendor.8fc5d82b021700e458db.bundle.js:12:18596)
   at Anonymous function (http://localhost:8080/vendor.8fc5d82b021700e458db.bundle.js:12:16304)
   at Zone.prototype.run (http://localhost:8080/vendor.8fc5d82b021700e458db.bundle.js:39:28533)
   at Anonymous function (http://localhost:8080/vendor.8fc5d82b021700e458db.bundle.js:9:15715)
   at Anonymous function (http://localhost:8080/vendor.8fc5d82b021700e458db.bundle.js:39:28195)
   at lib$es6$promise$$internal$$tryCatch (http://localhost:8080/vendor.8fc5d82b021700e458db.bundle.js:15:19609)
   at lib$es6$promise$$internal$$invokeCallback (http://localhost:8080/vendor.8fc5d82b021700e458db.bundle.js:15:19933)
   at Anonymous function (http://localhost:8080/vendor.8fc5d82b021700e458db.bundle.js:15:29419)
   at Anonymous function (http://localhost:8080/vendor.8fc5d82b0217"
   }
```
and but a "Loading..." message on the screen.
Any help highly appreciated. I've got to get this running in ie asap.
Thank you for your time in advance.
Jared

**Comment by jared83** [comment]
Do you think this problem is related to Angular 2 itself, or rather to the build process of generator-angular-webpack-starter?

**Comment by Zuzon** [comment]
uglifyjs kills him

**Comment by jared83** [comment]
Thanks @Zuzon 
ic. Then, do you recommend removing uglifyjs from the build process?

**Comment by jared83** [comment]
Thank you, thank you, thank you @Zuzon !
I commented-out uglify.js in the webpack.prod.config and it worked, although not right away - it somewhat started to work after a 3rd build.
I will test it a little bit more to see if it stays that way.
Big Kudos to you Zuzon.

**Comment by Zuzon** [comment]
>ic. Then, do you recommend removing uglifyjs from the build process?

just set "mangle:false" for uglifyjs plugin

**Comment by gdi2290** [comment]
I didn't even know someone created a generator for angular2-webpack-starter but ya the problem is the mangled code in beta.1

**Comment by jared83** [comment]
Well actually the 'mangle: false' was set by default, yet it didn't work. Here's the snippet:

```javascript
    new UglifyJsPlugin({
      // beautify: true,
      mangle: false,
      comments: false,
      compress : {
        screw_ie8 : true
      },
      // TODO(gdi2290): uncomment in beta.2
      //mangle: {
      //  screw_ie8 : true
      //}
    })
```

**Comment by gdi2290** [comment]
the generator is on an old version of the starter but there might also be a reserved keyword being used which is a known IE bug in beta.1

**Comment by texel** [comment]
@gdi2290 I don't think that's the exact issue- mangled code doesn't do it, compressed code does. There's a separate issue w/ the Injector that prevents mangled code from working properly, but this looks like a separate issue.

**Comment by SebastianStehle** [comment]
Is there already a workaround for compression?

**Comment by jared83** [comment]
Anyone knows is this issue has been addressed in beta.3?

**Comment by yfain** [comment]
mangle in UglifyJS still doesn't work in beta 8

**Comment by pdutka** [comment]
mangle in UglifyJS still doesn't work in beta 12... any word on this?

**Comment by gdi2290** [comment]
mangle should work with latest changes

**Comment by vicb** [comment]
obsolete
