### ISSUE TITLE
All Angular 2 apps broken in Internet Explorer 11 after beta.0

### ISSUE THREAD

**Issue by wardbell** [angular/angular#7144]
All Angular beta.1 - beta.6  applications crash in **Internet Explorer 11**

Last working version was beta.0.

Looks like they die in `TemplateCompiler`.

Messages vary:
* `SyntaxError: The use of a keyword for an identifier is invalid`
* `SyntaxError: Expected ';'`

StackTrace seems always the same:
```
SyntaxError: ...
   at evalExpression (https://code.angularjs.org/2.0.0-beta.6/angular2.dev.js:451:5)
   at TemplateCompiler.prototype._createViewFactoryRuntime (https://code.angularjs.org/2.0.0-beta.6/angular2.dev.js:24364:9)
...
```
Try ***any of the sample applications*** in the documentation including QuickStart.
All of them are shimmed for IE11

Plunkers crash too. Try the [QuickStart](https://angular.io/resources/live-examples/quickstart/ts/plnkr.html) or [Template Syntax](https://angular.io/resources/live-examples/template-syntax/ts/plnkr.html) plunkers

Discovered that beta.0 was the last working version by rolling the plunker index.html scripts back, version by version.

Tested with IE 11.103.10586.0 (update 11.0.28) in Windows 10.

**Comment by wardbell** [comment]
Duplicate of #6501.

Apparently the other shim libraries don't cover all of IE's problems.

Workaround is to put the following *npmcdn* script in the `index.html` after the other IE shims:
```
 <script src="https://npmcdn.com/angular2/es6/dev/src/testing/shims_for_IE.js"></script>
```
When I tested, it resolved to:
```
 <script src="https://npmcdn.com/angular2@2.0.0-beta.6/es6/dev/src/testing/shims_for_IE.js"></script>
```

**Comment by djabraham** [comment]
:+1: These shims fixed a lot of issues with beta 3 under IE 11.0.9600.18124.

**Comment by gchurchley** [comment]
1. Is this also considered the fix for [#6391](https://github.com/angular/angular/issues/6391) ?
2. When will shims_fo_IE.js be bundled with the other angular polyfills? Including a testing file seems like a hack.
Thanks!

**Comment by wardbell** [comment]
Please update to latest (beta.7 as I write) and try again using all three of these IE related shims:
```
    <!-- IE required polyfills, in this exact order -->
    <script src="node_modules/es6-shim/es6-shim.min.js"></script>
    <script src="node_modules/systemjs/dist/system-polyfills.js"></script>
    <script src="node_modules/angular2/es6/dev/src/testing/shims_for_IE.js"></script>
```
or in plunker
```
    <!-- IE required polyfills, in this exact order -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.33.3/es6-shim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.20/system-polyfills.js"></script>
    <script src="https://npmcdn.com/angular2/es6/dev/src/testing/shims_for_IE.js"></script>
```
Report back if still not working.

Yes, it the testing shim is temporary. We hope to merge the two Angular-supplied shims in a beta coming soon.

**Comment by bohiltea** [comment]
this fixes the issue:
<script src="https://npmcdn.com/angular2/es6/dev/src/testing/shims_for_IE.js"></script>

**Comment by gchurchley** [comment]
@wardbell - I have updated the plunker with the shims as recommended and it seems to be working correctly now. Thanks!

**Comment by hanijizan** [comment]
Angular2 rc1, same issue. I get a 'syntax error' with IE 11 set to Edge render mode and when i switch to IE 9 render mode this error appears.

**Comment by webprofusion-chrisc** [comment]
The IE shim is not in the @angular npm package for RC 1. You can include it from:

https://npmcdn.com/angular2@2.0.0-beta.17/es6/dev/src/testing/shims_for_IE.js

This fixes this particular issue.

**Comment by wardbell** [comment]
**We do not recommend those shims.** We currently recommend core-js. Please see the latest `package.json` in the current [QuickStart](https://angular.io/docs/ts/latest/quickstart.html#create-and-configure)

**Comment by luckmus** [comment]
that [pluker](http://run.plnkr.co/plunks/ZPE3Go/) doesn't work on IE. It from current QuickStart

**Comment by OniMokwena** [comment]
Hi Guys 
having an issue running my web app on IE edge,10 and 9 i keep getting this error "Unhandled promise rejection Failed to load app/app.component.html"
Tried all the steps you guys have suggested and still no success has anybody else gotten this error? If So how could did you solve it?

**Comment by ericmartinezr** [comment]
>Failed to load app/app.component.html

That pretty much says it all. Please also see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question so you can get an answer faster.

**Comment by hem19** [comment]
@wardbell : I am using ng2-translate for translation purpose but pipes don't seems to work in case of IE10+. I tried using shims as recommended for beta version of angular2. Downloaded shims_for_IE.js and placed it inside scripts folder of my app and accessed it through script tag in index.html but still Angular Pipes doesn't seems to work in IE10+ (in my case).

My code is this:  `<label>{{"UserName" | translate}}</label>`

Cross reference: http://stackoverflow.com/questions/38502639/ie-specific-translate-pipe-not-working-in-angular-2-rc4

**Comment by webprofusion-chrisc** [comment]
@hem19 ie10 you should now use core-js instead of shims for ie. Don't know if that will make a difference in this case though. Oliver who builds ng2-translate is usually very helpful.

**Comment by slashbrackets** [comment]
RC4 - getting this issue in IE 11 
Unhandled Promise rejection:  ; Zone: <root> ; Task: Promise.then ; Value: Error

Digging down I find this:
originalErr
description"Object doesn't support property or method 'keys'"

In Chrome this never happens.

I've included core-js in packages.json and ran npm install but no joy.

Ideas?

**Comment by chrischeshire** [comment]
I'm getting the error:

Object doesn't support property or method 'apply'. Looking at the stack trace i see:

![image](https://cloud.githubusercontent.com/assets/1882044/17902465/bfa6c450-6924-11e6-9770-ac0fe9d3488b.png)

Works in Chrome and IE Edge but not lower than that, i'm using rc4.

**Comment by adrianhara** [comment]
@slashbrackets you need to reference the code-js shims script file in your html page, are you doing this? Look at the example index.html from https://angular.io/docs/ts/latest/quickstart.html

**Comment by chrischeshire** [comment]
@slashbrackets i should have mentioned, i did add the shims:

![image](https://cloud.githubusercontent.com/assets/1882044/17941810/22a030e6-69f2-11e6-9d93-0ea518c04b9c.png)

I also went overkill and added these just in case:

<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.33.3/es6-shim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.20/system-polyfills.js"></script>
<script src="https://npmcdn.com/angular2/es6/dev/src/testing/shims_for_IE.js"></script>

**Comment by SPapaioannou** [comment]
Still it doesn't work for me in IE11. I'm getting this error: 

`"SyntaxError: Syntax error
	   at Anonymous function (eval code:3:1)
	   at Anonymous function (eval code:1:31)
	   at eval code (eval code:1:2)
	Evaluating http://localhost:3383/Scripts/app2/myapp/app.module.js
	Evaluating http://localhost:3383/Scripts/app2/myapp/bootstrapper.js
	Error loading http://localhost:3383/Scripts/app2/myapp/bootstrapper.js"`

And these are my scripts:

```
"~/Scripts/app2/node_modules/core-js/client/shim.min.js"
"~/Scripts/app2/node_modules/zone.js/dist/zone.js"
"~/Scripts/app2/node_modules/reflect-metadata/Reflect.js"
"~/Scripts/app2/node_modules/systemjs/dist/system.src.js"
```
Any ideas?

**Comment by MarcusCalidus** [comment]
Same problem here; 
happens with the Angular 2 release. But with RC6 and RC7 also.

```
"(SystemJS) Syntaxfehler
	SyntaxError: Syntaxfehler
	   at Anonymous function (eval code:3:1)
	   at Anonymous function (eval code:1:31)
	   at eval code (eval code:1:2)
	Evaluating http://10.1.8.225:8080/app/app.module.js
	Evaluating http://10.1.8.225:8080/app/main.js
	Error loading http://10.1.8.225:8080/app/main.js"
```

with my most minimalist app.module

```
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

@NgModule({
  imports:      [ BrowserModule ]
})
export class AppModule {
  ngDoBootstrap() {
    console.log('boot here');
  }
}
```

part of my main.ts

```
'use strict';

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app.module'; //execution breaks here!
```

my dependencies:
```
    "@angular/common": "2.0.0",
    "@angular/compiler": "^2.0.0",
    "@angular/compiler-cli": "^0.6.1",
    "@angular/core": "^2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "^2.0.0",
    "@angular/router": "^3.0.0-rc.3",
    "@angular/upgrade": "2.0.0",
    "body-parser": "^1.15.2",
    "bootstrap": "^3.3.6",
    "core-js": "^2.4.1",
    "moment": "^2.15.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^5.0.0-beta.11",
    "systemjs": "^0.19.27",
    "zone.js": "^0.6.17"
```

any input?

**Comment by MarcusCalidus** [comment]
It appears it was not an Angular2 problem. I compiled my typescript to ES6 instead of ES5. It now works with this tsconfig.json:

```
          module: "commonjs",
          noLib: true,
          target: "es5",
          sourceMap: true,
     	  emitDecoratorMetadata: true,
    	  experimentalDecorators: true,
          moduleResolution: "node",
          noImplicitAny: true,
          suppressImplicitAnyIndexErrors: true
```

**Comment by Delagen** [comment]
I am issue angular/zone.js#316 in all IE browsers

**Comment by mlaval** [comment]
I have no issues in IE11 with some applications built on Angular 2.0.0:
 - ng-bootstrap demo: https://ng-bootstrap.github.io/#/home
 - plunkr: https://plnkr.co/edit/PbWJINj7V8zDrh1sEjAX?p=preview (default one + core-js)

Can you please provide a reproducer?

**Comment by vicb** [comment]
Thanks @mlaval. 

I'm closing this issue. Please re-open an issue with a repro should this happen again. Thanks.

**Comment by Sri276286** [comment]
SCRIPT5009: 'System' is undefined  

I am still facing this issue. I tried including whatever told

My index.html
---------------------

```
<html>

<head>
    <title>RPortal</title>
    <base href="/">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- inject:js -->
    <script src="system.src.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.33.3/es6-shim.min.js"></script>
    <script src="https://npmcdn.com/angular2/es6/dev/src/testing/shims_for_IE.js"></script>
    <script src="vendors.min.js"></script>
    <script src="lib.bundle.js"></script>
    <script src="system-config.js"></script>
    <!-- endinject -->
</head>

<body>
    <app-root>Loading...</app-root>
    <script>
        System.import('main.js');
    </script>
</body>

</html>
```

In vendors.min.js, I bundled polyfills from

```
 import 'core-js/es6/symbol';
 import 'core-js/es6/object';
 import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
```

Please help me.

Please let me know if any information needed.

**Comment by skreborn** [comment]
@Sri276286 You have already opened a [separate issue](https://github.com/angular/angular/issues/12970), which is unrelated to this one. Please follow @ericmartinezr's suggestion on moving your question to a [support channel](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question) instead, as yours is not a bug report or feature request.

**Comment by Manjunath-Siddappa** [comment]
I am using Angular 2

I fixed all those above issues by doing 2 things

1. in **index.html**
add     `<meta http-equiv="X-UA-Compatible" content="IE=edge" />`

2. in **src\polyfills.ts**

uncomment
/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

I am not sure it will help everyone, but might do some one.

Cheers!

**Comment by MarkusFeldmann** [comment]
Yeah, this final Information finally helped.

thx a Million.

**Comment by davutg** [comment]
I still face the issue even though I tried all.  Compatibility mode is off,ts target is es5, polyfills uncommented, meta tag added, shims. added. But, this time error appears for some underlying projects I referenced. This only happens with IE11. FF,Chrome,mobile browsers are all fine.

**Comment by Delagen** [comment]
@davutg You dist code does not look as valid ES5
```
...e.Exception=class{constructor(...
```

**Comment by davutg** [comment]
@Delagen  thanks for your comment. 

I've spent two hours but couldn't solve this issue yet. I republished it again (this time without --prod option) .Unfortunately, I still have similar errors.

**Unable to get property 'call' of undefined or null reference** [mentioned at angular-cli](https://github.com/angular/angular-cli/issues/7776)

tsconfig looks like as seen here below and polyfills.ts lines uncommented. 
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false, 
    "moduleResolution": "node",    
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    
My target is 
    "lib": [ "es6", "dom" ]
  }
```
}

If I change es6 to es5 in "lib" array all  generic Array<>, Iterable, Set kind of classes cause errors.

I expected polyfills to solve all issues even for underlying projects. But, from the issue I referenced it was mentioned there could be errors caused from underlying projs.

I use libraries like observable-collection,typescript-linq and don't know where to carry on debugging. 

**More details,**

[https://davutg.github.io/ng5BookMarkBestSeller/](https://davutg.github.io/ng5BookMarkBestSeller/)

**To Check environment**
I've created a brand new app and once I use polyfills it works for this new project in IE. 
node_modules wiped,old shims , typings kind of recommendations and obsolete technics tried, neither of them solved my issue.  

and package.json is as seen here  

```
{
  "name": "ng5",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animation": "^4.0.0-beta.8",
    "@angular/animations": "^5.2.5",
    "@angular/common": "^5.2.5",
    "@angular/compiler": "^5.2.5",
    "@angular/core": "^5.2.5",    
    "@angular/forms": "^5.2.5",
    "@angular/http": "^5.2.5",
    "@angular/platform-browser": "^5.2.5",
    "@angular/platform-browser-dynamic": "^5.2.5",
    "@angular/router": "^5.2.5",
    "clientstore": "^1.0.5",
    "core-js": "^2.4.1",
    "ngx-cookie-service": "^1.0.10",
    "reactiveproperty": "^1.0.2",
    "rxjs": "^5.5.2",
    "typescript-linq": "^1.0.6",
    "typings": "^2.1.1",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.0",
    "@angular/compiler-cli": "^5.2.5",
    "@angular/language-service": "^5.2.5",
    "@types/core-js": "^0.9.46",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^6.0.101",
    "codelyzer": "^4.1.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.4.1",
    "karma-jasmine": "^1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "observable-collection": "^1.2.3",
    "protractor": "~5.1.2",
    "reactiveproperty": "^1.0.2",
    "ts-node": "^3.3.0",
    "tslint": "~5.7.0",
    "typescript": "~2.5.3"
  }
}
```

**Comment by Delagen** [comment]
@davutg Your output still has ES6 style declaration 
```
Object.defineProperty(exports, "__esModule", { value: true });
const rxjs_1 = __webpack_require__("./node_modules/rxjs/Rx.js");
const toSubscriber_1 = __webpack_require__("./node_modules/rxjs/_esm5/util/toSubscriber.js");
class ObservableArray extends Array {
    constructor() {
```

**Comment by davutg** [comment]
@Delagen I figured out the problem. As expected underlying projects don't support es5. Actually, their npm distributions are designed only for es6. 

When I remove following libs from my package.json project appeared in IE11, sure I lost some functionalities.  I don't know if there is a way of re-packaging these libs against es5 directly or any other way. My very own npm package works ("clientstore": "^1.0.5")  I used rollup and delivered for umd,es5 . I do not know what can I do for following not es5 compatible ones should I request from project owners to deliver their packages for es5 enabled or should I get a fork and work on it myself. 

"reactiveproperty": "^1.0.2"
"typescript-linq": "^1.0.6"
"observable-collection": "^1.2.3"

I lately noticed that even project owner mentioned [here](https://www.npmjs.com/package/typescript-linq) that project is compiled for es2015. If es2015 is Ecma Script's v6 edition, this explains the situation. But, I didn't understand why the lib is intentionally compiled for es2015 since there are dozens of IE11 still around. 

_Please be aware that this library is intentionally compiled into ECMAScript 2015. The library is neither tested nor designed to run on Javascript engines which doesn't support the ECMAScript 2015 standard._

I do not want to pollute this issue loop anymore but just wanted to share my novice experience for people like me and looking for a workaround if any for underlying libs, as well.

.

**Comment by nxb303** [comment]
I had to change some

<input type="radio" (input)="function()">
to
<input type="radio" (change)="function()">

in my angular templates, because internet explorer and safari did not call the function, so in the end, there was no object selected and the application ran into a null reference.
