### ISSUE TITLE
Cannot find name 'Promise'. with beta 7

### ISSUE THREAD

**Issue by tamasfoldi** [angular/angular#7280]
Hi!

After I have upgraded to angular2 beta 7, I get these errors: 
```
node_modules/angular2/platform/browser.d.ts(77,90): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/common/pipes/async_pipe.d.ts(25,38): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/compiler/xhr.d.ts(6,23): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/compiler/xhr_mock.d.ts(10,23): error TS2304: Cannot find name 'Promise'.
...and more
```
Here is the full version of it [http://pastebin.com/eXDwwmPa](http://pastebin.com/eXDwwmPa )

dependencies in my package.json:
```
  "dependencies": {
    "angular2": "^2.0.0-beta.7",
    "angular2-jwt": "^0.1.6",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "^5.0.0-beta.2",
    "systemjs": "^0.19.6",
    "zone.js": "^0.5.10"
  },
  "devDependencies": {
    "concurrently": "^1.0.0",
    "jasmine": "^2.4.1",
    "jasmine-core": "2.4.1",
    "lite-server": "^1.3.1",
    "phantomjs-polyfill": "^0.0.1",
    "typescript": "^1.8.0"
  }
```

Can you help me with it?

**Comment by ericmdantas** [comment]
Make sure you have a reference to angular typings in your app's entry point.

See: https://github.com/ericmdantas/angular2-typescript-todo/blob/master/index.ts#L1

**Comment by twilliamsgsnetx** [comment]
I am having these errors as well. On initial gulp build everything works fine. If I make a change to one of my .ts files, even if it's just a whitespace change, my gulp file throws a bunch of errors about "Cannot find name 'module''. and "Cannot find name 'Promise'". Saving it again several times and it starts building properly again, but I think it's failing on actually outputting the modified files after that.

I have a stackoverflow question with more details on this.

http://stackoverflow.com/questions/35580944/gulp-typescript-emitting-errors-upon-save-but-is-fine-with-subsequent-saves?noredirect=1#comment58946776_35580944

**Comment by tamasfoldi** [comment]
Thanks @ericmdantas! It solved my problem.

**Comment by ericmdantas** [comment]
:+1:

**Comment by myusrn** [comment]
on a related front i'm hitting build issued listed below with new typescript 1.8.1.0 installed only fix I've found is to manually add `declare var Promise: any; ` to the top of $(ProjectDir)node_modules\angular2\src\facade\promise.d.ts  

is there a /// <reference /> entry that is meant to resolve that?

```
1>------ Build started: Project: App1, Configuration: Debug Android ------
1>node_modules\angular2\src\facade\promise.d.ts(1,10): error TS2661: Build: Cannot re-export name that is not defined in the module.
1>node_modules\angular2\src\facade\promise.d.ts(1,10): error TS2661: Build: Cannot re-export name that is not defined in the module.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by gchurchley** [comment]
@ericmdantas  - I don't understand this fix. Why do we need to go back to using references?

**Comment by ericmdantas** [comment]
@gchurchley well, it's not for all the files, it's just for the main file so it's not that bad. 

I don't know the reason behind it, but it's got more people confused: https://github.com/angular/angular/issues/7038

**Comment by gchurchley** [comment]
@ericmdantas  - Thanks for the response.

**Comment by myusrn** [comment]
I hit this issue when moving from 2.0.0-beta.0 -> .7/.8 and now I have following in my app/main.ts
```
// /// <reference path="../node_modules/angular2/typings/browser.d.ts" />  // no longer contains all of es6 type definitions
/// <reference path="../node_modules/typescript/lib/lib.es6.d.ts" />
```
The reason I concluded was because in my cordova typescript projects I maintain a single (projectRoot)/tsconfig.json which leads me to have to define an `"exclude": [ . . . "node_modules" . . . ]` entry to keep it from trying to transpile *.ts files found in npm packages.   This i'm assuming has the has unwanted side effect of keeping typescript transpiler from being able to walk my node_modules folder to discover and automatically use *.d.ts typing files found in that path.

In the case of my non-cordova typescript projects, e.g. asp.net (dnx) 5 web app/api, I can use a combination of (projectRoot)/app/tsconfig.json + (projectRoot)/scripts/tsconfig.json, instead of single (projectRoot)/tsconfig.json, which in turn doesn't require me to maintain an `"exclude": [ . . . "node_modules" . . . ]` entry in those files since everything in those folders and below them is open game for transpiling.   Trouble is i'm not finding that typescript can be told to go up a folder level to their parent folder during its discovery process for *.d.ts typing files and so it still doesn't lead to it automatically picking up the *.d.ts files in (projectRoot)/node_modules folder tree and so I still have to operate with explicit /// <reference /> entry(ies) in app/main.ts .   

I've been looking around in https://github.com/Microsoft/TypeScript/wiki/tsconfig.json and http://json.schemastore.org/tsconfig to see if there is a tsconfig.json setting that enables telling typescript where specifically look to automatically discover *.d.ts typing files but found nothing as of yet.

This issue to do with tsconfig.json placement and settings leading to the need in some cases to define an app/main.ts /// <reference /> entry I see as being what @dsebastien called out in the issue #7038 link that was provided above.

**Comment by ceolter** [comment]
i also found adding the typings file directly to my 'list of files to compile' works

```
    var tsResult = gulp
        .src([
            'node_modules/angular2/typings/browser.d.ts',
            'src/**/*.ts'
        ])
        .pipe(gulpTypescript({
            typescript: typescript,
            module: 'commonjs',
            experimentalDecorators: true,
            emitDecoratorMetadata: true,
            declarationFiles: true,
            target: 'es5',
            noImplicitAny: true
        }));
```

**Comment by myusrn** [comment]
The following excerpt from https://github.com/Microsoft/TypeScript/wiki/tsconfig.json I would see as explaining why @ceolter approach, in lieu of /// <reference /> entry works.   Note that if noted tracking item gets address in tsVnext then support for includes could provide for wildcard story for including node_modules/***/**.d.ts type definitions.

> The "files" property cannot be used in conjunction with the "exclude" property. If both are specified then the "files" property takes precedence.
> Any files that are referenced by those specified in the "files" property are also included. Similarly, if a file B.ts is referenced by another file A.ts, then B.ts cannot be excluded unless the referencing file A.ts is also specified in the "exclude" list.
> There is no way now to indicate an “include” to a file outside the current folder in the tsconfig.json (tracked by #1927). You can achieve the same result by either: 1. Using a “files” list, or 2. Adding a /// <reference path=”..”>  directive in one of the files in your directory.

**Comment by eddieduro** [comment]
So not sure how true this will be for everyone but I was running into this exact issue and it had to do with npm not installing all the packages maybe due to server issues. But I just deleted my node_modules folder and did another npm install and I didn't have to use the reference path.

**Comment by btkarthick** [comment]
I got the same error in beta 17 too!!!

@ericmdantas fix, solved it.

**Comment by suminksudhi** [comment]
I did faced the same issue in 2.0.0-rc.1  while trying angular2-quickstart
resolved issue by updating tsconfig.json "target": "es5"  to "target": "es6"

**Comment by UajoV6** [comment]
After encountering with this issue, i did `npm install typings -g`
`after npm start`
resolved with no problem.

**Comment by ericmdantas** [comment]
Keep in mind that referencing the typings in the entry point of you app is not needed anymore (if you're using rc, that is), your entry point should look like this:

```typescript
import {bootstrap} from '@angular/platform-browser-dynamic';
import {TodoCmp} from './app/app';

bootstrap(TodoCmp);
```

**Comment by hanijizan** [comment]
@ericmdantas  Depends if you're transpiling to es6 or not. If not, i still get these errors:

TS2304: Cannot find name 'Promise'.
TS2304: Cannot find name 'Map'.
TS2304: Cannot find name 'MapConstructor'.
TS2304: Cannot find name 'Set'.

**Comment by twilliamsgsnetx** [comment]
Yeah I couldn't find my way around these problems for now, so I reverted back and will attempt later.

**Comment by ericmdantas** [comment]
Yeah, if you're transpiling to es5, you should also install the typings for es6-shim.

**Comment by hanijizan** [comment]
@ericmdantas That didn't help as Typings has changed. Now it doesn't carry `browser.d.ts` anymore. I tried other `.d.ts` files but that didn't work. Tried installing Typings with ambient dependencies es6-shims and jasmin, yet still the same issues. So it didn't change anything if i had Typings or not.

**Comment by ericmdantas** [comment]
For me it's working just fine, see if you can clone this repo: https://github.com/ericmdantas/angular2-typescript-todo and then run `npm i`, `typings install` and `tsc`. There should be no compile errors.

**Comment by hanijizan** [comment]
@ericmdantas I'm on visual studio, that repository is for nodejs i assume? couldn't it set up.

**Comment by ericmdantas** [comment]
@hanijizan if you have a newish node version installed, it should work. After all the steps above, just run `npm start`.

**Comment by hanijizan** [comment]
@ericmdantas it installs:

`-- typings@0.8.1 
  +-- any-promise@1.3.0 
  +-- archy@1.0.0 
  +-- bluebird@3.3.5 
  +-- chalk@1.1.3 
  | +-- ansi-styles@2.2.1 
  | +-- escape-string-regexp@1.0.5 
  | +-- has-ansi@2.0.0 
  | | `-- ansi-regex@2.0.0 
  | +-- strip-ansi@3.0.1 
  | `-- supports-color@2.0.0 
  +-- columnify@1.5.4 
  | `-- wcwidth@1.0.0 
  |   `-- defaults@1.0.3 
  |     `-- clone@1.0.2 
  +-- listify@1.0.0 
  +-- minimist@1.2.0 
  +-- typings-core@0.3.1 
  | +-- array-uniq@1.0.2 
  | +-- configstore@2.0.0 
  | | +-- dot-prop@2.4.0 
  | | | `-- is-obj@1.0.1 
  | | +-- object-assign@4.1.0 
  | | +-- os-tmpdir@1.0.1 
  | | +-- osenv@0.1.3 
  | | | `-- os-homedir@1.0.1 
  | | +-- uuid@2.0.2 
  | | +-- write-file-atomic@1.1.4 
  | | | +-- imurmurhash@0.1.4 
  | | | `-- slide@1.1.6 
  | | `-- xdg-basedir@2.0.0 
  | +-- debug@2.2.0 
  | | `-- ms@0.7.1 
  | +-- detect-indent@4.0.0 
  | | `-- repeating@2.0.1 
  | |   `-- is-finite@1.0.1 
  | |     `-- number-is-nan@1.0.0 
  | +-- graceful-fs@4.1.4 
  | +-- has@1.0.1 
  | | `-- function-bind@1.1.0 
  | +-- invariant@2.2.1 
  | | `-- loose-envify@1.1.0 
  | |   `-- js-tokens@1.0.3 
  | +-- is-absolute@0.2.5 
  | | +-- is-relative@0.2.1 
  | | | `-- is-unc-path@0.1.1 
  | | |   `-- unc-path-regex@0.1.2 
  | | `-- is-windows@0.1.1 
  | +-- lockfile@1.0.1 
  | +-- make-error-cause@1.1.0 
  | | `-- make-error@1.1.1 
  | +-- mkdirp@0.5.1 
  | | `-- minimist@0.0.8 
  | +-- object.pick@1.1.2 
  | | `-- isobject@2.1.0 
  | |   `-- isarray@1.0.0 
  | +-- parse-json@2.2.0 
  | | `-- error-ex@1.3.0 
  | |   `-- is-arrayish@0.2.1 
  | +-- popsicle@5.0.1 
  | | +-- arrify@1.0.1 
  | | +-- concat-stream@1.5.1 
  | | | +-- inherits@2.0.1 
  | | | +-- readable-stream@2.0.6 
  | | | | +-- core-util-is@1.0.2 
  | | | | +-- process-nextick-args@1.0.7 
  | | | | +-- string_decoder@0.10.31 
  | | | | `-- util-deprecate@1.0.2 
  | | | `-- typedarray@0.0.6 
  | | +-- form-data@0.2.0 
  | | | +-- async@0.9.2 
  | | | +-- combined-stream@0.0.7 
  | | | | `-- delayed-stream@0.0.5 
  | | | `-- mime-types@2.0.14 
  | | |   `-- mime-db@1.12.0 
  | | +-- methods@1.1.2 
  | | `-- tough-cookie@2.2.2 
  | +-- popsicle-proxy-agent@1.0.0 
  | | +-- http-proxy-agent@1.0.0 
  | | | +-- agent-base@2.0.1 
  | | | `-- extend@3.0.0 
  | | `-- https-proxy-agent@1.0.0 
  | +-- popsicle-retry@2.0.0 
  | +-- popsicle-status@1.0.2 
  | +-- promise-finally@2.1.0 
  | +-- rc@1.1.6 
  | | +-- deep-extend@0.4.1 
  | | +-- ini@1.3.4 
  | | `-- strip-json-comments@1.0.4 
  | +-- rimraf@2.5.2 
  | | `-- glob@7.0.3 
  | |   +-- inflight@1.0.4 
  | |   | `-- wrappy@1.0.1 
  | |   +-- minimatch@3.0.0 
  | |   | `-- brace-expansion@1.1.4 
  | |   |   +-- balanced-match@0.4.1 
  | |   |   `-- concat-map@0.0.1 
  | |   +-- once@1.3.3 
  | |   `-- path-is-absolute@1.0.0 
  | +-- sort-keys@1.1.1 
  | | `-- is-plain-obj@1.1.0 
  | +-- string-template@1.0.0 
  | +-- strip-bom@2.0.0 
  | | `-- is-utf8@0.2.1 
  | +-- thenify@3.2.0 
  | +-- throat@2.0.2 
  | +-- touch@1.0.0 
  | | `-- nopt@1.0.10 
  | |   `-- abbrev@1.0.7 
  | +-- typescript@1.8.10 
  | `-- zip-object@0.1.0 
  +-- update-notifier@0.6.3 
  | +-- boxen@0.3.1 
  | | +-- filled-array@1.1.0 
  | | +-- string-width@1.0.1 
  | | | +-- code-point-at@1.0.0 
  | | | `-- is-fullwidth-code-point@1.0.0 
  | | `-- widest-line@1.0.0 
  | +-- is-npm@1.0.0 
  | +-- latest-version@2.0.0 
  | | `-- package-json@2.3.2 
  | |   +-- got@5.6.0 
  | |   | +-- create-error-class@3.0.2 
  | |   | | `-- capture-stack-trace@1.0.0 
  | |   | +-- duplexer2@0.1.4 
  | |   | +-- is-redirect@1.0.0 
  | |   | +-- is-retry-allowed@1.0.0 
  | |   | +-- is-stream@1.1.0 
  | |   | +-- lowercase-keys@1.0.0 
  | |   | +-- node-status-codes@1.0.0 
  | |   | +-- pinkie-promise@2.0.1 
  | |   | | `-- pinkie@2.0.4 
  | |   | +-- read-all-stream@3.1.0 
  | |   | +-- timed-out@2.0.0 
  | |   | +-- unzip-response@1.0.0 
  | |   | `-- url-parse-lax@1.0.0 
  | |   |   `-- prepend-http@1.0.4 
  | |   +-- registry-url@3.1.0 
  | |   `-- semver@5.1.0 
  | `-- semver-diff@2.1.0 
  |   `-- semver@5.0.3 
  +-- wordwrap@1.0.0 
  `-- xtend@4.0.1 
====npm command completed with exit code 0====`

Yet still same errors. Nothing changed except it added bunch of packages i don't need.

**Comment by ericmdantas** [comment]
Did you run `typings install` after cloning?

**Comment by hanijizan** [comment]
Yes eric. I actually have also fully tried the angular2 quickstart which never worked in visual studio as it's tailored for node.

**Comment by ericmdantas** [comment]
Welp, I don't know then.

**Comment by myusrn** [comment]
@hanijizan you can find visual studio 2015 and vscode based implementations of angular2 quickstart, with build and debug enabled, at https://github.com/myusrn/dnxwithng2 and https://github.com/myusrn/vscng2qs respectively.

**Comment by hanijizan** [comment]
@myusrn actually i found a better way of doing it. Still `/// <reference>` is needed, but at least you don't have to install typscript for NodeJS. So essentially i found a `Typings` folder and copied it to my solution then added:

`/// <reference path="typings/browser.d.ts" />`

Works great. Although the typings seem rather different, this one I used is version 0.5.1 i believe. The latest version, 0.8.* didn't have that `browser.d.ts` in it.

**Comment by Piusha** [comment]
Hi  Once I run the angular2 application I am getting following error on browser. 

zone.js:101 GET http://localhost/node_modules/@angular/platform-browser-dynamic/index.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122send @ VM9838:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:584(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426

I cannot solve this issue Please help me to fix this.

**Comment by KostyaTretyak** [comment]
I decided a similar problem when corrected an error in the filename: not `typing.json` properly `typings .json`

**Comment by atarr2** [comment]
Solved this problem by deleting node_modules and redoing `npm install`... Only difference is I used `sudo npm install` the first time (didn't work) and `npm install` the second time (worked).

**Comment by whatbirdisthat** [comment]
i changed my `tsconfig.json` compilerOptions.target needs to be "es6"

**Comment by pablocarreraest** [comment]
the problem solve when a put 
```javascript
///<reference path="../node_modules/typescript/lib/lib.es6.d.ts"/> 
import { bootstrap }    from '@angular/platform-browser-dynamic';
import { AppComponent } from './app.component';
bootstrap(AppComponent);
```

but why i have to put that reference is now is not angular on beta? or how do I can handle in a better way this @ericmdantas

**Comment by Cedrigax** [comment]
@pablocarreraest you saved my life :-)

**Comment by pablocarreraest** [comment]
@Cedrigax  UPDATE SOLUTION
``` javascript
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "noImplicitAny": false,
    "rootDir": ".",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "moduleResolution": "node"
  },
  "exclude": [
    "typings/main.d.ts",
    "typings/main",
    "node_modules"
  ]
}
```
with that I don't have to put that reference
I really don't know how is the correct way to use the tsconfing.json but this works without putting the reference at the main.ts

**Comment by twilliamsgsnetx** [comment]
@pablocarreraest Are you still getting the errors each time you make a modification to one of your .ts files, regardless of the modification? That's the issue I'm getting and I cannot figure out why yet.

**Comment by pablocarreraest** [comment]
how is ur package.json? no I dont have anymore de error.

**Comment by Cedrigax** [comment]
thanks @pablocarreraest

**Comment by ruppalsingh** [comment]
@pablocarreraest Why does your `tsconfig.js` work? You haven't offered any explanation.

**Comment by pablocarreraest** [comment]
@ruppalsingh I'm also newbie in angular 2 but it seems to be all about the compiler of typescript. let me just learn well to keep an update of this issue [or if anyone have a good answer that can guide us it will be nice to hear] but me recommendation is to learn more of typescript at the [Typescript repo](https://github.com/Microsoft/TypeScript)

**Comment by VilemP** [comment]
Hi. My problem went away when using Typescript compiler from 2.0.3.

**Comment by zhenwenc** [comment]
Using the following also works. Tried with typescript 2.0.3
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "es6"]
  }
}
```

**Comment by rubimazaki** [comment]
Ionic2 RC0-1 base app contains a tsconfig.json that isn't compatible with Ionic...

Which option to use? Compiler does not recognize Promise objects.

**Comment by queejie** [comment]
@rubimazaki  Were you able to find a solution for this?  I can compile if I have node_modules excluded, but that breaks the intellisense of my IDE (PhpStorm).

**Comment by rubimazaki** [comment]
If I am not mistaken: enable the typescript lint (settings->typescript->tslint compiler -> click enable) and set it to load the lint from: <project_folder>/node_modules/tslint (or from project folder: tsconfig.json)
Not sure exactly which.

Important Note: If you want breakpoints to work, and working CSS - Keep a distance from RC0, and get back to Beta11. Took me two weeks to understand that... There are just too many new issues in RC0 that you really don't want to mess with. Some are simply registered with RC2... Don't waste your time..

**Comment by GeorgeWL** [comment]
@ericmdantas on his comment https://github.com/angular/angular/issues/7280#issuecomment-218547861 solved this for me.

Still, it needs fixing in the repo doesn't it?
