### ISSUE TITLE
Lexer error for non-English alphabet chararcters

### ISSUE THREAD

**Issue by mortensoby** [angular/angular#7456]
* **I'm submitting a ... **
[x ] bug report

I have a datamodel where Danish characters are used e.g. 'ø'. This works fine in my components. When I try to bind to a model entity which contains a Danish character, I get an error though. 
```
Lexer Error: Unexpected character [Ø] at column 7 in expression [testVarØ] ("
    <div>
      <h2>Hello {{name}}</h2>
      <input [ERROR ->][(ngModel)]="testVarØ" type="text"/>
    </div>
  "): App@3:13
Lexer Error: Unexpected character [Ø] at column 7 in expression [testVarØ=$event] ("
    <div>
      <h2>Hello {{name}}</h2>
      <input [ERROR ->][(ngModel)]="testVarØ" type="text"/>
    </div>
  "): App@3:13
    at new BaseException (https://code.angularjs.org/2.0.0-beta.8/angular2.dev.js:7385:21)
    at TemplateParser.parse (https://code.angularjs.org/2.0.0-beta.8/angular2.dev.js:24039:15)
    at https://code.angularjs.org/2.0.0-beta.8/angular2.dev.js:24744:54
    at Zone.run (https://code.angularjs.org/2.0.0-beta.8/angular2-polyfills.js:1243:24)
    at Zone.run (https://code.angularjs.org/2.0.0-beta.8/angular2.dev.js:13456:32)
    at zoneBoundFn (https://code.angularjs.org/2.0.0-beta.8/angular2-polyfills.js:1220:26)
    at lib$es6$promise$$internal$$tryCatch (https://code.angularjs.org/2.0.0-beta.8/angular2-polyfills.js:468:17)
    at lib$es6$promise$$internal$$invokeCallback (https://code.angularjs.org/2.0.0-beta.8/angular2-polyfills.js:480:18)
    at lib$es6$promise$$internal$$publish (https://code.angularjs.org/2.0.0-beta.8/angular2-polyfills.js:451:12)
    at https://code.angularjs.org/2.0.0-beta.8/angular2-polyfills.js:123:10
```

I have reproduced the problem here:
http://plnkr.co/edit/KEC0GQFYuotdnhP3XxAV?p=info

- Angular version: 2.0.0-beta.8
- Browser: [all ]
- Language: [all]

**Comment by zoechi** [comment]
Looks like #6061 but that should be fixed since a while.

**Comment by mortensoby** [comment]
@zoechi, I have linked to a plunk, which illustrates that the problem still exists.

**Comment by penmark** [comment]
Still the same with beta 15

**Comment by pkozlowski-opensource** [comment]
Duplicate of #517
