### ISSUE TITLE
Cannot find name 'Zone' in beta 10

### ISSUE THREAD

**Issue by Ristaaf** [angular/angular#7660]
[X] bug report

Using Beta 10 I get the following errors (some of them several times) when compiling my project:

node_modules/angular2/src/core/zone/ng_zone_impl.d.ts(9,44): error TS2304: Cannot find name 'ZoneSpec'.
node_modules/angular2/src/core/zone/ng_zone_impl.d.ts(30,28): error TS2304: Cannot find name 'ZoneDelegate'.
node_modules/angular2/src/core/zone/ng_zone_impl.d.ts(30,51): error TS2304: Cannot find name 'Zone'.
node_modules/angular2/src/core/zone/ng_zone_impl.d.ts(32,82): error TS2304: Cannot find name 'HasTaskState'.

I also tried the 5 minute quickstart, changing beta 9 to beta 10 and get the same errors.

This is on Windows 10 node 5.9.0, typescript 1.8.7

**Comment by sanex3339** [comment]
same errors on compilation stage

**Comment by robwormald** [comment]
known issue, fix is pending on #7655 - you can explicity reference the zone typings in your tsconfig in the meantime:
```
files: [ 'src/main.ts', 'typings/browser.d.ts', 'node_modules/zone.js/dist/zone.js.d.ts' ]
```

**Comment by kylecordes** [comment]
This one was pretty easy to keep up with, for those who have been following along with changes in how typing are set up in a2 and other TypeScript based projects. But it would be really nice if each new beta would be tried briefly with a couple of applications built with common tooling setups, so that bits like this one (and the new es6-promise peer rep) were mentioned in the release notes.

**Comment by pitops** [comment]
hmm i get the error as well but seems to origin elsewhere as the above solution from robwormald does not seem to work

```
message: '\u001b[31m/<path>/node_modules/angular2/src/facade/lang.d.ts(12,18)
: \u001b[39merror TS2304: Cannot find name \'Zone\'.' }
```

any clues?

**Comment by Ristaaf** [comment]
Another option, if you like me use exclude instead of files in the tsconfig.js is to add something like:
///<reference path="../node_modules/zone.js/dist/zone.js.d.ts"/>

To your bootstrap.ts (or app.ts or whatever you call it)

**Comment by pitops** [comment]
@Ristaaf  you mean something like this?

`///<reference path="../typings/browser.d.ts"/>`

**Comment by zoechi** [comment]
dup of #7652 ?

**Comment by rudijs** [comment]
+1 @robwormald  @Ristaaf 

Temp for 2.0.0-beta.10 until fixed, this works for me in bootstrap.ts (or app.ts or whatever you call it)

    /// <reference path="../node_modules/zone.js/dist/zone.js.d.ts" />

**Comment by vanessayuenn** [comment]
@rudijs that works for getting rid of most of the errors, but I'm still getting `zone.js:172 Uncaught Error: ZoneSpec required!` :(

**Comment by ericmdantas** [comment]
I'm still having the following errors:

```
node_modules/angular2/src/common/directives/ng_plural.d.ts(2,10): error TS2305: Module '"/Users/user/Desktop/project/node_modules/angular2/src/common/directives/ng_switch"' has no exported member 'SwitchView'.
node_modules/zone.js/dist/zone.js.d.ts(122,11): error TS2300: Duplicate identifier 'Zone'.
node_modules/zone.js/dist/zone.js.d.ts(441,13): error TS2300: Duplicate identifier 'Zone'.
typings/main/ambient/zone.js/zone.js.d.ts(8,15): error TS2300: Duplicate identifier 'Zone'.

```

**Comment by ericmartinezr** [comment]
@ericmdantas those errors were fixed in beta.11.

**Comment by playground** [comment]
I'm trying out beta 11, I'm still getting these errors.

Unhandled Promise rejection: ZoneSpec required! ; Zone: <root> ; Task: Promise.then ; Value: Error: ZoneSpec required!(…)consoleError @ zone.js:403drainMicroTaskQueue @ zone.js:432ZoneTask.invoke @ zone.js:368
zone.js:405 Error: Uncaught (in promise): Error: ZoneSpec required!(…)

Here are the imports
import 'zone.js';
import 'reflect-metadata';
import {platform, Component, enableProdMode, PACKAGE_ROOT_URL} from "angular2/core";
import {bootstrap, BROWSER_PROVIDERS, BROWSER_APP_PROVIDERS} from "angular2/platform/browser";

**Comment by ericmartinezr** [comment]
@playground I saw the same error message and I solved it by importing 

```
import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';
```

But that would be easier by not importing any of those directly, including reflect-metadata, and simply adding angular2-polyfills in your index.html.

**Comment by playground** [comment]
It also broke some of the unit tests for us.

  Failed: EXCEPTION: Error during instantiation of NgZone! (DynamicComponentLoader -> AppViewManager -> RootRenderer -> DomRootRenderer -> EventManager -> NgZone).
        ORIGINAL EXCEPTION: ReferenceError: Zone is not defined
        ORIGINAL STACKTRACE:
        ReferenceError: Zone is not defined
            at new NgZoneImpl (/Users/ljeff/git_repo/twc_cms/docroot/sites/all/modules/wu/jspm_packages/npm/angular2@2.0.0-beta.11/src/core/zone/ng_zone_impl.js:22:13)
            at MockNgZone.NgZone (/Users/ljeff/git_repo/twc_cms/docroot/sites/all/modules/wu/jspm_packages/npm/angular2@2.0.0-beta.11/src/core/zone/ng_zone.js:22:24)
            at new MockNgZone (/Users/ljeff/git_repo/twc_cms/docroot/sites/all/modules/wu/jspm_packages/npm/angular2@2.0.0-beta.11/src/mock/ng_zone_mock.js:34:12)

**Comment by gonzofish** [comment]
@ericmartinezr thanks for that code snippet. solved the problem for me!

**Comment by vanessayuenn** [comment]
awesome @ericmartinezr! that solved the `ZoneSpec required!` error for me

**Comment by CarlosAmaral** [comment]
I'm getting an "Uncaught TypeError: Cannot read property 'zone' of null" after updating to @11

**Comment by benneq** [comment]
https://angular.io/docs/ts/latest/

> The current beta.11 release has known bugs relating to significant changes to the zones subsystem. All apps will report an error to the console:
Uncaught TypeError: Cannot read property 'zone' of undefined
The app will run unimpeded but it is disconcerting. We hope to have this and other bugs repaired by beta.12. Thanks for your patience.

**Comment by CarlosAmaral** [comment]
@benneq Thank you.

**Comment by zwhitchcox** [comment]
If I use

```ts
import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';
```

it works, but when I uglify it with webpack, I get an error:
```console
EXCEPTION: RangeError: Maximum call stack size exceeded
browser_adapter.ts:73EXCEPTION: RangeError: Maximum call stack size exceededt.logError @ browser_adapter.ts:73t.logGroup @ browser_adapter.ts:84e.call @ exception_handler.ts:49(anonymous function) @ application_ref.ts:441t.invoke @ zone.js:364inner.inner.fork.onInvoke @ ng_zone_impl.ts:65t.invoke @ zone.js:363t.run @ zone.js:257(anonymous function) @ zone.js:609t.invokeTask @ zone.js:397inner.inner.fork.onInvokeTask @ ng_zone_impl.ts:54t.invokeTask @ zone.js:396t.runTask @ zone.js:294i @ zone.js:515invoke @ zone.js:467
main.835381d….bundle.js:1RangeError: Maximum call stack size exceeded(…)(anonymous function) @ main.835381d….bundle.js:1t.invoke @ zone.js:364t.run @ zone.js:257(anonymous function) @ zone.js:609t.invokeTask @ zone.js:397t.runTask @ zone.js:294i @ zone.js:515invoke @ zone.js:467
browser_adapter.ts:83EXCEPTION: Error: Uncaught (in promise): RangeError: Maximum call stack size exceeded
browser_adapter.ts:73EXCEPTION: Error: Uncaught (in promise): RangeError: Maximum call stack size exceededt.logError @ browser_adapter.ts:73t.logGroup @ browser_adapter.ts:84e.call @ exception_handler.ts:49(anonymous function) @ application_ref.ts:258t.object.i @ async.ts:127t.__tryOrUnsub @ Subscriber.ts:181t.next @ Subscriber.ts:133t._next @ Subscriber.ts:83t.next @ Subscriber.ts:56t._finalNext @ Subject.ts:154t._next @ Subject.ts:144t.next @ Subject.ts:90t.emit @ async.ts:113_zoneImpl.c.NgZoneImpl.onError @ ng_zone.ts:134inner.inner.fork.onHandleError @ ng_zone_impl.ts:88t.handleError @ zone.js:368t.runGuarded @ zone.js:274i @ zone.js:528invoke @ zone.js:467
browser_adapter.ts:73STACKTRACE:t.logError @ browser_adapter.ts:73e.call @ exception_handler.ts:52(anonymous function) @ application_ref.ts:258t.object.i @ async.ts:127t.__tryOrUnsub @ Subscriber.ts:181t.next @ Subscriber.ts:133t._next @ Subscriber.ts:83t.next @ Subscriber.ts:56t._finalNext @ Subject.ts:154t._next @ Subject.ts:144t.next @ Subject.ts:90t.emit @ async.ts:113_zoneImpl.c.NgZoneImpl.onError @ ng_zone.ts:134inner.inner.fork.onHandleError @ ng_zone_impl.ts:88t.handleError @ zone.js:368t.runGuarded @ zone.js:274i @ zone.js:528invoke @ zone.js:467
browser_adapter.ts:73Error: Uncaught (in promise): RangeError: Maximum call stack size exceeded
    at s (zone.js:576)
    at zone.js:612
    at t.invokeTask (zone.js:397)
    at Object.inner.inner.fork.onInvokeTask (ng_zone_impl.ts:54)
    at t.invokeTask (zone.js:396)
    at t.runTask (zone.js:294)
    at i (zone.js:515)
    at HTMLDocument.invoke (zone.js:467)t.logError @ browser_adapter.ts:73e.call @ exception_handler.ts:53(anonymous function) @ application_ref.ts:258t.object.i @ async.ts:127t.__tryOrUnsub @ Subscriber.ts:181t.next @ Subscriber.ts:133t._next @ Subscriber.ts:83t.next @ Subscriber.ts:56t._finalNext @ Subject.ts:154t._next @ Subject.ts:144t.next @ Subject.ts:90t.emit @ async.ts:113_zoneImpl.c.NgZoneImpl.onError @ ng_zone.ts:134inner.inner.fork.onHandleError @ ng_zone_impl.ts:88t.handleError @ zone.js:368t.runGuarded @ zone.js:274i @ zone.js:528invoke @ zone.js:467
zone.js:502Unhandled Promise rejection: Maximum call stack size exceeded ; Zone: angular ; Task: Promise.then ; Value: RangeError: Maximum call stack size exceeded(…)o @ zone.js:502i @ zone.js:531invoke @ zone.js:467
zone.js:504Error: Uncaught (in promise): RangeError: Maximum call stack size exceeded(…)o @ zone.js:504i @ zone.js:531invoke @ zone.js:467
```

**Comment by CaptainCodeman** [comment]
Yeah, proper minification is not currently possible. There are some uglification settings that are usable but they don't shrink things down as much as should be possible once things are fixed.

These work:

```
  {
    beautify: false,
    mangle: {
      screw_ie8 : true,
      keep_fnames: true
    },
    compress : { screw_ie8 : true },
    comments: false
  }
```
https://github.com/CaptainCodeman/angular2-webpack-polyfill/blob/master/webpack.prod.js

**Comment by Ristaaf** [comment]
I am trying to help remove some issues, so I am looking at my own, and this problem does not exist anymore since the rc changed most things about importing stuff. So I am closing this.

**Comment by bklynjones** [comment]
@Ristaaf  New to and have been moving though the [webpack Angular2 tut](https://angular.io/docs/ts/latest/guide/webpack.html#!#development-configuration)

I am using the new rc but am receiving the following error
```console
VM2778:679 Uncaught EXCEPTION: Error during instantiation of NgZone! (ApplicationRef -> ApplicationRef_ -> NgZone).
ORIGINAL EXCEPTION: ReferenceError: Zone is not defined
ORIGINAL STACKTRACE:
ReferenceError: Zone is not defined
    at new NgZoneImpl (eval at <anonymous> (http://localhost:8080/vendor.js:441:2), <anonymous>:22:13)
    at new NgZone (eval at <anonymous> (http://localhost:8080/vendor.js:303:2), <anonymous>:100:26)
    at createNgZone (eval at <anonymous> (http://localhost:8080/vendor.js:297:2), <anonymous>:22:12)
    at ReflectiveInjector_._instantiate (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:685:27)
    at ReflectiveInjector_._instantiateProvider (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:626:25)
    at ReflectiveInjector_._new (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:615:21)
    at ReflectiveInjectorDynamicStrategy.getObjByKeyId (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:270:50)
    at ReflectiveInjector_._getByKeyDefault (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:795:38)
    at ReflectiveInjector_._getByKey (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:767:25)
    at ReflectiveInjector_._getByReflectiveDependency (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:757:21)
    at ReflectiveInjector_._instantiate (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:655:36)
    at ReflectiveInjector_._instantiateProvider (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:626:25)
    at ReflectiveInjector_._new (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:615:21)
    at ReflectiveInjectorDynamicStrategy.getObjByKeyId (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:270:50)
    at ReflectiveInjector_._getByKeyDefault (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:795:38)
    at ReflectiveInjector_._getByKey (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:767:25)
    at ReflectiveInjector_._getByReflectiveDependency (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:757:21)
    at ReflectiveInjector_._instantiate (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:654:36)
    at ReflectiveInjector_._instantiateProvider (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:626:25)
    at ReflectiveInjector_._new (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:615:21)
    at ReflectiveInjectorDynamicStrategy.getObjByKeyId (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:270:50)
    at ReflectiveInjector_._getByKeyDefault (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:795:38)
    at ReflectiveInjector_._getByKey (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:767:25)
    at ReflectiveInjector_.get (eval at <anonymous> (http://localhost:8080/vendor.js:231:2), <anonymous>:576:21)
    at Object.coreLoadAndBootstrap (eval at <anonymous> (http://localhost:8080/vendor.js:297:2), <anonymous>:95:27)
    at Object.bootstrap (eval at <anonymous> (http://localhost:8080/vendor.js:93:2), <anonymous>:91:19)
    at Object.eval (eval at <anonymous> (http://localhost:8080/app.js:15:2), <anonymous>:8:28)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:15:2), <anonymous>:10:30)
    at Object.webpackJsonp.74 (http://localhost:8080/app.js:15:2)
    at __webpack_require__ (http://localhost:8080/polyfills.js:51:30)
    at Object.webpackJsonp.0 (http://localhost:8080/app.js:7:19)
    at __webpack_require__ (http://localhost:8080/polyfills.js:51:30)
    at webpackJsonpCallback (http://localhost:8080/polyfills.js:22:20)
    at http://localhost:8080/app.js:1:1```

Given the conflicting info on the thread I am not sure where to call Zone.js in the config files.  Any Clarity you might be able to lend would be helpful as I have assembled the code base precisely as written.
