### ISSUE TITLE
clearInterval crashes zones in beta.11

### ISSUE THREAD

**Issue by wardbell** [angular/angular#7666]
[x] bug report

Either of these will crash zones

```
var timerId = 42; // anything that isn't actually a handle
clearInterval(timerId);
// Error: cannot read property 'cancelTask' of undefined
```
and try this
```
var timerId = setInterval(()=>{},1000);
clearInterval(timerId); // clears the first timer
clearInterval(timerId); // called twice ... boom!
// Uncaught Error: Task does not support cancellation, or is already canceled.
```

`clearInterval` is supposed to be safe in both cases`. It worked in beta.9

Here it is in a plunker:
http://plnkr.co/edit/nyQIKU4JzTlwp5eOG7Qo?p=preview

Discovered while testing the docs "Cookbook Component Communication" sample. Here it is in the context of that cutdown sample:
http://plnkr.co/edit/pYlQdKk6qLOGhQwSreoG?p=preview

**Comment by ericmartinezr** [comment]
@wardbell the second one is this one https://github.com/angular/zone.js/issues/283, the first one I don't know...

**Comment by wardbell** [comment]
It does seem related @ericmartinezr

**Comment by NathanWalker** [comment]
Sounds like the error I'm seeing with beta.11 is related; coming from `angular2-polyfills`:
```
Uncaught TypeError: Cannot read property 'cancelTask' of undefined(anonymous function) @ angular2-polyfills.js?1458368121888:142
clearTimeout @ VM740:3
subs.push.destroy @ browser-sync-client.2.10.1.js:1
Manager.cleanup @ browser-sync-client.2.10.1.js:1
```

And:
```
Uncaught TypeError: Cannot read property 'zone' of undefined(anonymous function) @ angular2-polyfills.js?1458368121888:142
clearTimeout @ VM740:3
Socket.onClose @ browser-sync-client.2.10.1.js:1
```

This appears to be called twice on bootstrap from `angular2-polyfills.js`. First time `zone` is defined. Second time it's not:
```
var clearNative = utils_1.patchMethod(window, cancelName, function () { return function (self, args) {
   var task = args[0];
   task.zone.cancelTask(task);  <-- zone undefined 2nd time
}; });
```

**Comment by johnwheeler** [comment]
@NathanWalker 

I had to do this to make the errors go away - mind you - I have no idea of the side-effects or what any of this is doing...

```
var clearNative = utils_1.patchMethod(window, cancelName, function () { return function (self, args) {
    var task = args[0];
    if (task) {
        task.zone.cancelTask(task);
    }
}; });
```

FWIW, I tried the temp workaround from @todoubaba here

https://github.com/angular/angular/issues/7671#issuecomment-198700134

and it did _not_ solve the browsersync errors

**Comment by gdi2290** [comment]
if you build from source you can apply this workaround
https://github.com/AngularClass/angular2-webpack-starter/commit/1661e4ce847f90547e7bc875c57e8ebdfb3fef98

**Comment by mhevery** [comment]
Fixed here: https://github.com/angular/zone.js/commit/5783663a80926b6154d5c900a3a5645be7bd53bb

**Comment by char0n** [comment]
Hi,

I am using angular 2.0.0-beta.11 and zone.js 0.6.5 in hybrid application along with angular 1.5.2. I am still experiencing the issue with unhandled exception: EXCEPTION: Error: Task does not support cancellation, or is already canceled.

I can create plunker if necessary. Can anybody confirm ?

**Comment by kookster** [comment]
I'm seeing the same thing in angular 2.0.0-beta.11 with zone.js 0.6.**6**

Seems to be two issues, I am seeing times when it is trying to call `clearNative` with args containing an integer like 13 or 14 rather than a `ZoneTask`.  That happens a few times as my app starts up.

More frequently after that I see clearNative called twice on the same `ZoneTask`, where the 2nd time is doomed to fail as the `cancelFn` has been set to null in the first call. Haven't chased down where this is happening, but this change to `angular2-polyfills.js` prevents the errors from happening:
```
        var clearNative = utils_1.patchMethod(window, cancelName, function() {
          return function(self, args) {
            var task = args[0];
            if (task && task.cancelFn) { // THIS CONDITION
              task.zone.cancelTask(task);
            }
          };
        });
```

**Comment by kookster** [comment]
Actually, looks like this function has been fixed in a similar way in `zone.js`, just not in the `angular2-polyfills.js`:

https://github.com/angular/zone.js/blob/master/lib/browser/browser.ts#L86-L97

So basically we need angular2-polyfills.js updated with the latest `zone.js`.

**Comment by kookster** [comment]
I see beta 12 is out with this fix, this should be closed

**Comment by pkozlowski-opensource** [comment]
Thnx @kookster !

**Comment by char0n** [comment]
Nice, I can confirm that these errors are gone on hybrid angular1/2 application with angular2 v2.0.0-beta.12 and zone.js v 0.6.6

Thanks a lot for fixing this

**Comment by bennadel** [comment]
For what's it's worth, I also just happened across this in Beta 11:

`angular2-polyfills.js:460 Unhandled Promise rejection: EXCEPTION: TypeError: Cannot read property 'zone' of null`

... when trying to use `clearTimeout()`. It seems to be fixed in Beta 14. Thanks!

**Comment by char0n** [comment]
Yes I can still reproduce also on hybrid angular1/2 application.

angular=1.5.3
angular2=2.0.0-beta.13
zone.js=0.6.9

```javascript
app.js:129453 Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.5.3/$rootScope/inprog?p0=%24digest
    at app.js:116097
    at beginPhase (app.js:133412)
    at Scope.$apply (app.js:133152)
    at app.js:115493
    at ZoneDelegate.invoke (app.js:108306)
    at Zone.run (app.js:108201)
    at NgZoneImpl.runOuter (app.js:59983)
    at NgZone.runOutsideAngular (app.js:43180)
    at Object.next (app.js:115493)
    at SafeSubscriber.schedulerFn [as _next] (app.js:5753)
```

**Comment by mhevery** [comment]
@char0n Please file a separate issue, with a plunker reproduction.
