### ISSUE TITLE
Uncaught TypeError: Cannot read property 'zone' of undefined (beta.11)

### ISSUE THREAD

**Issue by wardbell** [angular/angular#7705]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[x] bug report
[ ] feature request
[ ] support request 

* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

The QuickStart and all apps based upon it report the following error to the console upon launch.

```
Uncaught TypeError: Cannot read property 'zone' of undefined
```

The app continues to run. You won't see it unless you happen to be looking at the console.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Does not seem to happen in plunker. 

Does when build and execute the code locally as directed. See [instructions in the angular/quickstart repo](https://github.com/angular/quickstart/blob/master/README.md)

In brief:
```bash
git clone  https://github.com/angular/quickstart  my-proj
cd my-proj
rm -rf .git
npm install
npm start
```

* **What is the expected behavior?**

No errors in console

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.11
- Browser:  Chrome
- Language: TypeScript 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by mhevery** [comment]
The error is introduced by `browser-sync-client.2.11.1.js` trying to `clearInteval(undefined)`. This has been fixed in https://github.com/angular/zone.js/commit/5783663a80926b6154d5c900a3a5645be7bd53bb and it is slated for https://github.com/angular/angular/pull/7700

**Comment by saumyatripathi** [comment]
@mhevery The upgrade to zone 0.6.5 doesn't seem to fix it for me. I am relatively new so excuse me if I am missing something very basic here.

**Comment by wardbell** [comment]
Ah ... that `clearInterval` was insidious!  Glad you figured it out.

**Comment by shakyShane** [comment]
thanks for tracking that down @mhevery - Browsersync author here. 

socket.io (or rather it's dep, engine.io) does indeed call `clearTimeout(undefined)` in a couple of places such as [here](https://github.com/socketio/engine.io-client/blob/master/lib/socket.js#L472) and [here](https://github.com/socketio/engine.io-client/blob/master/lib/socket.js#L489)

This does seem like something that should be fixed within zone.js, but I've personally tried and the latest version does not fix the issue - the only way I got it to work was by manually editing engine.io to something along the lines of 

```js
if (this.pingIntervalTimer) {
    clearTimeout(this.pingIntervalTimer);
}}
```

doing this in all places that `clearTimeout` is called does fix the issue - but I'm not sure that should be needed.

---

Just wanted to make you aware of my findings as the starter project is currently broken.

Thanks :)

**Comment by omeid** [comment]
Quick solution until a release is to include  the  `node_modules/zone.js/dist/zone.min.js`, `node_modules/zone.js/dist/long-stack-trace-zone.js`, and `node_modules/reflect-metadata/Reflect.js` instead of the `node_modules/angular2/bundles/angular2-polyfills.js` and make sure you upgrade to zone.js 0.6.5.

**Comment by omeid** [comment]
Quick solution until a releais to include  the  `node_modules/zone.js/dist/zone.min.js`, `node_modules/zone.js/dist/long-stack-trace-zone.js`, and `node_modules/reflect-metadata/Reflect.js` instead of the `node_modules/angular2/bundles/angular2-polyfills.js` and make sure you upgrade to zone.js 0.6.5.

**Comment by efortes** [comment]
Same problem here. When is the bug fix for this problem planned?

**Comment by naomiblack** [comment]
This is fixed in master, and will be in beta.12 (out this week)
