### ISSUE TITLE
Angular2 beta 0.11 More tasks executed then were scheduled exception...

### ISSUE THREAD

**Issue by born2net** [angular/angular#7721]
Up to 0.9 didn't see any issues (same code base) and as of 0.11 I am seeing More tasks executed then were scheduled. Searched PR and didn't see anyone mentioning this....

It seems to be related to new zone.js changes. 
any ideas?

I have a feeling maybe it's because I added the long stack trace in 0.11. and if so, any workarounds?
see below:

![capture](https://cloud.githubusercontent.com/assets/5090936/13956673/ce2e4d0a-f006-11e5-8070-631d01c312d0.PNG)

regards

Sean

**Comment by ericmartinezr** [comment]
There are reports for this issue here https://github.com/angular/zone.js/issues/290 and here https://github.com/angular/zone.js/issues/287

**Comment by born2net** [comment]
tx for the links... I wonder how come not more people are seeing this.
It's seems to be all over my code even when I use completely diff modules.
should I close this bug due to the other one?
Is the ng2 team working on this?
tx

Sean

**Comment by born2net** [comment]
FYI started appearing on 0.10

**Comment by ericmartinezr** [comment]
@born2net I would close this issue and continue in this one https://github.com/angular/zone.js/issues/287 since it has more comments. And provide an example of your code (plnkr or a repository), that's always helpful.

**Comment by born2net** [comment]
got it, tx!

**Comment by born2net** [comment]
FYI disabled snippet is a workaround until issue is fixed in zone.ts
```
line: 763 zone.ts
if (next < 0) {
        debugger;
        throw new Error('More tasks executed then were scheduled.');
      }
```

**Comment by born2net** [comment]
this is a big showstopper for me...
I can't release ng 0.12 Kitchen sink: http://ng2.javascriptninja.io
due to this bug...

ng team, PLEASE remove the Throw Exceptions in zone.js

ref: https://github.com/angular/zone.js/issues/290#issuecomment-200784785

Regards,

Sean

**Comment by MaikeMota** [comment]
Same problem here. The "More tasks executed then were scheduled" message always appear when has interation with semantic-ui elements.

![image](https://cloud.githubusercontent.com/assets/4526602/14023714/6c15ab80-f1c4-11e5-862c-4f645b6ffccd.png)

![image](https://cloud.githubusercontent.com/assets/4526602/14023734/870c8b48-f1c4-11e5-8217-e7ebe3e1dd01.png)

**Comment by mburger81** [comment]
@born2net I have the same problem but only appearing from beta.12 or zone.js 0.6.4 and normally only on smartphones or tablets

commenting the "if" it should work?

**Comment by born2net** [comment]
yes take out the statement in zone until fixed!

**Comment by alexi2014** [comment]
We found that all our apps have been broken by Beta.12. Following the suggestion above, we commented out the line
`throw new Error('More tasks executed then were scheduled.');`
in the node_modules\angular2\bundles\angular2-polyfills.js file, line 398. After this change the functionality have been fully restored and we don't observe any issues so far.

**Comment by alexi2014** [comment]
Forgot to mention - we moved from Beta.8.

**Comment by born2net** [comment]
yes 0.12 seems to be a solid build, once the line is removed from zone

**Comment by cagataycivici** [comment]
Same problem here with the spinner component;

http://www.primefaces.org/primeng/#/slider

Fails on beta12, after update from beta9.

**Comment by david10sing** [comment]
@born2net I had to remove it from angular2-polyfills as how @alexi2014 mentioned. Removing it from zone.js did not work for me.

**Comment by andrewkon** [comment]
+1 (same problem with swiper.js)

**Comment by ericmartinezr** [comment]
FYI this is supposed to be fixed by https://github.com/angular/zone.js/commit/a8ea55dd977898a9cba4d695beb93bf23e0cbc50 so hopefully we will see it in ng2 b13/ zone 0.6.7

**Comment by airondumael** [comment]
yes it was fixed by zone 0.6.8. 
Is there any estimate when will angular2 use zone 0.6.8 ?

**Comment by born2net** [comment]
bummer, I expected 0.13 to use the new zone

**Comment by CaptainCodeman** [comment]
Yeah, beta 13 still has zone issues - very disappointing that the fixed version isn't included.

**Comment by CaptainCodeman** [comment]
... but if you do add zone and pull it in instead of using angular2-polyfills then all these zone issues do finally seem to be resolved and performance feels a little zippier too.

**Comment by mburger81** [comment]
@CaptainCodemam can you please explane it better what do you mean or what wen should do? Thx

**Comment by mburger81** [comment]
@CaptainCodeman can you please explane it better what do you mean or what wen should do? Thx

**Comment by CaptainCodeman** [comment]
Instead of loading angular2-polyfills, load a newer version of zone.js

Example with webpack: https://github.com/CaptainCodeman/angular2-webpack-polyfill

**Comment by lpotapczuk** [comment]
+1 (same error with nvd3.js and d3.js)

**Comment by ericmartinezr** [comment]
Instead of adding angular2-polyfills you can import it as @CaptainCodeman suggested, or simply add script tags with the necessary scripts : reflect-metadata and zone.js.

```
<script src="node_modules/es7-reflect-metadata/dist/browser.js"></script>
<script src="node_modules/zone.js/dist/zone.js"></script>
```

**Comment by CaptainCodeman** [comment]
Note that you don't need to include reflect-metadata if you're using core.js as it has it included. I found core.js instead of es6-shim fixed some IE issues.

**Comment by msklvsk** [comment]
same here, beta.13, latest everything

**Comment by krishollenbeck** [comment]
I also saw this error today when trying to upgrade from **beta.8** to **beta.12**.  This appears to be an issue with zonejs version 0.6.6 and using ```setTimeout()``` in my case. Changing ```setTimeout()``` to ```setInterval()``` fixed few that I changed. However, we are running some third party jQuery plugins from ```ngAfterViewInit()``` and this error seems to occur every time a ```setTimeout()``` function is executed.

**Comment by CaptainCodeman** [comment]
To fix this wth beta.13:

don't use angular2-polyfills (contains older, broken zone version)
reference latest zone 0.6.8 in npm
load core.js + zone.js OR reflect-metadata + zone.js (es6-shim probably needed as well)

**Comment by ourway** [comment]
Remove angular2-polyfills and add zone and reflect-metadata with angular2-beta-13
```
...

 <script src="node_modules/reflect-metadata/Reflect.js"></script>
 <script src="node_modules/zone.js/dist/zone.js"></script>

...
```

**Comment by krishollenbeck** [comment]
@ourway @CaptainCodeman, Thanks for the info. That along with changing zone.js to v0.6.8 fixed the issue for me. Now on beta.13

**Comment by Lindstrom1989** [comment]
Managed to get it working in ionic 2 but had to copy Reflect.js and zone.js into my www folder and reference them from my index.html. hopefully they will fix this soon :+1:

**Comment by lpotapczuk** [comment]
The issue is still not fixed in Beta 14.

**Comment by andrewkon** [comment]
+1 for not fixed in 14

**Comment by lukedupin** [comment]
+1 for not fixed in 14

**Comment by zoechi** [comment]
There is a nice new GitHub feature to "add reaction"s instead of `+1` posts. Please use this instead :+1:

**Comment by kanchansingh1123** [comment]
Similar Issue 
![2016-04-10_13-11-14](https://cloud.githubusercontent.com/assets/6582774/14408756/8da2a980-ff1e-11e5-93cf-7e95c21d9744.png)

**Comment by PascalPrecht** [comment]
How about someone tries to fix it and send a PR to the zone repository?

**Comment by kanchansingh1123** [comment]
Hey! 

Awesome it is fixed for me after upgrading Angular to  "2.0.0-beta.14" with zone  "0.6.10" in my package.json and I run npm install.

**Comment by CaptainCodeman** [comment]
I don't understand how builds are decided - it seems odd that things are fixed but just not included in a release, sometimes for weeks. In the meantime there is confusion because it's "fixed" but lots of people still have the issue unless they *don't* follow the instructions and use the files it tells them to.

**Comment by Lindstrom1989** [comment]
The error has gone away but makes my app very buggy, views go black and crash, how ever manually importing reflect and zone instead of polyfills makes this go away. :/

**Comment by born2net** [comment]
looks good!

**Comment by RaleS** [comment]
Getting same error with beta 14 and Bing maps V8
https://plnkr.co/edit/wJzBoDWVFtDaEWx3cqWn?p=preview

Pan / zoom the map to reproduce the issue

**Comment by vulcaryn** [comment]
To fix in beta 14 (works for me):
- upgrade zone.js to 0.6.10
- remove angular2-polyfills and add zone and reflect-metadata (in your index.html)

**Comment by xhite** [comment]
Looks like it's fixed in Angular2 beta 15

**Comment by mekterovic** [comment]
This solved it for me, I've updated the whole stack:
    "angular2": "2.0.0-beta.15",
    "systemjs": "0.19.26",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.6.10"

**Comment by dchacke** [comment]
Just upgrading to zone.js 0.6.8 fixed it for me.

**Comment by PrinceOfAmber** [comment]
This error happened for me while using zone 0.6.12, from /www/build/js/zone.js:389:33 .  I have 

 "rxjs": "5.0.0-beta.6",
and angular "2.0.0-rc.4"

But by rolling back zonejs from 10 down to "^0.6.10" , it was resolved

**Comment by myquery** [comment]
<script src="node_modules/reflect-metadata/Reflect.js"></script>
 <script src="node_modules/zone.js/dist/zone.js"></script>
this does not fix the issue, and which line in zone.js will I  disable....

**Comment by myquery** [comment]
`Error: More tasks executed then were scheduled.
    at v (http://localhost:8100/build/polyfills.js:3:4864)
    at t._updateTaskCount (http://localhost:8100/build/polyfills.js:3:10922)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:10370)
    at e.runTask (http://localhost:8100/build/polyfills.js:3:7637)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:11397)
    at XMLHttpRequest.<anonymous> (http://localhost:8100/build/polyfills.js:3:2528)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:10284)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:37373:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:10220)
    at e.runTask (http://localhost:8100/build/polyfills.js:3:7637)
    at XMLHttpRequest.invoke (http://localhost:8100/build/polyfills.js:3:11397)
    at t.e [as scheduleFn] (http://localhost:8100/build/polyfills.js:3:2586)
    at t.scheduleTask (http://localhost:8100/build/polyfills.js:3:9971)
    at e.scheduleMacroTask (http://localhost:8100/build/polyfills.js:3:7952)
    at http://localhost:8100/build/polyfills.js:3:2993`
this error  just started appearing when i try to post data to my node backend
Please does any one has a fix for this, seem not find any solution at the moment

**Comment by mhevery** [comment]
@myquery please don't comment on closed issues. File new issue. This would should be filed with https://github.com/angular/zone.js
