### ISSUE TITLE
Bug: OnInit not fired when using Safari's back button

### ISSUE THREAD

**Issue by colinskow** [angular/angular#7722]
I am using Angular 2.0.0-beta.11 on OS X El Capitan. When Safari's browser history back function is used, `OnInit` does not get fired. It seems to work fine on Chrome.

Steps to reproduce:
1) Fire up the official [Tour Of Heroes Demo](https://angular.io/resources/live-examples/toh-5/ts/plnkr.html)
2) Click on any hero in the dashboard
3) Use the browser back button or click the "back" button in the demo. The dashboard doesn't populate.

Related: #4809

**Comment by Matt-hew** [comment]
I followed the tutorial and had the same issue. I'm using  Angular 2.0.0-beta.12, Safari 9.1 on OS X El Capitan 10.11.4.
On Chrome it works fine.

**Comment by goodfield** [comment]
+1

**Comment by MartinMa** [comment]
It also affects Safari Mobile (tested on iOS 9 with `"angular2": "2.0.0-beta.12"`).

**Comment by StormToft** [comment]
+1 still happening in beta 13 on iOS 9.2.1 and also OS X Safari

**Comment by daslicht** [comment]
How is that solved in Angular 1 ? Or is it there working either ?

**Comment by vcorr** [comment]
beta.15: OnInit is still not fired in Safari (El Capitan 10.11.5, Safari 9.1.1) also on iPhone

**Comment by zoechi** [comment]
@vcorr The issue is still open and the https://github.com/angular/angular/blob/master/CHANGELOG.md doesn't list it as fixed, therefore this is kinda expected.

**Comment by daslicht** [comment]
OnInit is not only fired in Angular but in JS in general :)
see, we had something similar in 2012:
http://stackoverflow.com/questions/8788802/prevent-safari-loading-from-cache-when-back-button-is-clicked

It has something to do with the back-forward cache.

Safari cache the whole page in Memory and if you navigate back the page is instantly shown without re-rendering and all scripts continue running.


The only dirty hack I have found yet its to start a time before navigating to the next page. Once you come back the timer can trigger some function.

**Comment by ravinderpayal** [comment]
Same problem here 
[StackOverflow Question](http://stackoverflow.com/questions/37192628/history-forward-backward-button-doesnt-work-angular-2-router)

**Comment by srapisarda** [comment]
I have the same problem, "**window.history.back()**" on safari does not reload the heroes list back. it looks like that the function "**ngOnInit() { this.getHeroes();}"**  in heroes.component is not executed. This looks like an environment browser issue.

**Comment by colinskow** [comment]
Here is a possible solution, the `onpageshow` event:

```js
window.onpageshow = function(event) {
    if (event.persisted && onInitNotAlreadyFired) {
        fireOnInit();
    }
};
```

See this [StackOverflow question](http://stackoverflow.com/questions/11979156/mobile-safari-back-button) for details.

**Comment by ianbelcher** [comment]
I did n't have much luck with capturing any `onpageshow` events after the initial load @colinskow. 

I did eventually find a fix to this issue which will get Safari working again which is described [on Stack Overflow](http://stackoverflow.com/a/37521006/981598) but basically you can use the following in your main app component to get your application to render in Safari properly on a back (and forward) button event.

```
constructor(_router:Router, 
            _applicationRef: ApplicationRef) {
    _router.subscribe((uri)=> {
        if (Object.prototype.toString.call(window.HTMLElement).indexOf('Constructor') > 0) {
            // We appear to be using Safari...
            _applicationRef.zone.run(() => _applicationRef.tick());
        }
    });
}
```

**Comment by gugamm** [comment]
Same problem here in IE 11. OnInit does not trigger when using the back button.

**Comment by ianbelcher** [comment]
@gugamm For the time being until this issue is resolved, you can also check of IE in the above workaround to get it work...

I've found that the following works:

```
constructor(_router:Router, 
            _applicationRef: ApplicationRef) {
    _router.subscribe((uri)=> {
        if (
          Object.prototype.toString.call(window.HTMLElement).indexOf('Constructor') > 0) // Safari
          || 
          /*@cc_on!@*/false || !!document.documentMode // IE
        {
            _applicationRef.zone.run(() => _applicationRef.tick());
        }
    });
}
```

**Comment by smithad15** [comment]
Seems to still be the case in the RC router on Safari as well.

**Comment by theodorejb** [comment]
This issue still exists with the new router: angular/vladivostok#64

I have an Angular 2 app ready to deploy, but it's being held back by this bug since I need to support Internet Explorer 11.

Shouldn't this issue block the final Angular 2 release? @vsavkin @mhevery

**Comment by justme1** [comment]
@vsavkin @mhevery any updates on this issue?

**Comment by tkazec** [comment]
Since it hasn't been mentioned yet – this also affects Android 4.0, 4.1, and possibly more. I successfully used the workaround here: https://github.com/angular/angular/issues/9565#issuecomment-229870503

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/commit/f08060b0b00c98341c7e1fd9acb984402c280396

**Comment by chrillewoodz** [comment]
This still happens in chrome.

**Comment by DzmitryShylovich** [comment]
plunkr and file a new issue

**Comment by gustavshf** [comment]
Experiencing this on Edge with the latest version of Angular.

**Comment by FelixQuehl** [comment]
I have the same problem when used with ionic 4.
