### ISSUE TITLE
`ngStyle` doesn't work while using `ChangeDetectionStrategy.OnPush` to the component

### ISSUE THREAD

**Issue by leftstick** [angular/angular#8406]
**Steps to reproduce and a minimal demo of the problem**

[plunker](http://plnkr.co/edit/wgMuHv?p=preview) for the issue.

**Current behavior**

The version i am using is `2.0.0-beta.17`
The `style` doesn't apply to the `h1` element, while `ChangeDetectionStrategy.OnPush` set at the same time.

**Expected/desired behavior**

The `style` should work

**Comment by pkozlowski-opensource** [comment]
I believe that it was fixed in the Rc.0. Could you please re-test with the latest version?

**Comment by leftstick** [comment]
I got build error, since `node_modules/angular2/typings/browser.d.ts` is missing. Is there any updates for this?

**Comment by leftstick** [comment]
Still doesn't work, can u help to check the [plunker](http://plnkr.co/edit/wgMuHv?p=preview), i am using the latest version `@2.0.0-rc.1`.

**Comment by zoechi** [comment]
I haven't used `OnPush` myself yet but isn't the point of `OnPush` to notify Angular about changes explicitely (except when events or other async calls happened)?

Adding `setTimeout(() => this.cd.markForCheck());` at the end of `ngAfterViewInit()` fixed it for me.
I used `setTimeout()` because Angular doesn't like values being changed in some livecycle callbacks.

**Comment by zoechi** [comment]
http://plnkr.co/edit/f6c6eT?p=preview

**Comment by leftstick** [comment]
U mean even internal update cannot trigger component re-render, right? I think i have misunderstand here,  i thought internal update just like `state` updates in `React`, it's possible to trigger the component re-render from inside.

Thanks for your explanation

**Comment by zoechi** [comment]
No, updates are not recognized if they aren't done by Angular itself (like input updated by change detection) OnPush means - don't run change detection until explicitely told.

**Comment by leftstick** [comment]
Thanks @zoechi , if you have time, can u help me clarify following snippet:

**app.component.ts**

```javascript
import {Component, ChangeDetectionStrategy, AfterViewInit} from '@angular/core';
import {Demo} from './demo';

@Component({
  selector: 'my-app',
  template: '<h1>My First Angular 2 App</h1><demo [options]="opts"></demo>',
  directives: [Demo]
})
export class AppComponent implements AfterViewInit{ 
  constructor(){}
  
  opts = {
       name: 'Hello'
  };
  
  ngAfterViewInit() {
   setTimeout(() =>{
     this.opts = {
       name: 'World'
     };
   }, 3000);
  }
}
```

**demo.ts**

```javascript
import {Component, ChangeDetectionStrategy, Input} from '@angular/core';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'demo',
  template: '<h1>{{ options.name }}</h1>'
})
export class Demo implements AfterViewInit{ 
  constructor(){}
  
  @Input() options;
}
```

`demo.ts` is written via `ChangeDetectionStrategy.OnPush` strategy, and i have a timeout to modify the `opts` in `app.component.ts`, and the component `Demo` updated as expected, but why? I have not tell it's being changed via `this.cd.markForCheck())`, is it because that `setTimeout` is recognized by `zone.js`?

**Comment by zoechi** [comment]
That's because `options` is an input and when an input changes Angular runs change detection for that component even whit `OnPush`.

**Comment by leftstick** [comment]
Thanks very much
