### ISSUE TITLE
Publish umd bundle for router v3

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#9465]
the v3 router doesn't publish umd bundle under the `bundles/` directory of the npm package, we should do this to be consistent with the other packages.

**Comment by IgorMinar** [comment]
fixed by #9422

**Comment by robinkedia** [comment]
Looks like this is still not fixed. npm install @angular/router still doesn't download umd bundle for v3 router.
