### ISSUE TITLE
routerLink on button elements doesn't work

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9471]
_From @gdi2290 on June 21, 2016 5:37_

```html
<button [routerLink]=" ['./'] ">Home</button>
```

_Copied from original issue: angular/vladivostok#100_

**Comment by robwormald** [comment]
_From @choeller on June 21, 2016 11:20_

I created a similar ticket for the now deprecated router v2. Even if it's now another approach I think it's worth linking.. https://github.com/angular/angular/issues/8357

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/commit/8c45aebc18507fbc05d9b154f5022fecd7e7556e

**Comment by gdi2290** [comment]
thanks!

**Comment by mattvague** [comment]
Hmm, as of @angular/router 3.0.0-beta.2 I'm still getting an issue using `routerLinkActive` on button elements:

`<button [routerLink]="['./dashboard']" routerLinkActive="active">Dashboard</button>`

will raise the following error

<img width="575" alt="screen shot 2016-08-05 at 12 19 29 pm" src="https://cloud.githubusercontent.com/assets/64985/17443126/eae77438-5b06-11e6-9aee-535dcdf66183.png">

because it seems `containsTree` is expecting a RouterLinkWithHref but is RouterLink.

Am I doing something wrong here?

Thanks!

**Comment by ghetolay** [comment]
@mattvague 

Problem comes from ```routerLinkActive``` not ```routerLink```.

I think it's because on rc.4  ```RouterLink``` has an ```urlTree``` property (which is passed to ```containsTree()```. ) never set. 
On master branch we can see they [replaced it with a getter](https://github.com/angular/angular/blob/master/modules/@angular/router/src/directives/router_link.ts#L102) so it's probably fixed (couldn't test I'm using ```<a>``` in the meantime). 

Can someone confirm this ?
