### ISSUE TITLE
MockBackend.mockRespond not throwing an error

### ISSUE THREAD

**Issue by gibo** [angular/angular#9824]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Using Mockbackend and calling mockRespond with the following object:
`new Response(new ResponseOptions(
  {
      status: 500,
      headers: new Headers(),
      type: ResponseType.Error,
      statusText: 'asd',
  }));
`
The http observable never fails, it returns success.

**Expected/desired behavior**

The http observable should throw an error.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all ] 
 
* **Language:** [ TypeScript ]

**Comment by chrisguttandin** [comment]
I came across the same problem. I was abled to fix it for now by extending the `MockBackend`.

```js
import { MockBackend, MockConnection } from '@angular/http/testing';
import { ReadyState, Request, Response } from '@angular/http';
import { BaseException } from '@angular/http/src/facade/exceptions';
import { isPresent } from '@angular/http/src/facade/lang';
import { isSuccess } from '@angular/http/src/http_utils';

class FixedMockConnection extends MockConnection {

    mockRespond(response: Response) {
        response.ok = isSuccess(response.status);

        if (response.ok) {
            super.mockRespond(response);
        } else {
            this.readyState = ReadyState.Done;
            this.response.error(response);
        }
    }

}

export class FixedMockBackend extends MockBackend {

    createConnection(req: Request): FixedMockConnection {
        if (!isPresent(req) || !(req instanceof Request)) {
            throw new BaseException(`createConnection requires an instance of Request, got ${req}`);
        }
        let connection = new FixedMockConnection(req);
        this.connections.next(connection);
        return connection;
    }

}
```

Afterwards you can use the `FixedMockBackend` instead of the regular `MockBackend` in your tests.

```js
// ...
    beforeEachProviders(() => [
        BaseRequestOptions,
        FixedMockBackend,
        {
            deps: [ FixedMockBackend, BaseRequestOptions ],
            provide: Http,
            useFactory: (backend, options) => new Http(backend, options)
        }
    ]);
// ...
```

I'm happy to turn this into a pull request if the angular team thinks this is a good approach.

**Comment by Hagendorn** [comment]
I have the same issue. I would like to trigger an error with a status code 403. But `mockRespond` doesn't work because the status code will not be checked. I can also not use `mockError` because the method only allow the type of `Error` which is in my opinion wrong, because `XHRBackend` has an observable of the type `Observable<Response>`. So `mockRespond` should also allow the type `Response` as valid parameter type. I found a separate issue for the type problem, see #7135.

At the moment is is not possible to use the `MockBackend` to mock response errors with a special status value. 

I would like to contribute to solve the issue. But for me it is not clear which way to go. 

Should `mockError` be fixed to support the type `Response`. Which than says, use `mockError` for mocking errors and use `mockRespond` and `mockDownload` for mocking success response.

Or should `mockRespond` and `mockDownload` check the status code. Which than handle the error automatically. But than I think `mockError` is not needed anymore.

**Comment by lthoang101** [comment]
I was facing the same issue. The temporary workaround that I've come up with is to do a double cast of type Response to type Error. 
e.g  mockError(myResponse as any as Error)

**Comment by vicb** [comment]
@asnowwolf do you want to try to fix this one ?

**Comment by asnowwolf** [comment]
Oh, sorry, I just saw it now.

I'm very busy now and I'll try to fix it next week. 😄

**Comment by asnowwolf** [comment]
@vicb

in the first comment, @chrisguttandin said "I'm happy to turn this into a pull request if the angular team thinks this is a good approach." 

So, I think we'd better to review his code first. 

I've done a quick review just now, I vote to "it's a good approach". 

@chrisguttandin you'd better apply the bugfix to MockBackend and follow the angular coding style, such as "use 'const' keyword if possible".

**Comment by chrisguttandin** [comment]
Hi @asnowwolf, I'm still happy to turn this into a pull request, but I think it seems to be not needed anymore. After updating to RC6 I could remove my fix from above and the tests still behaved as expected.

**Comment by asnowwolf** [comment]
Great!

2016年9月5日 下午7:44，"Christoph Guttandin" <notifications@github.com>写道：

**Comment by asnowwolf** [comment]
So... I think this issue could be closed now.

**Comment by chrisguttandin** [comment]
Probably yes, but I wasn't the one who opened that issue. It's solved for me, but I'm not sure if I fully understood it in the first place. :-)

**Comment by Hagendorn** [comment]
I can't confirm that this issue is fixed. I have still the issue that `mockRespond` doesn't respect the status code.

**Comment by raphaelluchini** [comment]
I'm using Angular 4.1.3, and I still have this issue! The behaviour of XHRBackend and MockBackend are different. :(

**Comment by gustavohenke** [comment]
I thought I was doing something wrong, because [the `MockBackend` example](https://angular.io/api/http/testing/MockBackend#example) tests that a error was caught, and that suite works.

However, when inspecting the suite closer, we can see the thrown error is not because the response had a status of `404`, but rather `TypeError: Cannot read property 'data' of null` (the response succeeded, `HeroesService` tried to call `.json().data` on it, and it failed).
